### ISSUE TITLE
Error in docs example (in Accepting specific file types)

### ISSUE THREAD

**Issue by iamdiogo** [react-dropzone/react-dropzone#1001]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/17580577/90324615-e2a0c000-df68-11ea-9a9f-86a49e780467.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Open the docs https://react-dropzone.js.org/#!/Accepting%20specific%20file%20types
2. Notice syntax error

**What is the expected behavior?**
No errors

**Device**
Latest chromium on linux

**Comment by wude935** [comment]
All you have to do is add a parenthesis to before the bracket on line 26 and it resolves itself.

**Comment by rolandjitsu** [comment]
This is fixed in https://github.com/react-dropzone/react-dropzone/pull/1002.
