### ISSUE TITLE
Classnames are not being applied in Next.js and Styled JSX

### ISSUE THREAD

**Issue by wude935** [react-dropzone/react-dropzone#1004]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Classnames are not being applied in Next.js and Styled JSX with the getRootProps function.  If I place the class name outside the getRootProps function, the styles will be correctly applied. Directly applying styles works fine though. 

![image](https://user-images.githubusercontent.com/36495274/90988019-1b3a2e00-e555-11ea-8bed-42e12bea4b41.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create new Next.js application
2. Install react-dropzone
3. Use react-dropzone and apply a class to the dropzone

https://codesandbox.io/s/elated-kirch-tybii?file=/pages/index.js 

**What is the expected behavior?**
Classnames are applied properly in Next.js . 

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Firefox 79, Windows 10

**Comment by usman10scorpio** [comment]
I just installed this package in my react application and I cant see the styling in there.


![bug](https://user-images.githubusercontent.com/12570317/91657199-adec4700-ead8-11ea-8ba9-073bc2da79a3.png)

**Comment by wude935** [comment]
Hey @usman10scorpio did you import the css file? 
Place this in the _app.js

`import "react-datepicker/dist/react-datepicker.css";
`

**Comment by vassbence** [comment]
[With styled-jsx you either need to use the `resolve` tag or `:global()`.](https://github.com/vercel/styled-jsx#styling-third-parties--child-components-from-the-parent) This is because of the way styled-jsx is scoping your css selectors.

I think you should give CSS modules a try, they are now fully supported in Next and have less off these small caveats.

**Comment by rolandjitsu** [comment]
@wude935 Our docs website uses the `className` too and it works without issues. So this must be related to next.js' server side rendering. I would suggest opening an issue on their side as I have very little knowledge of how next.js works.

On our side, there's not much logic around this. If you check [index.js#L680](https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L680), we just pass on whatever the user sends through the function.

**Comment by rolandjitsu** [comment]
Gonna close this for now as it doesn't seem like there's an issue with the lib. But if we can improve the next.js integration on our side, please let us know how or submit a PR.
