### ISSUE TITLE
accept: MIME type should be case insensitive

### ISSUE THREAD

**Issue by antoineol** [react-dropzone/react-dropzone#1005]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

The MIME type check with `accept` config is case-sensitive, but it should be case-insensitive according to SO / specs. Source: https://stackoverflow.com/a/12869287/4717408. Here is a scenario where it impacts the behavior. For an Excel file with extension .xlsm, we have the MIME types:

- On Chrome Windows: _application/vnd.ms-excel.sheet.macro**E**nabled.12_ (upper-case E)
- On Chrome Mac: _application/vnd.ms-excel.sheet.macro**e**nabled.12_ (lower-case e)

This leads to a behavior a bit hard to understand when I develop on Windows (I have copy/pasted the official MIME type which is the first variant, so I'm not aware of the case issue) and I test later on Mac. If I'm not familiar with detailed MIME type specs like being case-sensitive or not, or different platforms providing different cases, it will take some time before I find the source cause.

**If the current behavior is a bug, please provide the steps to reproduce.**

Sandbox: https://codesandbox.io/s/vigilant-curran-jqxwi

1. provide `accept: "application/vnd.ms-excel.sheet.macroEnabled.12"` MIME type filter
1. Try on Windows: it works (you can upload .xlsm Excel files)
1. Try on Mac: it does NOT work. Reason: the MIME type on Mac is application/vnd.ms-excel.sheet.macro**e**nabled.12 (lower-case e)

**What is the expected behavior?**

The MIME type should be case-insensitive, so providing any case in the `accept` config should work.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

Chrome, latest version on Windows and Mac

The current workaround is to provide both cases in the list of accepted MIME types: https://codesandbox.io/s/agitated-night-52c6b

**Comment by rolandjitsu** [comment]
@antoineol please move this to [attr-accept](https://github.com/react-dropzone/attr-accept). Would be nice if you could make a PR to add support for this.

**Comment by mmaliukevich** [comment]
So does drop-zone accept .xlsm file types at the current moment ?
I have faced with the same problem. My application rejected .xlsm and always show red border
