### ISSUE TITLE
cant use maxFiles limit

### ISSUE THREAD

**Issue by tommybernaciak** [react-dropzone/react-dropzone#1014]
- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

I can't use `maxFiles` prop. I it in the documentation here: https://react-dropzone.js.org/#!/Accepting%20specific%20number%20of%20files. However, when I added it I get an error: `Object literal may only specify known properties, and 'maxFiles' does not exist in type 'DropzoneOptions'.` I checked the implementation of the `DropzoneOptions` type and there is no `maxFiles` prop there. (react-dropzone 11.1.0)

**What is the expected behavior?**

`maxFiles` prop is allowed and working.

If this was removed from the library for any reason then please update and remove it from your documentation as well as it is misleading.

**Comment by Morteza-Jenabzadeh** [comment]
Please use the latest version

**Comment by GomatoX** [comment]
@Morteza-Jenabzadeh I can confirm this issue, I'm using 11.2.0 version.

**Comment by tommybernaciak** [comment]
I updated and it works.

**Comment by GomatoX** [comment]
@tommybernaciak okey, it's working, my issue.

**Comment by miter33** [comment]
Hi guys! I use the latest version 14.2.1 and I have the same problem as above <<Object literal may only specify known properties, and 'maxFiles' does not exist in type 'DropzoneOptions'.>>
I see that DropzoneOptions have this prop anyway it does not work. Maybe does someone know what the problem?
