### ISSUE TITLE
isDragReject should be true if the DragEvent contains more than the max number of files

### ISSUE THREAD

**Issue by ath92** [react-dropzone/react-dropzone#1017]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
When setting the `maxFiles` prop, if I drag more than that number of files over the dropzone, `isDragAccept` is true, and `isDragReject` is false.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Example: https://codesandbox.io/s/stoic-wilbur-3elnq?file=/src/app.js
2. Try dragging more than 1 file over the dropzone

**What is the expected behavior?**
`isDragReject` should be true, i.e. the border should be red in the example

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Tested in chrome. Latest version of `react-dropzone` (11.2.0)

**Comment by rolandjitsu** [comment]
I think this should be fixed now (see #1020). Gonna close it. If there's still issues please let us know.
