### ISSUE TITLE
Can't resolve 'file-selector'

### ISSUE THREAD

**Issue by nomadus** [react-dropzone/react-dropzone#1022]
After installing react-dropzone
npm install --save react-dropzone
I have the following error when trying to start the application.
./node_modules/react-dropzone/dist/es/index.js
Module not found: Can't resolve 'file-selector' in 'C:\src\app\node_modules\react-dropzone\dist\es'

The version is  "react-dropzone": "^11.2.0",

**Comment by nguyenvannghi** [comment]
The same issuse

**Comment by jhetuts** [comment]
Same here
Output:
![image](https://user-images.githubusercontent.com/32116471/96961265-d28ff880-1536-11eb-8797-90632ee2d845.png)
Version:
![image](https://user-images.githubusercontent.com/32116471/96961308-e76c8c00-1536-11eb-99f6-cd7eecee46f1.png)

Added `file-selector` explicitly on package.json still nothing.

**Comment by rolandjitsu** [comment]
That's my bad, I was trying to explicitly include the LICENSE file in the file-sector release and did not include the dist dir. Should be fixed now (see [v0.2.2](https://github.com/react-dropzone/file-selector/releases/tag/v0.2.2)).

**Comment by ex-git** [comment]
I still got **Module not found: Can't resolve 'file-selector'**. 
Add below to package.json resolved the issue.
 
"resolutions": {
    "file-selector": "^v0.2.2"
  }

**Comment by jhetuts** [comment]
> That's my bad, I was trying to explicitly include the LICENSE file in the file-sector release and did not include the dist dir. Should be fixed now (see [v0.2.2](https://github.com/react-dropzone/file-selector/releases/tag/v0.2.2)).

run `npm uninstall` and `npm install react-dropzone` right?

**Comment by rolandjitsu** [comment]
@ex-git  You probably need to clean your node_modules to get the latest.

**Comment by ex-git** [comment]
> @ex-git You probably need to clean your node_modules to get the latest.

I did. Maybe it will resolve by itself after sometimes.

**Comment by sugarpac** [comment]
@rolandjitsu 
Would you update dependencies [v0.2.2](https://github.com/react-dropzone/file-selector/releases/tag/v0.2.2) in package.json?
"dependencies": {
    "file-selector": "^0.1.12"
}
this means 0.1.12 <= n < 0.2.0

**Comment by rolandjitsu** [comment]
> @rolandjitsu
> Would you update dependencies [v0.2.2](https://github.com/react-dropzone/file-selector/releases/tag/v0.2.2) in package.json?
> "dependencies": {
> "file-selector": "^0.1.12"
> }
> this means 0.1.12 <= n < 0.2.0

Soon.

**Comment by vietsonhs** [comment]
@rolandjitsu  I have cleaned my node_modules and delete package-lock. However, i am still getting the same issue. Is it related to what @sugarpac  suggested?

**Comment by sugarpac** [comment]
> > @rolandjitsu
> > Would you update dependencies [v0.2.2](https://github.com/react-dropzone/file-selector/releases/tag/v0.2.2) in package.json?
> > "dependencies": {
> > "file-selector": "^0.1.12"
> > }
> > this means 0.1.12 <= n < 0.2.0
> 
> Soon.

Thanks in advance!

And please also update file-selector@[0.1.16](https://github.com/react-dropzone/file-selector/releases/tag/v0.1.16) to 0.1.17(including the dist dir) for users staying current react-dropzone version [v11.2.0](https://github.com/react-dropzone/react-dropzone/releases/tag/v11.2.0)

**Comment by TrejGun** [comment]
same here

**Comment by neutraali** [comment]
> That's my bad, I was trying to explicitly include the LICENSE file in the file-sector release and did not include the dist dir. Should be fixed now (see [v0.2.2](https://github.com/react-dropzone/file-selector/releases/tag/v0.2.2)).

Still breaking for `react-dropzone` itself tho.

**Comment by oktaykose** [comment]
@neutraali  If you install it will be fixed -> "file-selector": "^0.2.2"

**Comment by mnasyrov** [comment]
@rolandjitsu Please use exact versions for the dependencies.

**Comment by neutraali** [comment]
> @neutraali If you install it will be fixed -> "file-selector": "^0.2.2"

@oktaykose Did that a few times now using `react-dropzone@11.2.0`. Deleted `node_modules` and reinstalled - `file-selector` is still @ `0.1.12`.

**Comment by oktaykose** [comment]
@neutraali I think it would be better to use @10.2.1 until the new fix arrives.

**Comment by goldafonya** [comment]
@oktaykose I used @10.2.1. It don't work for me.

**Comment by oktaykose** [comment]
@goldafonya I'm using nextjs@9.5.5, react-dropzone@10.2.1 and file-selector@^0.2.2. I had no problem this way.

**Comment by QXJun** [comment]
Install file-selector@^0.2.2 in your project will be fixed this problem

**Comment by barbalex** [comment]
After installing react-dropzone v11.2.0 the yarn file entry is:
```
react-dropzone@11.2.0:
  version "11.2.0"
  resolved "https://registry.yarnpkg.com/react-dropzone/-/react-dropzone-11.2.0.tgz#4e54fa3479e6b6bb93f67914e4a27f1260807fdb"
  integrity sha512-S/qaXQHCCg7MVlcrhqd05MLC6DupITLUB0CFn3iCLs6OTjzxdGDF1WTktTe5Jyq8jZdxYfMHNUZOHL0mg+K0Dw==
  dependencies:
    attr-accept "^2.0.0"
    file-selector "^0.1.12"
    prop-types "^15.7.2"
```

Seems that file-selector is still installed in the wrong version.

**Comment by nguyenvannghi** [comment]
To fix: Install `"file-selector": "^0.2.2"`

**Comment by thecodejack** [comment]
temporarily you can also use this for v11.2.0

`react-dropzone-tmp@11.2.0`

**Comment by barbalex** [comment]
Yes, in my app this solves the problem. Thanks!

**Comment by dpdhruv** [comment]
Working for us too 🤟
