### ISSUE TITLE
onFileDialogCancel triggered on correct file selection

### ISSUE THREAD

**Issue by VinuOye** [react-dropzone/react-dropzone#1027]
Guys please help me on this. From long back am facing issue and am not able to make any progress. Please pull me out of this. Thanks in advance.

**Do you want to request a *feature* or report a *bug*?**

- [ *] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
 Even when we selected file onFileDialogCancel function is trigged.
**If the current behavior is a bug, please provide the steps to reproduce.**

1. Click to open file dialog
1. Now cancel dialog, it will trigger onFileDialogCancel function as expected.--- Success.
1. Now Open dialog again and select the file, again its triggering the onFileDialogCancel function -- failure.

**What is the expected behavior?**

onFileDialogCancel callback function for when closing the file dialog with no selection or when we click on cancel button.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Am using Windows 10 64-bit OS
Browser: Chrome Version 86.0.4240.111 
react-dropzone : v"^11.2.3"

**Comment by Morteza-Jenabzadeh** [comment]
I have tested this scenario and haven't faced with that bug.
Please provide a CodeSandbox, a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.

**Comment by VinuOye** [comment]
Here is the codesandbox link: https://codesandbox.io/s/hopeful-rubin-uivuy
Please do needful.

**Comment by VinuOye** [comment]
> I have tested this scenario and haven't faced with that bug.
> Please provide a CodeSandbox, a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.

Here is the codesandbox link: https://codesandbox.io/s/hopeful-rubin-uivuy
Please do needful.

**Comment by Morteza-Jenabzadeh** [comment]
I haven't seen the bug on ur sample code:

![test2](https://user-images.githubusercontent.com/52605187/97988348-1534b900-1df2-11eb-88db-38cf117187fc.gif)

**Comment by VinuOye** [comment]
> I haven't seen the bug on ur sample code:
> 
> ![test2](https://user-images.githubusercontent.com/52605187/97988348-1534b900-1df2-11eb-88db-38cf117187fc.gif)

For me in chrome its not working, Even this codesandbox as well. Chrome v:86.0.4240.111. But this codesandbox is working well in firefox.

My environment is :

Windows 10
Node: v12.17.0
"react": "^16.13.1",
"react-dom": "^16.13.1",
"react-scripts": "^3.4.1",
"react-dropzone": "^11.2.3"

Can i know in which OS you tested this, like MacOS or Windows

**Comment by rolandjitsu** [comment]
@VinuOye it looks like @Morteza-Jenabzadeh has tried replicating the issue on Windows 10.

I've also tried it on macOS on Chrome `86.0.4240.183` and I cannot reproduce what you're describing. Maybe you could provide a screencast of what you're experiencing? Also, could you provide a bit more info about your env?

**Comment by Mike-Petersen** [comment]
I had the same problem. Tried a lot and could not really find out why this happens.
It seems that i could solve it by setting noClick to true. If i do this the cancel and double opening of the file dialog is gone.

**Comment by rolandjitsu** [comment]
@Mike-Petersen are you using a Windows machine as well?

**Comment by rolandjitsu** [comment]
Closing this as there's no response from author and we cannot reproduce.
