### ISSUE TITLE
Dropzone fails to call onDragLeave when overflow changes on child element (Firefox only)

### ISSUE THREAD

**Issue by MasterEric** [react-dropzone/react-dropzone#1032]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

If a Dropzone has a child whose style changes the overflow attribute based on drag status, the event will be able to fire onDragEnter events but not onDragLeave events.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a Dropzone.
2. Configure a child element such that it changes its overflow attribute based on drag status.
3. Attempt to drag a file over the dropzone.

It was a pain to narrow down what was causing this issue in my project, but I successfully did so here: https://codesandbox.io/s/react-dropzone-overflow-bug-demo-exmhk

Note the console. onDragEnter successfully fires, and continues to fire whenever the user's cursor enters the bounds of the element, but onDragLeave is never printed.

Also note: I have found that the above CodeSandbox produces the unexpected behavior only on Firefox (version 83.0) and Chrome (Version 87.0.4280.66) on the same operating system behaves as expected.

**What is the expected behavior?**

The element should call onDragLeave, and set isDragActive to false.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

- React version 17.0.0
- react-dropzone version 11.2.4
- Firefox version 83.0
- Windows 10

I will likely be able to resolve this in the application I discovered this in by modifying the styling (I had set overflow on the active style but not the inactive style), but I wanted to report the issue as I experienced it.

**Comment by rolandjitsu** [comment]
@MasterEric is this still happening in the latest version of Firefox?

**Comment by MasterEric** [comment]
@rolandjitsu Just tested on Firefox 84.0.2 (64 bit Ubuntu) and the issue still occurs.

Note you can test it yourself with various browsers using the provided CodeSandbox, in which I was able to minimally reproduce the error.

**Comment by rolandjitsu** [comment]
@MasterEric gonna close this for now as this seems like something a user should deal with. If you feel otherwise and have a fix for it, please open a PR.
