### ISSUE TITLE
Drag feature is not working with Chrome Version 86.0.4240.183 (Official Build) (x86_64)

### ISSUE THREAD

**Issue by A00433626** [react-dropzone/react-dropzone#1033]
**Do you want to request a *feature* or report a *bug*?**

- [X] I found a bug
- [ ] I want to propose a feature

**What is the current behaviour?**
I'm using the react-dropzone (11.2.4) class-based component in my application. The drag feature is not working on MAC chrome But, still, it's working on safari and other browsers.

**Comment by daniel-datastax** [comment]
Not working on a Windows with latest Chrome 87.0.4x (currently) as well.

**Comment by richin13** [comment]
Is there an error message in the console?

**Comment by A00433626** [comment]
> Is there an error message in the console?

No error message but drag was not working

**Comment by daniel-datastax** [comment]
I am running on a Mac and everything works fine.

On a Windows machine however all the .CSV files I am trying to upload are falling into the REJECT array instead of ACCEPTED. 

I used Git Bash on Windows and found out that `file --mime-type one-liner.csv` reading as `one-liner.csv: text/plain` instead of "text/csv". I already checked a few times and it seems all well-formatted/well-generated csv files are being read as "" (empty) by the DropZone and thrown in the Rejected path.

```js
lastModified: 1606944926375
lastModifiedDate: Wed Dec 02 2020 16:35:26 GMT-0500 (Eastern Standard Time) {}
name: "one-liner.csv"
path: "one-liner.csv"
size: 18
type: ""
webkitRelativePath: ""
```

**Any clues?** @richin13

**Comment by A00433626** [comment]
> I am running on a Mac and everything works fine.
> 
> On a Windows machine however all the .CSV files I am trying to upload are falling into the REJECT array instead of ACCEPTED.
> 
> I used Git Bash on Windows and found out that `file --mime-type one-liner.csv` reading as `one-liner.csv: text/plain` instead of "text/csv". I already checked a few times and it seems all well-formatted/well-generated csv files are being read as "" (empty) by the DropZone and thrown in the Rejected path.
> 
> ```js
> lastModified: 1606944926375
> lastModifiedDate: Wed Dec 02 2020 16:35:26 GMT-0500 (Eastern Standard Time) {}
> name: "one-liner.csv"
> path: "one-liner.csv"
> size: 18
> type: ""
> webkitRelativePath: ""
> ```
> 
> **Any clues?** @richin13

Strange!. I'm working on Mac too. I have followed the documentation. Let me know if I have any issue with my code. Thank you.
const ALLOWED_FILE_TYPES = ".png, .pdf";
 onDrop=(file)=>{
        this.setState({sucessAlert:null,failAlert:null})
        let files=this.state.files;
        if(file.length>0){
         files.push(file)
         alert(`${file[0].name} Added Sucessfully`)
      }
      else if(file.type!=='.png' ||file.type!=='.pdf'){
        this.setState({failAlert:`File not suppported`})
      }
      }

render(){
return(
 <Dropzone onDrop={this.onDrop}
                     accept={ALLOWED_FILE_TYPES}
                     minSize={0}
                     maxSize={5042880}
                     multiple>
            {({getRootProps, getInputProps}) => (
              <section  className="container">
                <div {...getRootProps({className: 'dropzone'})}>
                  <input {...getInputProps()} />
                  <div className='dropzone-text-container'>
                  <p className='dropzone-text'> Drag and Drop </p>
                  </div>
                </div>
              </section>
            )}
          </Dropzone> 
);
}

**Comment by A00433626** [comment]
Strange!. I'm working on Mac too. I have followed the documentation. Let me know if I have any issue with my code. Thank you.
const ALLOWED_FILE_TYPES = ".png, .pdf";
 onDrop=(file)=>{
        this.setState({sucessAlert:null,failAlert:null})
        let files=this.state.files;
        if(file.length>0){
         files.push(file)
         alert(`${file[0].name} Added Sucessfully`)
      }
      else if(file.type!=='.png' ||file.type!=='.pdf'){
        this.setState({failAlert:`File not suppported`})
      }
      }

render(){
return(
 <Dropzone onDrop={this.onDrop}
                     accept={ALLOWED_FILE_TYPES}
                     minSize={0}
                     maxSize={5042880}
                     multiple>
            {({getRootProps, getInputProps}) => (
              <section  className="container">
                <div {...getRootProps({className: 'dropzone'})}>
                  <input {...getInputProps()} />
                  <div className='dropzone-text-container'>
                  <p className='dropzone-text'> Drag and Drop </p>
                  </div>
                </div>
              </section>
            )}
          </Dropzone> 
);
}

**Comment by A00433626** [comment]
<img width="427" alt="Screen Shot 2020-12-02 at 6 39 35 PM" src="https://user-images.githubusercontent.com/55320445/100940126-ca2fc380-34cd-11eb-8d29-4160f3333813.png">


Strange!. I'm working on Mac too. I have followed the documentation. Let me know if I have any issue with my code. Thank you.
const ALLOWED_FILE_TYPES = ".png, .pdf";
 onDrop=(file)=>{
        this.setState({sucessAlert:null,failAlert:null})
        let files=this.state.files;
        if(file.length>0){
         files.push(file)
         alert(`${file[0].name} Added Sucessfully`)
      }
      else if(file.type!=='.png' ||file.type!=='.pdf'){
        this.setState({failAlert:`File not suppported`})
      }
      }
