### ISSUE TITLE
#888 still persists for accept: '.stl'

### ISSUE THREAD

**Issue by rschurade** [react-dropzone/react-dropzone#1034]
As mentioned in the title and also mentioned in the comments for #888 after it was closed, that bug still exists for
file extensions other than mime types.

Please mention other relevant information such as the browser version, Operating System and react-dropzone version.
Browser Version: Chrome Version 87.0.4280.66 (Official Build) (64-bit)
OS: Window 10 Pro
React Dropzone Version: 11.2.4

The code below still evaluates the file type correctly as is visible in the onDrop function but the isDragReject flag is always true.

Thanks, let me know if I can help somehow.

`import React, { useCallback } from 'react';
import { useDropzone } from 'react-dropzone';

const FileDropzone = () => {
    const maxSize = 100000000;

    const onDrop = useCallback((acceptedFiles) => {
        console.log(acceptedFiles);
    }, []);

    const {
        isDragActive,
        getRootProps,
        getInputProps,
        isDragAccept,
        isDragReject,
        acceptedFiles,
        rejectedFiles,
    } = useDropzone({
        onDrop,
        accept: '.stl',
        acceptedFiles: '*.stl',
        minSize: 0,
        maxSize,
    });

    const isFileTooLarge =
        rejectedFiles &&
        rejectedFiles.length > 0 &&
        rejectedFiles[0].size > maxSize;

    return (
        <div className="container text-center mt-5">
            <div {...getRootProps()}>
                <input {...getInputProps()} />
                {!isDragActive && 'Click here or drop a file to upload!'}
                {isDragActive && !isDragReject && "Drop it like it's hot!"}
                {isDragReject && 'File type not accepted, sorry!'}
                {isFileTooLarge && (
                    <div className="text-danger mt-2">File is too large.</div>
                )}
            </div>
        </div>
    );
};

export default FileDropzone;`

**Comment by Morteza-Jenabzadeh** [comment]
Your [sandbox](https://codesandbox.io/s/affectionate-benz-xb3j8?file=/src/app.js) react-dropzone version is behind the latest version. I just update its version and everything worked fine.

**Comment by Morteza-Jenabzadeh** [comment]
generally, The problem is due to privacy [issues](https://stackoverflow.com/questions/11065803/determine-what-is-being-dragged-from-dragenter-dragover-events/23416174#23416174) we don't have access to file data(name, format, size..) in `dragover` eventHandler. The only information that we get from the browser are `type` and `kind`. So far no problem we can check the type. I have downloaded some `'.stl'` files from random sites. none of them has `type` property(I don't know why)

you can check it simply by adding a `dragover` eventlistener to DOM without react-dropZone implementation.

```ts
 React.useEffect(() => {
        /* events fired on the drop targets */
        document.addEventListener(
            'dragover',
            function (event) {
                // prevent default to allow drop
                event.preventDefault()
                console.log(event?.dataTransfer?.items[0])
            },
            false,
        )
    }, [])
```
Also, notice that `acceptedFiles`  is not the right way to set accepted file types. according to the document `accept` is the only way to filter acceptable files.

**Comment by rschurade** [comment]
My code example uses accept.

**Comment by Morteza-Jenabzadeh** [comment]
> > Also, notice that acceptedFiles is not the right way to set accepted file types. according to the document accept is the only way to filter acceptable files.
> 
> My code example uses accept.

I mean this line : 
```
    acceptedFiles: '*.stl',
```

**Comment by rschurade** [comment]
Oops sorry, that line was still in after trying several suggestions and older versions. They didn't work either of course.

**Comment by rolandjitsu** [comment]
@rschurade could you provide a sandbox illustrating this issue?

**Comment by rolandjitsu** [comment]
Gonna close this as there's no response from the reporter.

**Comment by yannickbuntsma** [comment]
Ran into this issue today on a project where we recently implemented this package, which led me to this issue report. I saw it was missing a reproduction, so I made one: https://codesandbox.io/s/friendly-bartik-xkupt.

Hope it helps get to the bottom of this.
