### ISSUE TITLE
Unwanted re-renders after every dragEnter and dragLeave events

### ISSUE THREAD

**Issue by shapaCacooca** [react-dropzone/react-dropzone#1035]
I faced the same problem as desrcibed in [839](https://github.com/react-dropzone/react-dropzone/issues/839).

Every dragEnter event causes `useDropzone` hook changing and re-render of whole component due to the fact, that [this line](https://github.com/react-dropzone/react-dropzone/blob/5a4ae9327c558915bbe3ff6c532ff7a63241da87/src/index.js#L523) never returns true, so this [dispatch](https://github.com/react-dropzone/react-dropzone/blob/5a4ae9327c558915bbe3ff6c532ff7a63241da87/src/index.js#L527) runs every time.

How can i prevent this behaviour and stop dragEnter event propagation correctly?

**Comment by morijenab** [comment]
**If the current behavior is a bug, please provide the steps to reproduce.**
 You can use https://codesandbox.io/embed/stupefied-kepler-btkpt to get started and illustrate the issue you're experiencing.

**Comment by rolandjitsu** [comment]
@shapaCacooca what you've described doesn't make sense. The check does not need to return `true`, the `return` will stop execution.

Would be helpful, though, if you could explain what you're trying to achieve and maybe provide an example as @morijenab mentioned in the above comment.

**Comment by nejcm** [comment]
Yes the return will stop execution but I am facing the same issue. Clicking on the container even with noClick set to true triggers a rerender every time. Will take a look if I find the time.

**Comment by rolandjitsu** [comment]
@nejcm @shapaCacooca is this still an issue?

**Comment by Silvercast** [comment]
@rolandjitsu yes, still an issue in my project even with latest v11.3.2.  The ´noDragEventsBubbling` flag doesn't seem to have any effect. It's quite annoying because it triggers the whole page re-render, clearing the states of other components in my page. I tried both `useDropzone` hook and  `<Dropzone>` wrapper component.

**Comment by Silvercast** [comment]
it might be that `useCallback` (as in the example code) is the culprit. Everything works when I remove the `useCallback` and apply the handle function directly

**Comment by morijenab** [comment]
I have noticed that there are two dispatches inside (onDragEnterCb, onDragLeaveCb) that cause the state to change and rerender begins even though the callbacks are not passed.
I think when the call back is not pass from parent we shouldn't update the state inside the event handler 
I moved both dispatches inside the lower ifs:

```js
 if (onDragEnter) {
 dispatch({
              draggedFiles,
              isDragActive: true,
              type: 'setDraggedFiles'
 })
onDragEnter(event)
}

if (isEvtWithFiles(event) && onDragLeave) {
    dispatch({
          isDragActive: false,
          type: 'setDraggedFiles',
          draggedFiles: []
   })
  onDragLeave(event)
      }
```

but with these changes, some test will be failed 
hope it help to find the bug

**Comment by azakero** [comment]
Any fix for this? If I upload or drag a file, it gets re-rendered.

**Comment by andrekat** [comment]
> it might be that `useCallback` (as in the example code) is the culprit. Everything works when I remove the `useCallback` and apply the handle function directly

i am facing the same problem .. what do you mean by applying the handling function directly? can you share your code? thanks!

**Comment by juanvicareer** [comment]
`    const {getRootProps, getInputProps} = useDropzone({
        accept: ".csv",
        onDrop: (acceptedFiles) => {
            setFiles(
                acceptedFiles.map(file => Object.assign(file, {
                        preview: URL.createObjectURL(file)
                    })
                )
            )
        }
    })`


Anyone know why my entire component re-renders whenever I drag a file in? I suspect the culprit is onDragEnter / onDragLeave :/

**Comment by rolandjitsu** [comment]
Gonna close this as I hope the above explanations are good enough. If not, please open a new issue with appropriate examples that illustrate what the issue is.
