### ISSUE TITLE
Single file upload drag not working on chrome: value of input always undefined 

### ISSUE THREAD

**Issue by kopax** [react-dropzone/react-dropzone#1037]
**What is the current behavior?**

When I drag a `.pdf` file into the drop zone, I can set the `files` using the state, however, this does not set the input value of `document.querySelector('input[type="file"][name="resume"]').value`.

When validating the form, it's value is always an empty string. It work fine when not using the drop zone but the dialogue.

```bash
Unhandled Rejection (InvalidStateError): Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.
```
Is there a way to have a proper form or should I just use the state and validate from it? 

**What is the expected behavior?**

I expect to get the value of the input set when dragging.

**If this is a feature request, what is motivation or use case for changing the behavior?**

When validating a form, the default input file behavior is to have a value which must be a path or an empty string.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

Chrome, react-dropzone@11.2.4, Debian Buster.

**Comment by rolandjitsu** [comment]
@kopax do you mind providing a codepen or something with an example of this validation?

I think the reason might be because when you use the drag 'n' drop we do not set the input with whatever files you dropped. While we could do that, I think it will probably make the logic too complex.

If you'd like, you can make a PR to address this.

**Comment by kopax** [comment]
I fixed it long time ago, don't remember how
