### ISSUE TITLE
Files grayed out when attempting to browse for Audio files via iPhone

### ISSUE THREAD

**Issue by tkentdna** [react-dropzone/react-dropzone#1039]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug (I assume it's a bug, but not sure if it's in react-dropzone or due to iPhone limitations/restrictions)
- [ ] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Using an app on laptop/desktop browser with react-dropzone to browse for audio files (.m4a) works fine (acceptedFileTypes="audio/*"). (Browsing for image & video files using their respective file types also works fine.)
1. However, using the same app on an iPhone (any browser: iOS Safari, Google Chrome, Duck Duck Go), the audio files are grayed out and cannot be selected. (Note: Browsing for image & video files in the iPhone "Photos Library" works fine.)
1. I tried locating the files both on the iPhone and in iCloud Drive, but results are the same.

**What is the expected behavior?**
- I expect that the audio files (.m4a) will be selectable when browsing with react-dropzone.  (Perhaps there's an extra setting or property for browsing on the iPhone?)

**Thanks for any help or suggestions you may be able to provide!**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by BulinskiD** [comment]
Hi, 
I was struggling with this problem for some time. My observations are:
- This is not an issue of react-dropzone, this is an issue of iOS. When you try to do the same with simple <input type="file" accept="audio/*" /> you will have the same problem.

- Solution => There is a simple workaround to this, you just have to be specific with MIME Types. When you specify in your accept prop types like so: "audio/mpeg,audio/ogg" and so on, everything should work just fine :)

**Comment by tkentdna** [comment]
Thanks, that simple workaround helped a lot!  Once I itemized the individual MIME types, the files were enabled for selection (to add to the drop zone).  

I then encountered a problem that required a minor workaround. With purely the itemized MIME types listed, react-dropzone "rejected" the file(s) that I selected. However, if I re-included "audio/*" in the itemized list of MIME types "audio/*,audio/mpeg,audio/ogg, ...", react-dropzone accepted the selected file(s). 

Thanks again for your response and help!

**Comment by polgiron** [comment]
hey, your workaround to make react-dropzone accept the "audio/mp3" file is not ideal unfortunately. Adding back the "audio/*" is making the iphone display "photo library" and "take video" options as well...

While having only the MIME "audio/mp3" doesn't seem to work

<img width="278" alt="Screenshot 2023-02-01 at 15 16 12" src="https://user-images.githubusercontent.com/8901804/216067538-1f97fc83-31e2-49c1-96aa-1ba0b2837c87.png">


Anyone would have another solution?
