### ISSUE TITLE
The "copy" cursor icon is displayed when the file type is not supported. Expecting the "none" cursor to be displayed.

### ISSUE THREAD

**Issue by mdebeus** [react-dropzone/react-dropzone#1042]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
When dragging a file into the drop-zone, the Copy cursor is displayed, even when the file type is not supported. I believe the fix for issue #749 is the culprit - the dropEffect should be set to "copy" only when the file type is supported, and set to "none" when the file type is not supported.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Drag an unsupported file into the drop-zone 

**What is the expected behavior?**
The cursor shows the "none" dragEffect which indicates that the item may not be dropped.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Browser: Chrome, Operating System: Windows, react-dropzone version: 10.2.1

**Comment by rolandjitsu** [comment]
@mdebeus the issue is that while dragging there's not much support in browsers to check the file type/size, etc. So it would be difficult to keep consistent across browsers.

Furthermore, the logic for validation is outside of the callback, so it would require a bit of refactoring to change that.

You're welcome to make a PR if you want.

**Comment by thenanyu** [comment]
Here https://github.com/react-dropzone/react-dropzone/blob/ebe21302966cfb016c743542ea4ab67b3d4f8bfc/src/index.js#L559 — could we possible test for at least the existence of files? using `isEvtWithFiles(event)`

Right now, everything that's dragged over a dropzone gets the green (+) sign, including things like links and html5 drag and drop object

**Comment by diegolameira** [comment]
Hey, just found this is back again with v14.2.2...

Is someone else having same issue as mine?

macOS Monterey 12.4
Chrome: Version 103.0.5060.114 (Official Build) (arm64)
Safari: Version 15.5 (17613.2.7.1.8)

**Comment by tim-ninan** [comment]
We are using 14.2.1 and experiencing the same issue as well....

@diegolameira Were you ever able to come to a work-around on this by any chance?
