### ISSUE TITLE
Distinct action for Multiple DropZone in the same component

### ISSUE THREAD

**Issue by fbmfbm** [react-dropzone/react-dropzone#1044]
**Do you want to request a *feature* or report a *bug*?**

- [0 ] I found a bug
- [0 ] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1.
1.
1.

**What is the expected behavior?**

I all,
I looking to filter/distinct action when two dropzones live in the same component.  What's the best solution to filter the dropzone when onDrop action occure ?
Searching in the doc and inthe closed issues but don't find anything.

Thank's for your help

**Comment by rolandjitsu** [comment]
@fbmfbm this may help: [event propagation](https://react-dropzone.js.org/#section-event-propagation).

**Comment by fbmfbm** [comment]
thank's for your answer Roland
