### ISSUE TITLE
Not capturing image file path

### ISSUE THREAD

**Issue by ljones87** [react-dropzone/react-dropzone#1047]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

acceptedFiles are missing the full file path, it only captures the file name

I've found its reproducible in any of the sandboxes demoing react-dropzone. 
I've forked on here which just adds a `console.log` of the file in `handleDrop`:
[https://codesandbox.io/s/basic-forked-xnuzp?file=/src/App.js](https://codesandbox.io/s/basic-forked-xnuzp?file=/src/App.js)

if that doesn't work, I forked off of [https://codesandbox.io/s/styling-dropzone-97d0r](https://codesandbox.io/s/styling-dropzone-97d0r)
but you would need to add the console to handleDrop

```
  const handleDrop = (acceptedFiles) => {
    console.log(acceptedFiles[0]);
    return setFileNames(acceptedFiles.map((file) => file.name));
  };
```
- select or drop file and view console

![Screen Shot 2021-02-10 at 7 45 39 PM](https://user-images.githubusercontent.com/27159818/107597673-957c6e80-6bd8-11eb-875e-8853f5c1c646.png)

Name and path are the same. No reference to the path in the local file system.

**What is the expected behavior?**
The path is  relative to the users system

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
    "react-dropzone": "11.3.1",
    macOS
    google: Version 88.0.4324.150

I have seen others mention something close to this issue [here](https://github.com/react-dropzone/react-dropzone/issues/804) & [here](https://github.com/react-dropzone/file-selector/issues/10) but have found no solutions relative to my using (I'm not using it within electron and the issue filed on file-selector seems to have just resolved itself)

**Comment by ljones87** [comment]
Other relevant details are we're using nextjs graphql + apollo.  
I'm successfully able to send the file blob if Im using axios in the client, but breaks when in node.
I am able to resolve the file path by using `process.cwd()` (duh) and prepending that to the path. However I'm still unable to get it to post with `FormData` on the BE. That sounds like a me issue though. 

Going to close, this doesn't seem related to react-dropzone but lmk if I should be expecting a different data approvedFile(s) format

**Comment by rolandjitsu** [comment]
@ljones87 I don't think that you can get the full path (absolute path) of the file(s) when using this lib in a browser. It will only work in Electron.

**Comment by ljones87** [comment]
Your right @rolandjitsu, I was confused by those other two posts around the same issue, specifically the thread on file-selecor https://github.com/react-dropzone/file-selector/issues/10.
I understand it’s a privacy/security thing to not have the path. I just still am having issue getting the image to post in a node environment. Only got it working using axios to post formData on the client.

Def some knowledge deficiency on my part regarding these image uploads.

**Comment by carloscrono** [comment]
@ljones87 did you solve the issue?

I am getting an error on the GraphQL side:

`2022-12-05T23:12:03.472Z 1286b79b-4e57-425a-8d71-ecacbe39f5d2 INFO {
"message": "Variable \"$file\" got invalid value { path: \"129622087_2770692176530303_9107061025120180342_n.jpg\" }; Upload value invalid.",
"extensions": {
"code": "BAD_USER_INPUT",
"exception": {
"stacktrace": [
"GraphQLError: Variable \"$file\" got invalid value { path: \"129622087_2770692176530303_9107061025120180342_n.jpg\" }; Upload value invalid.",
" at /var/task/node_modules/graphql/execution/values.js:116:15",
" at coerceInputValueImpl (/var/task/node_modules/graphql/utilities/coerceInputValue.js:131:9)",
" at coerceInputValueImpl (/var/task/node_modules/graphql/utilities/coerceInputValue.js:54:14)",
" at coerceInputValue (/var/task/node_modules/graphql/utilities/coerceInputValue.js:37:10)",
" at _loop (/var/task/node_modules/graphql/execution/values.js:109:69)",
" at coerceVariableValues (/var/task/node_modules/graphql/execution/values.js:121:16)",
" at getVariableValues (/var/task/node_modules/graphql/execution/values.js:50:19)",
" at buildExecutionContext (/var/task/node_modules/graphql/execution/execute.js:203:61)",
" at executeImpl (/var/task/node_modules/graphql/execution/execute.js:101:20)",
" at execute (/var/task/node_modules/graphql/execution/execute.js:60:35)",
" at execute (/var/task/node_modules/apollo-server-core/src/requestPipeline.ts:485:34)",
" at processGraphQLRequest (/var/task/node_modules/apollo-server-core/src/requestPipeline.ts:375:28)",
" at processTicksAndRejections (internal/process/task_queues.js:95:5)",
" at processHTTPRequest (/var/task/node_modules/apollo-server-core/src/runHttpQuery.ts:346:24)"
]
}
}
}`

I think my request is incomplete on the client side. I am not sure why.
