### ISSUE TITLE
Question about mime type

### ISSUE THREAD

**Issue by erikswed** [react-dropzone/react-dropzone#1050]
I needed Dropzone to give me mime types for any file user select.  like *.rar, *.any
I still learn Javascript and Doom and trying to understand why Dropzone don't give a `type` for some file extensions like e.g "rar"  

I see internally Dropzone is using the [file-selector](https://github.com/react-dropzone/file-selector/blob/master/src/file.ts) like so to parse the most common : Is it possible to get a complete list of mime types for any selected file if so how? Or do I have to pars every file myself and detect this?

export const COMMON_MIME_TYPES = new Map([
    ['avi', 'video/avi'],
    ['gif', 'image/gif'],
    ['ico', 'image/x-icon'],
    ['jpeg', 'image/jpeg'],
    ['jpg', 'image/jpeg'],
    ['mkv', 'video/x-matroska'],
    ['mov', 'video/quicktime'],
    ['mp4', 'video/mp4'],
    ['pdf', 'application/pdf'],
    ['png', 'image/png'],
    ['zip', 'application/zip'],
    ['doc', 'application/msword'],
    ['docx', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document']
]);

Image show empty mime type for *.rar file type:

![image](https://user-images.githubusercontent.com/3285249/110590172-b7392900-8177-11eb-857f-335396a57b4d.png)

**Comment by rolandjitsu** [comment]
@erikswed please use stackoverflow for this. If the file doesn't have a mime type, it's probably a browser issue, as this lib doesn't do anything with the files besides setting the file path if it can.
