### ISSUE TITLE
Provide onDragEvent rejection message

### ISSUE THREAD

**Issue by sebastienlabine** [react-dropzone/react-dropzone#1051]
- [x] I found a bug
- [x ] I want to propose a feature

**What is the current behavior?**
When dropping files that are rejected with isDragRejected, I can't get access to the reason why it's rejected before the user dropped the files.

**What is the expected behavior?**
 I would like to be able to get the rejection error on the drag so the the user can understand why their files are rejected and prevent them from dropping them.

**Comment by rolandjitsu** [comment]
@sebastienlabine this is a limitation in browser APIs. We cannot reliably tell, during the drag event, what the files are and how big they are. We only get the info during the drop event. Event though, some of the info may be available during the other events as well, it will probably be difficult to reliably reproduce the same behaviour across browsers.

If you check [src/index.js#L775](https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L775), you can see that we compute the rejections every time there's an interaction/event.

I'm going to close this as I don't think we can do much about it, but if you think you can find a way to do it, please feel free to open a PR.
