### ISSUE TITLE
Integrate Doka with react-dropzone

### ISSUE THREAD

**Issue by danish-tr** [react-dropzone/react-dropzone#1054]
Thank you for this wonderful module. 

I've been using react-dropzone in our project and I'm trying to integrate doka using [react-dropzone doka integration example](https://react-dropzone.js.org/#!/Doka/1).

I've install dependencies (doka) in aforementioned example using npm and I'm unable to import it as done in example. I got the **cannot resolve doka module** error.

Is there anything that I'm missing? 

Your support is much appreciated.

**Comment by rolandjitsu** [comment]
@danish-tr could you reach out to [doka](https://pqina.nl/doka)? I think there's an issue with the way you import or something like that.

**Comment by danish-tr** [comment]
@rolandjitsu I didn't reach out to [doka](https://pqina.nl/doka/) yet. I thought it would be opensource but it doesn't and I think I need to purchase first and then they will provide distribution folder for [doka](https://pqina.nl/doka/) right? 

Secondly, can you please post the npm package link used in the [example for doka](https://react-dropzone.js.org/#!/Doka/1)? 

It would be much appreciated.

**Comment by rolandjitsu** [comment]
> @rolandjitsu I didn't reach out to [doka](https://pqina.nl/doka/) yet. I thought it would be opensource but it doesn't and I think I need to purchase first and then they will provide distribution folder for [doka](https://pqina.nl/doka/) right?

You should reach out to them. Yes, you need to buy the license and they will provide you with some assets.

> Secondly, can you please post the npm package link used in the [example for doka](https://react-dropzone.js.org/#!/Doka/1)?
> 
> It would be much appreciated.

Please check [vendor/doka](https://github.com/react-dropzone/react-dropzone/tree/master/vendor/doka). Just note that the files provided are probably not supposed to be distributed or used without a license. We have them there so that we can illustrate how the integration is done.
