### ISSUE TITLE
AcceptedFiles typedef porblem

### ISSUE THREAD

**Issue by dancixx** [react-dropzone/react-dropzone#1055]
Typedefinition for acceptedFiles: Array<File> is not valid. There is no some props.

**Comment by rolandjitsu** [comment]
@dancixx the issue description doesn't follow our guidelines so I'm gonna close it. You're probably referring to: https://github.com/react-dropzone/react-dropzone/blob/ec934256bd13257915caee52dd3c88d733deb2db/typings/react-dropzone.d.ts#L42
but this sounds more like an issue with how your env uses the typings.
