### ISSUE TITLE
Setting :disabled pseudo class when dropzone is disabled

### ISSUE THREAD

**Issue by hellow554** [react-dropzone/react-dropzone#1059]
**Do you want to request a *feature* or report a *bug*?**
- [ ] I found a bug
- [X] I want to propose a feature

**What is the current behavior?**
When using the `disabled` property on the `useDropzone` function, the dropzone get's disabled in term of that it doesn't accept drops or mouse inputs anymore (AFAICT).
But to have some styling, e.g. `cursor: not-allowed` you have to manually set a class to the `div`/... .

There is the [`:disabled`](https://developer.mozilla.org/en-US/docs/Web/CSS/:disabled) pseudo class which could be set when the `disabled` property is set on the `useDropzone` function (and of course the `Dropzone` component as well).

**If this is a feature request, what is motivation or use case for changing the behavior?**

This would simplify css handling a lot as well as handling edge cases (e.g. determining if the dropzone is disabled twice).

```css
.dropzone {
  cursor: pointer;
}
.dropzone:disabled {
  cursor: not-allowed;
}
```

**Comment by rolandjitsu** [comment]
@hellow554 the dropzone doesn't deal with styling anymore. That's up to the user to decide how to deal with it.
