### ISSUE TITLE
Accept first file when dropping many with "multiple: false"

### ISSUE THREAD

**Issue by CarlosHdez** [react-dropzone/react-dropzone#1060]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [x] I want to propose a feature

**What is the current behavior?**
I'm not entirely sure if this is a bug
Whenever I drop multiple files on a dropzone configured with `multiple: false` all my files get rejected with the error `too-many-files`.

**If the current behavior is a bug, please provide the steps to reproduce.**

1.
1.
1.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
I was expecting it to return the first match, which would be the first file in the array, specially since the `accept` limitation works that way (i.e. I drop multiple files but only one has the accepted extension is passed)

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
This is happening on v11.3.2

**Comment by morijenab** [comment]
Hi Carlos
As far as I know, the `multiple` prop is an HTML attribute and the browser doesn't call the `drop` callback when `multiple` is false and multiple files are droped. 
which means we haven't access to files.

**Comment by rolandjitsu** [comment]
@CarlosHdez this is intentional. If `multiple` is false, it shouldn't allow the user to drop more than 1 file, hence the error you're getting.
