### ISSUE TITLE
There is a way to set files as uploads on render?

### ISSUE THREAD

**Issue by filoscoder** [react-dropzone/react-dropzone#1062]
There is a way to set files as uploads on render?
I mean, I'm using Dropzone on an edit page, and there are already image attachments from server, and I want to render Dropzone with these files from the server, and open to delete or add more before submitting.

I've already checked the docs, but I'm not sure how to do this.
Please give me a hand with this!

**Comment by rolandjitsu** [comment]
@filoscoder dropzone doesn't deal with state management of files from anywhere else than what the user dropped/selected. This can be easily achieved on the user side.
