### ISSUE TITLE
Set favorite/starred image on Preview

### ISSUE THREAD

**Issue by darduf** [react-dropzone/react-dropzone#1063]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I want to propose a feature

**What is the current behavior?**
react-dropzone preview displays the selected images.

**What is the expected behavior?**
After selecting the images - the user can then set the favorite/starred image from the preview,  to be used as the primary thumbnail for the item being photographed

**If this is a feature request, what is motivation or use case for changing the behavior?**
It would be useful to have this as an option - whereby the image file item is defined as the favorited/starred and can then be used in future presentations as the primary thumbnail or main image

**Comment by rolandjitsu** [comment]
@darduf the preview is just an example. You can take that and enhance it with your requirements.
