### ISSUE TITLE
2 dropzones in one component

### ISSUE THREAD

**Issue by fbmfbm** [react-dropzone/react-dropzone#1064]
I need to use 2 differents dropzones in one component for storing 2 different files withe useDropeZone version. I'm trying with onDropAccepted and retrieve event with input id...but the id never change.

i have 2 dropezone like that :
```

<div {...getRootProps({style})}>
<input id={'new_logo_input'} {...getInputProps()} />
<p>Drop logo (jpg,png)</p>
</div>
<div {...getRootProps({style})}>

<input id={'new_stamp_input'} {...getInputProps()} />
<p>Drop stamp (jpg,png)</p>
</div>
```
and useDropeZone like that :
```
const { fileRejections, getRootProps, getInputProps, isDragActive, isDragReject, isDragAccept} = useDropzone({
onDropAccepted: (files,event)=>{
console.log(files,event.target.id )
}
})
```
But the event.target.id return allways 'new_stamp_input'.....!!!

any one can help me ?

Thank's a lot

**Comment by rolandjitsu** [comment]
@fbmfbm I don't think that's possible. You'll need to create a wrapper component for dropzone and then you that twice.
