### ISSUE TITLE
File Uploader Dialog Box Not Movable on MAC

### ISSUE THREAD

**Issue by radheaki** [react-dropzone/react-dropzone#1067]
The dialog Box which is opening for uploading Files is not movable/draggable on  Mac. Please provide if any solution is there for this : ) .
<img width="850" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/39318570/118475473-ec3e9a80-b729-11eb-8832-f4a75bf15919.png">

**Comment by rolandjitsu** [comment]
@radheaki I think you should contact Apple for this as there's not much we can do about that.
