### ISSUE TITLE
Bad types for `acceptedFiles` and `fileRejections`

### ISSUE THREAD

**Issue by ShauniArima** [react-dropzone/react-dropzone#1068]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Type checking for `acceptedFiles` and `fileRejections` is not correct (`path` is not in `File`)

**What is the expected behavior?**

`acceptedFiles` and `fileRejections` must be correctly typed (`File` | `FileWithPath`).

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by Adzerty** [comment]
Hey, you should check issue #981

**Comment by rolandjitsu** [comment]
> But `name` and `path` do not represent the same thing here. The `path` contains the folder name whereas `name` only contains the name of the file with its extension.
> 
> https://codesandbox.io/s/bad-types-for-accepted-files-react-dropzone-kh5bq?file=/src/App.tsx
> 
> The workaround of #981 is working but it will be easier to use the package without needing type overrides.

We cannot do that because of the plugins impl. And https://github.com/react-dropzone/react-dropzone/issues/981 is the way to go.
