### ISSUE TITLE
React slow when select file from local

### ISSUE THREAD

**Issue by peacedyc** [react-dropzone/react-dropzone#1070]
I found a bug

it's the same with https://github.com/react-dropzone/react-dropzone/issues/1043

I can still reproduce the issue on Chrome 89.0.4389.114 from win10.
btw, my chrome is controlled by company. 
 
I tried a 20MB file on your demo page, it delayed a few seconds.

**Comment by rolandjitsu** [comment]
@peacedyc as the other issue states, it's most likely an issue with the browser on that platform.
