### ISSUE TITLE
onDrop with french (accent) characters doesn't work

### ISSUE THREAD

**Issue by bobkataboo** [react-dropzone/react-dropzone#1072]
Hello kind developers, I have the following problem:

When trying to upload a file with the following name "Capture d'écran.png" it does not work. When I change the name to image.png it works.

In the onDrop event, I wrote onDrop{files => console.log(files)} and in the not working case I receive an empty string as a name and the size is 0 kb. In the working example, it's all good. I have tested this in your demo as well, doesn't work either. See the photos below with the console logs.

https://i.stack.imgur.com/sq82b.png
https://i.stack.imgur.com/NvrG8.png

I really hope you can fix this.

Thanks,
Bo!

**Comment by rolandjitsu** [comment]
This needs some investigation.

**Comment by davidbasalla** [comment]
@bobkataboo do you have any more details about your browser, operating system etc? I just tested this and it all seems to work fine (OSX, Chrome v91). Same for the [basic example](https://react-dropzone.js.org/#section-basic-example):

<img width="972" alt="Screenshot 2021-06-28 at 17 03 25" src="https://user-images.githubusercontent.com/5112255/123659532-14dea780-d833-11eb-977b-74de1f946a7f.png">

**Comment by LoganDark** [comment]
@davidbasalla macOS can mask some of the issues you'll run into on Windows because it uses a Unix architecture, which has traditionally been very good with UTF-8, spaces in filenames, etc. Unfortunately, Windows is good at none of those things.

Anyway, I just tested for myself on Windows, and can't repro the issue either.

![image](https://user-images.githubusercontent.com/4723091/124585648-59a5a800-de0a-11eb-9687-43303a366b95.png)

@bobkataboo might have to provide some more details about their system, like the locale, version of Windows, browser used, etc.

**Comment by senorLobito** [comment]
Hi, I guess it won't help much but I experienced the same problem in Chrome - empty filename - if there are accents included. 

The important fact is, that it was working before. I tried to restart docker container with React and other stuff. What actually helped was to **restart the browser** which is weird. But it helped.

**OS:** Linux (Ubuntu 20.04.2 LTS),  **Browser:** Chrome 91.0.4472.164.  **react-dropzone:** 11.3.4

**Comment by saeedhemmati** [comment]
Same issue with Persian language

**Comment by rolandjitsu** [comment]
@senorLobito it sounds like it might be a browser issue.

@bobkataboo and @saeedhemmati could you guys provide some way to replicate this? And what env you're testing in?

**Comment by bobkataboo** [comment]
@rolandjitsu I have done further testing using the [basic example](https://react-dropzone.js.org/#section-basic-example). Here are the results:

System: Ubuntu 20.04.3 LTS
Browser: Version 1.31.91 Chromium: 95.0.4638.69 (Official Build) (64-bit)
Doesn't work
The same system using Firefox it works.

System: M1 macOS Big Sur -  11.5.1
Browser: Version 1.31.91 Chromium: 95.0.4638.69 (Official Build) (arm64)
Works

Please let me know if I can share any other details.

**Comment by codeBoCode** [comment]
Hello, 

We're having a lot of users with this issue. They're using French OSX. 

Please let me know if I can provide you with more information.

**Comment by rolandjitsu** [comment]
Unfortunately, I don't think there's anything we can do from our side. This sounds like a browser issue. This lib listens for change/drop events and then gets the file(s) and forwards to callbacks, there's nothing else that we do which would explain this behaviour. We do set `path` and `type` on files, which is inferred from `name` or `webkitRelativePath` if it exists, but that's as far as we go with file manipulations.

I suggest opening an issue at https://bugs.chromium.org/p/chromium/issues/list with the specifics described here.

I'll close this issue for now, but if there's any info on why this is happening and maybe if there's some Windows settings for it, I'll be glad to add some docs about it.

**Comment by marcus-franzen** [comment]
I've experienced this problem, but in the end it was not due to react-dropzone but a validation check comparing an AWS S3 URL to the file name with `if (url.includes(encodeURI(file?.name)))`. It seems that Safari is messing up encodeURI and therefore this comparison was always false.
