### ISSUE TITLE
preview not working after removing certain file from array in mulple files

### ISSUE THREAD

**Issue by sagartmg** [react-dropzone/react-dropzone#1073]
` onClick={()=>{
                                    let temp = [...files]
                                    temp = temp.filter((el,f_index)=>f_index != index)
                                    setFiles(temp);
                                }}`

is it due to this ?
`useEffect(() => () => {
        files.forEach(file => URL.revokeObjectURL(file.preview));
    }, [files]);`

**P.S.  this useEffect takes files values from the previous state rather than the new dropped files .. is this the default behaviour of this package ?**

Yes the preview are being changed but  this revoking seems important since it is mentioned in documentation. 
without removing this line, how to solve my problem

after removing a file from state, the blog url for preview does not always work 

![chrome_Hm47idrGY5](https://user-images.githubusercontent.com/49345528/121770700-9de6b500-cb8a-11eb-9af1-a1e4cd80aa3a.png)

**Comment by rolandjitsu** [comment]
@sagartmg this is more of a SO question. The revoke is there to cleanup the URIs we created for the images. You can change the effect to only revoke images that were removed (keep the state in some other var).
