### ISSUE TITLE
Click the dropzone does not open file selector on Android 11

### ISSUE THREAD

**Issue by atav32** [react-dropzone/react-dropzone#1075]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Clicking the dropzone on an Android browser does not reliably show the native file selector.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to https://codesandbox.io/embed/stupefied-kepler-btkpt
2. Tap the dropzone

**What is the expected behavior?**
Should open native Android file browser

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
- Android 11
- Chrome 91
- react-dropzone v11.3.2
- default browser permissions

**Comment by ml242** [comment]
I am running into the same bug on versions 9 and 10, and the only phone I can find is 11 and while the library worked fine with it, I really appreciate the sandbox because it made it so quick to test. I'm going to continue checking other android phones as I get my hands on them.

**Comment by rolandjitsu** [comment]
@atav32 @ml242 I cannot reproduce on latest Android. Have you tried the dropzone docs website?

**Comment by ml242** [comment]
I was not able to reproduce on my Android 11 but looking at bug reports and watching Fullstory I have evidence of it in happening with 11 too (both people letting the concierge know there were issues and video of rage clicking).

**Comment by rolandjitsu** [comment]
> I was not able to reproduce on my Android 11 but looking at bug reports and watching Fullstory I have evidence of it happening with android 11 too (both people letting the concierge know there were issues and video of rage clicking).
> 
> I'm going to use the HTML5 input=file for awhile on Android to see if that helps users.
> 
> Android Version came from the headers but it should be accurate.

Got it. I'm not sure what I can do given the fact that I cannot reproduce on the latest Android and I don't have access to older versions. Btw, the sandbox may behave differently from the docs website due to iframe usage and possible security restrictions?

**Comment by atav32** [comment]
Yup, can reproduce the bug on some of the examples on the website.

**Comment by ml242** [comment]
@atav32  - i tried 3 android 11's but couldn't reproduce with your link.

Getting closer on my problem, it seems like the users who are affected are using the android browser within another app that opens my site.

I've seen versions 7-11 affected.

When an app does that, is the browser in an iFrame? How do the permissions work, and could it just be a bug in their app? It's frustrating.

**Comment by rolandjitsu** [comment]
> @atav32 - i tried 3 android 11's but couldn't reproduce with your link.
> 
> Getting closer on my problem, it seems like the users who are affected are using the android browser within another app that opens my site.
> 
> I've seen versions 7-11 affected.
> 
> When an app does that, is the browser in an iFrame? How do the permissions work, and could it just be a bug in their app? It's frustrating.

It depends on how you've built your app. Normally, an app would use [intent](https://developer.android.com/reference/android/content/Intent.html#ACTION_VIEW), which would probably just open the URL in the default browser or ask you what to use.

But I suppose you're talking about opening the URL within the same app, which means you're most likely using a [WebView](https://developer.android.com/reference/android/webkit/WebView). If that's the case, there's some [extra steps](https://stackoverflow.com/questions/5907369/file-upload-in-webview) you need to take (use something like [Android-AdvancedWebView](https://github.com/delight-im/Android-AdvancedWebView)). Also check this [bug report](https://issuetracker.google.com/issues/36983532).

When I said iframes, I meant in the context of a web app that renders the dropbox within some iframe and maybe the browser having some issues with that.

**Comment by rolandjitsu** [comment]
@atav32 @ml242 is the comment above valid? Is that how you're using the dropzone? If yes, can you try the suggestion I linked to? If it works, we can document it for future users.

**Comment by thusinh1969** [comment]
I can NOT click to open file dialog on iPhone (Safari ) IOS 14.7.1, while it works fine on PC browsers.

Steve

**Comment by atav32** [comment]
@rolandjitsu I'm not using a webview.

I'm just trying the codesandbox example. I even tried it outside the codesandbox iframe, at https://btkpt.csb.app/, and it still doesn't work.

Looks like the only device I have this problem on is a Pixel 4a on Android 11. I'm not sure if it's specific to the Pixel 4 or to Android 11 (since I don't have another device on Android 11)

I've tried these other Androids, and they all worked as expected:
- Huawei P30 lite (Android 9)
- Galaxy S10 (Android 10)
- Pixel 2 (Android 10)
- Pixel XL (Android 10)

**Comment by rolandjitsu** [comment]
> @rolandjitsu I'm not using a webview.
> 
> I'm just trying the codesandbox example. I even tried it outside the codesandbox iframe, at https://btkpt.csb.app/, and it still doesn't work.
> 
> Looks like the only device I have this problem on is a Pixel 4a on Android 11. I'm not sure if it's specific to the Pixel 4 or to Android 11 (since I don't have another device on Android 11)
> 
> I've tried these other Androids, and they all worked as expected:
> 
> * Huawei P30 lite (Android 9)
> * Galaxy S10 (Android 10)
> * Pixel 2 (Android 10)
> * Pixel XL (Android 10)

I have a Pixel 3 w/ Android 11 and it works on that as well. But it seems unlikely to be due to the phone and more todo with the OS or browser version or something else.

**Comment by atav32** [comment]
Ok, finally figured it out. Chrome on this one device didn't have file access permissions 🤦

Unfortunately, the browser doesn't prompt me for file access permission and the setting isn't shown in any shortcut menus the way camera permissions sometimes are. Had to dig through the privacy settings to find it.

Sorry for the wild goose chase everyone! 🦆

**Comment by rolandjitsu** [comment]
> Ok, finally figured it out. Chrome on this one device didn't have file access permissions 🤦
> 
> Unfortunately, the browser doesn't prompt me for file access permission and the setting isn't shown in any shortcut menus the way camera permissions sometimes are. Had to dig through the privacy settings to find it.
> 
> Sorry for the wild goose chase everyone! 🦆

Glad you found the culprit. Are there any specific steps or behaviour that we could document for others? I wonder if the other reports in this post are related 🤔

**Comment by atav32** [comment]
Now that I know what to look for, it seems like it's happened to a couple other devs, https://github.com/react-dropzone/react-dropzone/issues?q=is%3Aissue+permission.

Not familiar enough with the File System Access to know this, but is there a way to check for persisted permissions and show an error message if file access is denied by the browser?

**Comment by rolandjitsu** [comment]
> Now that I know what to look for, it seems like it's happened to a couple other devs, https://github.com/react-dropzone/react-dropzone/issues?q=is%3Aissue+permission.

It could be.

> Not familiar enough with the File System Access to know this, but is there a way to check for persisted permissions and show an error message if file access is denied by the browser?

Basically, [file-selector](https://github.com/react-dropzone/file-selector) is the lib responsible for doing all the drop/select event handling (getting the files from the event). I'm not sure if there's an API that you can use to request permissions in Chrome. But if Chrome itself didn't have the permissions, I don't think that a web app could know that.

**Comment by atav32** [comment]
For me, I had to go to
1. Android settings
2. Privacy
3. Permission manager
4. Files and media

And make sure Chrome (other another browser) wasn't in the "Denied" list

**Comment by atav32** [comment]
> > Not familiar enough with the File System Access to know this, but is there a way to check for persisted permissions and show an error message if file access is denied by the browser?
> 
> Basically, [file-selector](https://github.com/react-dropzone/file-selector) is the lib responsible for doing all the drop/select event handling (getting the files from the event). I'm not sure if there's an API that you can use to request permissions in Chrome. But if Chrome itself didn't have the permissions, I don't think that a web app could know that.

It looks like the File System Access API can ask about the available browser permission state, https://developer.mozilla.org/en-US/docs/Web/API/FileSystemHandle/requestPermission. However, it's not implemented on Firefox and Safari...

It looks like it's part of the latest W3C draft, https://wicg.github.io/file-system-access/#api-filesystemhandle-requestpermission, so hopefully there'll be broader support in the next 24 months.

Would checking these permissions be in scope for this library?

**Comment by rolandjitsu** [comment]
> > > Not familiar enough with the File System Access to know this, but is there a way to check for persisted permissions and show an error message if file access is denied by the browser?
> > 
> > 
> > Basically, [file-selector](https://github.com/react-dropzone/file-selector) is the lib responsible for doing all the drop/select event handling (getting the files from the event). I'm not sure if there's an API that you can use to request permissions in Chrome. But if Chrome itself didn't have the permissions, I don't think that a web app could know that.
> 
> It looks like the File System Access API can ask about the available browser permission state, https://developer.mozilla.org/en-US/docs/Web/API/FileSystemHandle/requestPermission. However, it's not implemented in Firefox and Safari...

Ok, I see.

> It looks like it's part of the latest W3C draft, https://wicg.github.io/file-system-access/#api-filesystemhandle-requestpermission, so hopefully there'll be broader support in the next 24 months.

Yeah, unfortunately that might take some time.

> Would checking these permissions be in-scope for the [file-selector](https://github.com/react-dropzone/file-selector) library?

I don't think so. But we should definitely document this so that the users can handle it if necessary.

**Comment by ml242** [comment]
Hello all, I didn't have access to play with the Android app but it looks like a permissions problem and this is adding to the evidence. 

So - not a bug in this lib.

**Comment by rolandjitsu** [comment]
Since the culprit was permissions and considering that the file system access API is still a draft, I'm gonna close this issue. For any other issues, unrelated to this, please open a new issue.

On a side note, I've started using the file system access API in https://github.com/react-dropzone/react-dropzone/pull/1123 to open the file picker, so it may be a good time to start using the `requestPermission`. The only trouble I see with that is that I'd need to call that on every file that's dropped, and if the user selects a lot of them, that may result in a lot of dialogs?
