### ISSUE TITLE
Bug: MIT license, but it includes copyrighted commercial code

### ISSUE THREAD

**Issue by joecullin** [react-dropzone/react-dropzone#1076]
The addition of Doka's copyrighted files seems incompatible with the MIT license.

I can see in https://github.com/react-dropzone/react-dropzone/issues/1054 that you said, "Note that the files provided are probably not supposed to be distributed or used without a license. We have them there so that we can illustrate how the integration is done."

The auditors at my company aren't happy with that. It means we're either going to have to fork, or stick to an old version, or find an alternative. All for an "example" of something that we don't even use. I'm sure we're not the only company who will shy away from using the module because of this.

Did the Doka author give you an "ok" to include these files? If so, could you link some sort of disclaimer in the files?

Instead of including the actual files, a short README for Doka users would probably be better.

**Comment by rolandjitsu** [comment]
@joecullin you're welcome to make a PR with a disclaimer. I will also contact the doka onwer to ask them what to do about it.
