### ISSUE TITLE
Firefox not reporting mime type in Firefox when file is dropped as part of a folder

### ISSUE THREAD

**Issue by bmueller-sykes** [react-dropzone/react-dropzone#1077]
- [x ] I found a bug

When I drop a folder which contains an XML file in Firefox (89.0.2) on the Mac (11.4), the `type` property of the xml file in the array that is handed to acceptedFiles is empty. However, if I drop just that XML file by itself onto the drop target, the type is reported. I'm using the basic example from the docs (below). I haven't been able to replicate this behavior in other browsers to this point. If I do, I'll update the ticket.

If I drop just the XML file in the console, I see this:
<img width="591" alt="Screen Shot 2021-06-25 at 3 52 37 PM" src="https://user-images.githubusercontent.com/12236379/123484066-5f5eea80-d5cd-11eb-9107-4342369f5559.png">

However, if I drop a folder called `myfolder` with this structure:

```
myfolder (root folder)
    - test.xml
    - content (sub folder)
        - orange-lady.png 
```

...then I see this result:
<img width="551" alt="Screen Shot 2021-06-25 at 3 55 03 PM" src="https://user-images.githubusercontent.com/12236379/123484295-b82e8300-d5cd-11eb-903c-d28260fbd8ba.png">

The png file has a type attached, but `test.xml` has a blank type. Given that Firefox reports it when it's dropped by itself, it seems like this is a case of the type not being carried over when react-dropzone processes a folder.

This is the code in its entirety. I'm on `react-dropzone 11.3.4` and `react 17.0.2`

```
import React from 'react';
import {useDropzone} from 'react-dropzone';

function DropTest(props) {
  const {acceptedFiles, getRootProps, getInputProps} = useDropzone({multiple: true});

  const files = acceptedFiles.map(file => {
    console.log("FILE", file)
    return (
      <li key={file.path}>
      {file.path} - {file.size} bytes
    </li>
    )
  });

  return (
    <section className="container">
      <div {...getRootProps({className: 'dropzone'})}>
        <input {...getInputProps()} />
        <p>Drag 'n' drop some files here, or click to select files</p>
      </div>
      <aside>
        <h4>Files</h4>
        <ul>{files}</ul>
      </aside>
    </section>
  );
}

export default DropTest;
```

**Comment by rolandjitsu** [comment]
@bmueller-sykes the folder reading is done in [react-dropzone/file-selector](https://github.com/react-dropzone/file-selector). You should move the issue there.

It's possible Firefox doesn't return the type with the current API we use in that lib to recurse the folders. It needs more investigation.

**Comment by rolandjitsu** [comment]
I can confirm this happens in Firefox. Gonna try to see if it can be fixed.

**Comment by rolandjitsu** [comment]
Ok, I think this got fixed with https://github.com/react-dropzone/file-selector/commit/8bf52d4d288825d292c0e0d25c46a5f734ba6700.

https://user-images.githubusercontent.com/1479737/152092563-03d06afc-b410-4f35-82f8-bcea87f642f4.mp4

And the version got bumped in https://github.com/react-dropzone/react-dropzone/pull/1123 which I'll merge soon.

**Comment by rolandjitsu** [comment]
Closed by https://github.com/react-dropzone/react-dropzone/commit/3ad4f007d70401e1d9adbc93ba2dfd69cc8c2a27. This is the best I could do for now.

**Comment by haywirez** [comment]
Discovered that this unfortunately also happens in Chrome (104.0.5112.79), not just Firefox 😕 Strangely despite other file drag & drop issues Safari tech preview does have the correct listing behavior.
