### ISSUE TITLE
Need to limit the Total file size limit to 5mb 

### ISSUE THREAD

**Issue by ashacr** [react-dropzone/react-dropzone#1078]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug: Unable to limit the total file size
- [ ] I want to propose a feature

**What is the current behavior?**
Individual file size limiting not the total file size

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Unable to show the error message when total file exceeds the 5 mb
1.

**What is the expected behavior?**
Show error message total file size exceeds the max limit 5mb
1.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by ashacr** [comment]
any suggestion please

**Comment by LoganDark** [comment]
The file object contains `size` which is a size in bytes, you can limit that to a max of `5242880` for 5MB.

**Comment by ashacr** [comment]
> The file object contains `size` which is a size in bytes, you can limit that to a max of `5242880` for 5MB.

Yes. This scenario will work only on individual file size not the overall files size. example...
file 1 - 1Mb
file 2 - 2MB
file 3 - 3 Mb etc...
This scenario I have to calculate the total file size and display the error message for the last file which exceeding 5 MB.

**Comment by LoganDark** [comment]
> > The file object contains `size` which is a size in bytes, you can limit that to a max of `5242880` for 5MB.
> 
> Yes. This scenario will work only on individual file size not the overall files size. example...
> file 1 - 1Mb
> file 2 - 2MB
> file 3 - 3 Mb etc...
> This scenario I have to calculate the total file size and display the error message for the last file which exceeding 5 MB.

You can add up the sizes of all the files that have been uploaded. This is out of scope for react-dropzone.

**Comment by rolandjitsu** [comment]
> > The file object contains `size` which is a size in bytes, you can limit that to a max of `5242880` for 5MB.
> 
> Yes. This scenario will work only on individual file size not the overall files size. example...
> file 1 - 1Mb
> file 2 - 2MB
> file 3 - 3 Mb etc...
> This scenario I have to calculate the total file size and display the error message for the last file which exceeding 5 MB.

This sort of logic has to be implemented on the user side. The dropzone cannot cover every single scenario/use case that users have. It provides the minimum features that are good enough to cover most use cases and it gives enough flexibility to allow the users to impl. their own behaviours.

**Comment by ashacr** [comment]
It's good practice to avoid spreading for jsx attribute . This prevents accidently passing **dangerouslySetInnerHMTL** to an element
![image](https://user-images.githubusercontent.com/13048236/130760373-650ce849-19e2-4ebc-b39d-962ff101d1f5.png)
How we can avoid the spread operator inside the input  for security purpose, what could be alternative solution?

**Comment by LoganDark** [comment]
I think if you are allowing the user to control all props of your element (even adding new ones) that is a security vulnerability anyway. Especially since it can contain attributes that control javascript execution
