### ISSUE TITLE
Drozone style class | isn't loaded

### ISSUE THREAD

**Issue by abelardolg** [react-dropzone/react-dropzone#1080]
- [ x] I found a bug

Hi there,
I installed the last version:
`"react-dropzone": "^11.3.4",`

When I dropped your example into my code:
https://react-dropzone.js.org/#section-previews

the dropzone style class wasn't loaded:
![image](https://user-images.githubusercontent.com/22522883/124388481-6bd8f680-dce3-11eb-9aba-014095b7e6d4.png)

Where is  this style class defined into your example, please?
` <div {...getRootProps({className: 'dropzone'})}>`
Brs.
[FileUploader.component.txt](https://github.com/react-dropzone/react-dropzone/files/6760165/FileUploader.component.txt)

**Comment by rolandjitsu** [comment]
@abelardolg that's a global class declared in 
https://github.com/react-dropzone/react-dropzone/blob/623623e8a8363d06e098aee5eeade3927e8def55/examples/theme.css#L15

**Comment by e-hop** [comment]
i'm faving the same issue. Just dragged the example and the css doesn't shows

**Comment by Ishu1998** [comment]
I had to import it manually, works...

```
import { useDropzone } from "react-dropzone";
import "react-dropzone/examples/theme.css";
```

**Comment by Rickgrendel** [comment]
Is it an idea to create a PR with just a normal CSS folder made for distribution? It really doesn't seem like good practice to import something from an examples folder.

**Comment by rolandjitsu** [comment]
Styling is the user's responsibility and not in the scope of this library. And the examples we provide are just that, examples, and not meant for use in production.
