### ISSUE TITLE
Take photo (from camera) option is enabled on mobile when trying to accept GIF only

### ISSUE THREAD

**Issue by react-dev92** [react-dropzone/react-dropzone#1084]
Hi,

I'm using latest version of react-dropzone. I found a bug and want to report it

Here's the behaviour:

I'm using dropzone to accept only specific file types by specifying the mimetype as per https://react-dropzone.js.org/#section-accepting-specific-file-types. When on mobile devices, on clicking the browse button, a menu is shown which has gallery, file system and camera (Take photo or video) options

- When specifying video/mp4 type, "Take Video" option has to be shown and camera opened should only have video tab.
- When specifying image/jpg type, "Take Photo" option has to be shown and camera opened should only have photo tab.
- When specifying video/mp4 and image/jpg types, "Take Photo or Video" option has to be shown and camera opened has both video and photo tab

All working well until now

- However, when specifying video/mp4 and image/gif types, "Take Photo or Video" option is shown. GIF images cannot be captured from a mobile device camera and this allows user to take photos and pass it to the dropzone and there error has to be shown. 

The issue
For image/gif mimetype - Take Photo option should not be shown in the browse menu. 
When specifying video mime types and image/gif mimetype in accepted list, "Take Photo or Video" option should not be shown. Only the "Take Video" option should be shown. 

Please help me with getting this behaviour fixed.

I'm testing on iOS 14 safari browser and Android 10 Chrome 92 browser.

Attaching screenshots of the menu below

![Take_photo_or_video](https://user-images.githubusercontent.com/88501261/128384095-f4e7eb9c-4699-42f4-9bcd-cdf30517dc76.PNG)
![Take_photo](https://user-images.githubusercontent.com/88501261/128384124-8fb0d9b1-9258-4a2e-a482-cd4c5f058a5d.PNG)

**Comment by react-dev92** [comment]
@rolandjitsu Can you take a look at this issue and help me fix this.

**Comment by rolandjitsu** [comment]
@react-dev92 I don't think there's anything we can do about this. This behaviour is implemented in the browser and it's probably different in each browser. This lib doesn't do anything specific to mime types, it just sets the accept property on the input.

**Comment by sakshijha8** [comment]
Delete the <input {...getinputprops}/>, it is worked for me.
