### ISSUE TITLE
[suggestion] adding role=button, aria-roledescription to getRootProps might enhance accessiblity

### ISSUE THREAD

**Issue by mcha-dev** [react-dropzone/react-dropzone#1085]
- [ ] I found a bug
- [x] I want to propose a feature

Hello,

I think if we make `getRootProps` return the following props, the component will be more accessible 

```
role="button"
aria-roledescription="dropzone area that accepts files"
```
- [conesandbox link](https://codesandbox.io/s/practical-austin-o5ude?file=/src/index.tsx)
- Demo with Apple's Voice Over  (🔊on)

https://user-images.githubusercontent.com/13101565/128459803-344f2e2c-033e-4db6-a908-d35e9bcece52.mov

> https://www.w3.org/TR/wai-aria-1.1/#aria-roledescription

**Comment by rolandjitsu** [comment]
I think it's the user's (the dev) responsibility to add the right accessibility tags as they may vary by use case. So I'd like to avoid adding them to the lib as it will introduce unnecessary management of these props (we'll need to let the user set them as well).

Btw, I think the docs suggest passing extra props via `getRootProps({extraProp: ...})` to avoid overriding props that the dropzone needs.

**Comment by mcha-dev** [comment]
I agree that it is the users' responsibility. I just thought since `getRootProps()` is attaching `onClick` event on the target, it might as well set a proper `role`.

Maybe a note [under the sample in the readme](https://github.com/react-dropzone/react-dropzone#usage) to remind users to provide proper accessibility properties would be enough then.

> Btw, I think the docs suggest passing extra props via `getRootProps({extraProp: ...})` to avoid overriding props that the dropzone needs.

Thanks for pointing that out.

**Comment by rolandjitsu** [comment]
@mcha-dev feel free to make a PR with that.
