### ISSUE TITLE
'ErrorCode' is not exported from 'react-dropzone'

### ISSUE THREAD

**Issue by strmer15** [react-dropzone/react-dropzone#1091]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

When I attempt to use `ErrorCode.FileTooLarge` in my Typescript React project, I get the error `Attempted import error: 'ErrorCode' is not exported from 'react-dropzone'.` Looking at the ESM distribution, it looks like the enum defined in the typings is not actually available at runtime from the library.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. import { ErrorCode } from 'react-dropzone'
1. Attempt to use `ErrorCode.FileTooLarge` in your Typescript code.

**What is the expected behavior?**

I'd expect that I could use the `ErrorCode` enum in my code to reference error code strings when detecting why a file was rejected..

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

`react` 16.14.0
`react-dropzone` 11.4.0
`typescript` 4.4.3

**Comment by rolandjitsu** [comment]
Yes, it's true. The typings export that type but there's no JS object for it. Would you mind making a PR to fix this? Otherwise I can do it later this week.

**Comment by strmer15** [comment]
> Yes, it's true. The typings export that type but there's no JS object for it. Would you mind making a PR to fix this? Otherwise I can do it later this week.

Thanks for the reply! I've created a PR to add this to the runtime whenever you get a chance to look at it.
