### ISSUE TITLE
ref.open() does not work

### ISSUE THREAD

**Issue by randyou** [react-dropzone/react-dropzone#1098]
- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
ref.open() does not work .

**If the current behavior is a bug, please provide the steps to reproduce.**
https://codesandbox.io/s/6m2dx
1. Use Chrome Version 94.0.4606.61.
2. Click the button 'open'.

**What is the expected behavior?**
Open file selector.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
macOS Catalina version 10.15.7 
Chrome Version 94.0.4606.61 (Official Build) (x86_64)

**Comment by rolandjitsu** [comment]
I'm on the same Chrome version, but Big Sur and I cannot replicate.

**Comment by randyou** [comment]
@rolandjitsu I reset my MacOS, it fixed. thks.
