### ISSUE TITLE
Missing example for React without JSX

### ISSUE THREAD

**Issue by rpsirois** [react-dropzone/react-dropzone#1101]
- [ ] I found a bug
- [X] I want to propose a feature

**What is the current behavior?**
Unable to get examples to work.

**If the current behavior is a bug, please provide the steps to reproduce.**
Examples require JSX.

**What is the expected behavior?**
If this is a React library, then it should work with React and not require JSX (per https://reactjs.org/docs/react-without-jsx.html).

**If this is a feature request, what is motivation or use case for changing the behavior?**
Not everyone uses JSX who also use React.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
https://reactjs.org/docs/react-without-jsx.html

Thanks.

**Comment by rpsirois** [comment]
```
import React from 'react'
const e = React.createElement

import Dropzone from './dropzone.js'

export default function App() {
    return e( 'section', { className: 'section' }, [
        e( 'div', { className: 'container' }, [
            e( Dropzone )
        ])
    ])
}
```
```
import React, { useCallback } from 'react'
const e = React.createElement

import { useDropzone } from 'react-dropzone'

export default function Dropzone() {
    const onDrop = useCallback( files => {
        console.log( files )
        })
    }, [] )

    const { getRootProps, getInputProps } = useDropzone({ multiple: false, onDrop })

    return e( 'div', { ...getRootProps() }, [
        e( 'input', { ...getInputProps() } )
        , e( 'p', {}, 'Drop File Here' )
    ])
}
```

This code results in the #useCallback call throwing `Error: Invalid hook call.` (React 17.0.2).

**Comment by rolandjitsu** [comment]
@rpsirois I've never attempted doing this, but I guess it's worth investigating if we can make it work.

**Comment by rolandjitsu** [comment]
@rpsirois please see https://react-dropzone.js.org/#section-no-jsx. I hope that's good enough.
