### ISSUE TITLE
URGENT :Click is not working any more on drop zone.

### ISSUE THREAD

**Issue by youngheart12** [react-dropzone/react-dropzone#1103]
I suddenly realised that dropzone is only supporting the dragged file now not on click, i thought it is a bug that i introduced but on looking to your repo and or live example at this https://react-dropzone.js.org/
i found it is not working here also, 

**It can affect lot of service depended on you,**

**Comment by HavermansStef** [comment]
Not really. Also experiencing the issue on Chrome 95 and on Firefox.

**Comment by swoppy** [comment]
It works for me now on Chrome 96

**Comment by fosteman** [comment]
Same issue here. Version 95.0.4638.69 (Official Build) (arm64) - does not click in the sandbox nor in my react build https://codesandbox.io/embed/vigorous-wildflower-trymo

**Comment by fosteman** [comment]
Just updated to Version 96.0.4664.55 (Official Build) (arm64), and it works again.

**Comment by rolandjitsu** [comment]
It doesn't seem to be an issue with this lib, or I don't see how to fix this, so I'll close it for now.
