### ISSUE TITLE
How can I disable folder to be dropped ?

### ISSUE THREAD

**Issue by shlroland** [react-dropzone/react-dropzone#1105]
`react-dropzone`: 11.0.1
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [x] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1.
1.
1.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
a folder could contain many file, but I want to upload so much files. So how can I disable folder to be dropped
**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by rolandjitsu** [comment]
You cannot. You can see the constraints you can use at https://react-dropzone.js.org/#src.
