### ISSUE TITLE
Accessibility improvement

### ISSUE THREAD

**Issue by tommyka** [react-dropzone/react-dropzone#1110]
I have noticed that when using ```useDropzone``` the root element don't get any role or aria-label.

Because the root element gets to be focusable and essentially works as a button, it could be a good idea to use the role attribute to make screenreaders read it out as a button.

That together with a label prop in ```useDropzone``` that set a aria-label on the root element so it will be read out like a button action.

In short.
Add role=button and aria-label in root props

**Comment by rolandjitsu** [comment]
@tommyka that sounds like a great improvement. Please make a PR with that.

**Comment by rolandjitsu** [comment]
Actually, this is up to the user (shouldn't be forced by us if the user decides not to allow click). So if you'd like to set any extra props, you can easily do so via:
```jsx
import React from 'react';
import {useDropzone} from 'react-dropzone';

function Basic(props) {
  const {acceptedFiles, getRootProps, getInputProps} = useDropzone();
  
  const files = acceptedFiles.map(file => (
    <li key={file.path}>
      {file.path} - {file.size} bytes
    </li>
  ));

  return (
    <section className="container">
      <div {...getRootProps({className: 'dropzone', 'aria-label': 'dropzone'})}>
        <input {...getInputProps()} />
        <p>Drag 'n' drop some files here, or click to select files</p>
      </div>
      <aside>
        <h4>Files</h4>
        <ul>{files}</ul>
      </aside>
    </section>
  );
}
```

Note the `...getRootProps({className: 'dropzone', 'aria-label': 'dropzone'})` which sets `aria-label`.

Are are you asking for something else?

**Comment by rolandjitsu** [comment]
Gonna close for now as I think that being explicit, rather than implicit, is a better option. And some users may want to set different role and aria-label than what we decide on.

**Comment by tommyka** [comment]
As long as you are making something that behaves like a button, a blind or low-sight user should be told that its a button.
This should be the default, then it could be overwritten but the developer if they want another role.

If its up to the developer to set everything, then it don't make sense that it makes a click listener on with getRootProps without explicitly being told to make it clickable. But that would make the component less usable.
I do agree that aria-label should be set by the developer, because the text can be inferred form the content of the element.
But without the role of button, it would not be interpreted correctly by the screenreaders.

**Comment by rolandjitsu** [comment]
> As long as you are making something that behaves like a button, a blind or low-sight user should be told that its a button. This should be the default, then it could be overwritten but the developer if they want another role.

Sure, we can do that. Add a default `role='button'`.

**Comment by rolandjitsu** [comment]
Will be solved by https://github.com/react-dropzone/react-dropzone/pull/1124.

**Comment by qpido** [comment]
Suggestion for improvement: 
do not add the role by default if setting 'noClick: true'.
I'm using the whole viewport as a drop area so imho the role doesnt make sense in this case.
What do you think?

**Comment by rolandjitsu** [comment]
> Suggestion for improvement: do not add the role by default if setting 'noClick: true'. I'm using the whole viewport as a drop area so imho the role doesnt make sense in this case. What do you think?

That makes sense.

**Comment by khmelevskii** [comment]
Is it possible to remove role attribute?
