### ISSUE TITLE
Incorrect styles applied when attempting to drop a file > set maxSize

### ISSUE THREAD

**Issue by Marius-AdamDT** [react-dropzone/react-dropzone#1114]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Incorrect styles are applied when attempting to drop a file > set maxSize.

**If the current behavior is a bug, please provide the steps to reproduce.**

1 .Created a [Code Sandbox that reproduces the bug](https://codesandbox.io/s/blazing-wildflower-y53mv?file=/src/Dropzone.js). 
2. Attempt to drag a file larger than 2mb. 
3. Notice the green border on the dropzone

**What is the expected behavior?**
Rejected styles should be applied, in this case, red border.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
React-dropzone v 11.4.2

**Comment by rolandjitsu** [comment]
I cannot reproduce in Chrome 96.0.4664.110, macOS.

**Comment by Marius-AdamDT** [comment]
Chrome Version 97.0.4692.71, macOS.
Dropped file size 23MB 

https://i.gyazo.com/b5eaec018c55fa63a1e8cc2a15398ae6.gif

**Comment by ppanthony** [comment]
I can confirm I'm also seeing this behaviour.

Seems to stem from the fact that draggedFiles is a data transfer item object as opposed to a real file on drag over, but the fileMatchSize function checks each dragged file for a .size key, which it cant find. As such, it returns true out of the the fileMatchSize function. 

`const isDragAccept = fileCount > 0 && allFilesAccepted({ files: draggedFiles, accept, minSize, maxSize, multiple, maxFiles })`
```

getFilesFromEvent callback here I think could potentially 

export function fileMatchSize(file, minSize, maxSize) {
  if (isDefined(file.size)) {
    if (isDefined(minSize) && isDefined(maxSize)) {
      if (file.size > maxSize) return [false, getTooLargeRejectionErr(maxSize)];
      if (file.size < minSize) return [false, getTooSmallRejectionErr(minSize)];
    } else if (isDefined(minSize) && file.size < minSize)
      return [false, getTooSmallRejectionErr(minSize)];
    else if (isDefined(maxSize) && file.size > maxSize)
      return [false, getTooLargeRejectionErr(maxSize)];
  }
  return [true, null];
}
```

**Comment by rolandjitsu** [comment]
Ah, yes. I missed the accept prop. I was using a zip file to test, which didn't match the accept and worked as expected.

Yes, during drag, we don't have access to the file data, so we cannot tell what's its size (at least that was the case at the time I've worked on the implementation).

So I'm not sure if we can do anything about that.

**Comment by ppanthony** [comment]
@rolandjitsu - https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/getAsFile - I came across that method when investigating, haven't tried it out or anything but wondering if if is relevant here, or if the datatransfer item object is more internal than that.

**Comment by rolandjitsu** [comment]
> @rolandjitsu - https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/getAsFile - I came across that method when investigating, haven't tried it out or anything but wondering if if is relevant here, or if the datatransfer item object is more internal than that.

@ppanthony yeah, that's the API we use (if you checkout the [file-sector](https://github.com/react-dropzone/file-selector) lib which react-dropzone uses).

> I've had a bit of time to investigate this further. Turns out the HTML5 spec doesn't allow you to do this. The dragenter event doesn't have access to the actual files  ...

Yes, I've been down that road and the conclusion was the same. There's not cross-browser reliable way of getting all the info we need in order to accurately set the  `isDragAccept`/`isDragReject` props while dragging.

> Sorry for wasting anyone's time.

No worries.

**Comment by Marius-AdamDT** [comment]
Thank you both @rolandjitsu, @ppanthony  for taking the time to look into this and the detailed explanations. Feel free to close the issue
