### ISSUE TITLE
Typescript error raised for catch variable

### ISSUE THREAD

**Issue by GSuggitt** [react-dropzone/react-dropzone#1115]
I am using 2.11.0
 
**Do you want to request a *feature* or report a *bug*?**

- [x ] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
I recently upgraded to Typescript 4.5.4, but I believe this is an isse with any Typescript after 4.4

Upon compiling my code I get the error:
node_modules/react-dropzone-uploader/dist/Dropzone.tsx:504:44 - error TS2571: Object is of type 'unknown'.

The code causing the issue is:
```
uploadFile = async (fileWithMeta: IFileWithMeta) => {
    const { getUploadParams } = this.props
    if (!getUploadParams) return
    let params: IUploadParams | null = null
    try {
      params = await getUploadParams(fileWithMeta)
    } catch (e) {
      console.error('Error Upload Params', e.stack)
    }
    if (params === null) return
    const { url, method = 'POST', body, fields = {}, headers = {}, meta: extraMeta = {} } = params
    delete extraMeta.status
```

The error is on "e.stack" as e is typed as unknown.

I believe that before Typescript 4.4, the error variable defaulted to "any". Now, if I am running Typescript with "strict" option true, the type of the catch variable defaults to "unknown"

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by rolandjitsu** [comment]
@GSuggitt if you check https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#use-unknown-catch-variables, the way to handle errors is:
```ts
try {
    executeSomeThirdPartyCode();
}
catch (err) { // err: unknown

    // Error! Property 'message' does not exist on type 'unknown'.
    console.error(err.message);

    // Works! We can narrow 'err' from 'unknown' to 'Error'.
    if (err instanceof Error) {
        console.error(err.message);
    }
}
```

On a side note, the [stack](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack) property is a non-standard property.

**Comment by rolandjitsu** [comment]
Are you taking about the shared example above or which code?

In any case, I think that using `err instanceeof Error` should work as typescript will infer the type from there. Which is what they suggest doing too in the link I shared.

**Comment by GSuggitt** [comment]
It is not MY code that is failing, it is YOURS

When I build my project I get the error:

node_modules/react-dropzone-uploader/dist/Dropzone.tsx:504:44 - error TS2571: Object is of type 'unknown'.

504       console.error('Error Upload Params', e.stack)

and YOUR code is:

  uploadFile = async (fileWithMeta: IFileWithMeta) => {
    const { getUploadParams } = this.props
    if (!getUploadParams) return
    let params: IUploadParams | null = null
    try {
      params = await getUploadParams(fileWithMeta)
    } catch (e) {
      console.error('Error Upload Params', e.stack)
    }
    if (params === null) return
    const { url, method = 'POST', body, fields = {}, headers = {}, meta: extraMeta = {} } = params
    delete extraMeta.status


So please, fix your code so that Typescript doesn't complain.

In the meantime I am setting Typescript option useUnknownInCatchVariables to false, although I am loath to do this.




________________________________

**Comment by rolandjitsu** [comment]
> It is not MY code that is failing, it is YOURS

I haven't mentioned anything about that in my comment. I simply asked which code you were talking about that it doesn't compile. And I provided a suggestion for how to handle it which is what the typescript team suggests doing.

> When I build my project I get the error:
> node_modules/react-dropzone-uploader/dist/Dropzone.tsx:504:44 - error TS2571: Object is of type 'unknown'.

I've actually just noticed that you're reporting the issue in the wrong repository. You may want to head to https://github.com/fortana-co/react-dropzone-uploader and report there.

>  So please, fix your code so that Typescript doesn't complain.

This is an open source project, so you cannot just expect that raging about it in a comment will fix whatever issues you're facing. You could be more polite and maybe contribute yourself 😉
