### ISSUE TITLE
Inject block programmatically?

### ISSUE THREAD

**Issue by orbachar** [react-dropzone/react-dropzone#1116]
Hi I wonder if is there a way to inject a new block to editor js, programmatically, from an outside event, while allowing to edit the content with the regular behavior of ```onChange``` prop.

the way I though of doing that, was to listen to onChange prop as usual, get the blocks on save, and when an outside event happens, push a new block to the content returned from ```onChange```, and pass it on ```value``` prop. 
Unfortunately using both ```value``` and ```onChange``` props cause infinite loop. 

I wonder if is there another way achieving that?

**Comment by rolandjitsu** [comment]
@orbachar I'm not sure I follow. The dropzone is not an editor. Maybe you submitted the issue to the wrong repo?

**Comment by orbachar** [comment]
lol you are right. sorry wrong repo
