### ISSUE TITLE
React 18 Support

### ISSUE THREAD

**Issue by Sandeep06Dev** [react-dropzone/react-dropzone#1121]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

1. Unable to install react-dropzone with react18.rc version.

**What is the expected behavior?**

**It should be supported as react 18 will be launched by next month**

**Comment by rolandjitsu** [comment]
An example would be preferred.

**Comment by Sandeep06Dev** [comment]
Unable to install it using **npm install react-dropzone** command in react-18. it shows a dependency error.

**Comment by rolandjitsu** [comment]
> Unable to install it using **npm install react-dropzone** command in react-18. it shows a dependency error.

Could you add the error you get here?

**Comment by rolandjitsu** [comment]
Working on this in https://github.com/react-dropzone/react-dropzone/pull/1144, just not sure how to release (maybe as RC from the next branch 🤔 ).
