### ISSUE TITLE
Doesnt find mimetype (application/vnd.ms-outlook) for .msg files. isDragAccept takes files: draggedFiles, and the type in here comes empty.

### ISSUE THREAD

**Issue by RubenRodrigues26** [react-dropzone/react-dropzone#1122]
**Do you want to request a *feature* or report a *bug*?**

- [X] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Current behaviour in steps.
**If the current behavior is a bug, please provide the steps to reproduce.**

1.Drag a .msg file into the dropzone.
2.As an example if you have a custom feature where rejected files makes the dropzone red, it shows red.
draggedFiles as a type property and its a empty string as if I uploaded a html file it would be text/html in
this scenario should be application/vnd.ms-outlook
![image](https://user-images.githubusercontent.com/22688876/152007854-edd9f928-4fbd-41a6-925d-e178bbfd5a2a.png)

3.The file its still able to be uploaded.

**What is the expected behavior?**
Dropzone regognized the file type and dropzone its green.
**If this is a feature request, what is motivation or use case for changing the behavior?**
From my undertanding it should be working for .msg is not then please consider as a feature instead of a defect.
**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Windows 10, Chrome and react=dropzone all to the latest version.

**Comment by rolandjitsu** [comment]
@RubenRodrigues26 have you read through [accepting specific file types](https://react-dropzone.js.org/#section-accepting-specific-file-types)? There's a good chance that there's nothing we can do about it.

**Comment by RubenRodrigues26** [comment]
Hi,

Yes I have read this and either doesn't work for .msg file because for some
reason can't find the mimetype and it's a bug or could be a browser issue
with .msg files it's that's the case then I suppose it fall inter your
documentation for browser limitation, so I guess the question is really
that should it find the mimetype for .msg files?

A terça, 1/02/2022, 23:54, Roland Groza ***@***.***> escreveu:

**Comment by rolandjitsu** [comment]
@RubenRodrigues26 it sounds like a browser limitation in the sense that it doesn't understand the mime type for that file. If you check [common MIME types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types), the file ext is not shown there.

The only thing we can do is set the type in [file-selector](https://github.com/react-dropzone/file-selector/blob/d48d9bc355cd99a1aa50478c37e8c68da82cb8da/src/file.ts#L1), but this won't help with validation while dragging.

**Comment by rolandjitsu** [comment]
Just pushed https://github.com/react-dropzone/file-selector/commit/8bf52d4d288825d292c0e0d25c46a5f734ba6700 which should help set the right MIME type on the file object.

**Comment by RubenRodrigues26** [comment]
Hi,

Makes sense so the only think that could make it work it's to extende the
drop zone functionality and make also take the name and therefore the file
extension at the drag time so it could recognize any file?

A quarta, 2/02/2022, 03:50, Roland Groza ***@***.***>
escreveu:

**Comment by rolandjitsu** [comment]
> Hi, Makes sense so the only think that could make it work it's to extende the drop zone functionality and make also take the name and therefore the file extension at the drag time so it could recognize any file?

Some data is not accessible during drag and there's nothing we can do about that. Whatever is possible is already implemented.

**Comment by RubenRodrigues26** [comment]
Hi Roland,

Thank you for the feedback and your time really appreciated, usually it's a
hard thing to accept, in software development, that something doesn't work
but sometimes that's the hard reality. Have a great day we can
resolve/remove this issue.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rolandjitsu** [comment]
You can check the [spec](https://html.spec.whatwg.org/multipage/dnd.html#security-risks-in-the-drag-and-drop-model) and read more [here](https://stackoverflow.com/a/28487486/1092007). What that means is that we can only see the `kind` and `type` while dragging (`ondragstart` event). So as long as you use MIME types for `accept` and not file extensions, we can validate. But also note that if you drag a directory, we'll not be able to see the contents until dropped, hence no reliable validation. 

Then there's also the cross-browser compatibility: you may not get the same behaviour in all browsers.

No worries. If you find any other issues please feel free to open another issue.
