### ISSUE TITLE
[BUG] Version 11.6.0 not backward compatible for the accept option

### ISSUE THREAD

**Issue by rolandjitsu** [react-dropzone/react-dropzone#1131]
### Discussed in https://github.com/react-dropzone/react-dropzone/discussions/1130

<div type='discussions-op-text'>

<sup>Originally posted by **Seijinx** February  5, 2022</sup>
I have the feeling `11.6.0` should have been a `12.0.0` since it breaks the `accept` option for `useDropzone` no more supporting extensions filtering.

For now I have to freeze to `11.5.3` to delay an important refactor on my side.

What do you think ?</div>

**Comment by akaSybe** [comment]
thanks, you saved my day
