### ISSUE TITLE
Add the posibility of specifying the file extensions with the useFsAccessApi

### ISSUE THREAD

**Issue by davbrito** [react-dropzone/react-dropzone#1141]
https://github.com/react-dropzone/react-dropzone/blob/650af6265c422b216eeb4c3aa77ed37605d1b3d5/src/utils/index.js#L183-L202

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/window/showOpenFilePicker#parameters)

> `accept`: An [Object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object) with the keys set to the [MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types) and the values an [Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) of file extensions (see below for an example).

For example:

```js
const pickerOpts = {
  types: [
    {
      description: 'Images',
      accept: {
        'image/*': ['.png', '.gif', '.jpeg', '.jpg']
      }
    },
  ],
  excludeAcceptAllOption: true,
  multiple: false
};
```

There should be a way to especify the array of file extensions instead of the MIME type only.

**Comment by rolandjitsu** [comment]
@davbrito there's a plan, see https://github.com/react-dropzone/react-dropzone/discussions/1136, to address this issue. We need to find a way that works for both the FS access API and the input click method.

**Comment by rolandjitsu** [comment]
@davbrito so I've got a PR in the pipeline which will address this. But it will be a breaking change. And there's a few things I need to cleanup before. 

But the way to set the `accept` attr now is:
```js
```

**Comment by davbrito** [comment]
That seems nice. If there is anything that I can do to help just tell me.

**Comment by steveoh** [comment]
Does this mean that 

```js
const acceptableFileTypes = ['.pdf', '.doc', '.docx', '.jpeg', '.jpg', '.png'];
```

would be come

```js
const acceptableFileTypes = {
      'image/*': ['.jpg', '.jpeg', '.png'],
      'application/pdf': ['.pdf'],
      'application/msword': ['.doc'],
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document': ['.docx'],
}
```

**Comment by dolphin0618** [comment]
> 这是否意味着
> 
> ```js
> const acceptableFileTypes = ['.pdf', '.doc', '.docx', '.jpeg', '.jpg', '.png'];
> ```
> 
> 会成为
> 
> ```js
> const acceptableFileTypes = {
>       'image/*': ['.jpg', '.jpeg', '.png'],
>       'application/pdf': ['.pdf'],
>       'application/msword': ['.doc'],
>       'application/vnd.openxmlformats-officedocument.wordprocessingml.document': ['.docx'],
> }
> ```

```
const acceptableFileTypes = {
      'image/*': ['.jpg', '.jpeg', '.png'],
      'application/*': ['.pdf','.doc','.docx']
}
```
