### ISSUE TITLE
Setup to allow autoFocus to work or something similar

### ISSUE THREAD

**Issue by Nate-Wilkins** [react-dropzone/react-dropzone#1145]
When setting up react-dropzone there's no good way to auto focus the element.
I've tried using refs and auto focusing after mount but it doesn't work.

Is there a way to get this built directly into the library?

Does anyone know if there is a workaround to this?

Here's a sandbox demonstrating the problem.
https://stackblitz.com/edit/react-ts-kax8n9

**Comment by rolandjitsu** [comment]
> When setting up react-dropzone there's no good way to auto focus the element. I've tried using refs and auto focusing after mount but it doesn't work.
> 
> Is there a way to get this built directly into the library?
> 
> Does anyone know if there is a workaround to this?

Could you share what you tried? Maybe a codesandbox?

**Comment by Nate-Wilkins** [comment]
Sure thing! Here's a sandbox of the problem.
https://stackblitz.com/edit/react-ts-kax8n9

**Comment by rolandjitsu** [comment]
> Sure thing! Here's a sandbox of the problem. https://stackblitz.com/edit/react-ts-kax8n9

Thanks. Yeah, the `input` is not displayed, so you cannot focus. Try [w79ely](https://codesandbox.io/s/react-dropzone-example-forked-w79ely?file=/src/App.js), let me know if that's what you're looking for.

**Comment by rolandjitsu** [comment]
I'm thinking it may be useful to have an `autoFocus` 🤔
