### ISSUE TITLE
Draggable html elements don't trigger onDrop.

### ISSUE THREAD

**Issue by annkay108** [react-dropzone/react-dropzone#1146]
```JavaScript
import React from "react";
import { useDropzone } from "react-dropzone";

function MyDropzone() {
  const { getRootProps, getInputProps } = useDropzone({
    onDrop: () => alert("on drop triggered")
  });

  return (
    <>
      <div {...getRootProps()}>
        <input {...getInputProps()} />
        <p>Drag 'n' drop some files here, or click to select files</p>
      </div>
      <img
        src="https://upload.wikimedia.org/wikipedia/en/9/95/Test_image.jpg"
        draggable="true"
        alt="test_image"
      />
    </>
  );
}

export default MyDropzone;
```

**Comment by annkay108** [comment]
import React from "react";
import { useDropzone } from "react-dropzone";

function MyDropzone() {
  const { getRootProps, getInputProps } = useDropzone({
    onDrop: () => alert("on drop triggered")
  });

  return (
    <>
      <div {...getRootProps()}>
        <input {...getInputProps()} />
        <p>Drag 'n' drop some files here, or click to select files</p>
      </div>
      <img
        src="https://upload.wikimedia.org/wikipedia/en/9/95/Test_image.jpg"
        draggable="true"
        alt="test_image"
      />
    </>
  );
}

export default MyDropzone;

**Comment by rolandjitsu** [comment]
@annkay108 this lib does not address draggable elements, only files. For that, please use something like https://react-dnd.github.io/react-dnd.
