### ISSUE TITLE
[BUG] Dialog box is unresponsive

### ISSUE THREAD

**Issue by hellenfc** [react-dropzone/react-dropzone#1147]
**Describe the bug**
File dialog opens but it's not clickable. I can't close it, scroll or choose a file using the mouse.

**To Reproduce**
- Using a Mac. Tested in Firefox and Chrome
https://react-dropzone.js.org/#section-opening-file-dialog-programmatically
- In this  example click the file dialog
- Try to choose a file
- It won't respond

**Expected behavior**
One file dialog is opened I can choose a file a upload.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome, firefox
 - Chrome version Version 98.0.4758.102 (Official Build) (x86_64)
 - Firefox  version 97.0.1 (64-bit

**Comment by JobiJoba** [comment]
Mmmm, I've the same issue. How did you fix your problem?
