### ISSUE TITLE
[BUG] Previews broke in 12.0.3 + Chrome

### ISSUE THREAD

**Issue by sborsje** [react-dropzone/react-dropzone#1149]
**Describe the bug**
I recently noticed previewing (as described in the [react-dropzone docs](https://react-dropzone.js.org/#section-previews)) isn't working anymore. When selecting an image from the user filesystem, Chrome will show a broken image placeholder instead of the actual image. I was only able to reproduce this in Chromium-based browsers (Chrome/Edge), others (Safari/Firefox) seem to be fine.

**To Reproduce**
1. Go to https://react-dropzone.js.org/#section-previews
2. Click on the dropzone
3. Select any image file 
4. See the broken image placeholder

**Expected behavior**
I expected to see a preview of the to be uploaded image.

**Screenshots**
<img width="1010" alt="Screenshot 2022-03-01 at 22 37 23" src="https://user-images.githubusercontent.com/28392/156253061-2b09b984-4e1e-4dca-8a39-bc020a43cb2b.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.2.1
 - Browser: Chrome
 - Version: 98.0.4758.109 (Official Build) (arm64)

**Additional context**
According to `git bisect` the first commit where this issue starts to appear is: https://github.com/react-dropzone/react-dropzone/commit/dbaec3f5ac48c21ad15f71aaaa0ac330a557a2ce

**Comment by rolandjitsu** [comment]
Unable to reproduce on macOS 11.6.2 (M1), Chrome 98.0. It's possible it may only be an issue on macOS 12, but I doubt it 😕  I won't be able to test until I upgrade my OS 😬 

Can you check your console and see if there's any errors reported?

**Comment by sborsje** [comment]
Yup! But it's not very helpful: `net::ERR_FILE_NOT_FOUND`.

I also tested with Chrome Canary (Version 101.0.4927.0 (Official Build) canary (arm64)), but I got the same result.

![Screenshot 2022-03-06 at 14 46 30](https://user-images.githubusercontent.com/28392/156926130-7f50972b-c2b5-4e65-9df5-94553fdd73fa.png)
<img width="1077" alt="Screenshot 2022-03-06 at 14 44 59" src="https://user-images.githubusercontent.com/28392/156926133-7ca91c23-9875-4082-9478-a3b760e52797.png">

**Comment by rolandjitsu** [comment]
@sborsje it actually does help, sort of. The issue must be with https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL. It seems the images loaded from that are not rendered anymore. Needs more investigation.

**Comment by alexHlebnikov** [comment]
Same problem here on same Mac OS and Chrome.

**Comment by alexHlebnikov** [comment]
Dropping back to 12.0.2 solved my problem.

**Comment by RileyMShea** [comment]
Both 12.0.4 and 12.0.2 have the same issue for me. My guess is newer chrome versions are either slower at writing the preview to disk or faster at revoking the ObjectURL(or both).

https://stackoverflow.com/a/63111446

> Revoking a blob:// URI is a synchronous operation, downloading a file on the other hand is not.

> Even though the data can be in memory and thus downloaded really fast, it is not always the case. The Blob's data may not even be in a single place, for instance some blobParts could be in memory, some others on user's disk or even in a shared folder access through a network. Also simply requesting the OS for access to write can actually be made asynchronously.
> 
> So by the time you call revokeObjectURL, the browser may still haven't had the time to write your file to disk and when it tries to do so, or to access a new blobPart, there is no more pointers available at the provided address.
> 
> There is unfortunately no event letting us know when this writing to disk is done, at least not until the [native-file-system API](https://github.com/WICG/native-file-system) becomes official, so the best we can do for now is to wait a fair amount of time before revoking the blob:// URI.
> For reference, [FileSaver.js](https://github.com/eligrey/FileSaver.js/) does wait 40s.

## Current workaround

I doubt it's the best way but my current solution just adds a sleep >=100ms before the revoke so the blob has time to be written to disk. It at least seems to work on localhost that way.

```jsx
  useEffect(() => {
    // Make sure to revoke the data uris to avoid memory leaks
    const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms))
    const cleanup = async () => {
      await sleep(100)
      files.forEach((file) => URL.revokeObjectURL(file.preview))
      console.log("revoked")
    }
    cleanup()
  }, [files])
```

**Comment by Uluwatta** [comment]
Just noticed this issue :)

Following PR might fix this, not sure whether it's the perfect fix but making sure that the blob/data URLs are revoked after image load and component unmount will help avoid urls to get revoked before its consumption

https://github.com/react-dropzone/react-dropzone/pull/1172
