### ISSUE TITLE
[ENHANCEMENT] Support old drag/drop behaviour for non files

### ISSUE THREAD

**Issue by 1Jesper1** [react-dropzone/react-dropzone#1151]
https://github.com/react-dropzone/react-dropzone/pull/619

This PR broke usability for us, because now users can't drag and drop mails from Outlook.
Please implement a property to choose for the old behaviour.

**Comment by rolandjitsu** [comment]
@1Jesper1 would you be able to explain your use case a bit more?

**Comment by 1Jesper1** [comment]
OnDrop was not triggered when drag and drop a Outlook mail to the dropzone from version https://github.com/react-dropzone/react-dropzone/releases/tag/v6.0.0
It seems to work from version https://github.com/react-dropzone/react-dropzone/releases/tag/v8.0.1

Reproduce:
1. Open Outlook application.
2. Drag a mail to dropzone.

**Comment by rolandjitsu** [comment]
@1Jesper1 I understand what you're asking. But I don't see how that relates to files. Is the mail a file? Or how does it work?

Bringing back that behaviour will most likely break other things, so I want to understand the use case better to see if there's a way to impl. w/ breaking more things.

**Comment by 1Jesper1** [comment]
@rolandjitsu Since the functionality was fixed in version 8.0.1, there is no further investigation needed!

**Comment by rolandjitsu** [comment]
@1Jesper1 I'm glad it all worked out!
