### ISSUE TITLE
Image Preview Production issue

### ISSUE THREAD

**Issue by muhaymin-bin-mehmood** [react-dropzone/react-dropzone#1154]
**Describe the bug**
I am using react-dropzone and it is working great in development mode but when i make a build and deploy the preview of dropzone is not showing. I also checked the console but it's clear

**Expected behavior**
![Capture](https://user-images.githubusercontent.com/72308336/157966804-97ff24d6-a9f9-429d-912f-864ce862a94e.JPG)

** Current Behavior **
Even after uploading multiple images 
![Capture](https://user-images.githubusercontent.com/72308336/157967329-2c408721-23e5-463f-bc44-1243326e3477.JPG)

** Code Example **

`       

        import { useDropzone } from 'react-dropzone';
        const PostAdd = () => {
         const [files, setFiles] = useState([]);
        const [imageError, setImageError] = useState('')
        const [loader, setLoader] = useState(false)
        
      const { getRootProps, getInputProps } = useDropzone({
        accept: 'image/*',
        onDrop: (acceptedFiles: any) => {
            if (acceptedFiles[0].size > 300000) {
                setImageError('Image size should be less than 300KB')
                setLoader(true)
            } else {
                setLoader(false)
                setFiles(
                    acceptedFiles.map((file: any) =>
                        Object.assign(file, {
                            preview: URL.createObjectURL(file),
                        })
                    )
                );
            }
        },
    });
    
    const thumbs = files.map((file: any, index: any) => (
        <div key={file.name} className="image_wrapper">
            {console.log('file', file)}
            <div>
                <img src={file.preview} alt="Capture Preview" />
            </div>
            <button onClick={(e: any) => editImage(e)}>Edit</button>
        </div>
    ));

    useEffect(
        () => () => {
            // Make sure to revoke the Object URL to avoid memory leaks
            files.forEach((file: any) => URL.revokeObjectURL(file.preview));
        },
        [files]
    );
    
        return (
        <>
        
        <div className='form_group'>
            <section className="container">
                <div {...getRootProps({ className: 'dropzone' })}>
                    <input name="carImage" {...getInputProps()} onChange={(event) => {
                    }} />
                    <BsCameraFill style={{ fontSize: '50px' }} />
                    <p>Add Photos</p>
                    {imageError && loader ? <p className='error'>{imageError}</p> : null}
                </div>
                <aside className='image_preview'>{thumbs}</aside>
            </section>
        </div>
                    
        </>
            )
        }
        export default PostAdd `

**Comment by rolandjitsu** [comment]
Should have been fixed w/ https://github.com/react-dropzone/react-dropzone/pull/1172.
