### ISSUE TITLE
[ENHANCEMENT] fileRejections doesn't reload after removing elements

### ISSUE THREAD

**Issue by ko22009** [react-dropzone/react-dropzone#1158]
When files upload more than specific count, we see error about max count.
If we remove files and fileRejections become less or equal maxFiles, check doesn't apper. we saw fileRejections files with errors, but errors doesn't have.

Maybe It is not provided by concept.

**Comment by rolandjitsu** [comment]
@ko22009 I don't follow what you're asking for. Could you, maybe, provide some pseudo code illustrating what you're asking for?

**Comment by rolandjitsu** [comment]
No response, so gonna close. Feel free to provide more info and context so we can reproduce whatever issues you were trying to describe and we'll reopen.
