### ISSUE TITLE
[BUG] In react 18, dragging accepted file over dropzone sets isDragReject to true

### ISSUE THREAD

**Issue by andylacko** [react-dropzone/react-dropzone#1167]
**Describe the bug**
Described in issue name

**To Reproduce**

https://codesandbox.io/s/react-dropzone-example-forked-nfvn0p

`useDropzone({..., accept: 'image/*'})`

drag the image (eg.) over the dropzone, it set state to `isDragReject`

**Expected behavior**
Should set isDragAccept to true

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser Chrome
 - Version 99

**Comment by travisdahl** [comment]
Seeing same issue in react 16

**Comment by rolandjitsu** [comment]
@andylacko @travisdahl this may be a [browser limitation](https://react-dropzone.js.org/#section-accepting-specific-file-types). During drag, we don't have access to the file data, as such, we cannot tell if it's rejected/accepted. But I may be wrong.

**Comment by andylacko** [comment]
It is probably not, because the library is working in chrome when using react 17, in safari, the accept + reject states didn't work before, because the browser has limitations in recognising files.

I believe it is due to setState "batching" logic of react 18 and those useEffect hooks are skipped, just idea 💡

**Comment by rolandjitsu** [comment]
I'm not sure that's the case. See [feat/react-18](https://github.com/rolandjitsu/react-dropzone/tree/feat/react-18) which uses React 18. As far as tests go, everything is passing.

**Comment by vsrc** [comment]
Yeah, can confirm same happening with my project but only on Chrome v100.0.4896.88. Safari and Firefox are working fine. I am using React v18 and react-dropzone v12.0.5. But the bug is happening only during the drag stage, as soon as file is dropped correct file gets accepted and wrong file gets rejected. 

My suggestion, if there is an issue with browser not allowing the access to the file data during the drag stage I personally think it would be better to have graceful drop to the optimistic resolution. As in `isDragReject` is only true if we can confirm it.

In that case we can always add additional instruction to the page about accepted file types and when file gets rejected notify user why it was rejected. With current behavior users get false alarm and spooked when trying to upload valid file formats.

**Comment by rolandjitsu** [comment]
@vsrc fair enough. I think this needs more investigation though as it may be an actual issue.

**Comment by alfupe** [comment]
In my case it is happening in Chrome (tested versions 85 and 100) and React 18. In another project, React 17 and Chrome 100 is working fine.

**Comment by MuscularSloth** [comment]
@alfupe your solution works perfect for me too. Classic mounting solves problem with isDragReject and Thumb preview. 

I think it has some conflicts with new React 18 features.

**Comment by travisdahl** [comment]
There does seem to be a regression bug here though, when I used `.xls, .xlsx` in v11.1.0 it greyed out the option when i clicked to open the file chooser. This no longer happens on 12. Sorry for the back and forth, took me a min to realize what was going on

**Comment by kristinzinser** [comment]
My specs:
- React v18
- React Dropzone v12.1
- Chrome v100.0.4896.127 on Mac 
- example: https://codesandbox.io/s/inspiring-tdd-to1p4r?file=/src/App.js - everything that i attempt to drop sets `isDragReject` to `true` even though in the documentation example (https://react-dropzone.js.org/#section-styling-dropzone) it does not evaluate to `true` for the same files. 

why is this? how do i solve this issue? again im using the _same exact_ code as the documentation example and in the codesandbox link, you can see it triggers the style for `isDragReject` over and over again despite the style for `isDragAccept` being triggered for the documentation example. 

(note: i first discovered this issue with React v16.13.1 and react dropzone v^11.5.1, but only _recently_; a few weeks ago when I completed the feature using this component, it was working; nothing has broken in the code)

**Comment by rolandjitsu** [comment]
> My specs:
> 
> * React v18
> * React Dropzone v12.1
> * Chrome v100.0.4896.127 on Mac
> * example: https://codesandbox.io/s/inspiring-tdd-to1p4r - everything that i attempt to drop sets `isDragReject` to `true` even though in the documentation example (https://react-dropzone.js.org/#section-styling-dropzone) it does not evaluate to `true` for the same files.
> 
> why is this? how do i solve this issue? again im using the _same exact_ code as the documentation example and in the codesandbox link, you can see it triggers the style for `isDragReject` over and over again despite the style for `isDragAccept` being triggered for the documentation example.
> 
> (note: i first discovered this issue with React v16.13.1 and react dropzone v^11.5.1, but only _recently_; a few weeks ago when I completed the feature using this component, it was working; nothing has broken in the code)

I can confirm that on React 18, the accept behaviour is not consistent or doesn't work as expected.

Side note: You don't need to pass the `isDragAccept` etc props to `getRootProps`, see https://codesandbox.io/s/trusting-leftpad-zvryj2?file=/src/App.js.

**Comment by rolandjitsu** [comment]
> It is probably not, because the library is working in chrome when using react 17, in safari, the accept + reject states didn't work before, because the browser has limitations in recognising files.
> 
> I believe it is due to setState "batching" logic of react 18 and those useEffect hooks are skipped, just idea 💡

I think you may be right. At least it's on the right track. Reading through https://html.spec.whatwg.org/multipage/dnd.html, the data is only available throughout the duration of the drag and drop events. And I guess React 18 is now handling dispatch async, which means that our hook will most likely not get the data in time before the drag and drop operation is done.

Gonna look into some ways to handle this if possible.

**Comment by rolandjitsu** [comment]
@andylacko @vsrc @alfupe @MuscularSloth @travisdahl @kristinzinser could you upgrade to v14 and let me know if the issue is resolved?

**Comment by meseven** [comment]
@rolandjitsu I tried with v14 and the problem seems to be resolved. Thanks :)

**Comment by MuscularSloth** [comment]
@rolandjitsu I've updated react-dropzone to v14 and tried with react v18 and its new root component mounting. Now it accepts all files, ignores `accept` rule and has problems with thumbnails. 
React v18 + classic mounting root component + react-dropzone v14 continued ignore `accept` rule and still had problems with thumbnails. 
And only when I returned react-dropzone v12 + React v18 + classic mounting root component it started work correctly.

**Comment by alfupe** [comment]
> @rolandjitsu I've updated react-dropzone to v14 and tried with react v18 and its new root component mounting. Now it accepts all files, ignores `accept` rule and has problems with thumbnails. React v18 + classic mounting root component + react-dropzone v14 continued ignore `accept` rule and still had problems with thumbnails. And only when I returned react-dropzone v12 + React v18 + classic mounting root component it started work correctly.

The way accept is processed has changed, it is a breaking change. 

Whereas before you could pass accept as, for instance:
`accept: [
    'text/csv',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  ]`

Now you must do it like:
`accept: {
    'text/*': ['.csv'],
    'application/vnd.ms-excel': ['.xls'],
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': ['.xlsx']
  }`

Check this: https://react-dropzone.js.org/#section-accepting-specific-file-types

**Comment by MuscularSloth** [comment]
> > @rolandjitsu I've updated react-dropzone to v14 and tried with react v18 and its new root component mounting. Now it accepts all files, ignores `accept` rule and has problems with thumbnails. React v18 + classic mounting root component + react-dropzone v14 continued ignore `accept` rule and still had problems with thumbnails. And only when I returned react-dropzone v12 + React v18 + classic mounting root component it started work correctly.
> 
> The way accept is processed has changed, it is a breaking change.
> 
> Whereas before you could pass accept as, for instance: `accept: [ 'text/csv', 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', ]`
> 
> Now you must do it like: `accept: { 'text/*': ['.csv'], 'application/vnd.ms-excel': ['.xls'], 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': ['.xlsx'] }`
> 
> Check this: https://react-dropzone.js.org/#section-accepting-specific-file-types

My bad. Thanks! Works perfect =)

**Comment by kristinzinser** [comment]
> @andylacko @vsrc @alfupe @MuscularSloth @travisdahl @kristinzinser could you upgrade to v14 and let me know if the issue is resolved?

it appears to have resolved with `14.1.1` 🎉 🥳 thank you for the quick turnaround!

**Comment by travisdahl** [comment]
> @andylacko @vsrc @alfupe @MuscularSloth @travisdahl @kristinzinser could you upgrade to v14 and let me know if the issue is resolved?

It does appear to be working correctly. One thing that would make for a better user experience is to display the extensions rather than the mime-types in the rejection message....

for example, in the screenshot below it may be easier to parse if it said `File type must be .xls,.xlsx` (whats in the arrays)

![image](https://user-images.githubusercontent.com/379314/166335017-344bc4a2-c278-4697-8738-aa71a346d83f.png)

**Comment by andylacko** [comment]
@travisdahl , @kristinzinser thx It works!

**Comment by marcelino-borges** [comment]
Reviving this 2 years later...

I have (partial package.json):
```json
{
    "react-dropzone": "^14.3.5",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "storybook": "^8.4.7",
    "@storybook/react": "^8.4.7",
    "vite": "^6.0.4",
    "typescript": "^5.7.2",
}
```

I have this `accept`: 
```json
{
    "application/zip": [".zip"],
}
```

When I drag a `.zip` file over the dropzone, `isDragReject` is set to true, but when I drop the file is accepted (comes in my `onDrop` callback). 

Testing in a Storybook app, same behavior in Chrome, Firefox and Edge.

**Comment by sKopheK** [comment]
experiencing same with custom
```
 { 'application/x-zip': ['.sqx'] }
```

**Comment by rolandjitsu** [comment]
> Reviving this almost 3 years later...
> 
> I have this [partial] package.json:
> 
> {
>     "react-dropzone": "^14.3.5",
>     "react": "^18.3.1",
>     "react-dom": "^18.3.1",
>     "storybook": "^8.4.7",
>     "@storybook/react": "^8.4.7",
>     "vite": "^6.0.4",
>     "typescript": "^5.7.2",
> }
> I have this `accept`:
> 
> {
>     "application/zip": [".zip"],
> }
> When I drag a `.zip` file over the dropzone, `isDragReject` is set to true, but when I drop the file it is accepted (comes in my `onDrop` callback arg). Also `isDragAccept` keeps false.
> 
> Testing in a Storybook app, same behavior in Chrome, Firefox and Edge.
> 
> Any thoughts?

I believe this is a browser limitation during drag. Checkout https://react-dropzone.js.org/#browser-limitations and let me know if that makes sense.
