### ISSUE TITLE
[ENHANCEMENT] File upload without clearing current file list

### ISSUE THREAD

**Issue by afternoon2** [react-dropzone/react-dropzone#1168]
**Is your feature request related to a problem? Please describe.**
Currently, the user is unable to upload multiple files one-by-one, because the file list of the input is always cleared before uploading new stuff.

**Describe the solution you'd like**
Suggested solution would be to add a boolean configuration param, for example `isFileListResetOnUpload`, or a `behavior` flag (as it is in `@dropzone-ui/react`) - a union type `'add' | 'replace'` - [link here](https://github.com/dropzone-ui/dropzone-ui-react#dropzone-ui-react-components-api)

**Describe alternatives you've considered**
In my project, I had a request to enable the multiple file upload for both options, by selecting or dragging multiple files once, or to upload them one-by-one. To override the `react-dropzone` behavior, I wrote a custom hook that used refs:

```ts
const [files, setFiles] = useState<File[]>([]);
const prevFilesRef: MutableRefObject<File[]> = useRef([]);

const onDrop = useCallback(
  (acceptedFiles: File[]) => {
    setFiles(getFilesWithUniqueNames(prevFilesRef.current, acceptedFiles));
  },
  [setFiles, prevFilesRef]
);

useEffect(() => {
  prevFilesRef.current = files;
}, [files]);
```

I will try to create a PR related to this issue once I've got a bit time to work on that.

Anyway, thank you for this awesome library! :)

**Comment by rolandjitsu** [comment]
@afternoon2 the internal state of the lib is just that, internal. And I think similar issues/requests were created in the past and the suggestion was the same: use a similar approach to what you've added above. And file management is not in the scope of this lib and should be handled by the user.
