### ISSUE TITLE
[BUG] Causes MODULE_NOT_FOUND on a RedwoodJS app

### ISSUE THREAD

**Issue by noire-munich** [react-dropzone/react-dropzone#1170]
**Describe the bug**
I've installed the module on a RedwoodJS app on a dedicated branch, it causes the error code: MODULE_NOT_FOUND.

I've tried removing & recreating a fresh `node_modules` + `yarn.lock` but it didn't change much.
If I switch to main and re build these, my app works.
If I then switch to branch without reloading local server, my app works.

If I reload the local server, it doesn't work anymore.

My application only uses the hook `useDropzone`:
```
import { useDropzone } from 'react-dropzone'
```
And that's about it - early stage.

**Expected behavior**
No error.

**Screenshots**

**Desktop (please complete the following information):**
  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.6.1 - /tmp/yarn--1649247582491-0.7608869441700472/node
    Yarn: 1.22.18 - /tmp/yarn--1649247582491-0.7608869441700472/yarn
  Browsers:
    Chrome: 100.0.4896.75
    Firefox: 98.0.2
  npmPackages:
    @redwoodjs/core: ^1.0.0 => 1.0.0 
    @redwoodjs/eslint-config: ^1.0.0 => 1.0.0 
    @redwoodjs/record: ^1.0.0 => 1.0.0 

**Additional context**
Six months ago with a former version it didn't cause that error. The branch was stale and I had to pick it again to merge it in a new branch this week.

**Comment by rolandjitsu** [comment]
@noire-munich I've never used redwoodjs before. But that sounds like a build issue. This lib should be compatible with systems like webpack, so if redwood uses that, it should be working.

**Comment by noire-munich** [comment]
@rolandjitsu RedwoodJS uses webpack indeed.
This fixed the issue:

```
# package.json
  "resolutions": {
    "webpack": "5.71.0"
  },
```

**Comment by rolandjitsu** [comment]
@noire-munich is it because redwood uses a newer version? or an older one?

**Comment by noire-munich** [comment]
@rolandjitsu more explanation here: https://github.com/redwoodjs/redwood/issues/5054#issuecomment-1091260832

RW uses storybook and there's been different versions of webpack, so the fix forces one version to be used. RW is patched now, sorry I opened an issue here - I didn't experience the aforementioned issue, a core team member saw the match.
