### ISSUE TITLE
[BUG]  Property 'path' does not exist on type 'File'

### ISSUE THREAD

**Issue by aslan-alt** [react-dropzone/react-dropzone#1176]
**Describe the bug**
 Property 'path' does not exist on type 'File'

<img width="778" alt="Screen Shot 2022-04-24 at 18 39 17" src="https://user-images.githubusercontent.com/54422571/164972531-ce2ea9c7-d656-459a-8248-c1c0d13498a1.png">

**Expected behavior**
no type error

**Screenshots**

**Additional context**

**Comment by aslan-alt** [comment]
PR：https://github.com/react-dropzone/react-dropzone/pull/1178

**Comment by c0ncentus** [comment]
have the same issue ...

**Comment by loganpowell** [comment]
if you're just annoyed by the ts warnings, here's a dirty patch:
```ts
// extend File interface
declare global {
    interface File {
        path: string
    }
}
```

**Comment by anthonyblond** [comment]
Maybe the docs should be updated. I thought the full path is not meant to be visible to users anyway, with only the name being available as per https://developer.mozilla.org/en-US/docs/Web/API/File

**Comment by anselmo-ssoltech** [comment]
No updates?

**Comment by barbalex** [comment]
I guess this is solved with https://github.com/react-dropzone/react-dropzone/commit/960c6d33179a86e79c1ff65902e7393b54e322b3

**Comment by rolandjitsu** [comment]
@barbalex do let me know if the issue went away.

**Comment by barbalex** [comment]
I don't have a project where I am working on this functionality now. Hopefully others can chime in

**Comment by rolandjitsu** [comment]
Closing this for now,
