### ISSUE TITLE
[BUG] File dialog enables only the first file type from accept, others are disabled

### ISSUE THREAD

**Issue by shomyx** [react-dropzone/react-dropzone#1191]
**Describe the bug**
When defining the `accept` object like 

```
useDropzone({
  accept: {
    'image/jpeg': [],
    'image/png': [],
  }
})
```

the file drop option works properly. In case the user wants to pick a file from file dialog, only the first file type from `accept` is enabled, the rest are disabled and greyed out.

**To Reproduce**
1. Go to "Accepting specific file types": [Click me](https://react-dropzone.js.org/#section-accepting-specific-file-types)
2. Click on the dropzone field
3. File dialog opens up
4. User can select a `.jpeg` file, but not a `.png` file

**Expected behavior**
All defined file types in the `accept` object should be enabled for selection via file dialog

**Desktop:**
 - OS: macOS Monterey (Version 12.3.1)
 - Browser: Chrome (Version 101.0.4951.54 (Official Build) (x86_64))
 - React DropZone: 14.2.0

**Comment by rolandjitsu** [comment]
@shomyx that's expected behaviour when using the [File System Access API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API). If you check the screencast I've attached, you'll see that you need to select the option to select other mime types based on the `accept` attr.

https://user-images.githubusercontent.com/1479737/167239126-15ef8900-ecad-4b13-9605-e2a217b72b7a.mp4

**Comment by shomyx** [comment]
@rolandjitsu Thanks for the clarification.

**Comment by shomyx** [comment]
@GlennBlicharzBounteous That does the trick for my use case. Actually it's a lot better than having to choose a single file type each time the user wants something else than the first defined one. Thanks for the tip. 🙂

**Comment by rohitah** [comment]
Also, faced similar issue
 
following didn't work in chrome browser. 

```
    accept: {
      'image/png': ['.jpg', '.jpeg', '.png'],
      'application/pdf': ['.pdf']
      'image/png': ['.jpg', '.jpeg', '.png', '.pdf']
    },

```
So changed it as follow and it works fine now even in chrome 

```
    accept: {
      'image/png': ['.jpg', '.jpeg', '.png', '.pdf']
    },

```

**Comment by getalihassan** [comment]
thanks I am using ubuntu jimmy
react-dropzone: 14.2.2
ran into same issue

useFsAccessApi: false

fixed it for me. 
just wondering will it have any effects on safari/macOS, windows?
