### ISSUE TITLE
[BUG] The app receives an empty blob preview file when the user selects (or drag&drops) an image file.

### ISSUE THREAD

**Issue by MuscularSloth** [react-dropzone/react-dropzone#1194]
The app receives an empty blob preview file when the user selects (or drag&drops) an image file.
React 18

https://codesandbox.io/s/react-dropzone-thumb-problem-ws66by?file=/src/App.js

P.S. Maybe this is not a bug, but I haven't found any solution yet.

**Comment by rolandjitsu** [comment]
@MuscularSloth I think this issue was reported before and fixed in a previous commit. The issue is how we use `useEffect()`. Please checkout [y0bk0h](https://codesandbox.io/s/react-dropzone-thumb-problem-forked-y0bk0h).

**Comment by MuscularSloth** [comment]
> @MuscularSloth I think this issue was reported before and fixed in a previous commit. The issue is how we use `useEffect()`. Please checkout [y0bk0h](https://codesandbox.io/s/react-dropzone-thumb-problem-forked-y0bk0h).

Thx a lot! Works perfect!
