### ISSUE TITLE
[ENHANCEMENT] Make it possible to remove file from acceptedFiles stat

### ISSUE THREAD

**Issue by awitherow** [react-dropzone/react-dropzone#1195]
https://github.com/react-dropzone/react-dropzone/issues/805

why was this closed without any thoughtful insight into providing an actual solution?

**Comment by rolandjitsu** [comment]
@awitherow there's at least 3 examples there, e.g https://github.com/react-dropzone/react-dropzone/issues/805#issuecomment-481405924, on how to achieve that. And as mentioned previously, managing the files state post drop/select is the user's responsibility.
