### ISSUE TITLE
[BUG] Drag & drop from compression file manager

### ISSUE THREAD

**Issue by 0x4950** [react-dropzone/react-dropzone#1203]
**Describe the bug**
Drag & drop from a compression folder (Windows File Explorer for .zip or 7zip GUI File Manager) results in a file with size 0 (zero).

**To Reproduce**
This behavior can be reproduced on the project website as well, no need for complex setups.
1. Take a file (xlsx, docx, pdf) and compress it in any way.
2. Go to compression file explorer (e.g. for Windows you can double click on zip file and it would open like a normal folder and show the file. Same for 7zip, when double click you get a File Manager of their own.)
3. Drag the file to the dropzone area and see (console/debugger breakpoints) it's size.

**Expected behavior**
I would expect the file to be registered correctly as if it was dragged and dropped from a folder.

**Desktop (please complete the following information):**
 - Windows 11 Pro, version: 21H2
 - Version 102.0.5005.63 (64-bit)

** Additional context **
Chain of calls discovered: 
`onDropCb (file.ts) -> getFilesFromEvent/fromEvent (file-selector.ts) -> getDataTransferFiles -> toFilePromises -> fromDataTransferItem -> file = item.getAsFile();`

At this point what is returned is
```
lastModified: 1654174157153
lastModifiedDate: Thu Jun 02 2022 14:49:17 GMT+0200 (Central European Summer Time) {}
name: "Test.xlsx"
size: 0
type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
webkitRelativePath: ""
```

The hour is wrong because this is time that the drop happened and not an actual modification. Size is zero. For xlsm (not this one) the type is also empty.

But the zero file size can be seen even from the start (at `onDropCb` call), where there is a property `files` in the `event` and it has size 0.

I suspect it has something to do with browser access to the file system because those files are not actually copied from a standard path. For example when I was using 7zip and I tried to drag and drop a docx file to an empty Chrome tab I got an error that the file cannot be accessed and on the URL there was an address to `AppData/Local/Temp`. Maybe the path of the temp file is somehow not playing well with the drag & drop functionality on the browser.

**Comment by rolandjitsu** [comment]
@0x4950 if I understand correctly, you're trying to drop a file directly from an archive and the file that you get from the dropzone is 0 bytes?

It sounds like a browser limitation and I don't think there's anything we can do about it on our end.

**Comment by 0x4950** [comment]
I see, wasn't sure if it was something because of the library or the browser and thought of giving it a shot. Thanks!
