### ISSUE TITLE
[BUG] "accept" for multiple mime types doesn't work in Chrome

### ISSUE THREAD

**Issue by gottfired** [react-dropzone/react-dropzone#1206]
**Describe the bug**
Providing multiple mime types does not work in Chrome

**To Reproduce**
1. Go to https://react-dropzone.js.org/#section-accepting-specific-file-types
2. Click on dropzone that should accept png and jpg files
3. Navigate to folder with png and jps images.
4. Only jpg images are selectable
5. This does not happen in Safari or Firefox, only Chrome

**Expected behavior**
png and jpg should be selectable

**Screenshots**

![Screenshot 2022-06-07 at 10 27 38](https://user-images.githubusercontent.com/4855371/172333867-e3fe63a5-55de-426d-a461-fcdcc20abb71.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser Chrome
 - Version 102

**Comment by topaxi** [comment]
We are facing the same issue, trying to set mime/file-endings for different image formats plus pdf.

**Comment by nikola1970** [comment]
+1 

Having the same issue.

**Comment by erfans-omnea** [comment]
I'm having the same issue in Chrome (works in Safari)
macOS Monterey
Drag-n-drop is working, but manual file browser grays out all files (except the first one)

This is the file type limitation on passed and it only enables images.

```
const imageType = { 'image/*': [] }
const zipType = { 'application/zip': [] }
const docTypes = {
  'application/msword': [], // .doc
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document': [], // .docx
  'text/csv': [],
  'application/vnd.ms-excel': [], // .xls
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': [], // .xlsx
  'application/pdf': [],
}
const acceptedTypes = { ...imageType, ...zipType, ...docTypes }

**Comment by erfoon** [comment]
I'm having the same issue in Chrome (works in Safari)
macOS Monterey
Drag-n-drop is working, but the manual file browser greys out all files (except the first provided type)

This is the file type limitation on passed and it only enables images.

```
const imageType = { 'image/*': [] }
const zipType = { 'application/zip': [] }
const docTypes = {
  'application/msword': [], // .doc
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document': [], // .docx
  'text/csv': [],
  'application/vnd.ms-excel': [], // .xls
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': [], // .xlsx
  'application/pdf': [],
}
const acceptedTypes = { ...imageType, ...zipType, ...docTypes }

**Comment by cbustamanter** [comment]
+1

Having the same issue.

**Comment by Damiqib** [comment]
+1

Having the same issue - only the first in list is used and all other types get ignored.

**Comment by taylor-cedar** [comment]
I figured out the issue. Not sure if it's Chrome bug or a dropzone bug.

```js
opts = { 
  types: [
    {accept: {"image/jpg": []}}, 
    {accept: {"image/jpg": []}}
  ]
}

window.showOpenFilePicker(opts)
```

It works in Chrome if the format is the following:
```js
opts = { 
  types: [
    {
         accept: {
           "image/jpg": [], 
           "image/jpg": []
         }
     }
  ]
}
```

See the single accept vs multiple accept

**Comment by temrb** [comment]
+1

  accept: {
      'video/*': ['.hevc', '.mp4', '.mov', '.m4v', '.avi'],
      'image/*': ['.jpeg', '.png', '.heif'],
    },
    
    for me it doesn't accept image if it's video first. Doesn't accept video if image is first in the object.

**Comment by rolandjitsu** [comment]
![Screenshot 2022-06-11 at 10 03 11](https://user-images.githubusercontent.com/1479737/173168580-3cb74fdf-3e67-448d-b542-4e67ef767895.png)

The selection works as expected. Above screenshot illustrates the behaviour on macOS. There's an `Options` button which you can use to switch b/t the types.

**Comment by gottfired** [comment]
Imo, that's very unintuitive, it used to be similar to current Firefox/Safari behaviour with older versions of dropzone, where all file types were selectable simultaneously in Chrome. Only IT savvy users would understand the difference between different image types, and start using that drop down. See also https://github.com/react-dropzone/react-dropzone/pull/1207

**Comment by gapton** [comment]
There is a PR marked as accepted.

With that said, until the PR merge, here is a temporary fix : 

> accept={{
>     "image/*": ['.jpg','.jpeg','.png','.pdf'],
>  }}

This will trick OSX Finder to allow all the extensions, but the options button will be weirded out : 
<img width="473" alt="image" src="https://user-images.githubusercontent.com/637259/174923681-28fa858c-3ab9-425c-a6ef-a8346d1ba595.png">

**Comment by taylorhakes** [comment]
@gapton That hack only partially works. The HTML file input will allow all image file types, so the second time you open that dialog all image types are selectable. Test it by closing the dialog and then opening it again.
