### ISSUE TITLE
[BUG] Drag & drop did not work with Safari on MacOS

### ISSUE THREAD

**Issue by nguyenhuuloc304** [react-dropzone/react-dropzone#1213]
**Describe the bug**
Dear,
I **cannot** drag email from outlook and drop into the panel. But when I copy email and paste into desktop screen, then drag and drop it to the panel, it worked. **this is just happen with Safari**. 

Other browsers work fine.

I encountered the issue with:
MacOS 11.6.5
Safari 15.4
Outlook 16.62
react-dropzone: 11.2.4  

Record for issue:
https://user-images.githubusercontent.com/21157325/176875437-77ef85e7-2d4d-4f04-8f92-0ddc862704f2.mp4

Could anyone can help on this issue? much appreciated!. thank you

**Comment by rolandjitsu** [comment]
This is not an issue with the lib. It's probably an issue with the OS or browser.

**Comment by nguyenhuuloc304** [comment]
Hi @rolandjitsu , two colleagues of mine have the same issue and we tried to adjust some configurations in Safari browser. But the issue is still there.

**Comment by rolandjitsu** [comment]
> Hi @rolandjitsu , two colleagues of mine have the same issue and we tried to adjust some configurations in Safari browser. But the issue is still there.

@nguyenhuuloc304 there's nothing we can do on our side. If the browser doesn't report an event which has files set on it, we cannot process that event to get the file data.

You can try adding a drop event handler on the a div and see what's reported. I do not have outlook installed on my mac, but I can confirm the same behaviour when using the native macOS email app.

**Comment by nguyenhuuloc304** [comment]
Hi @rolandjitsu , much appreciated your suggestion, let me do some experiment.
