### ISSUE TITLE
[BUG] Multiple MIME types not working on macOS window

### ISSUE THREAD

**Issue by matteo95g** [react-dropzone/react-dropzone#1214]
**Describe the bug**
When passing multiple MIME types to the `accept` prop, after opening the OS explorer window, it doesn't allow selecting all the types passed.

**To Reproduce**
```
<Dropzone
  onDrop={onDrop}
  multiple
  accept={{
    'image/*': ['.png'],
    'application/pdf': ['.pdf'],
  }}
/>
```

**Expected behavior**
Allow to select .pdf and .png files

**Screenshots**
<img width="800" alt="Screen Shot 2022-07-01 at 12 47 25" src="https://user-images.githubusercontent.com/18466456/176928238-82de13ba-b972-4637-adad-39b65a93476f.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 103.0.5060.53

**Comment by rolandjitsu** [comment]
See https://github.com/react-dropzone/react-dropzone/pull/1207.
