### ISSUE TITLE
[ENHANCEMENT] I need to store the files in every drop.

### ISSUE THREAD

**Issue by Nenrei** [react-dropzone/react-dropzone#1215]
I noticed that every time I drop or select a file, the previous dropped files are deleted.
This happens even if I save the accepted files in state.

What I need is, for example:
First I select a file named file1.
This file appears bellow the dropZone.
Then I select another file, file2.
Right now only "file2" will appear.
And I need "file1" and "file2"

Is there a way to do this? Or can be added?

**Comment by Bravemobin** [comment]
Can you find solution ?
