### ISSUE TITLE
[BUG] Accept application/octet-stream with extension .dll

### ISSUE THREAD

**Issue by cretumarius** [react-dropzone/react-dropzone#1232]
First of all thanks for this awesome library! 

**Describe the bug**
I am implementing a feature that allows the user to upload only .dll files by drag and drop or by opening the file picker. I encountered a possible bug when having
`accept: {
      "application/octet-stream": [".dll"],
    },`
    
**To Reproduce**
1. Drag an `.exe` file and drop it in the drop area.
2. The file will be considered rejected and you can check the error (`File type must be application/octet-stream,.dll`) by console logging the `fileRejections` array.
3. Open file picker by calling `open`
4. In the file picker besides `.dll` files you can select also the `.exe` file
5. Select the same `.exe` file as before
6. The file is considered accepted and `fileRejections` array is empty.

**Expected behavior**
By opening the file picker you should not be able to select the .exe file. If the issue is with the file picker then after selecting it the file should be considered rejected.

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Edge, Chrome]

**Additional context**
If anyone can help me with this I will be very thankful.

**Comment by bigface030** [comment]
I encountered same bug with
`accept: { "application/octet-stream": [".vrm"], },`

**Comment by bigface030** [comment]
Test for `.exe` file, the MIME type is different between two input method:
- for drag & drop: `application/x-msdownload`
- for file picker: `application/octet-stream`

**Comment by ModKub** [comment]
Any updates about this bug?

**Comment by rolandjitsu** [comment]
@cretumarius this is a browser limitation, this lib has no control on how the browser allows users to select files. The lib sets the `accept` accordingly as far as I can tell.
