### ISSUE TITLE
[BUG] isDragReject not triggered on maxSize

### ISSUE THREAD

**Issue by Maetes** [react-dropzone/react-dropzone#1238]
**Describe the bug**

**To Reproduce**
use the simple example from the docs, change to:   

```
const {
    acceptedFiles,
    getRootProps,
    getInputProps,
    isDragReject
  } = useDropzone({ maxSize: 1 });
```

and console.log isDragReject when you drag a big file over the zone

**Expected behavior**
isDragReject correctly fires when dragging a file over the zone which is too big

**Comment by Interject-VictorC** [comment]
is there any progress or news on thig bug? Thank you!

**Comment by rolandjitsu** [comment]
@Maetes @Interject-VictorC note that during drag, we don't have access to all data on the file, so we may not be able to tell what the size or other info is. See https://react-dropzone.js.org/#browser-limitations (briefly touches on a similar subject).

**Comment by rolandjitsu** [comment]
I can confirm that `{isDragReject}` is not accordingly set when setting `maxSize`. I'll have a look to see why.
