### ISSUE TITLE
Don't allow duplicates of a file

### ISSUE THREAD

**Issue by Gkanawati** [react-dropzone/react-dropzone#1241]
Describe the solution you'd like
There should be a way to make sure users can't upload 2 of the same files.

Describe alternatives you've considered
I've tried to do this outside of the dropzone, but there doesn't seem to a way.

Teachability, Documentation, Adoption, Migration Strategy
It could just be a prop passed in called noDuplicates

My solution its not perfect, im looking for better solutions for this problem:

```
const { getRootProps, getInputProps } = useDropzone({
    accept: 'image/*',
    onDrop: (acceptedFile) => {
      const newFiles = acceptedFile.map(file => {
        return Object.assign(file, {
          preview: URL.createObjectURL(file)
        })
      })
      setFieldValue('files', [
        ...files,
        ...newFiles
      ])

      files.map(file => {
        newFiles.forEach(newFile => {
          if (newFile.name == file.name) {
            setToast({
              open: true,
              severity: 'error',
              text: 'Não é possível adicionar imagens duplicadas!'
            })

            const filteredArray = files.filter((item, index) => files.indexOf(item) == index)
            setFieldValue('files', filteredArray)
          }
        })
      })
    }
  })

  const handleRemoveFile = (fileName) => {
    const newFiles = files.filter(item => item.name !== fileName)
    setFieldValue('files', newFiles)
  }
```

**Comment by phuongwd** [comment]
@Gkanawati Just curious, why do you not use the [Custom validation](https://react-dropzone.js.org/#section-custom-validation)?

**Comment by Gkanawati** [comment]
> @Gkanawati Just curious, why do you not use the [Custom validation](https://react-dropzone.js.org/#section-custom-validation)?

There's what i was looking for!
