### ISSUE TITLE
[BUG] File path not available on Electron if clicking to select files

### ISSUE THREAD

**Issue by JuanIrache** [react-dropzone/react-dropzone#1249]
**Describe the bug**
Dragging files into the Electron app provides the absolute file path, clicking to select the files with a dialog does not

**To Reproduce**
1. Clone minimal example https://github.com/JuanIrache/react-dropzone-electron-path-debug
2. npm install
3. npm run dev
4. drag a file and see how the path prints correctly
5. click to select a file and see how it does not

**Expected behavior**
The file path can be read

**Desktop:**
 - OS: macOS Ventura
 - Browser: Electron
 - Version: 20 and others

**Additional context**
This was working on react-dropzone@11, breaks on @12 and newer

**Comment by JuanIrache** [comment]
`useFsAccessApi: false
`
fixes this

**Comment by harmonikas996** [comment]
@JuanIrache you're THE legend! Thanks a bunch!

**Comment by kolyasya** [comment]
@JuanIrache thanks! Fixed my issue with the missing file path in Electron app when using react-dropzone.

`useDropzone({ onDrop, useFsAccessApi: false })`

**Comment by steveoh** [comment]
This fixed an issue for me at one point but updating libraries today has this happening again.

**Comment by rolandjitsu** [comment]
@steveoh what version are you on now? Note that we've made the file access API disabled by default now.

**Comment by steveoh** [comment]
Newest version. Electron made a change that the prerender has to provide the location with a new webutils api and the renderer cannot access it directly.

**Comment by rolandjitsu** [comment]
> Newest version. Electron made a change that the prerender has to provide the location with a new webutils api and the renderer cannot access it directly.

Is this something we need to fix/handle on our end?

**Comment by steveoh** [comment]
Not in my opinion.

**Comment by steveoh** [comment]
@rolandjitsu now since 14.3.0 electron is broken again.
