### ISSUE TITLE
[Bug] Custom File Types

### ISSUE THREAD

**Issue by mochetts** [react-dropzone/react-dropzone#1265]
**Describe the bug**

It seems that react dropzone doesn't allow me to restrict the selection of file types to some custom format.

**To Reproduce**

Render a normal html input like this:

```html
<input type="file" accept=".segy, .sgy" />
```

This will scope the accepted files of the file picker to these two types, see:

https://user-images.githubusercontent.com/3678598/212408247-e2b37818-4051-4d01-a83b-d6e944c1530d.mov

Now, with `react-dropzone` I couldn't find a way to do the same as it only seems to allow standard mime types or every file.

**Expected behavior**
React dnd should allow to configure custom file formats. Same as the standard HTML file input.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 108.0.5359.124

**Context**

It seems that if I pass in these options to the dropzone config:
```
accept: { '': ['.segy', '.sgy'] }
```

It does render the right options for the input:
<img width="582" alt="image" src="https://user-images.githubusercontent.com/3678598/212409798-370e09c0-aed5-414c-8575-a73ecec8b5f4.png">

However, If I click to open the file picker, it opens with all files accepted. See the below video for more details:

https://www.loom.com/share/cdd0a74b894f442987ba91c26be0dc62

**Update 1**

After digging into the code, I saw that the file picker is being opened programmatically (not with a click event) which is making the accept attribute not to be considered for the file picker.

Now, after setting the accept property as:
```
accept: { 'application/octet-stream': ['.segy', '.sgy'] } # any binary, with these two extensions
```
It did scope the file picker, but the drag is still being marked as `isDragReject = true`.

**Comment by devcoderbuzz** [comment]
Hi Team,
wanted to know if any fix ??  i dont use call back as i need to pass additional params to call back.

**Comment by djizco** [comment]
Any updates on this? Having the same issue. I can't use noClick in my case because I'm trying to use it with a button, and it just accepts all types.

Accept prop should be modified to accept the native input "accept" values.

I have a dynamic input that needs to accept files types in this format: ".jpeg,.pdf,.csv" ...etc.  Using application/octet-stream works but I don't necessarily want that attached as an accepted file type.

**Comment by mervick** [comment]
@djizco try my solution above, and wrap your button inside label
```js
 return (
    <label {...getRootProps()}>
      <input {...getInputProps()} />
    </label>
  )
```

**Comment by rolandjitsu** [comment]
This is related to the use of file access APIs. Disabling that will probably result in what you expect.

**Comment by rolandjitsu** [comment]
Closing this for now. Please set `useFsAccessApi` to false if it's true or update to the latest version and the issue should, in theory, go away. 

But note that the `accept` will get both the mime type and file extensions in the latest version.
