### ISSUE TITLE
[BUG] `required` causes "An invalid form control with name='' is not focusable"

### ISSUE THREAD

**Issue by emlai** [react-dropzone/react-dropzone#1268]
**Describe the bug**
When using a `required` dropzone inside a form, submitting the form causes [An invalid form control with name='' is not focusable](https://stackoverflow.com/questions/22148080/an-invalid-form-control-with-name-is-not-focusable).

**To Reproduce**
1. Go to https://codesandbox.io/s/react-dropzone-example-forked-qxixgj?file=/src/App.js
2. Click on 'Submit'
3. See error `An invalid form control with name='' is not focusable` in console.
4. Remove `{ required: true }` and the submit is successful.

**Expected behavior**
react-dropzone should either support `required: true` or mention in the documentation what to do instead.

**Additional context**
This was previously addressed in https://github.com/react-dropzone/react-dropzone/pull/606 but seems to have regressed in 37306d94e6bd2e50ee56566950bd38775ec1e398.

Related issue: https://github.com/react-dropzone/react-dropzone/issues/523

**Comment by c-shubh** [comment]
My current workaround for this is to style the underlying file input with a small height and width and negative z-index.

https://codesandbox.io/s/react-dropzone-example-forked-9b7kb9?file=/src/App.js

**Comment by vdaguenet** [comment]
I fixed it by adding some style to the `input`:
```tsx
<input {...getInputProps({ name, required })}
  /* Hack to fix "An invalid form control with is not focusable" error */
  style={{
    display: 'initial',
    opacity: '0',
    position: 'absolute',
    zIndex: -1,
  }}
/>
```

However, this hides the browser error message on Safari, so make sure to have a custom error text for your users.

**Comment by rolandjitsu** [comment]
@vdaguenet 's suggestion is what I would have suggested too since you can style the input as you wish.

https://github.com/react-dropzone/react-dropzone/pull/1219 is probably also gonna address this.
