### ISSUE TITLE
[ENHANCEMENT] Integrate with the File System Access API as a progressive enhancement

### ISSUE THREAD

**Issue by tomayac** [react-dropzone/react-dropzone#1271]
It would be great if this made use of `DataTransferItem.getAsFileSystemHandle()` from the [File System Access API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API) as a progressive enhancement as per my [write-up](https://web.dev/patterns/files/drag-and-drop-files/#progressive-enhancement). This way, dropped files could be edited right away (instead of forcing a download of a copy), which would be a great win for apps that need to modify dropped files, like online image editors. Also see the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/getAsFileSystemHandle).

**Comment by rolandjitsu** [comment]
@tomayac that makes sense. The right place for this enhancement would be https://github.com/react-dropzone/file-selector .

Are you up for a PR to add this feature?

**Comment by rolandjitsu** [comment]
I think we can close this now since the feature was shipped (though, it seems to be causing a few issues for some).
