### ISSUE TITLE
Issue #980

### ISSUE THREAD

**Issue by YisehakE** [react-dropzone/react-dropzone#1278]
**Describe the bug**
How do I get other file values(ex: Buffer, md5) besides name and size? (Closed issue with no answer - #980)

**Comment by rolandjitsu** [comment]
There's an example at https://react-dropzone.js.org/ on how to read file contents. The dropzone gives you a https://developer.mozilla.org/en-US/docs/Web/API/File, it's up to you to do with it whatever you want.
