### ISSUE TITLE
[ENHANCEMENT] I want a way to add more files to my current state

### ISSUE THREAD

**Issue by saver711** [react-dropzone/react-dropzone#1279]
i want to be able to create dropzone with the 2 functionalities
- click on the dropzone input: overwrite files
- click on onother button (plus icon): add more files

**Comment by fosteman** [comment]
Same here. 
My use case is in managing footage. I have a drone that takes hundreds of photos, and sometimes, it records them into several folders (i.e. `DCIM100` `DCIM200` etc). 
I need to upload all of them, but can only select from one folder at a time.

Need a way to "add" and not "reset" the `acceptedFiles`. Or somehow manage the state outside of `acceptedFiles` ?

**Comment by rolandjitsu** [comment]
@saver711 you can manage your own state to achieve what you're describing. It's not within the scope of this lib to do what you mentioned.
