### ISSUE TITLE
[BUG] Incorrect MIME type of renamed image

### ISSUE THREAD

**Issue by NovikovRE** [react-dropzone/react-dropzone#1284]
**Describe the bug**
Invalid type of renamed image. In attached archive a webp8 image renamed to jpg, but the validator still accepts it. Is there any deep image validation, or just filename parsing?

**To Reproduce**

1. Exclude webp file type  `{ 'image/jpeg': ['.jpeg', '.jpg'], 'image/png': ['.png'] }`
2. Upload image from archive

**Expected behavior**
File rejected with type error

**Actual behaviour**
File accepted

**Screenshots**
![image](https://user-images.githubusercontent.com/100194730/227914932-71d1936c-10c3-408f-94ee-107e03908ed0.png)
![image](https://user-images.githubusercontent.com/100194730/227915286-27334281-3ed2-4b6b-a194-54e70b947f3b.png)

[webp.zip](https://github.com/react-dropzone/react-dropzone/files/11077456/webp.zip)

**Comment by rolandjitsu** [comment]
@NovikovRE the validation depends on what the browser tells us: mime type (type), file extension, file size. We don't run any other kind of validation beyond that.
