### ISSUE TITLE
[BUG] isDragRejected when type is empty (3D Meshes files)

### ISSUE THREAD

**Issue by etcarrupt** [react-dropzone/react-dropzone#1311]
**Describe the bug**
According to the iana.org page, the mesh mime-type should be empty:
![image](https://github.com/react-dropzone/react-dropzone/assets/19837393/6c591a23-f579-4f59-b796-d3978c072e51)

When I try to set the accept property to { "": [".stl"] }, the control always has the "isDragReject" to true when I drag over. But, when I drop the file, it is accepted.

I also try to use a custom validator:
const validator = (file: File) => {
  console.log(file);
  return null;
};

The log show that a image file has the correct type (first line). And my mesh file has an empty type (second line):
![image](https://github.com/react-dropzone/react-dropzone/assets/19837393/20625eb1-6b6a-4f22-9601-9c768bcd66a3)

**Expected behavior**
isDragReject should be false and isDragAccept should be true.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 14.2.3

**Comment by yahyashareef48** [comment]
i am having the same problem

**Comment by rolandjitsu** [comment]
It sounds like what you're describing is similar to https://github.com/react-dropzone/react-dropzone/issues/1270. In which case, that's expected. But maybe I'm misunderstanding the issue.

**Comment by etcarrupt** [comment]
@rolandjitsu Yes it's similar, except the mime type (more accurately the absence of mime type in my case) I wanted to use is official. But not common as the documentation asks.
Official list of mime type: https://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by rolandjitsu** [comment]
@etcarrupt based on
> When I try to set the accept property to { "": [".stl"] }, the control always has the "isDragReject" to true when I drag over. But, when I drop the file, it is accepted.

That's expected because you use the file extension, which is not available during drag, but only on drop. So we cannot reliably tell if we can accept or not the file. If the browser can detect the type, then I suggest you try to use a mime type instead of a file extension and see if that works.

> Official list of mime type: https://www.iana.org/assignments/media-types/media-types.xhtml

You should check https://developer.mozilla.org/en-US/docs/Web/HTTP/MIME_types/Common_types instead. Being in IANA doesn't mean that the browser understands it.

**Comment by etcarrupt** [comment]
@rolandjitsu I understand. Thanks for the clarification.
