### ISSUE TITLE
[ENHANCEMENT]  Support for transformFile option ?

### ISSUE THREAD

**Issue by vasilvestre** [react-dropzone/react-dropzone#1314]
**Is your feature request related to a problem? Please describe.**
dropzone/dropzone allow to transformFile. It's useful to change HEIC to PNG or so, actually the preview for heic do not work so I wanted this solution.

**Describe the solution you'd like**
A `transformFile` option as it exists in dropzone/dropzone

**Comment by derwaldgeist** [comment]
Same here, we need to convert HEIC files to JPG, as they are common on iPhones. Currently, dropping a HEIC file in Chrome results in an error and a broken preview image. A `transformFile` option would be helpful for this scenario.

**Comment by rolandjitsu** [comment]
@vasilvestre are you referring to the preview example or the [pintura](https://pqina.nl/pintura/) integration? Because this lib does not handle any transforms or edits or previews.

**Comment by vasilvestre** [comment]
> @vasilvestre are you referring to the preview example or the [pintura](https://pqina.nl/pintura/) integration? Because this lib does not handle any transforms or edits or previews.

The issue is a bit old but so far, the native library allow you to work on the file. The HEIC is the example that's the most common because browser can't handle HEIC and sometimes iOS takes care to convert files to jpg/png but not always.
In this case, the preview is broken
I may be able to create a reproducer but I'm not sure as I don't have any apple device

**Comment by rolandjitsu** [comment]
@vasilvestre could you maybe explain what you mean by *the native library*? 

> I may be able to create a reproducer but I'm not sure as I don't have any apple device

No worries. If you could, that'd be great. Otherwise it's also ok.

**Comment by vasilvestre** [comment]
> @vasilvestre could you maybe explain what you mean by *the native library*? 

Dropzone/dropzone has a "transformFile" hook at upload, you can change it's format etc... Which wasn't (isn't) available on reactdropzone

**Comment by rolandjitsu** [comment]
> Dropzone/dropzone

Can you share a link to this?

**Comment by vasilvestre** [comment]
> > Dropzone/dropzone
> 
> Can you share a link to this?

https://docs.dropzone.dev/configuration/events

**Comment by rolandjitsu** [comment]
@vasilvestre ok, I see. Note that this repo is not https://github.com/dropzone/dropzone (https://docs.dropzone.dev/). This repo is https://react-dropzone.js.org/ and it's a react lib.

We do not provide any high level features like the lib you mentioned does.

**Comment by vasilvestre** [comment]
I get that, I left the issue to ask for the enhancement/feature :)
I'm not a front dev and this was an issue years ago on a project I work on

**Comment by rolandjitsu** [comment]
> I get that, I left the issue to ask for the enhancement/feature :) I'm not a front dev and this was an issue years ago on a project I worked on

I see, ok. 

I believe that you can already apply whatever transformations you want to the files today w/ introducing a new prop. You could either do something like:
```js
const {acceptedFiles} = useDropzone()
const transformedFiles = acceptedFiles.map(myTransform)
```

Or use the `onDrop` callback to run some transform function.

To that end, I'll go ahead and close this for now.
