### ISSUE TITLE
Extending Dropzone - Click and select file not working Chrome

### ISSUE THREAD

**Issue by cenkkizil** [react-dropzone/react-dropzone#1329]
When we open the sample site in Chrome and select the file by clicking. File selection does not work. It works with Firefox and Safari. When we drag and drop the file, it also works in Chrome.

1. Go to https://react-dropzone.js.org/#section-extending-dropzone
2. Click on select file
3. Not work

**Desktop (please complete the following information):**
 - OS: macOS 14.0
 - Browser chrome
 - Version 119.0.6045.159

**Comment by rolandjitsu** [comment]
@cenkkizil is this still an issue?

**Comment by rolandjitsu** [comment]
Closing this for now. If this is still an issue, please open a new one.
