### ISSUE TITLE
[BUG] The dragzone is calling the custom validator on hover with a file

### ISSUE THREAD

**Issue by alexandreczg** [react-dropzone/react-dropzone#1333]
**Describe the bug**
When a custom validator is enabled and the user hovers the dropzone with a file dragged, it custom validator gets called with an `undefined` causing errors in the console.

**To Reproduce**
1. Just use the official example from [here](https://react-dropzone.js.org/#section-custom-validation)
2. Find a file to drag over the dropzone
3. Observe the errors in the console of your browser 
```
TypeError: Cannot read properties of undefined (reading 'length')
    at nameLengthValidator (test.tsx:6:19)
    at eval (index.js:122:1)
    at Array.every (<anonymous>)
    at allFilesAccepted (index.js:113:1)
    at eval (index.js:578:61)
```

**Expected behavior**
The custom validator should not be called until the files are actually dropped in the dropzone.

**Screenshots**

![image](https://github.com/react-dropzone/react-dropzone/assets/131292734/16327c63-0229-4464-8e53-d2d0a26b1d2b)

Here's a GIF:

![dragzone-error](https://github.com/react-dropzone/react-dropzone/assets/131292734/993b82fc-0118-4f2c-95af-dd1669a77d12)

**Desktop (please complete the following information):**
 - OS: MacOs & Windows
 - Browser Chrome and Firefox
 - Version Latest

**Comment by fecoderchinh** [comment]
Tried to add `?` as `file.name?.length`.
It's work for me.

**Comment by alexandreczg** [comment]
@fecoderchinh yes, you can build some guardrails on your own, such as:

```typescript
const validateInputFile = useCallback(
        (file: File | DataTransferItem) => {
            if (file instanceof DataTransferItem) {
                // This is a on drag item that gets passed as an argument to this function
                // it caused errors below, since it does not have the same properties as File
                return null;
            }
...
```

But I'd like to understand why is the validate function being called before the files are actually released into the dragzone. If you have an expensive validation function, this would cause some performance issues.

**Comment by rolandjitsu** [comment]
> @fecoderchinh yes, you can build some guardrails on your own, such as:
> 
> ```ts
> const validateInputFile = useCallback(
>         (file: File | DataTransferItem) => {
>             if (file instanceof DataTransferItem) {
>                 // This is a on drag item that gets passed as an argument to this function
>                 // it caused errors below, since it does not have the same properties as File
>                 return null;
>             }
> ...
> ```
> 
> But I'd like to understand why is the validate function being called before the files are actually released into the dragzone. If you have an expensive validation function, this would cause some performance issues.

@fecoderchinh the validation runs during all the drag events, including on drag over/enter/etc.

Let me know if there are any issues with the validation otherwise.

**Comment by rolandjitsu** [comment]
Closing this for now. If there's indeed some issue, please open a new ticket.
