### ISSUE TITLE
[ENHANCEMENT] Image ratio (or size) validation

### ISSUE THREAD

**Issue by Patzi275** [react-dropzone/react-dropzone#1336]
**Is your feature request related to a problem? Please describe.**
Actually it is possible to validate file size, but it's not possible for image ratio or size.
We cannot use the custom validation because it's not async, what is needed to wait for the image loading

**Describe the solution you'd like**
I want there to be parameters other than maxSize or minSize to validate the image ratio.

**Comment by adrivelasco** [comment]
this will be awesome. I was also unable to get this image resolution validation working with `getFilesFromEvent`.

**Comment by rolandjitsu** [comment]
There is a proposal for async validation which could allow what you're asking for. But since this lib is meant to deal with all kinds of files, we will not impl. specific logic to handle images and their ratio/size.
