### ISSUE TITLE
[BUG] `isDragReject` set to `true` for accepted `.rar` file type

### ISSUE THREAD

**Issue by grigorischristainas** [react-dropzone/react-dropzone#1342]
**Describe the bug**
This issue is reproducible in Windows, but not in Linux. 

I am trying to visually indicate whether a file is accepted or not for upload through drag & drop by checking the `isDragReject` value and changing the style of a specific area. However, this value is incorrect when trying to upload a `.rar` file. More specifically, it is set to `true` while dragging the file over the upload area, but the file is eventually accepted.

**To Reproduce**
Please check the following codesandbox: 
https://codesandbox.io/p/devbox/musing-mestorf-9j2y64?file=%2Fsrc%2F_app.jsx%3A10%2C5-10%2C17

1. Have demo .rar and .png files available locally
2. Drag & drop the .rar file on the corresponding area (styled with a green border)
3. You should see the border turn to red
4. Drop the file on the area
5. File is marked as accepted and displayed under the `Accepted files` section

Repeat the previous steps with the .png file. You should not see the area border turn to red.

**Expected behavior**
Expected the `isDragReject` value to be equal to `false` but instead it is equal to `true`. However, the file is eventually accepted. This causes an incorrect behavior when trying to visually indicate whether this file is valid or invalid for upload.

**Desktop:**
 - OS: Windows 10 Pro
 - Browser: Reproduced in latest versions of Chrome and Firefox
 - Version: 14.2.3

**Comment by rolandjitsu** [comment]
@grigorischristainas this may be a browser limitation, please checkout [Accepting specific file types](https://react-dropzone.js.org/#section-accepting-specific-file-types), the **Browser limitations** section.

**Comment by rolandjitsu** [comment]
I will close this issue for now as the issue summary points to an expected behaviour.
