### ISSUE TITLE
IsDragReject evaluating to true when accepting 'application/ld+json' file type

### ISSUE THREAD

**Issue by navacmo** [react-dropzone/react-dropzone#1346]
**Describe the bug**
When using mime type 'application/ld+json' the isDragReject is emitting true. 

**To Reproduce**
[code sandbox example of the issue](https://codesandbox.io/p/sandbox/react-dropzone-example-forked-rkvncr?file=%2Fsrc%2FApp.js%3A24%2C6&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltf9mdjz0007356hwtfkk0gi%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltf9mdjz0003356hvrhdvpzf%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltf9mdjz0004356hb0o2zxcm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltf9mdjz0006356hwpq1028r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltf9mdjz0003356hvrhdvpzf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltf9mdjz0002356h03ucjvrm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A24%252C%2522startColumn%2522%253A6%252C%2522endLineNumber%2522%253A24%252C%2522endColumn%2522%253A6%257D%255D%257D%255D%252C%2522id%2522%253A%2522cltf9mdjz0003356hvrhdvpzf%2522%252C%2522activeTabId%2522%253A%2522cltf9mdjz0002356h03ucjvrm%2522%257D%252C%2522cltf9mdjz0006356hwpq1028r%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltf9mdjz0005356h74fvyg8a%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltf9mdjz0006356hwpq1028r%2522%252C%2522activeTabId%2522%253A%2522cltf9mdjz0005356h74fvyg8a%2522%257D%252C%2522cltf9mdjz0004356hb0o2zxcm%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltf9mdjz0004356hb0o2zxcm%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

1. Pick a file with extension .json or .jsonl (JSONL is the new format for JSON with Lines)
2. Try dragging the file into the drop box
4. See the color of the dashed border turning red and file getting accepted by the input. 

**Expected behavior**
1. isDragReject should emit a false value. 
2. isDragAccept should emit a true value.

**Screenshots**
![screenshot_of_the_issue](https://github.com/react-dropzone/react-dropzone/assets/138220278/96a94617-fb10-4ec1-9fef-fa7a7586d08e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 122.0.6261.95

**Additional context**
See the mimetype information here. The input should accept application/ld+json for .jsonl extension
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

**Comment by rolandjitsu** [comment]
It could be related to https://github.com/react-dropzone/react-dropzone/issues/1342. 

In any case, I just had a quick look and as far as I can see, the file type is not reported by the browser. So [file-selector](https://github.com/react-dropzone/file-selector) attempts to infer it using the file extension, but we only have an entry for `jsonld`.  And according to https://developer.mozilla.org/en-US/docs/Web/HTTP/MIME_types/Common_types, the expected file extension is also `jsonld`.

And according to https://jsonlines.org/:
> MIME type may be application/jsonl, but this is not yet standardized; any help writing the RFC would be greatly appreciated (see [issue](https://github.com/wardi/jsonlines/issues/19)).

So I'll go ahead and add the `application/jsonl` type to common types when the `.jsonl` ext. is used.
