### ISSUE TITLE
[BUG] render upload language always English

### ISSUE THREAD

**Issue by Lijiaoa** [react-dropzone/react-dropzone#1352]
**Describe the bug**
in google, 
![图像 (20)](https://github.com/react-dropzone/react-dropzone/assets/61399850/2481e1d5-5807-4677-85b8-64874db25df3)

in edge:
![图像 (21)](https://github.com/react-dropzone/react-dropzone/assets/61399850/7750a607-df57-427e-b331-77e62302eace)

**so I want to render it uniformly in English**

**To Reproduce**

3. Select file '....'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rolandjitsu** [comment]
I believe this is driven by the browser and this lib does not control how to display that. Checkout this [SO](https://stackoverflow.com/questions/20517321/change-language-input-type-file), it may help with what you're trying to achieve.
