### ISSUE TITLE
[BUG] Version 14.2.6 could not read the typings file

### ISSUE THREAD

**Issue by RinMinase** [react-dropzone/react-dropzone#1371]
**Describe the bug**
There seems to be an issue in handling the typings.

**To Reproduce**
1. Install **version 14.2.6**
2. Import the package in any typescript project

There should be an error similar below:
```
Could not find a declaration file for module 'react-dropzone'.
'[...redacted...]/node_modules/react-dropzone/dist/es/index.js' implicitly has an 'any' type.

There are types at '[...redacted...]/node_modules/react-dropzone/typings/react-dropzone.d.ts',
but this result could not be resolved when respecting package.json "exports".
The 'react-dropzone' library may need to update its package.json or typings.
```

**Expected behavior**
Types should be read.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 14.0
 - Browser N/A (Since this is only found in importing the library)
 - Version 14.2.6

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
I have found that `typings/react-dropzone.d.ts` is present, but it does not seem to be read, would this perhaps be related to [this commit](https://github.com/react-dropzone/react-dropzone/commit/2471dd9c63a5b2ef972931761ff30ade06fae2be)

I likewise have found that this only happens **only** with the latest version (during the writing of this report) **14.2.6**. I manually installed 14.2.3, 14.2.4 and 14.2.5 and found no issues with them. 🙇🏻‍♂️

**Comment by dugan-dev** [comment]
Same thing happening for me.

**Comment by r2k1g2** [comment]
I have the same issue but the type error seems to have appeared on version 14.2.4. 

I was on version 14.2.3 on which it worked. I wanted to upgrade to the latest version but the type error appeared.
I reset my version to 14.2.3 and tried upgrading to 14.2.4 but the type error appeared again.
Perhaps the issue is linked to [this commit](https://github.com/react-dropzone/react-dropzone/commit/960c6d33179a86e79c1ff65902e7393b54e322b3) ?

Hope it helps.

**Comment by rolandjitsu** [comment]
I believe the issue is related to https://github.com/react-dropzone/react-dropzone/commit/2471dd9c63a5b2ef972931761ff30ade06fae2be. Let me see if I can find a quick fix.

**Comment by rolandjitsu** [comment]
@RinMinase what version of node are you on?

Also, if anyone can try https://github.com/react-dropzone/react-dropzone/pull/1372 and see if that helps, I'd appreciate it.

**Comment by AndrewJSchoen** [comment]
@rolandjitsu I can confirm that this error is present for me as well. Here are my npm/node versions:
node: v20.17.0
npm: 10.8.2

**Comment by RinMinase** [comment]
@rolandjitsu Sorry for not including it in the description above
I'm currently on `v20.17.0`.

**Comment by AndrewJSchoen** [comment]
@RinMinase did you set it as a npm git dependency? If so, would you mind sharing how you configured it in the package.json? I can't get it to recognize the commit for some reason.

**Comment by RinMinase** [comment]
@AndrewJSchoen Apologies, I'm sure that I am not testing it the way the maintainers do. 🙇🏻

Please do note that I was only testing the changes from the PR. These additional steps below would not reflect permanently in your `node_modules` folder.

Here were my steps for this:
(I likewise tried adding the git repository as a dependency with yarn earlier as well, but since the this was not possible)
- I cloned the branch of the PR
- Built the project and the typings (yarn build + yarn typescript)
- Copied over to my project using the library
- Checked to see if the types are working correctly

**Comment by ngodacthien** [comment]
Im fix ok. Add this code to package.json and down to .5

**Comment by cheskoxd** [comment]
Also having this same issue, downgraded to 14.2.3 to fix
