### ISSUE TITLE
[BUG] react-dropzone@14.2.6 missing types

### ISSUE THREAD

**Issue by RicardoGEsteves** [react-dropzone/react-dropzone#1376]
**Describe the bug**

Missing types on react-dropdown @14.2.6, getting typescript errors on develop environment and building on vercel.

Failed to compile.
./node_modules/.pnpm/@xixixao+uploadstuff@0.0.5_react-dropzone@14.2.6_react@18.3.1react@18.3.1_typescript@5.6.2/node_modules/@xixixao/uploadstuff/lib/UploadDropzone.tsx:2:43
Type error: Could not find a declaration file for module 'react-dropzone'. '/vercel/path0/node_modules/.pnpm/react-dropzone@14.2.6_react@18.3.1/node_modules/react-dropzone/dist/es/index.js' implicitly has an 'any' type.
  There are types at '/vercel/path0/node_modules/.pnpm/@xixixao+uploadstuff@0.0.5_react-dropzone@14.2.6_react@18.3.1react@18.3.1_typescript@5.6.2/node_modules/react-dropzone/typings/react-dropzone.d.ts', but this result could not be resolved when respecting package.json "exports". The 'react-dropzone' library may need to update its package.json or typings.
  1 | import { useCallback, useState } from "react";
2 | import type { Accept, FileWithPath } from "react-dropzone";
    |                                           ^
  3 | import { useDropzone } from "react-dropzone";
  4 | import { twMerge } from "tailwind-merge";
  5 | import { UploadFileResponse } from ".";
 ELIFECYCLE  Command failed with exit code 1.
✖ 'pnpm build' failed
Error: Command "pnpm dlx convex deploy --cmd 'pnpm build'" exited with 1

**Comment by rolandjitsu** [comment]
@RicardoGEsteves this should be fixed with the latest version (see https://github.com/react-dropzone/react-dropzone/pull/1372). Let me know if it does or not.

**Comment by RicardoGEsteves** [comment]
> @RicardoGEsteves this should be fixed with the latest version (see #1372). Let me know if it does or not.

Thank you for your reply @rolandjitsu, yes it's fixed now. After bumping it to latest everything works fine.
