### ISSUE TITLE
[BUG] Browser crashes with errocode RESULT_CODE_KILLED_BAD_MESSAGE on Edge and Chrome

### ISSUE THREAD

**Issue by KidOfJealous** [react-dropzone/react-dropzone#1397]
**Describe the bug**
I simply build a web app with a file dropzone and when I drop one file on it, the browser crashed. Old versio 14.2.3 works well but I did not lock the version so it did not work after the newest update on yesterday.

**Expected behavior**
![image](https://github.com/user-attachments/assets/a84cb66a-0d63-4284-b082-9f23d533c256)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome, Edge]

**Comment by rolandjitsu** [comment]
@KidOfJealous have you updated your browser(s) as well or your OS?

I found some [similar issue](https://techcommunity.microsoft.com/t5/discussions/microsoft-edge-error-code-result-code-killed-bad-message/m-p/2492184) being reported that's unrelated to this lib.

**Comment by wojbak** [comment]
I was able to recreate this issue using production build.
Library version: `^14.3.5`, issue is only happening on drop, manual files selection is working correctly.
My browser is updated. Recreated on Macbook pro.

<img width="840" alt="Screenshot 2024-11-09 at 23 54 24" src="https://github.com/user-attachments/assets/cb5a5891-c4c2-4b93-8449-abcb6405e89e">

**Comment by wojbak** [comment]
Lowering library version to `14.2.9` resolved the issue, so I can confirm that it was caused by the latest build

**Comment by ahmetaydar** [comment]
I downgraded the version to 14.2.9 and resolved. thanks @wojbak

**Comment by rolandjitsu** [comment]
> I was able to recreate this issue using production build. Library version: `^14.3.5`, issue is only happening on drop, manual files selection is working correctly. My browser is updated. Recreated on Macbook pro.
> 
> <img alt="Screenshot 2024-11-09 at 23 54 24" width="840" src="https://private-user-images.githubusercontent.com/185230861/384647369-cb5a5891-c4c2-4b93-8449-abcb6405e89e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MDUxMzMsIm5iZiI6MTczMTUwNDgzMywicGF0aCI6Ii8xODUyMzA4NjEvMzg0NjQ3MzY5LWNiNWE1ODkxLWM0YzItNGI5My04NDQ5LWFiY2I2NDA1ZTg5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QxMzMzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjQ2MDY3MTg2NjlhYzg2ZmFkYTUxYjJjN2NiZWNmMzI3NWMwNDFjNWIzYmY0NDRiMTM5ZTRmMzM1ODdlOWNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.W-MaQcwDSKhqlRElsKm9Jcq0dPVnySEB2jdZERHjIdk">

Hmm ... I cannot reproduce on my macOS (12.7) and Chrome 130.

**Comment by ahmetaydar** [comment]
> > I downgraded the version to 14.2.9 and resolved. thanks @wojbak
> 
> What OS and browser/version are you on?

OS: Windows 10 pro
Browser Chrome 130.

**Comment by euvs** [comment]
Same issue. 
Chrome: Version 130.0.6723.117 (arm64)
Mac: 13.5.1
Dropzone: 14.3.5  (crashing browser)
Dropzone: 14.2.9  (not crashing)

**Comment by wbaklazec-sch** [comment]
> > I downgraded the version to 14.2.9 and resolved. thanks @wojbak
> 
> What OS and browser/version are you on?

Chrome: Version: 130.0.6723.117 (arm64)
Mac: 14.6.1

**Comment by rolandjitsu** [comment]
Interesting. For mac, it seems that newer versions have the issue since I cannot reproduce on mine on https://react-dropzone.js.org/ (I'm also on arm).

**Comment by rolandjitsu** [comment]
Is everyone getting the `RESULT_CODE_KILLED_BAD_MESSAGE` error?

**Comment by euvs** [comment]
The crash starts to happen from `v14.3.0` for me. `v13.2.9` works fine.

I looked at the diff between the two versions. The only thing that stood out to me was the `file-selector` package version. 

https://github.com/react-dropzone/react-dropzone/compare/v14.2.9...v14.3.0#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deL6252

As an experiment I pinned `file-selector` to the previous version `v0.6.0` while using `v14.3.0`. Result - no crash. 

It looks like the problem is somewhere in the "file-selector" dependency package.

**Comment by Pboy208** [comment]
Having the same problem with `v14.2.3`
- Browser: chrome v130.0.6723.117 (safari works fine)
- OS: macOS Somona v14.5

**Comment by bencroskerylite** [comment]
I'm getting this error now since upgrading, from what I've found this is a bug related to using `getAsFileSystemHandle()` in a non-https context in Chrome. I'm using http for my app, if I switch to https the crash goes away.

I found this PR that adds a check for `window.isSecureContext` to workaround this problem: https://github.com/transloadit/uppy/pull/4310/commits/09ac70724f13047341f7b9cc3e8243c2b4a51b71

Adding that check here in the file-selector package would probably fix this crash from what I can tell: https://github.com/react-dropzone/file-selector/blob/master/src/file-selector.ts#L124

**Comment by rolandjitsu** [comment]
> I'm getting this error now since upgrading, from what I've found this is a bug related to using `getAsFileSystemHandle()` in a non-https context in Chrome. I'm using http for my app, if I switch to https the crash goes away.
> 
> I found this PR that adds a check for `window.isSecureContext` to workaround this problem: [transloadit/uppy@09ac707](https://github.com/transloadit/uppy/commit/09ac70724f13047341f7b9cc3e8243c2b4a51b71)
> 
> Adding that check here in the file-selector package would probably fix this crash from what I can tell: https://github.com/react-dropzone/file-selector/blob/master/src/file-selector.ts#L124

Thanks for adding more context. That sort of makes sense, well, it doesn't, it should just throw an exception/error in the console and not crash the browser 😆 But the fact that not being in a secure context wouldn't work makes sense (that's the requirement).

We also use the same check in this package and I guess we should use it in the other package(s) as well.

**Comment by jonkoops** [comment]
This honestly sounds like a bug in Chromium based browsers, if this is reproducible it should be reported to the Chrome team. It cannot be that a simple call to a Web API crashes a whole browser tab like this. Btw, I am not able to reproduce this on Chrome 131.0.6778.85. For those experiencing this issue, does upgrading your browser to the latest version fix the problem?

**Comment by jonkoops** [comment]
Looks like there is already a bug report for this: https://issues.chromium.org/issues/40186242

**Comment by rolandjitsu** [comment]
> This honestly sounds like a bug in Chromium based browsers, if this is reproducible it should be reported to the Chrome team. It cannot be that a simple call to a Web API crashes a whole browser tab like this. Btw, I am not able to reproduce this on Chrome 131.0.6778.85. For those experiencing this issue, does upgrading your browser to the latest version fix the problem?

I'm also unable to reproduce in either Chrome (131.0.6778.70), Firefox (132.0.2) or Safari (17.6) on macOS 12.7.6 (arm). 

Some of the reports are on later versions. It may just happen on newer OSes.

**Comment by bencroskerylite** [comment]
Looks good! I just tried installing latest react-dropzone, it pulled in file-selector@2.1.1, and if I try the same test case from last week I don't get any crash (if I manually downgrade file-selector to 2.1.0 I reproduce the problem again so looks like the fix is working).

**Comment by rolandjitsu** [comment]
> Looks good! I just tried installing latest react-dropzone, it pulled in file-selector@2.1.1, and if I try the same test case from last week I don't get any crash (if I manually downgrade file-selector to 2.1.0 I reproduce the problem again so looks like the fix is working).

Ok, thanks for confirming. Let's see what other users say.

**Comment by luigimannoni** [comment]
I used to have these crashes last month or so, but seemingly it was something not related to dropzone but tied to the uppy.js package I was using after dropping the files, I can confirm that these reappeared after updating my chrome yesterday.

Likewise I pulled in `file-selector@2.1.1` and seems to be working.

**Comment by jonkoops** [comment]
Thanks for confirming, I think we can safely consider this issue resolved :+1:
