### ISSUE TITLE
Remove display none from input element

### ISSUE THREAD

**Issue by vladshcherbin** [react-dropzone/react-dropzone#161]
Since it is hidden, we can't use Tab to select it and choose a file.

If is remains visible, but has style of width: 0, height: 0 - we are able to choose this element.

**Comment by okonet** [comment]
PR?

**Comment by VladShcherbin** [comment]
@okonet sure, will do today

**Comment by okonet** [comment]
Possible related to #180 

@VladShcherbin what about the PR? Still gonna do it?

**Comment by VladShcherbin** [comment]
@okonet hey, I've tried to do it, but we need to show the active state somehow with css (as you press tab  key and want to see it becomes active).

We can use `+` selector, but this way we need to make sure `input` element is placed before the styled element.

**Comment by okonet** [comment]
I'm open to any solution at this point. I also think that current implementation prevents using Dropzone inside of `form` element with `submit` handler, so I'd say, it's worth trying. I like the idea BTW and glad to help.

**Comment by arjshiv** [comment]
Naive question:, but can we use`opacity: 0` instead of `display: none` ? That should create an element on the stacking context which should be clickable and tabbable http://stackoverflow.com/a/742324

**Comment by VladShcherbin** [comment]
@arjshiv you can set the opacity, but the item (input element) will produce white space inside the dropbox element (width + height of the element).

But it's not the main problem - you need to show the user that the dropbox element gets focused. To do this - you can add a class when input is focused or use css selector.

**Comment by VladShcherbin** [comment]
Probably an easy solution can be smth like this:

```js
const dropzoneClassName = classNames('dropzone', { focused: this.state.isFocused })

<Dropzone className={dropzoneClassName}>
  <input onFocus={this.handleInputFocus} />
</Dropzone>
```

And the input element can be set to 0 / 0 (width / height) and 0 opacity.

**Comment by arjshiv** [comment]
@VladShcherbin Thanks - that's helpful. I'll try and see if I can take a crack at it later this week if you and @okonet are open to it

**Comment by arjshiv** [comment]
@VladShcherbin yeah that's exactly the kind of thing I had in mind

**Comment by VladShcherbin** [comment]
@arjshiv sure, go for it. I tried some time ago, but unfortunately didn't end up with the tests setup.

Would be great if you'll try to solve it ;)

**Comment by VladShcherbin** [comment]
@arjshiv @okonet  [here](https://github.com/VladShcherbin/department/blob/master/src/components/Forms/components/Dropzone.js) is a simple dropbox component I'm using in my apps and a [small demo](https://esnextb.in/?gist=7df161cc836c07127ed4b9e1a2af9881).

It toggles the `focused` class and works as described above. Maybe it can help to do similar thing here.

**Comment by josh18** [comment]
What if we just add `tabindex="0"` to the outer div, add a listener for `onKeyPress` and then filter for <kbd>Space</kbd> / <kbd>Enter</kbd>?

**Comment by okonet** [comment]
I'd rather skip implementing `:focus` behavior -- this might end up very messy and on different platforms might then work differently.

**Comment by josh18** [comment]
It is a pretty important feature for usability, without it keyboard only users won't be able to use it. What part are you thinking could get messy? Seems pretty straight forward to me.

**Comment by okonet** [comment]
I'm not doubting accessibility is important but implementing these features yourself isn't the best strategy from my experience. So I'm open to a standard-based solution that doesn't involve custom event handling etc.

**Comment by okonet** [comment]
@josh18 I've edited my initial comment that might lead to the confusion.

**Comment by VladShcherbin** [comment]
@okonet I've used two solutions:

1) Using input `onFocus` & `onBlur` events (when input is focused / blurred, the `focused` class is toggled)

```js
<Dropzone className={giveMeTheClass}>
  <input onFocus={addFocusedClass} onBlur={removeFocusedClass} />
</Dropzone
```

2) Using just css selector (but it needs markup changes)

```js
<Dropzone>
  <input />
  <div className="dropzone-box" />
</Dropzone>
```

css part

```css
input:focused + .dropzone-box {
  border-color: blue;
}
```

Both of them worked for me, though I didn't test them on phones, tablets, IE.

Not sure, if there is a better solution or which one is the best. I've seen the first solution (focus trick) in other element libraries.

**Comment by VladShcherbin** [comment]
Personally, I also ended with using the first solution - no need for a `dropzone-box` element and is easy to implement (just toggle a class with a name from props).

**Comment by okonet** [comment]
@VladShcherbin I like the first one better since we want to support inline styling not just CSS. Does it work with the hidden `<input />` as well? Can you submit a PR with it?

**Comment by josh18** [comment]
Ah ok I see what you mean. However adding enter / space input seems to be pretty common.
[Example 1](http://webaim.org/techniques/keyboard/tabindex#zero-negative-one)
[Example 2](https://www.w3.org/WAI/GL/wiki/Making_actions_keyboard_accessible_by_using_keyboard_event_handlers_with_WAI-ARIA_controls#Example_2:_Keyboard_support_for_a_set_of_toggle_buttons)

I'm not such a fan of the adding classes option as the default focus (e.g. glow on Chrome) won't work so I think you would either have to set a focus style or trust that a user is going to set a custom focus style. I guess that's the same if you use the `+` selector.

Another possible option is to use a `<button>` instead of a `<div>` and then just reset all the styles on the button, not sure I would recommend that though.

**Comment by VladShcherbin** [comment]
@okonet I tried to setup on local previously, but failed with the tests setup. The needed steps: 

- input onHover / onBlur events
- dropzone onHover / onBlur props (for custom events)
- add a focused state with default false
- toggle focused state in input handle events
- add dropzone prop for a focused class
- add this class to dropzone
- add inline styles for focused state
- input has to be visible, my css for it is

```css
input {
  display: block;
  width: 0;
  height: 0;
  border: none;
  opacity: 0;
  overflow: hidden;
}
```

**Comment by okonet** [comment]
Great! I'll try to find some time to work on this one but I'd appreciate a PR for it as well!

**Comment by josh18** [comment]
What's the plan on creating focus style for the dropzone div? For example if you add a focus class what style would you use for `.dropzone.isFocused`? Create a custom style? Or just leave it blank and rely on the user to add a custom style?

IIRC browsers don't necessarily have the same default focus style and Firefox doesn't have any, instead it just uses the default focus style of the OS you are using.

**Comment by VladShcherbin** [comment]
@josh18 you can look at the [source code](https://github.com/okonet/react-dropzone/blob/master/src/index.js#L152-L206) to see, how `active`, `rejected` and default styles are handled.

Basically, if you provide you classes or styles- it will you them, if you don't provide anything - will use default ones.

**Comment by josh18** [comment]
Sorry I probably wasn't very clear with my question, I mean what css properties are you going to use? For example in Chrome the default for `:focus` is `outline: -webkit-focus-ring-color auto 5px;`

**Comment by VladShcherbin** [comment]
I'd choose `border-color` / `outline` or something, that doesn't need browser prefixes. Actually, since currently there is no such feature, any styling will be good as it can easily be changed later.

**Comment by josh18** [comment]
Wouldn't you want it to be consistent with the default browser styles though? Otherwise there's a high chance it is going to be different from all the other focus styles on the page.

**Comment by VladShcherbin** [comment]
It depends on the personal taste, I actually never rely on default library styles. The real answer is - the person with the PR will have to decide this for us :)

**Comment by okonet** [comment]
The more I think about it, the less I like the approach of providing these styles by this library. Following the "React-way" should allow easy composition. Having lot's of such decisions in the library will potentially break some use cases for many people.

Consider the following example: you have a Dropzone around a `<textarea>`, like GitHub does. I believe it is the `<textarea>` you want to get be focused when you navigate with the keyboard and not the `<input>`. Same way, if you want to make the Dropzone look like a normal input, there should be an easy way of passing styles to the input element.

I think, in the end, this should be done in the user-land, i.e. it should be a developer's job to provide accessible content inside the Dropzone. One exception, though, is the ability to style the input should be also provided. I think this is pretty easy and elegant solution that would not break anything.

Thoughts?

**Comment by josh18** [comment]
Good point, I didn't think about having multiple controls inside (though in your example I think you would want *both* focusable).

Letting the developer add styles to the file input seems like a good idea to me. If possible maybe you could also let them add attributes so they can add things like `onFocus` and `aria-label`?

The only problem with this approach is that I think lots of developers will either forget or ignore the accessibility part. Maybe if these changes go through I can write up some accessible examples to remind them and help them get started? Do you think that would be helpful?

**Comment by okonet** [comment]
@josh18 I'd be happy to include your accessibility tips. I also think this lib could provide sane defaults out of the box (talking about `aria-label` for example) + a way to customize it.

I'm still not sure how to tackle such a change. One of the pain points is also integrating this component with forms (`redux-form` or simple ones) since the implementation detail about the `input` is hidden. On the other hand, I realize most of the developers appreciate the ease of integration. Does anyone have an idea here?

PS: Should ↑ be a separate discussion?

**Comment by josh18** [comment]
Sorry I don't quite understand what you are meaning, can you expand on this?
> since the implementation detail about the `input` is hidden

Also I just realised you can already edit the input via inputProps which is really useful, maybe one of the changes we make is split up overridable (style, aria-label) and non-overridable props (ref, onChange, etc).

**Comment by forabi** [comment]
I think this can be solved with the following steps: 
1. use a root element of type `button` instead of `div`
2. allow tabindex on dropzone props.
3. add `onClick` prop on root with a value of `this.open`.

**Comment by luisfuertes** [comment]
I have this code:
```
<form>
  <input />
  <Dropzone ref={"dropzone"}>
      <button type="button" onClick = { (e) => { e.preventDefault(); this.refs.dropzone.open(); } } />
  </Dropzone>
</form>
```

The problem is when i press enter with input focused, onClick dropzone button is trigered. But if move button out of Dropzone, it isnt happens.

I don know if it is related with this issue. Sorry if not
