### ISSUE TITLE
isDragReject true for accepted file extension

### ISSUE THREAD

**Issue by davey-h** [react-dropzone/react-dropzone#171]
I have seen this work appropriately when setting the MIME type but has not been working when setting the file extension. I want to set a more specific extension, but for the sake of the bug I have been seeing `.png` being rejected when choosing to accept `.png` files. The hidden input is working as expected, but the hover and subsequent event is not working as expected.

React dev tools showing current accept:
![screen shot 2016-05-10 at 4 45 54 pm](https://cloud.githubusercontent.com/assets/10803935/15162030/d8d68e04-16ce-11e6-86da-40d5309438f9.png)

Screenshot of rejection:
![drag-reject](https://cloud.githubusercontent.com/assets/10803935/15162145/7e7cd39a-16cf-11e6-9f33-9308cc7ebc43.png)

I apologize if I've missed something. I'm looking back at your [attr-accept](https://github.com/okonet/attr-accept) project to trace it back.

**Comment by okonet** [comment]
It should work: https://github.com/okonet/attr-accept/blob/master/test/index.js#L112 What are you having in `files` array? Might this be a browser issue?

**Comment by davey-h** [comment]
I set multiple to false so am seeing this when `onDrop` goes through

```
[
   {
      FilelastModified:1462117336000
      lastModifiedDate:Sun May 01 2016 11:42:16GMT-0400 (EDT)
      name:"picard-facepalm.png"
      preview:"blob:http%3A//localhost%3A3000/248462f3-31b5-4249-bda4-72683789066e"size:688312type:"
      image/png"webkitRelativePath:""__proto__:Filelength:1__proto__:Array
   }
]```

**Comment by okonet** [comment]
Interesting... The file object looks good to me. 

Can you try using wildcard in the `accepts` attribute? `*.png`.

I'll run attr-accept tests against your object.

**Comment by davey-h** [comment]
Unfortunately adding the wildcard doesn't fix the issue for chrome and it also breaks the hidden `<input>` as I think you plug the accept directly in and the input `accept` doesn't recognize wildcards. 

Are you able to replicate the issue or is there something unique happening at my end?

**Comment by mirague** [comment]
What is your Chrome version?

**Comment by abimelex** [comment]
Using accept: 'text/csv' does also not work here on windows computers with any kind of browser and version. Have it on OSX is no problem...

**Comment by okonet** [comment]
So it's a OS / browser issue after all?

**Comment by davey-h** [comment]
I don't think that addresses my issue. I use OSX and the latest Chrome. My issue is related to using file extension and not by specifying the MIME type

**Comment by davey-h** [comment]
Actually, it might be an OS issue. Just tested on Linux with no issue. That or 3.5.0 fixed it. Either way, I think this can be considered closed

**Comment by okonet** [comment]
3.5.0 could not fix it, so I assume it's OS-related inconsistency? Would be great if someone could create a reproducible example.

**Comment by davey-h** [comment]
Yes, it is an OS-related inconsistency. Just checked back with OSX and can still reproduce.

```
<Dropzone
                  accept={this.props.accept}
                  multiple={false}
                  className="form--dropzone"
                  activeClassName="form--dropzone--active"
                  rejectClassName="form--dropzone--reject"
                  onDropAccepted={this.setUploadSuccess}
                  onDropRejected={this.setUploadFail}
                >
```

and what is being passed down: `accept: ".cdxml"`

**Comment by martin-svk** [comment]
Using the MIME types instead of file extensions solved this proplem for me. 
With file extensions it worked on firefox but not on chrome. Same OS -> Ubuntu.

**Comment by qrpike** [comment]
Having this problem
OS: `macOS High Sierra`
Browser: `Chrome Version 62.0.3202.62 (Official Build) (64-bit)`

I drag in a .sketch file, and have `*.sketch` as the wildcard, but it adds the reject class, and the `type` key of the file object is `""`.

**Comment by okonet** [comment]
Doesn't anyone want to take this one and fix it?

**Comment by rkmarks** [comment]
I'll have some time tomorrow to work on this. Though might have something w/ attr-accept npm module. Not sure. I'll dig in

**Comment by rdjpalmer** [comment]
@rkmarks did you get anywhere with the fix for this? I've just been in the scenario of having to fix our usage of `text/csv` seeing as it doesn't work on windows, and now I'm getting the issue described here. Happy to help with the fix if needed /cc @okonet

**Comment by rkmarks** [comment]
Hey @rdjpalmer I unfortunately haven't had a chance to fix this, i've been busy w/ projects at work. If you have the time you are more than happy to take this off my hands 😄

**Comment by rdjpalmer** [comment]
@rkmarks sure, I can pick this up on Monday. Did you do any investigation at all? Could you or @okonet point me in the direction of where best to look? 😅

**Comment by rdjpalmer** [comment]
So I'm thinking this has to do with how `isDragReject` is being set:

https://github.com/react-dropzone/react-dropzone/blob/ccb859f1eaa43683952bc4f3d4b6d3283a8582a8/src/index.js#L310-L311

as per the documentation, we're unable to read the file name mid-drag, only the mime-type. So in cases where we have an `accept` that isn't a mime, `filesCount > 0` will be `true`, and `isDragAccept` will be `false` because of how `attr-accept` validates the mimes:

```jsx
    return acceptedFilesArray.some(type => {
      const validType = type.trim()
      if (validType.charAt(0) === '.') {
        return fileName.toLowerCase().endsWith(validType.toLowerCase())
      } else if (/\/\*$/.test(validType)) {
        // This is something like a image/* mime type
        return baseMimeType === validType.replace(/\/.*$/, '')
      }
      return mimeType === validType
    })
```

https://github.com/okonet/attr-accept/blob/master/src/index.js#L24-L33

My initial thoughts are to check what kind of `accept` prop we have (mime or extension) and include that in the setting of `isDragReject`, something like:

```jsx
const acceptIsMime = /\/\*$/.test(this.props.accept)

const isDragReject = acceptIsMime && filesCount > 0 && (!isDragActive || !isMultipleAllowed)
```

Maybe the test for what kind of `accept` we have should actually live in `fileAccepted`?

How do we feel about this solution?

**Comment by lruckman** [comment]
Shouldn't a combination of mime's and extensions in the accept list address this?

**Comment by amitpatil321** [comment]
Thanks @ArtemBernatskyy : You are close to god :) It solved my csv issue.

**Comment by caravinci** [comment]
This however doesn't fix the problem for files with unspecified MIME types.
Any hints on how to handle that case?
