### ISSUE TITLE
When wrapped in a label tag the browser file picker triggers twice.

### ISSUE THREAD

**Issue by brianac** [react-dropzone/react-dropzone#182]
I'm not entirely sure why but I had my Dropzone wrapped in a label tag and it would cause the browser file picker to trigger twice. It would ignore whatever you chose from the first picker and just use the ones in the second picker. 

I realized my mistake in wrapping the entire thing in a label tag instead of just it's label but thought you might want to know. I've fixed my html structure and now works perfectly.

Interestingly when I added the disableClick prop it would cause the browser picker to only open once so this must be getting around whatever code you had to suppress that.

**Comment by okonet** [comment]
Can this be closed?

**Comment by brianac** [comment]
Yeah just thought I'd let you know. Although in hindsight there probably isn't a whole lot you can do about it

**Comment by futpib** [comment]
This was related to a parent `label` somehow in my case. See this answer: https://stackoverflow.com/a/52227434/4477664

**Comment by beausmith** [comment]
Yeah, I just ran into this too. If there is a `label` associated to the dropzone file input, then clicking the label will cause the browser file select dialog to appear twice.

Having labels associated with inputs is useful for web accessibility. I feel like this is a fix worth making.

**Comment by rolandjitsu** [comment]
@beausmith You'll need to disable click on the dropzone element. Just add the `{onClick}` handler and prevent default:
```jsx
<Dropzone>
    {({getRootProps}) => <div {...getRootProps({onClick: evt => evt.preventDefault()})} />}
</Dropzone>
```

If that will not work, please make a reproducible example so we can look into it.

**Comment by beausmith** [comment]
@rolandjitsu - Thanks for the suggestion. I just tried it, but unfortunately this solution blocks the click-to-choose-file feature completely.

I will post a reproducible example.

**Comment by beausmith** [comment]
@rolandjitsu Here is a reproducible example showing how wrapping a label around the input (valid `html`) causes the browser's file picker to be triggered twice:

https://codesandbox.io/s/j2z5j2n519

**Comment by rolandjitsu** [comment]
@brianac see [o174pv349](https://codesandbox.io/s/o174pv349) for a fix. At the moment, this is the only way to make this work.

I guess the label click already triggers a click on the input, and we also do the same from our `onClick()` handler, hence the open twice.

I'll reopen and see if we can do anything to improve this.

**Comment by beausmith** [comment]
Stoked! Thank you for implementing a fix for this @okonet. 

@brianac - Thanks for the initial report!

**Comment by karangarg45** [comment]
> @beausmith You'll need to disable click on the dropzone element. Just add the `{onClick}` handler and prevent default:
> 
> ```js-jsx
> <Dropzone>
>     {({getRootProps}) => <div {...getRootProps({onClick: evt => evt.preventDefault()})} />}
> </Dropzone>
> ```
> 
> If that will not work, please make a reproducible example so we can look into it.

If anyone is coming here and using this solution as a fix, this will work for you but it introduces another issue where you won't be able to select the same file twice. To select the same file twice you need to clear the input value after every file select which is done here 
https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L387
But if you are stopping event propogation this will never be called. 
The another fix would be to call this manually in your code manually. The dropzone hook returns the inputRef so you can call this method manually

**Comment by Stopa** [comment]
It seems that this issue has been re-introduced. I am still getting this error in Chrome from version 10.2 up to the latest version. Reproduction: https://codesandbox.io/s/pedantic-leakey-61oo3?file=/src/App.js

If you click on label and close the dialog either by choosing a file or canceling, another file select dialog is open.

**Comment by Stopa** [comment]
> It seems that this issue has been re-introduced. I am still getting this error in Chrome from version 10.2 up to the latest version. Reproduction: https://codesandbox.io/s/pedantic-leakey-61oo3?file=/src/App.js
> 
> If you click on label and close the dialog either by choosing a file or canceling, another file select dialog is open.

On closer inspection, this issue is solved by passing `noClick: true` to the `useDropzone` hook.

**Comment by rolandjitsu** [comment]
Please check https://github.com/react-dropzone/react-dropzone/issues/1107#issuecomment-1025046644 for more info.
