### ISSUE TITLE
Drag and Drop file would open new tab on windows firefox

### ISSUE THREAD

**Issue by TylerYang** [react-dropzone/react-dropzone#206]
Hi folks, just implemented a dropzone sample in my own app.  Everything is perfect in chrome(Both windows and OSX and ubuntu) and safari.

However on windows(only on windows), if I use a firefox(version 48 which is the lastest one) to drag and drop a file on `react-dropzone`. It would open a new tab and load the file.

Also, this would happen on the [official demo page](http://okonet.ru/react-dropzone/). 
![test](https://cloud.githubusercontent.com/assets/5443053/17433157/9bdacd8e-5b35-11e6-8e04-69e2ff6dbda9.PNG)

At the meantime, I check another dropzone which is implemented with jquery. It doesn't have the same issue. 
![test2](https://cloud.githubusercontent.com/assets/5443053/17433296/792b29cc-5b36-11e6-80a4-0996a3bc64fd.PNG)

So after that, I read their source code, [they invoke e.stopPropagation() and e.preventDefault() at the same time.](https://github.com/enyo/dropzone/blob/v4.3.0/dist/dropzone.js#L613). 

Then I try to add these code to react-dropzone, `e.nativeEvent.stopPropagation()` and `e.nativeEvent.preventDefault()`. Still, I got the same issue. : (

Any suggestions would be appreciated.  : )

**Comment by okonet** [comment]
Might be a JS error? Did you look in to the console?

**Comment by TylerYang** [comment]
Yes, there is no error message in the console and the component works great actually, except the new tab.

**Comment by okonet** [comment]
Unfortunately I don't have Windows machine, so if you can narrow down and fix a bug, I'll be gladly accept your PR.

**Comment by imdragonet** [comment]
https://github.com/RubaXa/Sortable/issues/985
