### ISSUE TITLE
Should contain default styles or it should be up to user?

### ISSUE THREAD

**Issue by okonet** [react-dropzone/react-dropzone#221]
I feel like if the dropzone component was unstyled by default, it would make it clear that it should be done in the user-land and no false expectation would be there.

On the other hand, integrating the library for the first time would require some more work without clear visual clues. This can be frustrating for the first-time users.

What styling strategy are you using in your project? Inline styles or passing class names? Should it support Radium or other styling libs?

After looking at #220, I'm not sure if the default styles should ever be the part of the library. If you're using it, please help me make a right decision.

**Comment by okonet** [comment]
See a discussion also here: https://github.com/okonet/react-dropzone/pull/220#issuecomment-243050289

**Comment by arjshiv** [comment]
@okonet I just started using this. We are using inline styles, and I thought that the default styling (with the dashed border) was very helpful in the initial integration. From a UI perspective, the one thing that would make it even easier is if it has a default `activeStyle` when you drag something in.  People with larger apps will probably override it anyway, but default active styles will make it even more of a plug'n'play experience for devs who want to get it done quickly.

I'm happy to help where required on this. Great project, would love to contribute!

**Comment by josh18** [comment]
Maybe just add a bool property `defaultStyles` to turn the styles off / on? Of course if they have it turned on and add in their own styles then their own styles would take priority. I personally would have it off by default and then just make it really obvious in the docs that it is an option.

**Comment by ajwagner777** [comment]
I hate to bring up a potentially old issue, but this issue is an important one to me (and possibly a deal breaker).  We are building a rather large app, and I would really prefer to keep the styling consistent with the rest of the app's branding.  I would propose the following:

- Add a class to the container that would allow styling hooks for the different states (default, drag over, invalid, others?)
- Add a prop that can conditionally remove the inlined styles
- Add some documentation to README 

This preserves current functionality for current users, and allows for much better styling.  I am happy to submit a PR to this effect.  Just wanted to make sure this was okay before putting in the work.

**Comment by okonet** [comment]
@ajwagner777 the issue isn't old and still actual. Let me answer your questions:

> Add a class to the container that would allow styling hooks for the different states (default, drag over, invalid, others?)

There is a way of styling the dropzone the way you want. There are actually a few several ways: you can use `className` or inline styles. So, if you're using a `className` it will ignore inline styles completely. There is no documentation on that but if you look at `propTypes` here: https://github.com/okonet/react-dropzone/blob/master/src/index.js#L267-L272 you'll find all of them.

I'll gladly accept documentations PRs since I don't have much time to work on this project now.

This issue is more about how should default styles be handled. I think the best way to handle that would be by providing some default styles as a separate export, that isn't applied by default. So, the styling, in general, should be done in the userland. As a fallback you can import default styles and apply them just to start quickly.

Thoughts?

**Comment by ajwagner777** [comment]
What I ended up doing was exactly what you said; I looked at the propTypes and noticed that you could give it a `activeClass` and `rejectClass`.  Then I paired that with `style={{}}`, and got what I needed.

**Comment by okonet** [comment]
@unbalanced wrote on the PR (https://github.com/okonet/react-dropzone/pull/220#issuecomment-243216577) so I'm moving it here:

> Hey guys,

> I love to see components released with default look&feel. it easier to start using components that already has some default look.

> The problem i see is that Inline-ing css in components makes it harder to reuse the component in different projects, since different projects usually means different sizes/colors/etc.. and some inline styles are just not possible to override (they are strong like !important)
Note, it might not be the case here, but many components have more than just one div and thus the inline styles on child elements are not reachable to override like in DropZone and this is where inline styles suck the most.

> We'll have a better developer-experience and a better overall-modularity by using className. 
If we'll let the component-creator to set his default lock&feel and the reusing-developer to easily override css rules if needed by extending the default class of every html element that the component is creating.

> WDYT?
