### ISSUE TITLE
Suggestion: Option to prevent dragging and dropping elements on the page onto the dropzone

### ISSUE THREAD

**Issue by akinnee-gl** [react-dropzone/react-dropzone#255]
In the meantime, here is my solution for doing this:

```
onDragEnter={function( event ) {
    const dt = event.dataTransfer;
    if ( !(
        dt.types &&
        ( dt.types.indexOf ? dt.types.indexOf( "Files" ) !== -1 : dt.types.contains( "Files" ) )
    ) ) {
        this.setState( { isDragActive: false } );
    }
}}
```

```
onDrop={files => {
    if ( files.length === 0 ) {
        return;
    }

    // handle files dropped here
}}
```

**Comment by okonet** [comment]
I like the approach! Shouldn't we always check if we are dealing with files and do nothing if not?

**Comment by akinnee-gl** [comment]
Yes, the main issue is that if you drag a link or image from elsewhere on the page over the dropzone, the dragover class is still added, which is confusing to the user.

**Comment by jochenberger** [comment]
And probably, `onDrop` should not be called with an empty `files` array in that case.

**Comment by okonet** [comment]
Makes sense. Can this be made into a PR with tests etc?

**Comment by SepiaGroup** [comment]
this is really nice for drag/drop. is there a way to do the same for files selected via the file dialog box?

**Comment by okonet** [comment]
Any news on this one? Also, can we check if it also works with files from download bar of the Chrome?

**Comment by ps-aux** [comment]
Any news on this ? Facing the same problem.

**Comment by jochenberger** [comment]
As of https://github.com/okonet/react-dropzone/pull/332/commits/76abf268a259b8a8d1ca8bb8dd4bffb42160a15d, you have to `disablePreview` or you'll get the TypeError mentioned in #162.

**Comment by okonet** [comment]
One of the solutions to avoid the exception would be wrapping it in `try ... catch` block I guess.

**Comment by jochenberger** [comment]
I'd rather fix the underlying issue. Can't we just check if `file.kind === 'file'`? See https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/kind

**Comment by okonet** [comment]
It won't work in IE and Safari :/

**Comment by buob** [comment]
Not sure why github doesn't link to the PR, but this is fixed in https://github.com/okonet/react-dropzone/pull/338

**Comment by highalps** [comment]
Facing same problem too. 
(drag Draggable element occurs error, TypeError: "Failed to execute 'createObjectURL' on 'URL'")
any news on this? :)

**Comment by Mangatt** [comment]
Any progress on that? I'm using Dropzone with React DnD and it causes some trouble.

```javascript
Failed to generate preview for file DataTransferItem {kind: "string", type: "application/json"} 
TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
```

My accept attribute is even set to image/*, but that is ignored for some reason in this case.

**Comment by okonet** [comment]
It's probably doe to some browsers not reporting mime types. See https://github.com/okonet/react-dropzone/issues/276

**Comment by omryr** [comment]
is there any solution to this? I cant find a way to prevent dropping DOM elements into the dropzone

**Comment by tention** [comment]
The solution on top does not seems to work on Firefox. Anyone has better fix for this?

**Comment by okonet** [comment]
PR anyone?

**Comment by joaoreynolds** [comment]
First off, this is such an awesome library.

So I found a pretty easy way to replicate this same error message without having other draggable dom elements on the page. I can get the same error to occur if I drag a chrome shortcut button onto the dropzone as well. I'm not sure how my users are getting this error to happen, but every once-in-a-while Sentry reports the error. I can only guess users are dragging random things onto the dropzone that should be ignored.

The good news is the state `isDragActive` recovers back to `false` when that happens (where before it would say active).

**Comment by rasco** [comment]
Well one part of the problem is this:
The preview creation (`window.URL.createObjectURL(file)`) **is done on all files**, regardless whether they are accepted or not. 
Shouldn't previews only be created for accepted files?

**Comment by josh-stevens** [comment]
So I have a use case where I actually _want_ to accept drag and dropped images from the page itself. I'll be investigating whether or not the object dragged from the page itself can be used with this library since it's not coming from the user's filesystem. So I'm glad there was never a PR to fully prevent this

**Comment by vapurrmaid** [comment]
@josh-stevens any luck with your investigation - I may have a use-case as well

**Comment by SourceCipher** [comment]
The only solution for now is to disable `disablePreview` and displaying your images in base64

**Comment by ashok-sc** [comment]
So is the conclusion that there's no easy way to disable Drag 'n drop on the Dropzone component? I really need this for my use case..

**Comment by codewithsk** [comment]
@josh-stevens Any luck with your use case?

**Comment by okonet** [comment]
Does anyone wants to take over this and create a PR? I'm happy to re-open it.

**Comment by yuri-sakharov** [comment]
I also solve this problem as proposed @akinnee-gl
```
    onDragOver = e => {
        const types = e.dataTransfer.types;
        const hasFilesInEvent =  types && types.length === 1 && types[0] === 'Files';;
        if (!hasFilesInEvent) {
            return;
        }
        this.setState({ isDragActive: true });
    };
```
don't miss
```
onDrop={files => {
    if ( files.length === 0 ) {
        return;
    }

    // handle files dropped here
}}
````
also this solution relevant for `onDragEnter`

**Comment by Rc85** [comment]
Checking if files.length in onDrop worked for me. Why do we need the check the onDragOver() event?

**Comment by afilp** [comment]
I think that the "Support for image URL dropping" (https://github.com/react-dropzone/react-dropzone/issues/349) would be very powerful! You mentioned there that we should follow that enhancement in this issue.

Is it relevant though? This issue is about "preventing" an image URL from being dropped-in, while we would like to have the opposite: Allow the appearance of an image that comes from a URL being dragged.

Should this be a different issue?

Thanks!

**Comment by mayur-gaikwad7474** [comment]
This issue still persists for windows laptops. On a mac, it is working fine.
