### ISSUE TITLE
dragActive / dragReject styles

### ISSUE THREAD

**Issue by RaulTsc** [react-dropzone/react-dropzone#375]
Hey,

Nice little library! 👍  

But I've got a small issue:

So I have the UploadField component

```javascript
const ERUploadField = ({ text, fileType, name, input: { value: fields, onChange }, meta: { touched, error } }: any) => (
  <div className={css.ERUploadField_container}>
    {fileType.includes('image') && <ImagePreview fields={fields} />}
    {fileType.includes('pdf') && <PdfPreview fields={fields} />}

    <Dropzone
      multiple
      style={{}}
      name={name}
      accept={fileType}
      onDrop={onChange}
      onDragLeave={() => { console.log('leave'); }}
    >
      {({ isDragActive, isDragReject }) => (
        <div>
          {isDragActive &&
            <div className={css.ERUploadField_activeDropzone}>Active</div>}

          {isDragReject &&
            <div className={css.ERUploadField_rejectDropzone}>Reject</div>}

          {!isDragActive && !isDragReject && <div className={css.ERUploadField_normalDropzone}>{text}</div>}
        </div>
      )}
    </Dropzone>
    {touched &&
      error &&
      <span className="error">{error}</span>}
  </div>
);
```

And then I have two upload fields like so:

```javascript
      <FormUploadField fileType="image/*" name="pictureUpload" />

      <FormUploadField fileType="application/pdf" name="floorplansUpload" />
```

See attached pictures.
![rsz_screen_shot_2017-03-09_at_140156_2](https://cloud.githubusercontent.com/assets/13545609/23749629/c5ba6a42-04d1-11e7-8753-5058fb920a15.png)
![rsz_screen_shot_2017-03-09_at_140200_2](https://cloud.githubusercontent.com/assets/13545609/23749632/c5bc24b8-04d1-11e7-8859-2394825b7696.png)
![rsz_screen_shot_2017-03-09_at_140214_2](https://cloud.githubusercontent.com/assets/13545609/23749630/c5bb0628-04d1-11e7-8174-23242f91167d.png)
![rsz_screen_shot_2017-03-09_at_140219_2](https://cloud.githubusercontent.com/assets/13545609/23749631/c5bb2b94-04d1-11e7-86f2-b9add3f8e018.png)

Dragging a picture over the second field and then over the first one, and dropping it there does not make the second field have normal state -- it will remain in Rejected state. Basically what happens is onDragLeave does not call setState again and it doesn't re-render. That is because of this check:

https://github.com/okonet/react-dropzone/blob/master/src/index.js#L89-L91

Removing those lines of code makes everything work as expected.

**Comment by okonet** [comment]
Thanks for reporting it. It seems like an issue. 

Can you please create a reproducible case on GitHub, WebpackBin or here: https://react-dropzone.netlify.com/#basic-example (in latter case please include the example's code here in comments)
