### ISSUE TITLE
Cannot opening file dialog programmatically on Ipad, Iphone (ios 9, 8.3) with fastclick

### ISSUE THREAD

**Issue by romanlex** [react-dropzone/react-dropzone#431]
Hello. I have this code in my button:
```javascript
<button className="btn btn-attach" title="Прикрепить изображение" onClick={e => this.openDropzone(e)}>
	<em className="icon material-icons">wallpaper</em>
</button>
```
and method:
```javascript
openDropzone(e) {
	e.preventDefault();
	console.log('openDropzone');
	this.dropzone.open();
}
```
Dropzone ref is ```ref={(node) => { this.dropzone = node; }}```
My button place inside Dropzone.
```
<Dropzone ref={(node) => { this.dropzone = node; }}
	  accept={this.state.dropzone.accept}
	  maxSize={this.state.dropzone.maxSize}
	  multiple={this.state.dropzone.multiple}
	  disableClick={this.state.dropzone.disableClick}
	  name="files"
	  className={dropZoneClasses}
	  onDrop={e => this.onDrop(e)}
	  onDropRejected={e => this.onDropRejected(e)}
	  onDragEnter={e => this.onDragEnter(e)}
	  onDragLeave={e => this.onDragLeave(e)}>
	<div className="content-control__textarea">
		...
		<div className="content-control__panel">
			<button type="submit" className={submitClasses} disabled={!this.state.valid}>Отправить</button>
			<button className="btn btn-attach" type="button" title="Прикрепить изображение" onClick={e => this.dropzone.open()}>
				<em className="icon material-icons">wallpaper</em>
			</button>
			<button className="btn btn-attach" type="button" title="Прикрепить файлы" onClick={e => this.dropzone.open()}>
				<em className="icon icon-paper-clip"/>
			</button>
		</div>
	</div>
</Dropzone>

```
But dialog not opening on mobile devices. How I can fix it?

```
"react": "^15.3.2",
"react-dropzone": "^3.13.0",
"react-fastclick": "^3.0.2-alpha.1",
```

----
update:
If I disable react-fastclick - all work properly

**Comment by gauravcm30** [comment]
@okonet Hey did you get any solutions for this problem?? Please share solution I am also facing the same.
Thanks for reply

**Comment by rkmarks** [comment]
@gauravcm30 are you using `react-fastclick` as well? Not familiar w/ that library however I am not sure if that is particularly needed for this component to work in iOS devices. can you provide more context?

**Comment by gauravcm30** [comment]
@rkmarks  Thank you for your reply. I am not using `react-fastclick`, downgrade the `react-dropzone` version to `3.7.3`  works perfectly fine for me.

**Comment by okonet** [comment]
Could you please try the official example and confirm if it's working or not working: https://react-dropzone.js.org/#opening-file-dialog-programmatically

**Comment by fredehh** [comment]
@okonet I have the issue without fastclick. When the button to open dropzone (as in the tutorial) nothing happens. This is for android (webview).

**Comment by rkmarks** [comment]
@fredehh are you using the official examples or is this something your wrote? If so can you provide a repo we can duplicate the issue from?

**Comment by fredehh** [comment]
@rkmarks  It corresponds to the code in the example. The issue is that it does not work in my webview android application. It seems that the refDropzone.open does not work.

`const FileUploadZone = ({onUpload, accept, ...props}) => {
  let refDropzone;

  return (
    <DropzoneWrapper {...props}>
      <Dropzone
        className='pa3'
        onDrop={files => onUpload(files[0])}
        multiple={false}
        disableClick
        ref={(node) => { refDropzone = node; }}
        accept={accept}
      >
        <div>{i18next.t('button.dragDrop')}</div>
        <SimpleButton onClick={() => refDropzone.open()}>{i18next.t('button.orSelect')}</SimpleButton>
      </Dropzone>
    </DropzoneWrapper>
  );
};`

**Comment by rkmarks** [comment]
@fredehh thank you for the information. However there seems to be more going on under the hood of your component. Can you attach a a link to your repo that has this code so I can clone and review?

**Comment by meteorplus** [comment]
@fredehh you code works perfectly well done dude :)

**Comment by meteorplus** [comment]
@rkmarks  just try it out on ios or android and you will have to click 3 or 4 times to open the files list on your phone

**Comment by rkmarks** [comment]
@meteorplus i just went to the official examples in my chrome browser on my Android phone and did not have to click 3 of 4 times for it to access my apps for files. Tried it as well on the Samsung internet browser and could not duplicate. 🤔

**Comment by meteorplus** [comment]
@rkmarks bro try it on safari or iOS ;)

**Comment by rkmarks** [comment]
@meteorplus just did on my iPad, on Safari. No problem. Even tested it on Safari 6.1 and didn't have that problem w/ the examples

**Comment by meteorplus** [comment]
@rkmarks sorry then so I think I was using an older version or something had to do this workaround to make work but happen when have a div with test inside the component so may be that's different?

**Comment by rkmarks** [comment]
@meteorplus it's possible do you know which version you were using?
