### ISSUE TITLE
Firefox issue: only *.jpg not *.jpeg files accepted for image/jpeg

### ISSUE THREAD

**Issue by yoDon** [react-dropzone/react-dropzone#460]
This issue is Firefox-specific and can be seen using the react-dropzone demo "Accepting specific file types" in the docs at https://react-dropzone.js.org/

Operating system Win10

**Steps to repro**:

1. Launch Firefox (current version, I'm on 54.0.1)
2. Browse to react-dropzone homepage https://react-dropzone.js.org/
3. Scroll down to the "Accepting specific file types" demo
4. Click on the dropzone target to get the file browser

**Expected behavio**r: File browser shows *.jpeg images in addition to *.jpg and *.png images

**Actual behavior**: File browser does not show *.jpeg images, only *.jpg and *.png

**Comparison behaviors**: 
1. Chrome and Edge both show *.jpeg images using this demo
2. Other React Dropzone wrappers show *.jpeg images in Firefox when accepting image types, eg. https://github.com/felixrieseberg/React-Dropzone-Component

**Comment by okonet** [comment]
It seems like a Firefox browser issue. Can you please report this at bugzilla? Also, if you know how to fix this, PR is welcomed!

**Comment by SaraVieira** [comment]
Hello @yoDon ,

This appears to be fixed in firefox 55 , can you please confirm too ?

<img width="941" alt="screenshot 2017-08-21 23 26 53" src="https://user-images.githubusercontent.com/1051509/29540777-18135484-86c8-11e7-8f51-73db2afbde47.png">

**Comment by rkmarks** [comment]
@yoDon @SaraVieira I can confirm the same w/ FF 55, appears to have been resolved

**Comment by SaraVieira** [comment]
I'm going to close this, feel free to reopen if it still happens to you
