### ISSUE TITLE
MS Edge: Lists all file types, even though file types are restricted

### ISSUE THREAD

**Issue by oliver-bauer** [react-dropzone/react-dropzone#464]
**Do you want to request a *feature* or report a *bug*?**
- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Egde Browser shows not only specifically selected file types,  but all files in the current folder

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Open https://react-dropzone.js.org/#accepting-specific-file-types
2. Click on the react-dropzone field
3. File selection opens and let's users select files
4. File selection shows all files in the respective folder, even though file types should be limited

**What is the expected behavior?**
You should only be able to see the specifically selected file types (as in FF and Chrome)

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Windows 10, 
Microsoft Edge 38.14393.1066.0
Microsoft EdgeHTML 14.14393

**Comment by anthonyraymond** [comment]
Not a `react-dropzone` issue. Microsoft Edge does not support hints at this point....
[StackOverflow answer](https://stackoverflow.com/a/32214646/2275818)
