### ISSUE TITLE
Feature request: disable

### ISSUE THREAD

**Issue by maasha** [react-dropzone/react-dropzone#472]
It would be grand if there was an option to disable the dropzone entirely, so that it only renders, but has no functionality. That is useful for tasks done in a particular order - to have the dropzone disabled until some configuration steps on the webpage are complete.

**Comment by okonet** [comment]
Great feature request. Do you want to work on this?

**Comment by maasha** [comment]
I have limited experience with Javascript and have no insight into how react-dropzone works - it should surely be something quick to do for someone who have her mind wrapped around the code already. I'd be happy to test.

**Comment by kainanaina** [comment]
Where can I find information about minimal browser support?

**Comment by trinhngocdieu** [comment]
[Zalo Chat](http://chat.zalo.me)

**Comment by okonet** [comment]
@kainanaina how is your question related to this issue?

**Comment by okonet** [comment]
Thanks @oieduardorabelo for working on this! This is now implemented in https://github.com/react-dropzone/react-dropzone/pull/473
