### ISSUE TITLE
Looking for contributors

### ISSUE THREAD

**Issue by okonet** [react-dropzone/react-dropzone#479]
### Feb 2022
The previous message still holds true. This lib is still being actively maintained, even though it doesn't seem like there's much activity at times.

The plan for this year is to:
* [ ] Add support for [React 18](https://reactjs.org/blog/2021/06/08/the-plan-for-react-18.html)
* [ ] Update the dev deps to latest for all repos (things move fast, so there were quite a few changes)
* [ ] Fix styleguide issues in all repos
* [x] Use [File System Access API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API) to open the file picker instead of triggering click on an `<input type="file">` (note that this is a draft, so only supported in some browsers)
* [ ] Standardise how the `accept` attr works ([File System Access API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API) doesn't support file extensions, but the `<input>` does)
* [ ] Address the [issues](https://github.com/react-dropzone/react-dropzone/issues) which seem to be causing the biggest headaches
* [ ] Revamp the docs for [react-dropzone](https://github.com/react-dropzone/react-dropzone)
* [ ] Revamp the logo?
* [ ] Add docs site for [file-selector](https://github.com/react-dropzone/file-selector) and [attr-accept](https://github.com/react-dropzone/attr-accept)
* [ ] Improve community health (add issue/PR templates, code of conduct, funding, etc)
* [ ] Improve organisation page
* [ ] Work on the OpenCollective plans and try to get more backers/sponsors
* [ ] Find at least 1 collaborator that can help with PR reviews and other chores
* [ ] Others (community suggestions, etc)

With that said, I'm still looking for contributors that can help with PR reviews and chores every now and then. So if you're interested, please email me or head over to https://github.com/react-dropzone/react-dropzone/discussions/1136.

**NOTE** Any further updates will be posted in discussions instead of here.

### Jan 2019
This issue/message is by no means reason for concern, the lib is still being maintained. The issue/message is here to encourage more ppl. to contribute and help with arising issues.

There is no need to add more comments to this topic, instead, if you feel like something needs to be fixed or changed, feel free to make a PR.

## Original Message
> I've been maintaining this repository for quite some time already and I'd like to slowly step down as the main maintainer. I could remain on board for discussions and code reviews, though.

> The reason for that is that I try to spend more time with my 👨‍👦 and OSS work takes quite some time of it. OpenCollective campaign doesn't show any interest in this project from people who use this software so I decided to give up on this project and concentrate on other projects like 🚫💩 lint-staged.

> If you're interested in helping out, please step out and let me know.

**Comment by yasuf** [comment]
specifically what do you do here? I'm assuming its reviewing PRs and merging them and releasing new versions, I'd like to know more about what it would involve

**Comment by arjshiv** [comment]
Same question as @yasuf here. Happy to help in any way I can but would love to get more clarity on the actual ask.

**Comment by okonet** [comment]
Thanks for your questions. I think my main work at this stage is keeping track of open issues and incoming PRs, doing code reviews and discussing possible solutions to existing problems. 

I did las big chunk of work producing the new documentation web-site which is automatically deployed using Netlify. 

Releases are also being produced automatically using sematntic-release so it's crucial to understand the type of change PR is introducing before the merge (I use squash commit GitHub UI to write the final commit messages). See https://github.com/okonet/react-dropzone/releases

I'm planning to create a separate GitHub organization for this project (should I call it`dropzone`?) to make contributions even easier.

**Comment by paramaggarwal** [comment]
It would be best if we could get this into https://github.com/reactjs

**Comment by okonet** [comment]
@paramaggarwal I'm open for that. How hard would it be to get there?

**Comment by paramaggarwal** [comment]
I believe we'll need to get in touch with the members there. Over the past year this has grown from 800 stars to over 3000 stars today - this very well needs to be a community project now.

(cc: @acdlite @gaearon @ide @jlongster)

**Comment by khrizt** [comment]
I'd love to contribute, is there a quick start guide or something? I've cloned the repo but I'm not sure how to check issues or try the library. I'm using the library in my project and I know how to use it but I'm not sure if I can develop using this repo or I need to create some wrapper repo to render the library.

Another thing is it better to fork the repo and work on my own?

**Comment by okonet** [comment]
Amazing points. I'll add the contribution guide to the readme. For now just do `npm start`

**Comment by khrizt** [comment]
I've got a couple of warnings / errors installing and running from the cloned repo:

> Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.

and

> Failed to generate preview for file bad_val TypeError: Cannot create property 'preview' on string 'bad_val'

Is there anything I can do to fix it¿

**Comment by okonet** [comment]
You could try to fix the first one. I dunno where it's coming from. The second one is by design.

**Comment by rkmarks** [comment]
I would also be happy to help maintain. I've used this library in a few places now would be honored to keep it up to date and contribute back to it

**Comment by headzoo** [comment]
I find myself using this component every couple of months. So I'd be happy to help as well.

**Comment by okonet** [comment]
@rkmarks @headzoo Invited!

**Comment by headzoo** [comment]
Thanks for the invite. Presumably you need help maintaining the library, including fixing bugs, keeping up with browser API changes, and handling PR, and you will still be guiding its development? I'm happy to help.

**Comment by okonet** [comment]
@headzoo yes! I don't have time to go over all of them but I'd like to be included (but not insist) for the key API decisions. I'm still doing some coding (#42 for example) but would like to stop doing that :)

**Comment by aganglada** [comment]
I'm super happy to help maintaining this awesome package

**Comment by okonet** [comment]
@aganglada helping answering and closing issues would be a great start I think!

**Comment by hubgit** [comment]
If you're still looking for maintainers, I can probably help.

I think the first priority is [removing the class name handling, leaving that to the children](https://github.com/react-dropzone/react-dropzone/pull/468), as that'll remove a lot of complexity.

**Comment by yrshaikh** [comment]
If you are still looking, I would want to help.

**Comment by okonet** [comment]
@yrshaikh sure! it would be great if you could start by answering issues

**Comment by paramaggarwal** [comment]
Dear maintainers, could you please raise a request to transfer the repo to github.com/reactjs org - I am trying to help consolidate the react projects which are really popular into the community organisation.

**Comment by rkmarks** [comment]
@paramaggarwal I can see about making that request.

**Comment by okonet** [comment]
@paramaggarwal I'm all for it. Where do I do that?

**Comment by paramaggarwal** [comment]
I am also not sure how to do it... Try using the transfer link at the bottom of https://github.com/react-dropzone/react-dropzone/settings...

**Comment by rkmarks** [comment]
Would that make a request to them or just simply transfer it? I've looked at the ReactJS org site and couldbt find a contact email.

**Comment by paramaggarwal** [comment]
I think they will need to approve it for the transfer to go through. So we might get to hear back from them around any requirements there might be...

**Comment by rkmarks** [comment]
Ah makes sense. I do not have permission unfortunately. Only @okonet has owner perms I believe

**Comment by okonet** [comment]
> You don’t have the permission to create repositories on reactjs

I can't transfer unless I'm part of that org :-/

**Comment by okonet** [comment]
Can someone add me as a contributor to /reactjs? cc (and sorry) @cpojer @gaearon @jlongster @knowbody @mxstbr

**Comment by knowbody** [comment]
@okonet I'm only a member there so you need to ask someone who's an admin

**Comment by denizs** [comment]
I'd absolutely loved to contribute! 👍

**Comment by rkmarks** [comment]
@knowbody sorry this has been delayed do you know of any admins I can reach out to? I would be happy to discuss w/ them to see if this can be moved

**Comment by benmonro** [comment]
I'm happy to help. this component is kick ayuss.

**Comment by tvelev92** [comment]
I am interested in contributing

**Comment by okonet** [comment]
Okay I have invited anyone (I hope) who said he wants to contribute. If I have forgotten you, please let me know.

**Comment by divyenduz** [comment]
@okonet : If there is room, you can invite me as well. I use react-dropzone at multiple places and will be able to contribute back.

**Comment by okonet** [comment]
@divyenduz haha, there is room for everyone!

**Comment by gondar00** [comment]
@okonet I am interested in contributing

**Comment by rkmarks** [comment]
@gondar00 perfect, i would recommend starting w/ reviewing the issues and seeing if there is anything you can contribute to :)

**Comment by TrySound** [comment]
@okonet I would like to improve build step.

**Comment by okonet** [comment]
What’s wrong with the build step now?

**Comment by TrySound** [comment]
There are a couple of problems I could solve.

**Comment by okonet** [comment]
@TrySound I've added you as a collaborator but can we please focus on important stuff before we start optimizing bits? There are tons of PRs awaiting the review as well as issues. This is there help is mostly appreciated atm.

**Comment by johnrhampton** [comment]
@okonet, I use this library in multiple projects also and would be thrilled to help maintain it. It has been a huge help to me and would love to pay that forward. If you are still looking for assistance maintaining the repo, please let me know.

**Comment by karltaylor** [comment]
Would love to come on board as collaborator 👍

**Comment by ChristianReifberger** [comment]
Hi, if there is still help needed I'd like to contribute. I've used React-Dropzone a few times already, recently for a project for a client and it worked great

**Comment by okonet** [comment]
Added both of you @karltaylor and @ChristianReifberger

**Comment by samueldervis** [comment]
If you still need help, I'd love to contribute.

**Comment by okonet** [comment]
@samueldervis invited

**Comment by Jiasm** [comment]
Maybe I can help you, That's a awesome project.

**Comment by rolandjitsu** [comment]
@okonet is this still the case? Or can we lock and close this issue and update the docs?

**Comment by okonet** [comment]
@rolandjitsu your call. I'd like to see as many people maintaining it as possible

**Comment by rolandjitsu** [comment]
@okonet This has been active for a year or so. My only concern is that we shouldn't give ppl the impression that there is no further development on the lib. Otherwise I agree with you.

**Comment by okonet** [comment]
I’m not sure how “looking for maintainers” gives ppl this feeling. You are free to edit my initial message if you feel like it has to change.

**Comment by rolandjitsu** [comment]
Ok, it must be just me then 😄 I'm good, no need to change anything.

**Comment by needcaffeine** [comment]
@okonet I use this library extensively, and would love to contribute if you're still accepting maintainers.

**Comment by Grantlyk** [comment]
Did you people find a new maintainer?

**Comment by rolandjitsu** [comment]
@Grantlyk yes 😄 But you're always welcomed to contribute if you wish.

**Comment by pedroapfilho** [comment]
I've implemented this library on almost every company I worked, so if you guys still want something, I would be happy to help!

**Comment by rolandjitsu** [comment]
@pedroapfilho and @salman1995 you're free to contribute at any time.

**Comment by pedroapfilho** [comment]
> @pedroapfilho and @salman1995 you're free to contribute at any time.

Ya! I know! 'll create some PRs (I do have some workarounds on some projects to make it work as expected), its just because there was this quote on the documentation, so I came here to offer... hahaha
