### ISSUE TITLE
Firefox Issue: React Dropzone is not rendering in Firefox 55.0 +

### ISSUE THREAD

**Issue by sharma-varun** [react-dropzone/react-dropzone#480]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1.
1.
1.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by sharma-varun** [comment]
I am using react-dropzone, its working fine in Chrome but in Firefox 55.0+ it's not getting rendered at all.

**Comment by SaraVieira** [comment]
Hello @sharma-varun ,

Can you please provide more details ?
I can run it in firefox 55.0.2

![Uploading Screenshot 2017-08-21 23.23.39.png…]()

**Comment by okonet** [comment]
https://react-dropzone.js.org/ works fine in Firefox 55.0.2 for me. If you have any particular details, please feel free to re-open.

**Comment by sharma-varun** [comment]
Its working on Firefox 55.0.1 but not in 55.0.2, for 55.0.2 it doesn't even load the component into the dom and its just an empty div.

**Comment by sharma-varun** [comment]
I was able to solve and run in Firefox.
Thanks
