### ISSUE TITLE
Storyshots (Storybook addon): TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by GHermet** [react-dropzone/react-dropzone#485]
Storyshots (Storybook addon): **TypeError: Cannot read property 'addEventListener' of null**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

When running storyshots test from jest, it fails because `this.inputFileEl` does not exist yet  when this line is ran `this.fileInputEl.addEventListener('click', this.onInputElementClick, false)`

**Steps to reproduce**

1.  add [storybook](https://github.com/storybooks/storybook)
2.  add [storyshots](https://github.com/storybook-eol/storyshots)
3.  build a story file with a react-dropzone component following these [instructions](https://storybook.js.org/configurations/default-config/)
4. run this command `npm run test:watch`

**What is the expected behavior?**

It should assess the existence of `this.inputFileEl` before adding or removing any event listener 
```
    if (this.fileInputEl) {
	this.fileInputEl.addEventListener('click', this.onInputElementClick, false);
   }
```

OS: macOS Sierra 10.12.6 (16G29)
Browser: Google Chrome 60.0.3112.101 (Official Build) (64-bit)
react-dropzone: ^3.13.0

**Comment by holloway** [comment]
I believe this is the core issue... https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html#mocking-refs-for-snapshot-testing

**Comment by GHermet** [comment]
Thanks for the link ! turns out we used the skip snapshot regex from the storyshot API as it was not needed

**Comment by ZakTax** [comment]
Hi @holloway I am experiencing same error but can't figure out the right `createNodeMock`.

The [createNodeMock example at Storyshots](https://github.com/storybooks/storybook/tree/master/addons/storyshots#using-createnodemock-to-mock-refs) starts me at the following:

```
createNodeMock: (element) => {
      if (element.type === TextareaThatUsesRefs) {
        return document.createElement('textarea')
      }
    },
```

I've tried:
```
createNodeMock: (element) => {
      if (element.type === DropzoneComponent) {
        return document.createElement('div')
      }
    },
```
and 
```
createNodeMock: (element) => {
      if (element.type === DropzoneComponent) {
        return document.createElement(DropzoneComponent)
      }
    },
```

Neither work, not sure where to go next. Can you help me find a solution?

**Comment by rubyconn** [comment]
@ZakTax 

The following works for me.

```js
    createNodeMock: element => {
      if (element.type === 'input' && element.props.type === 'file') {
        return document.createElement('input')
      }
      return null // to make eslint happy
    },
```

**Comment by ZakTax** [comment]
@uosl yes! thanks :)
