### ISSUE TITLE
Safari: Web inspector results in empty acceptedFiles

### ISSUE THREAD

**Issue by piercefreeman** [react-dropzone/react-dropzone#486]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

I open the Safari web inspector and drag a file to a dropzone on https://react-dropzone.js.org.  The dropzone calls onDrop with an empty array of acceptedFiles and empty rejectedFiles.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Control+click on the page to "Inspect Element"
2. Reload page
3. Drag any file to the dropzone on the page (tested specifically from a folder within the dock)
4. The dropzone doesn't pass through the file, despite the styling changing and the subsequent drag of the same file working fine.

**What is the expected behavior?**

The onDrop handler should be called with a non-zero list of acceptedFiles, since the file is accepted normally.

It's worth noting that this behavior sometimes occurs even when I haven't opened the web inspector recently.  But it's relatively random whereas displaying the inspector reproduces the behavior every time.

**If this is a feature request, what is motivation or use case for changing the behavior?**

N/A

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

Safari 10.1.2, OS X 10.12.6, dropzone 4.1.0.

**Comment by okonet** [comment]
I can't reproduce it with Safari Version 10.1.2 (12603.3.8). What version of Safari are you using. Please provide a screen video or more details on how to reproduce.

**Comment by piercefreeman** [comment]
@okonet Thanks for looking into this.  I've slightly edited the reproduction steps to make it easier to recreate.  I've also uploaded a video with a demo.

https://ufile.io/4dtol

**Comment by rkmarks** [comment]
@piercefreeman I too was unable to duplicate this issue and I am on Safari Version `Version 10.1.2 (12603.3.8)`. After viewing the video it seems to be strange bug. Also can you provide the Safari version?

**Comment by SaraVieira** [comment]
@piercefreeman I can't reproduce this either 😕
