### ISSUE TITLE
lint / build dependencies incorrectly not marked as devDependencies

### ISSUE THREAD

**Issue by Kovensky** [react-dropzone/react-dropzone#490]
The `react-dropzone` `package.json` includes `babel-preset-env`, `babel-preset-stage-1`, `eslint-config-prettier` and `eslint-plugin-prettier` as `dependencies` even though they are not used at runtime.

This results in users of published versions of the library being forced to install those packages, even though they are only needed for development. They should be `devDependencies`.

This may be, in turn, required by the use of a `prepublish` script, which happens to be run by `npm` on install (it's deprecated, but won't be going away for a few years yet). To work around that, it's probably better to depend on `in-publish` and using `"prepublish": "not-in-publish || npm run prepare", "prepare": "(the current prepublish command)"`.

**Comment by zxlin** [comment]
To second this post, users of this lib are also warned to install `prettier` due to it being a peer-requirement in `eslint-plugin-prettier` which should be a react-dropzone dev-dependency.

Warning message:
```
npm WARN eslint-plugin-prettier@2.2.0 requires a peer of prettier@>= 0.11.0 but none is installed. You must install peer dependencies yourself.
```

Thanks!
