### ISSUE TITLE
Add size-limit locally and on CI

### ISSUE THREAD

**Issue by okonet** [react-dropzone/react-dropzone#495]
We should use https://github.com/ai/size-limit in order to keep the bundle size at minimum and ensure it doesn't increase with time.

**Comment by SaraVieira** [comment]
Can we use [bundlesize]( https://github.com/siddharthkp/bundlesize) instead ? @okonet

**Comment by okonet** [comment]
Why?

**Comment by SaraVieira** [comment]
Nvm , this one has a why and bundlesizse doesn't , I was saying bundlesize because it's the one I use the most 😝

I'll create a quick PR to add this

**Comment by okonet** [comment]
Yeah, open source hype contest in action 🤷‍♂️ 😄

**Comment by SaraVieira** [comment]
But you won 😕
