### ISSUE TITLE
Export ES2015 sources alongside with UMD bundle

### ISSUE THREAD

**Issue by okonet** [react-dropzone/react-dropzone#496]
Webpack supports `js:next` attribute in `package.json` allowing users take advantages of tree shaking and other build-time optimizations for external modules. We should leverage it and provide users with both ES5 compatible and ES6 sources.

**Comment by rkmarks** [comment]
@okonet i'll work on this as I've gotten to work w/ webpack quite often at my currently job.

**Comment by rkmarks** [comment]
also to clarify  you mean `jsnext:main` not `js:next`? couldn't find anything on `js:next`

**Comment by okonet** [comment]
> also to clarify you mean jsnext:main not js:next

Yes, sorry for the confusion.

**Comment by rkmarks** [comment]
no worrires :) should have a PR up in a few days. got tied up this weekend

**Comment by anajavi** [comment]
Isn't the jsnext:main superseded by "module"?

**Comment by okonet** [comment]
Whoever will do this should do a research.

**Comment by anajavi** [comment]
Here's a quick test I made: https://github.com/anajavi/react-dropzone/commit/767cdf67f6fad19eed3b7f7713cc6a176d86fd37

I just quickly tested that it works with my application. My production build went down a couple of kilobytes with this. 

I'm not familiar enough with react-dropzone to send a PR. So if somebody wants to pick this commit and make a PR, I don't mind.

**Comment by okonet** [comment]
Related to size-limit: https://github.com/ai/size-limit/issues/8

**Comment by anajavi** [comment]
What would be needed besides https://github.com/anajavi/react-dropzone/commit/767cdf67f6fad19eed3b7f7713cc6a176d86fd37 for pull request?

I checked and jest can't test es2015 without transforming modules with babel. Size-limit seems to work out of the box with this build.

**Comment by okonet** [comment]
@anajavi I don't know and I don't have much time these days so if you can create a complete PR, I'd appreciate that.
