### ISSUE TITLE
Empty input tag when file was drag&dropped

### ISSUE THREAD

**Issue by Tomekmularczyk** [react-dropzone/react-dropzone#497]
I have a react-dropzone in form which has `onSubmit` callback, which looks like this:

```
  onSubmit = (e: SyntheticInputEvent<*>) => {
    e.preventDefault();
    const { postNewFile } = this.props;

    postNewFile(new FormData(e.currentTarget));
  };
```

This works fine when I manually select the file from a popup. However when I drag and drop the file I get response from server that I sent empty file. I'm guessing that while drag & drop, the input tag value doesn't change.

Is it a standard behavior?

I expected that drag & drop will preserve the same behavior as when manually selecting the file.

I know I can use `inputProps` and use `onDrop` to make controlled input but that would require to keep the file in memory (state).

**Comment by okonet** [comment]
Yes. That's the browser's limitation that you can't set the `input` value for `type=file` AFAIK. For that reason you have to handle uploads manually and clean up after yourself. If you aware of a solution, please submit a PR.

**Comment by Flavien** [comment]
So `react-dropzone` can't be used for uploading files if they added via drag and drop? Wasn't that the main purpose of this package?

**Comment by rolandjitsu** [comment]
@Flavien sorry, but that's not the purpose of the lib. This lib just gives you the file objects, it's up to you to do whatever you want w/ them.
