### ISSUE TITLE
I use the official example directly, but sometimes it doesn't respond when clicked

### ISSUE THREAD

**Issue by zhangyanyan1002** [react-dropzone/react-dropzone#501]
<Dropzone
        className={styles.imgContainer}
        multiple={this.props.hasMultiple}
        accept="image/*"
        onDrop={this.onDrop}
      >
        <img className={styles.addImg} src={add} alt="" />
      </Dropzone>

**Comment by rkmarks** [comment]
@zhangyanyan1002 I am unable to duplicate your issue. can you provide more information please. i.e what  browser you're using, what `this.onDrop` is doing, etc.

**Comment by zhangyanyan1002** [comment]
Chrome browser
The onDrop method uploads and stores successful uploaded picture information
eg：
  onDrop(files) {
    const { dispatch } = this.props;
    dispatch(actionEditCompanyImgUrlsSuccess(files));
    this.setState(
      files,
    );
  }

**Comment by zhangyanyan1002** [comment]
As long as you set the accept= "image/*" property, this problem occurs. If you don't set it, it's normal, but I need to upload the picture

**Comment by taikn** [comment]
Having the same issue on iOS safari 10, file dialog opens only every other click

**Comment by zhangyanyan1002** [comment]
Yes, I tried some IOS phones, and they all had the same problem。

**Comment by okonet** [comment]
I just checked on the official documentation site and every example worked as expected on my iPhone using Safari and latest iOS 10. So if you experience problems I'll need a reproducible example in a separate GitHub repository. Thanks.

**Comment by JohannLai** [comment]
I got the same problem too, use the official example directly, but sometimes it doesn't respond when clicked, sometime I clicked many time , and then it will respond, my brower is Chrome.

**Comment by JohannLai** [comment]
I change to fixed it , now I know than when I click the DropZone,  it will enter onInputElementClick function, and then the file dialog dont open

**Comment by JohannLai** [comment]
I think is  this line does't work `this.fileInputEl.click();`

**Comment by JohannLai** [comment]
I use another computer to test , it work ! 
the same environment.
that is so trange

**Comment by zhangyanyan1002** [comment]
Thank you, but I still have this problem after updating. As long as the accept= "image/*" is set, the IOS phone will not open or open very slowly.
