### ISSUE TITLE
onClick does not fire on latest safari

### ISSUE THREAD

**Issue by beckend** [react-dropzone/react-dropzone#502]
https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L218

onClick handler is not firing 

**Do you want to request a *feature* or report a *bug*?**

- [X] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**
Safari 10.1.2
onClick dropzone does not fire on safari desktop, works on other browsers, ms edge, chrome, firefox

**What is the expected behavior?**
it should fire

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
react dropzone 3.13.3

the fix is actually to remove setTimeout and it works, but then i do not know how ie11/edge would behave.

**Comment by okonet** [comment]
It works on https://react-dropzone.js.org in Safari 10.1.2. Please create a reproducible example that I can paste there and try or create a GH repository.

**Comment by beckend** [comment]
This is going to rather hard to recreate in a repo, I integrated the plugin deep in our closed source codebase. Going to close this since i i will not pursue a deeper debug for now.
However, in our codebase, the file dialog can never be opened with the setTimeout, it never failed without the setTimeout.

**Comment by okonet** [comment]
Well, that's why we need a minimal reproducible example. Often there issues caused by other code that is not related to the dropzone.
