### ISSUE TITLE
Dropzone on Safari 9.1 (ElCaptain) is not working.

### ISSUE THREAD

**Issue by dsznajder** [react-dropzone/react-dropzone#508]
- [x] I found a bug

**What is the current behavior?**
When we are clicking on element which is attached to Dropzone component, it's not showing whole modal for uploading a file

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Go on Safari browser 9.1 and try to upload some file via Dropzone

**What is the expected behavior?**
It should behave like on newer versions of safari :) :dancer:

**Please mention other relevant information such as the browser version, Operating System, and react-dropzone version.**

- MacOS ElCaptain
- Safari 9.1 (Latest)

**Comment by rkmarks** [comment]
@dsznajder I just tested the official examples on Safari 6.1 and was not able to duplicate the issue. Can you provide more details on what exactly you are doing to duplicate the issue?

**Comment by dsznajder** [comment]
Component just not opening the dialog window for upload. Even if I provide a `ref` callback to this, also on Chrome with this `ref` dialog window is opening twice.

**Comment by rkmarks** [comment]
Can you provide a repo w/ the code you are using so I can review to duplicate?

**Comment by dsznajder** [comment]
I cannot, I've already handled this by checking if a browser is a safari and opening by `ref` as in the example. Probably this was misread on documentation, sorry for troubling You. :)

**Comment by SaraVieira** [comment]
@dsznajder Can this be closed ?

**Comment by dsznajder** [comment]
Yeah sure :)
