### ISSUE TITLE
Does react-dropzone support image type gif?

### ISSUE THREAD

**Issue by puffstream** [react-dropzone/react-dropzone#518]
Having issues with gif, doesn't look its animating after adding image type with gif.

**Comment by okonet** [comment]
Please rename the issue since it's violating code of conduct: http://todogroup.org/opencodeofconduct/

**Comment by puffstream** [comment]
Sorry its not clear as to what conduct I've violated? Or maybe provide some examples, thanks!

**Comment by SaraVieira** [comment]
Hi @puffstream ,

So the problem is that you called us guys and there are also a couple of girls doing open source 😝
I adjusted the title :)

About your issue I created this code sandbox that uploads gifs:
https://codesandbox.io/s/5y84ylr8r4

Can you explain your issue with a demo ?

**Comment by puffstream** [comment]
@SaraVieira Thanks for fixing..

We're using your library along with this one - https://github.com/jerryshew/react-image-cropper/issues/20 and looks like the issue is on this side with Canvas, Canvas doesn't support gifs. So we're looking at our options.. much appreciated for the speedy reply and sandbox :)

Good work!

**Comment by SaraVieira** [comment]
No problem and a bummer you need to change options 🙁

Can I close this? ☺️

**Comment by okonet** [comment]
Thanks @SaraVieira for taking this one!

**Comment by puffstream** [comment]
Thanks!!
