### ISSUE TITLE
Cannot import Dropzone using Typescript

### ISSUE THREAD

**Issue by ashok-sc** [react-dropzone/react-dropzone#520]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug

**What is the current behavior?**
When I have the line `import Dropzone from 'react-dropzone';` at the top of my file in typescript I'm unable to compile with the following error:

`ERROR in [at-loader] ./src/client/components/uploader.tsx:2:8
    TS1192: Module '"/Users/ashokraju/src/sc/caas-app/node_modules/@types/react-dropzone/index"' has no default export.`

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Add line `import Dropzone from 'react-dropzone';` to top of React component file.
1. Try to compile the file. 
1. Get the above error.

**What is the expected behavior?**
Should be able to compile.

In believe this is an issue with the type definitions?

**Comment by oyvindym** [comment]
Got the exact same bug. 

Also, if I import Dropzone using `import * as Dropzone from 'react-dropzone';` I get the following error when mounting the component:

```
invariant.js:42 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

Using following package versions:
```
{
    "@types/react": "16.0.14",
    "@types/react-dom": "16.0.1",
    "@types/react-dropzone": "4.1.0",
    "react": "16.0.0",
    "react-dom": "16.0.0",
    "react-dropzone": "4.2.1",
    "typescript": "2.5.3",
    ...
}
```

**Comment by Lexanius** [comment]
@oyvindym This solution works for me only with version 4.1.3

maybe `"module": "dist/es/index.js",` let the type file not working but it is only my opinion.

See:
https://github.com/react-dropzone/react-dropzone/compare/v4.1.3...v4.2.1

**Comment by oyvindym** [comment]
@Lexanius Thanks, that did it. The issue still stands though, for `v4.2.1`

**Comment by ashok-sc** [comment]
Thanks @Lexanius . I'm going tor evert to 4.1.3 for now. Hopefully this issue is resolved soon for latest version.

**Comment by rkmarks** [comment]
similar workaround has been uncovered in #328 closing this issue
