### ISSUE TITLE
Add support to required input

### ISSUE THREAD

**Issue by rafacianci** [react-dropzone/react-dropzone#523]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [X] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1.
1.
1.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
I want that the field provide the required props.
To set on HTML input that the field is required. :)
**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by rkmarks** [comment]
Closing issue as you can pass the required field on the inputProps
