### ISSUE TITLE
In Firefox isDragActive doesn't work correctly when dragging over child elements

### ISSUE THREAD

**Issue by kurtfurbush** [react-dropzone/react-dropzone#526]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
In Firefox, dragging a file and hovering over Dropzone children causes isDragActive to change to false. Hovering over the rest of the Dropzone correctly triggers isDragActive = true.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Using Firefox, go to the react-dropzone Basic Example.
2. Drag a file over the dropzone below the text (child element).
3. Note the green outline.
4. Drag the file over the text (child element).
5. Note the active styling reverts.

**What is the expected behavior?**
Dragging the file over dropzone children should not cause isDragActive to return false. Works as expected in Chrome, IE, Edge.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Firefox: 56.0.2
OS: Windows 10

**Comment by okonet** [comment]
Thanks for reporting this one. I can confirm there is a bug. Interestingly we have a code that worked in FF as well so this is a regression (maybe even in Firefox). Can you please submit a PR to fix it?

**Comment by okonet** [comment]
Related code: https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L91-L94

**Comment by kurtfurbush** [comment]
I've been trying to debug this for a while but keep getting "too much recursion" debug errors in Firebug.

It seems that the onDragEnter event is possibly not happening before onDragLeave (as it does in Chrome) when moving from parent > child and vice-versa, which means this.dropTargets list doesn't correctly contain the "other" element (pushed in onDragEnter), which causes onDragLeave to continue and set isDragActive to false.

**Comment by bologer** [comment]
Issue is relevant, any ideas how to patch it?

**Comment by bologer** [comment]
`onDragLeave()` is not being fired as well when I move file to dropdown area and then move it away.

**Comment by andygock** [comment]
I'm also experiencing this issue, Firefox 64.0, does anyone have any solutions on this?

**Comment by cupofjoakim** [comment]
I'm currently experiencing this as well on Firefox 67.0.4, any known fixes? :(

**Comment by remijean** [comment]
Même problème sous Chrome 79

**Comment by cupofjoakim** [comment]
@okonet Can we reopen this?

**Comment by okonet** [comment]
Instead of re-opening this I'd like to see a PR that fixes that. What's the point of having the issue?

**Comment by okonet** [comment]
But yeah here you go!

**Comment by rolandjitsu** [comment]
@cupofjoakim as @okonet mentioned, opening the issue won't magically make it go away. You're welcome to make a PR with a fix.

@kurtfurbush would be nice to provide a simple codesandbox that illustrates the issue.

**Comment by kurtfurbush** [comment]
The repro I gave was using the documentation example.

**Comment by rolandjitsu** [comment]
@kurtfurbush I'm asking this because it's easier to work in isolation; the docs have a lot of examples.

**Comment by cupofjoakim** [comment]
@rolandjitsu Closing the issue hides it from potential contributors that have the same issue. I understand that a PR would be better, but by keeping it open others won't have to report it again.

**Comment by nataliadziedzic** [comment]
I'm on version 14.2.3 and this bug still appears

**Comment by nataliadziedzic** [comment]
After investigating my case it turns out that it does not work properly when as a child I have an Image component from Nextjs, the usual img tag doesn't seem to be a problem

**Comment by avysotskiy-sc** [comment]
This bug still exist in 2024

**Comment by rlebhar-clone** [comment]
if you want that to work you have to disable the pointer event on the children to prevent triggering the leave.

On the child that trigger the leave : 

```
.pointer-events-none {
    pointer-events: none;
}
```
