### ISSUE TITLE
Check the file size limits and type at the same time

### ISSUE THREAD

**Issue by b0gok** [react-dropzone/react-dropzone#527]
- [ ] I found a bug
- [X] I want to propose a feature

**What is the current behavior?**
For now it only checks that files have accepted type and not check size limits here
https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L306

**What is the expected behavior?**
I suggest checking the type of files and file size limits here
https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L306

Additionally we can add cause of rejection here 
https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L172
For example
```js
rejectedFiles.push({ file, why: 'maxSize' });
rejectedFiles.push({ file, why: 'type' });
```

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
react-dropzone@4.2.1

I can provide a PR. What do you think about it?

**Comment by okonet** [comment]
Thanks but no. I removed this on purpose since it made the library harder to adopt in some cases and introduced extra complexity for reasons etc. We had a discussion in #321 if you're interested.
