### ISSUE TITLE
Dropping files directly from mobile devices didn`t work (chrome @latest)

### ISSUE THREAD

**Issue by KaiSchniggendiller** [react-dropzone/react-dropzone#529]
- [x ] I found a bug

**What is the current behavior?**

Files directly dropped from connected mobile devices are not accepted by using dropzone in chrome and firefox. In edge it works (sometimes).
![dropzoneimagetest](https://user-images.githubusercontent.com/8722534/32545429-ffa4c9b8-c47b-11e7-8fab-76dfec52f5f5.jpg)

Metadata in files on devices are not complete. eg. filetype is missing (attached file).

I`m trying to drop img, png, gif.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. connect smartphone to pc
2. drag file to dropzone
3. check files array -> empty

**What is the expected behavior?**

1. connect smartphone to pc
2. drag file to dropzone
3. check files array -> dropped files

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

- Win10 @latest
- chrome (61.0.3163.100),  firefox 
- dropzone @latest

**Comment by i3i2uno** [comment]
@KaiSchniggendiller did you make any progress on this issue? Im running into the same thing...
