### ISSUE TITLE
Remove debug statements from production bundle

### ISSUE THREAD

**Issue by dwjft** [react-dropzone/react-dropzone#531]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [x] I want to propose a feature

**What is the current behavior?**

```javascript
if (!disablePreview) {
	          try {
	            file.preview = window.URL.createObjectURL(file); // eslint-disable-line no-param-reassign
	          } catch (err) {
	            if (process.env.NODE_ENV !== 'production') {
	              console.error('Failed to generate preview for file', file, err); // eslint-disable-line no-console
	            }
	          }
	        }
```

**What is the expected behavior?**

I found these lines of code in the production bundle. Please remove them from the bundle altogether. It is only useful for development of the module itself, not useful for developers using the library.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Including development code inside production builds is a no no.

**Comment by okonet** [comment]
> Please remove them from the bundle altogether. It is only useful for development of the module itself, not useful for developers using the library.

You're welcome to do this work. Submit a PR!
