### ISSUE TITLE
Firefox mobile version 57.0 on Android (tested on Xiaomi Mi 5s with Linage OS and Samsung Galaxy S8 with TouchWiz) doesn't open file selection dialog.

### ISSUE THREAD

**Issue by masterwendu** [react-dropzone/react-dropzone#536]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Firefox mobile version 57.0 on Android (tested on Xiaomi Mi 5s with Linage OS and Samsung Galaxy S8 with TouchWiz) doesn't open file selection dialog.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. go to https://react-dropzone.js.org/ with Firefox mobile
2. try to open the file selection at the examples section
3. it won't work

**What is the expected behavior?**
On click on Dropzone it should open the Android file selection.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
*  react-dropzone 4.2.3
* Firefox mobile on Android version 57.0
* Android version 7

**Comment by rkmarks** [comment]
@masterwendu I was not able to duplicate on my firefox viewing it through a simulator w/ the mentioned versions above. Can you provide any further debugging to support this issue?

**Comment by masterwendu** [comment]
@rkmarks Thank you for looking into my issue. I am sorry I found it. It was related with the android permissions. It was not allowed to add photos from firefox.
