### ISSUE TITLE
safari iOS doesn't support comma separated mime types

### ISSUE THREAD

**Issue by Lindstrom1989** [react-dropzone/react-dropzone#538]
```
<input type="file" accept="image/jpg, application/pdf" multiple="" name="attachment">
<input type="file" accept="image/jpg application/pdf" multiple="" name="attachment">
```
In iOS safari the first one greys out all files and the second one works for those types.
in dropzone the first accept prop works but the second will reject all files.

**Comment by rkmarks** [comment]
@Lindstrom1989 I was not able to duplicate this issue on my iPad using safari with the example with multiple accept types from react-dropzone.js.com.
