### ISSUE TITLE
Introduce new options - maxFiles and maxOverallSize

### ISSUE THREAD

**Issue by Zakerius** [react-dropzone/react-dropzone#540]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [x] I want to propose a feature

**If this is a feature request, what is motivation or use case for changing the behavior?**

I would like to allow user to upload up to max 10 files and their size together up to max 10mb. So it would be possible either upload one file 10mb or 10 files with 1mb.

I can try to add those features by myself, should I open new pull request?

**Comment by rkmarks** [comment]
@Zakerius I did something like this in my own component for a project at work. You can definitely submit a PR to see if this something that can be utilized by others. Though I think it would probably be best to handle that in the component that is consuming the react-dropzone.

**Comment by okonet** [comment]
No, no need for a PR. We had this before and this was removed. See https://github.com/react-dropzone/react-dropzone/pull/364#issuecomment-284330207
