### ISSUE TITLE
Disable onClick

### ISSUE THREAD

**Issue by lukejpreston** [react-dropzone/react-dropzone#541]
I don't know if this is a bug or feature

I want to drag a file into a `textarea` and then it gets populated with the contents of the file (it is meant to be an XML). This works fine but when you click on anything in the `dropzone` it is then asking to upload a file. I feel it should be possible to disable the `onClick` feature. I have tried `stopPropagation` but this does not seem to exist.

I have a gif of my problem. When I drag the file into the drop zone it then `console.logs` the contents. When I proceed to click on the `textarea` it starts to prompt for me to open a file which is not the desired behavior. I would ideally like to be able to drag a new file to replace the old one, so I do not want to disable the dropzone. I also would not like to have a separate space for the dropzone.

Also as an accessibility note, not everyone can drag and drop hence you might be inclined to put in a button for people to click. If this is inside the dropzone it will prompt you twice to upload a file if you click the button, hence more incentive for this feature.

![disable-onclick](https://user-images.githubusercontent.com/4129128/33838284-f41962aa-de86-11e7-98f3-09dc2fff47ec.gif)

**Comment by lukejpreston** [comment]
never mind you have a `disableClick` I didn't read the docs close enough

**Comment by dant00ine** [comment]
Anyone else having trouble getting disableClick to work?

**Comment by cd17822** [comment]
@dant00ine +1

**Comment by mihaimartalogu** [comment]
In case anyone stumbles upon this after searching for how to disable opening the file dialog when clicked (but keep the dropzone active), the solution is to add an onClick property that stops the event propagation:
```javascript
onClick={event => event.stopPropagation()}
```
**However**, this needs to be done on the element that gets the root  props, **not** on the DropZone itself, i.e.:
```javascript
<Dropzone
  ...
  // not here
>
  <div
    {...getRootProps()}
    // but here:
    onClick={event => event.stopPropagation()}
  >
```

**Comment by mrlubos** [comment]
@mihaimartalogu Check out the discussion in #530 on why we should not stop propagation. Of course depends on your use case, but in general, this is not encouraged.

**Comment by rolandjitsu** [comment]
Actually, see https://github.com/react-dropzone/react-dropzone/issues/783.

**Comment by mihaimartalogu** [comment]
@mrlubos Thanks for the pointer, interesting read, but now I'm even more confused about stopPropagation 😅

My use case is a lightbox image gallery (https://github.com/benhowell/react-grid-gallery) inside the Dropzone:

```javascript
<div
{...getRootProps({
  onClick: event => event.stopPropagation()
})}
>
  <Gallery .../>
```

The `stopPropagation` solution above (same one as 
https://github.com/react-dropzone/react-dropzone/issues/783#issuecomment-472570408) works for me: it prevents opening the file dialog, and the Gallery receives the click properly (and displays the lightbox). It doesn't work if I replace it with a `preventDefault`: both the file dialog and the lightbox are opened (file dialog first).
Figuring out the reason would probably involve a deep-dive into the onClick implementation of react-dropzone (or maybe even dropzone.js itself)...

**Comment by rolandjitsu** [comment]
@mihaimartalogu try https://github.com/react-dropzone/react-dropzone/pull/801 and let me know if your use case still works with the changes we made. You can still use `event.stopPropagation()`, but you can also just use `useDropzone({noClick})`/`<Dropzone noClick>`.

P.S. we don't have a dependency on [dropzone.js](https://www.dropzonejs.com), this lib is a native react impl.

**Comment by UttamMarandi** [comment]
I was facing similar issues while building a chat input. I have wrapped my chatbox inside react-dropzone to allow drag-drop feature and set the "noClick" to true. So users can only drag-drop to upload files. But I also have an upload button where I wanted the upload on click to work.

 What I did was use two instances of useDropzone. In one noClick is set to true and in other no click is set to false. 
 And passed the upload button as a react node to the component.

`export const Dropzone = ({ children, clickableChildren, onDrop }) => {
  const { getRootProps, getInputProps } = useDropzone({
    onDrop,
    noClick: true,
  });
  const {
    getRootProps: getButtonRootProps,
    getInputProps: getButtonInputProps,
  } = useDropzone({
    onDrop,
    noClick: false,
  });

  const { className: rootClassName, ...restRootProps } = getRootProps();
  const { className: buttonClassName, ...restButtonProps } =
    getButtonRootProps();

  return (
    <div>
      <div {...restRootProps}>
        {/* Disabled */}
        <input {...getInputProps()} />
        {children}
      </div>
      <div {...restButtonProps}>
        {/* Enabled */}
        {clickableChildren}
        <input {...getButtonInputProps()} />
      </div>
    </div>
  );
};`

**Comment by JakeSidSmith** [comment]
Similarly to @UttamMarandi I needed one area to be dropped on and another to click. I did this by destructuring the `onClick` and applying it to the element I wanted.

```jsx
const { onClick, ...rootProps } = getRootProps();
const inputProps = getInputProps();

<div {...rootProps}>
  <input {...inputProps} />
  <button onClick={onClick}>
    Drag your files here, or click to select files
  </button>
</div>
```
