### ISSUE TITLE
doubleclick as option 

### ISSUE THREAD

**Issue by noudadrichem** [react-dropzone/react-dropzone#542]
Hi,
Great package!
Only thing: I want to be able to doubleclick to open my explorer/finder, now it only supports onClick so i'm using `disableClick={true}` Is there a workaround or setting to get doubleClick to work?

If not than handle this as a feature request 😝

_Single click currently only selects the element._

TL;DR
This on double click: 
http://d.pr/i/a0e2BH/nEKS7dCe

**Comment by rkmarks** [comment]
the dropzone itself supports onClick however in your consuming component you can use event handling however you please. I do not see this being something usable for all use cases. closing

**Comment by noudadrichem** [comment]
The package supports file upload on click, you want me to rebuild this whole functionality because my feature request is not relevant?

sad..

![crying](https://media.giphy.com/media/l1KVaj5UcbHwrBMqI/giphy.gif)

**Comment by rkmarks** [comment]
I apologize if its misconstrued. I'm merely stating that for most use cases, if not all, a single click is all that is necessary and being that this component is being designed to be very customizable once consumed it makes sense for the consumer to create the logic for what they are hoping to accomplish. However, if you would like to still see if your request is something others are willing to accept please submit a PR and we would be happy to review.

**Comment by noudadrichem** [comment]
I'm just requesting that the function that currently runs onClick can also run at onDoubleClick. As you're saying yourself the package is being designed to be very customizable. 

Just a request. haha 😝
