### ISSUE TITLE
Allow multiple with a max count

### ISSUE THREAD

**Issue by ktalebian** [react-dropzone/react-dropzone#545]
Is it possible to allow multiple files drop, but still limit it to a certain number? For example only allow at most 20 files to be dropped at a time.

**Comment by moosch** [comment]
I'd think that was something to be handled by your `onDrop` function

**Comment by rkmarks** [comment]
@ktalebian I believe @moosch is correct you can overwrite the onDrop function to handle your use case.

**Comment by okonet** [comment]
Yes. Use `onDrop` callback.

**Comment by heshamelmasry77** [comment]
okay guys is there an example for this using onDrop ?
