### ISSUE TITLE
Chrome 63 hangs dragging a file onto the drop zone whilst the file dialog is open. 

### ISSUE THREAD

**Issue by dennisroche** [react-dropzone/react-dropzone#549]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

Chrome 63 hangs dragging a file onto the drop zone whilst the file dialog is open. 

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Go to https://react-dropzone.js.org/ and use the 'Basic example'. 
2. Click the drop zone to open the file dialog.
3. Drag a **single** file from the file dialog into the drop zone. 
    - The file dialog doesn't close
    - Doesn't crash when dragging multiple files
4. Open or cancel the file dialog. Chrome crashes :boom:.

**What is the expected behavior?**

The drop zone shouldn't accept a file being dropped whilst the file dialog is open.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

```
react-dropzone 4.2.3
chrome 63.0.3239.132
windows 10 (1709)
```

**Comment by dennisroche** [comment]
I also believe that I have a fix for this issue. :smile:

**Comment by okonet** [comment]
I’d be happy to merge your fix!

**Comment by dennisroche** [comment]
i'll push up a PR soon.

**Comment by dennisroche** [comment]
PR up. 👍

**Comment by okonet** [comment]
Fixed in https://github.com/react-dropzone/react-dropzone/pull/551
