### ISSUE TITLE
Accept any MIME type ?

### ISSUE THREAD

**Issue by jpfiorilla** [react-dropzone/react-dropzone#550]
Hello,

I'm building an application that contains a file browser, to which the user can upload essentially any type of file.

I'm attempting to allow this using `<Dropzone accept="*/*" ... />`, but this instead has Dropzone reject any file I can test it with.

I'm currently trying to sidestep this by doing `<Dropzone accept="text/*, audio/*, video/*, image/*, application/*" ... />`, but this still disallows files seemingly at random (eg it won't let me upload a `.scss` file despite allowing `text/*`).

What's the intended way to allow any file type? Thank you!

**Comment by okonet** [comment]
Just don't define `accept` and it will accept any file.

**Comment by hotcakedev628** [comment]
I defined `accept` to allow images and videos in my React app.
Ideally, I want to show [heic](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/mt846532(v=vs.85)) mime type images by drag and drop.
But it doesn't show anything.
```
const { getRootProps, getInputProps, open, isDragActive } = useDropzone({
    multiple: false,
    onDrop: handleDrop,
    accept: "image/*,video/*",
```
