### ISSUE TITLE
Upgrading to 4.2.7 causes issues with find("Dropzone") in tests

### ISSUE THREAD

**Issue by sesh** [react-dropzone/react-dropzone#559]
- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

In version `v4.2.6` and below, tests that look like this worked fine:

```javascript
const onDrop = jest.fn();
const component = <DropzoneWrapper onDrop={onDrop} />

const Dropzone = component.find('Dropzone');
Dropzone.simulate('dropAccepted');
expect(onDrop).toHaveBeenCalled();
```

This test now fails because `component.find()` returns no elements.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Add a test similar to the one provided here (or the ones in v4.2.6 of react-dropzone)
2. Run `npm t`

**What is the expected behavior?**

Tests that pass in one minor version should continue to pass.

**Workaround**

If you're running into this issue, you can fix it by referring to Dropzone directly. See the diff between v4.2.6 and v4.2.7 for an example of how this was done:

https://github.com/react-dropzone/react-dropzone/compare/v4.2.6...v4.2.7

**Comment by okonet** [comment]
Seems also related to https://github.com/react-dropzone/react-dropzone/pull/556. Can you please send me a fix for that?

**Comment by sesh** [comment]
@okonet I don't have enough knowledge of this package to help out with a fix at the moment. There is also a simple workaround that other people can use going forward.

**Comment by dan-lee** [comment]
Our build also fails with the following diff in the snapshots
```diff
-   <Dropzone
+   <t
       acceptStyle={
       Object {
```

I guess this came in by now providing ES builds: https://github.com/react-dropzone/react-dropzone/commit/1fd768b2a95d53dadc8c746cb83a373bbe312ab5

I am not entirely sure what's going on, but the name of the class seems to get minified/transpiled?

**Comment by thaddeusreid** [comment]
After upgrading from `4.2.6` to `4.2.7` I also experienced test failures on a personal project.

Changing the `find` argument from a string
```js
...
component.find('Dropzone')
```
to the component module got them passing.
```js
const Dropdown = require('react-dropzone');
...
component.find(Dropzone);
```
