### ISSUE TITLE
4.2.7 isFileDialogActive timeout issue

### ISSUE THREAD

**Issue by timothyallan** [react-dropzone/react-dropzone#560]
Heya all.

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
as of 4.2.7 I am getting a null issue in the `onFileDialogCancel` timeout.

In the below snippet, _this4.fileInputEl is null, and so .files fails on it. 4.2.6 works great.I've tested the lastest versions of Chrome, and even IE11

```
 key: 'onFileDialogCancel',
    value: function onFileDialogCancel() {
      var _this4 = this;

      // timeout will not recognize context of this method
      var onFileDialogCancel = this.props.onFileDialogCancel;
      // execute the timeout only if the FileDialog is opened in the browser

      if (this.isFileDialogActive) {
        setTimeout(function () {
          // Returns an object as FileList
          var files = _this4.fileInputEl.files;


          if (!files.length) {
            _this4.isFileDialogActive = false;
          }

          if (typeof onFileDialogCancel === 'function') {
            onFileDialogCancel();
          }
        }, 300);
      }
    }
```
**If the current behavior is a bug, please provide the steps to reproduce.**

I'm selecting a file from the browser file popup, which replaces the dropzone component with an image preview. The error occurs when the preview appears, only in 4.2.7.

**What is the expected behavior?**

No error.

**Comment by okonet** [comment]
Looks like https://github.com/react-dropzone/react-dropzone/pull/556 introduced a regression. Would you be ready to help fixing it? Probably a null check will suffice.

**Comment by timothyallan** [comment]
My heart says yes, my multiple project deadlines say probably not :)

**Comment by yuri-sakharov** [comment]
Hi,
when will be merge or better solution?
