### ISSUE TITLE
React Dropzone disable property does not work

### ISSUE THREAD

**Issue by aaayumi** [react-dropzone/react-dropzone#562]
**Do you want to request a *feature* or report a *bug*?**

I want to report a potential bug.  I tried a 'disabled' feature of opening file dialog. But it didn't work.
I also post it on StackOverFlow. - [React Dropzone disable property does not work](https://stackoverflow.com/questions/48462993/react-dropzone-disable-property-does-not-work)

**What is the current behavior?**
In the console, it prints out `true` and `false` for `this.state.disabled`. But file dialog automatically is opened when I click a dropzone.

**What is the expected behavior?**
When `this.state.disabled`, file dialog should not be opened when dropzone is clicked.

**Comment by aaayumi** [comment]
I found out that I have to use a specific version. The latest version didn't include `disabled` property. The version I use was `v4.1.0`.

**Comment by okonet** [comment]
Please provide a PR with the fix if possible.

**Comment by okonet** [comment]
We'll also need tests that would cover that case.
