### ISSUE TITLE
Use forked version of attr-accept

### ISSUE THREAD

**Issue by ajsharp** [react-dropzone/react-dropzone#566]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

react-dropzone relies on attr-accept, which as of now is effectively unmaintained (see https://github.com/okonet/attr-accept/issues/17). The last published version is tied to an outdated babel 5 preset, which breaks the build when trying to build in a modern babel 6 stack. 

When I try to build a new parcel project, I get the following error:

```
Using removed Babel 5 option: [PATH]/parcel/node_modules/attr-accept/.babelrc.stage - Check out the corresponding stage-x presets
```

This is because the current published version of attr-accept uses the stage 0 preset (https://github.com/okonet/attr-accept/blob/v1.1.0/.babelrc). 

If react-dropzone maintained an up-to-date fork of attr-accept -- at least for the time being, until attr-accept finds new ownership -- this issue is easily fixed, as attr-accept HEAD has the [updated babelrc settings](https://github.com/okonet/attr-accept/blob/6063d5936428da407e21bac8633c446405a053c2/.babelrc). In that case, react-dropzone could rely on either a separate npm package also published by this project (maybe react-dropzone-attr-accept) or just use a git dependency.

**Comment by okonet** [comment]
I'm the author of both packages so I don't see any reason for forking it.

**Comment by amiiit** [comment]
@okonet any updates on this? It seems like `attr-accept` is already fixed in the last release `v1.1.2`. But `react-dropzone` still depends on the older `v1.0.3`. Do you think just updating the dependency here would work?

**Comment by okonet** [comment]
@amiiit what needs to be done to resolve this?

**Comment by okonet** [comment]
Please create a PR
