### ISSUE TITLE
Routing immediately after a file upload

### ISSUE THREAD

**Issue by coopersamuel** [react-dropzone/react-dropzone#572]
- [x] I found a bug

**What is the current behavior?**
Using React Router to route to a new location immediately after uploading a file with react-dropzone. This issue occurs only when browsing the file system to upload, not when using the drag/drop method.

The route is firing before react-dropzone can register that the file system dialog box has closed, which throws an error in the console: `Cannot read property 'files' of null`  

**Steps to reproduce.**

1. Set up React Router to change route in the onDrop handler
2. Browse the file system and select a file to upload (drag/drop method will not throw this error, only browse method)
3. Observe the route change and error in the console

**What is the expected behavior?**
No error in the console

**Workaround**
Workaround achieved by using a setTimeout() to delay the route change until onFileDialogCancel() can run to completion

**Comment by rkmarks** [comment]
@coopersamuel do you have a repo I could duplicate this on?

**Comment by coopersamuel** [comment]
@rkmarks i can't get you access to the repo, but i'll try to set up some kind of quick example to demonstrate the issue - does react-dropzone have some kind of bundle i could include in a jsfiddle?

**Comment by thoja21** [comment]
@rkmarks @coopersamuel - is this essentially the same issue I reported in  #570 ? I'm not familiar with how React Router works but I was getting that same error if the DropZone control was removed from the DOM before setTimeout in onFileDialogCancel had finished. @coopersamuel I can't see this happening in the snippet you added though?

**Comment by coopersamuel** [comment]
@thoja21 yes, probably a similar situation. What don't you understand about the snippet? `history.push('/somewhere');` will route to another location within the application via React Router, thus removing control from dropzone.

**Comment by thoja21** [comment]
@coopersamuel Thanks, useful to know. Sorry didn't twig that `history.push('/results');` would route - whoops....

**Comment by thoja21** [comment]
@coopersamuel #561 fixed this issue for me. Can you confirm the latest release fixes this problem for you too?
