### ISSUE TITLE
Drag and drop not working on Microsoft edge (Bug on Edge)

### ISSUE THREAD

**Issue by sadokmtir** [react-dropzone/react-dropzone#576]
I cannot drag and drop files from the folder to the dropzone element only on microsoft edge. Although in this thread, Microsoft team mentioned it support HTML5 [drag and drop](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/8964523-support-html5-drag-and-drop-of-files-from-explorer#{toggle_previous_statuses}).

Tested on windows 10 and Microsoft Edge 41.16299.248.0 ; MS Microsoft EdgeHTML 16.16299

Update: On localhost development, I was not able yo upload files and when it was served from production server, I was able to upload files. I have no idea why (may be some setting from Microsoft Edge)

**Comment by gonmercado** [comment]
I can confirm that too @sadokmtir, the simplest dragdrop example will fail to drag and drop any file on Edge 41.16299.15.0, Windows 10 and react-dropzone version 4.2.8

**Comment by rkmarks** [comment]
closing as this was fixed in #578
