### ISSUE TITLE
Dropzone returning empty file type if I am trying to upload .xls file on mac (with MS office installed).

### ISSUE THREAD

**Issue by garima-birdeye** [react-dropzone/react-dropzone#579]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1.
1.
1.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by rkmarks** [comment]
@garima-birdeye I was looking into this issue and it may be a browser related issue based on OS. I tested on chrome and was able to duplicate, but on firefox the type was there. I also tested on safari and could not duplicate this issue as well. You may want to report that to chrome so they can fix it for mac OS builds.

**Comment by garima-birdeye** [comment]
@rkmarks  This only happens if we have MS office installed in MAC and then in any browser (be it chrome, safari or any other.)

chrome version : Version 63.0.3239.132 (Official Build) (64-bit)
safari version : Version 10.1.1 (12603.2.4)
MAC version : 10.12.5 (16F73)
dropZone verison : 4.1.3

**Comment by Ionut-Milas** [comment]
I'm having the same issue uploading docx files on Chrome with Windows 10.
On MAC works just fine

**Comment by koos303** [comment]
If I save an existing Excel file as File Format ''Strict Open XML Spreadsheet (.xlsx)" it works with file type `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`

**Comment by viveknigam3003** [comment]
This is happening for me as well on Photoshop files when clicking to upload files, while when I'm dropping the files using dnd it works fine. I'm using Mac M1 and Chrome
