### ISSUE TITLE
Issue on linux and small images 

### ISSUE THREAD

**Issue by leantorres73** [react-dropzone/react-dropzone#581]
**Do you want to request a *feature* or report a *bug*?**

- [X] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

On linux, images with small size are not uploaded. I've tested with images of 170kb and It appears 0B inside the react modal. 

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Need linux installed
1. Try to upload an image of less than 200kb ()
1. '0B' will appear instead of the original size and it will not be uploaded

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by rkmarks** [comment]
@leantorres73 I was unable to duplicate this issue using the basic examples on my Ubuntu desktop w/ a 30kb jpg file. Do you have any source code that we can review to see where you may be having this issue? also please add which version of react-dropzone you are using.

**Comment by leantorres73** [comment]
Yeah sorry I think it was a folder permission issue... I was trying to upload from my "pictures" folder. I copied the file to another folder and it worked. I also saw in gmail when I tried to attach the same picture that I get a message saying "this image is 0 bytes" . 
Thanks for the help
