### ISSUE TITLE
geojson type not recognized

### ISSUE THREAD

**Issue by rheinheimer** [react-dropzone/react-dropzone#582]
I found a bug

**What is the current behavior?**
geojson files do not appear to be accepted, despite their being a [valid MIME type](https://www.iana.org/assignments/media-types/application/geo+json). I've been able to create a workaround, of course, but just accepting ".geojson" files, but that doesn't help with validation. Another workaround is to change the .geojson extension to .json, in which case it comes through accepted, with the appropriate application/json type.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Add "application/geo+json" to the accept prop.
1. Drop a *.geojson file into the dropzone.
1. See that the file appears in the rejectedFiles list, with no MIME type, rather than acceptedFiles.

**What is the expected behavior?**
The file should be accepted.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
react-dropzone version: 4.2.9. Chrome version: 63.0.3239.132

**Comment by rkmarks** [comment]
I was able to duplicate this and I've tagged it as a bug. If you are able to see where the issue is please provide a PR and update tests as necessary but I think this has something to do w/ the `attr-accept`module.

**Comment by okonet** [comment]
The fact it's a valid MIME type isn't enough if browser doesn't support it. Does it work properly on simple input? As a work around you could use an extension instead of mime type.
