### ISSUE TITLE
can't upload without using drag and drop in Safari 11.0.3

### ISSUE THREAD

**Issue by Victor502** [react-dropzone/react-dropzone#584]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug

**What is the current behavior?**
I'm using latest version of react-dropzone 4.2.9 and I can't upload an image without using drag and drop on Safari 11.0.3.  If I select a file through my computer nothing is available to upload

**If the current behavior is a bug, please provide the steps to reproduce.**

1. try to upload an image without dragging and dropping 
1. can't select any file
1. works in Chrome

**What is the expected behavior?**
To be able to upload an image without drag and drop

**If this is a feature request, what is motivation or use case for changing the behavior?**
cross browser compatibility 

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

MacOS High Sierra 10.13.3  |  Safari version 11.0.3  |  react-dropzone version 4.2.9

**Comment by rkmarks** [comment]
@Victor502 I know the component works just fine w/ Safari 11.0.3 as I can view the click event. I'm wondering if there is an issue w/ High Sierra. Can you provide your code if this is custom or are you using the examples?

**Comment by Victor502** [comment]
We've found that it does have to do with High Sierra, it works with our clients that have El Capitan, and earlier versions of High Sierra.
