### ISSUE TITLE
Using dropzone inside a <form> causes form action to be triggered

### ISSUE THREAD

**Issue by marekolszewski** [react-dropzone/react-dropzone#586]
**Do you want to request a *feature* or report a *bug*?**
- [X] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
When you put a dropzone inside a form tag, clicking on the dropzone triggers the form's action. In my case, the default action causes the page to reload with a '?' added to the current URL, causing the page to scroll to the top.

My current work around is to add the following 'null' action to my form: `<form action='javascript:;'>`

**What is the expected behavior?**
The form's action should not be triggered.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Tested using Chrome 65 on Mac OS 10.12
Dropzone version: 4.2.9

**Comment by rkmarks** [comment]
@marekolszewski when it comes to react and forms the `action` has an event that is triggered like an `onChange` you would probably want to do an `e.preventDefault()` in your action function or if you are not using the action by doing `action=#` that should prevent a full page reload.

**Comment by Fiewor** [comment]
I also experienced this and had to add an `e.preventDefault()` as suggested by @rxmarbles but I think this is undesired behavior, unless of course it is unavoidable and is therefore explicitly mentioned in the documentation (I haven't checked so I can't confirm this).
