### ISSUE TITLE
.csv file doesn't appear in Custom filers filter when open react-dropzone

### ISSUE THREAD

**Issue by reemtariqq** [react-dropzone/react-dropzone#587]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
- when open browse files and files appears under custom files in the dialog  .csv file doesn't appear
**If the current behavior is a bug, please provide the steps to reproduce.**

1. open file dialog 
1. custom files filter appear
1. .csv file doesn't appear

**What is the expected behavior?**
 .csv file should appear
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by rkmarks** [comment]
@reemtariqq can you provide the browser, OS, and react-dropzone you are using please? I was unable to duplicate w/ the examples on chrome v65 in MAC OS.

**Comment by reemtariqq** [comment]
i'm using windows 10 and latest version of react-dropzone

**Comment by reemtariqq** [comment]
we managed to solve this issue by adding the extension and mime types in the acceptedfile prop as following 
.csv , .xslx
