### ISSUE TITLE
trouble with disableClick

### ISSUE THREAD

**Issue by dant00ine** [react-dropzone/react-dropzone#588]
Anybody else having trouble getting disableClick to work?

I have tested other boolean attributes such as disablePreview, and these are working for me. Using the same syntax, I am unable to get anything out of the `disableClick` attribute.

I am expecting that when set to true, clicking on the upload area or image preview area should not open up the image upload dialogue.

I want to disable the default click to upload and replace it with a button, here's the code I am using. Other than the disableClick attribute, everything is working as expected.

```
<Dropzone onDrop={this.onDrop} disableClick ref={(node) => {dropzoneRef = node}}>
    <p> Drag photos or <span onClick={ () => {dropzoneRef.open()}} > Click Here </span> </p>
</Dropzone>
```

But clicking anywhere in the area, or in the image preview area, the browser upload dialogue will still open.

"react-dropzone": "^4.2.9"

Any idea on what I could be doing wrong? Is this indeed a bug? What information could I provide to be more helpful?

**Comment by rkmarks** [comment]
Hey @dant00ine can you also provide the browsers you are testing this in? I was not able to duplicate this issue w/ the default examples and the disableClick worked just fine.

**Comment by dant00ine** [comment]
Sorry it's been a while to come back to this, but I still can't avoid this problem.

Even with the simplest code for the dropzone, clicking anywhere, including on an image preview, will trigger the file upload dialogue. I don't even understand how there would be any connection there??

I can reproduce on FireFox and Chrome. I'll see if I can reproduce in an online repo somewhere.

```
                  <Dropzone 
                            onDrop={this.onDrop} 
                            disableClick={true}
                        />

                        <div className="photo-preview-area">
                            {
                                this.state.product_images &&
                                this.state.product_images.map( (img, idx) =>
                                    <li key={img.name}>
                                        <span onClick={() => {this.removeImage(img.name)}}>X</span>
                                        <span>{idx++}</span>
                                        <img src={img.preview} />
                                        <p className="photo-preview-caption">{img.name}</p>
                                    </li>
                                )
                            }
                        </div>

```
