### ISSUE TITLE
fileMatchSize for dropped URLs

### ISSUE THREAD

**Issue by versae** [react-dropzone/react-dropzone#589]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
For links dropped, the function [`fileMatchSize()`](https://github.com/react-dropzone/react-dropzone/blob/master/src/utils/index.js#L33) always returns `false` since `file.size` is undefined.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Define a component
```
        <Dropzone
          onDrop={(acceptedFiles, rejectedFiles) => {console.log(acceptedFiles), console.warn(rejectedFiles)}}
          disablePreview={true}
        >
          <p>Drop your files or click here to upload</p>
        </Dropzone>
```
1. Drag some URL from another tab into the space
1. See how every URL is rejected in the console.

**What is the expected behavior?**
It should not check for size of files when URLs are being dropped. Basically it should always return `true` if `file` doesn't have `.size` attribute.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Google Chrome is up to date
Version 65.0.3325.181 (Official Build) (64-bit)
$ node --version
v8.9.4
"react": "^16.2.0",
"react-dropzone": "^4.2.9",

**Comment by rkmarks** [comment]
sounds like a perfect way to contribute 😄
