### ISSUE TITLE
Adding default type="file" to drop zone input?

### ISSUE THREAD

**Issue by jpetitcolas** [react-dropzone/react-dropzone#590]
- [x] I want to propose an improvement

Currently, when instantiating a drop zone, it creates an `input` without any default `type` attribute:

https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L417-L420

I need it for end to end testing (Selenium requires a `type="file"` to be able to fill upload fields). Moreover, it adds more semantic.

I can easily circumvent the issue adding a `type="file"` prop directly on the parent component. Yet, I wonder if it has been voluntarily omitted. If not, I'll open a PR to fix it. :)

**Comment by okonet** [comment]
It is not true. It create `type="file"`. See https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L376

**Comment by jpetitcolas** [comment]
My bad. We probably lose the prop somewhere on our side. Sorry for the noise! Great project by the way! :+1:
