### ISSUE TITLE
Dropzone contents are re-mounted continously while resizing

### ISSUE THREAD

**Issue by kroltan** [react-dropzone/react-dropzone#592]
**Do you want to request a *feature* or report a *bug*?**
- [X] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Resizing the window causes the `Dropzone`'s children to be unmounted and mounted again, potentially causing repeated side effects if the components within are not pure.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Given this code
    ```jsx
    class MyComponent extends Component {
        componentDidMount() {
            console.log("some side effect");
        }

        render() {
            return "some content";
        }
    }

    // Used somewhere like this
    <Dropzone>
        <MyComponent/>
    </Dropzone>
    ```
1. Resize the window
1. Observe the console output, there will be one message for each resize event

**What is the expected behavior?**
The content component is mounted when the `Dropzone` is mounted, and unmounted only when the `Dropzone` is, too.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Observed on Firefox 59, Linux Mint, and react-dropzone@4.2.9

**Comment by okonet** [comment]
Looks like a big. Can you please investigate and create a PR with a fix?

**Comment by Nodman** [comment]
@kroltan I was not able to reproduce this (tried both firefox and chrome). Can you please provide more information on your environment, like React versions?

**Comment by okonet** [comment]
I’m closing this unless we get a reproducible codesandbox
