### ISSUE TITLE
Update babel presets

### ISSUE THREAD

**Issue by horacioh** [react-dropzone/react-dropzone#593]
is in the interest of this library to update the babel presets to `babel-preset-env` ?

if true, I can provide a PR for this. I wanted to update this in my application that uses this package but because it uses the old presets I cannot update.
some official info about this: http://babeljs.io/env

thanks!

**Comment by okonet** [comment]
Yes, please!

**Comment by horacioh** [comment]
great! working on this :)

is there any Contribution guidelines?

**Comment by horacioh** [comment]
running `yarn start` i'm getting this error without touching any line of code:

```
| -> yarn start
yarn run v1.3.2
warning ../../../package.json: No license field
$ styleguidist server
You can now view style guide in the browser.

Local:            http://localhost:8080/

On your network:  http://192.168.1.114:8080/

Failed to compile.
./src/index.js
Syntax error: Unexpected token (281:17)

  279 |   }
  280 |
> 281 |   renderChildren = (children, isDragActive, isDragAccept, isDragReject) => {
      |                  ^
  282 |     if (typeof children === 'function') {
  283 |       return children({
  284 |         ...this.state,
```

**Comment by TrySound** [comment]
@horacioh Am I blind or this library already uses `babel-preset-env` for a long time?

https://github.com/react-dropzone/react-dropzone/blob/master/.babelrc#L4-L16
