### ISSUE TITLE
Migrate to React 16.3

### ISSUE THREAD

**Issue by rolandjitsu** [react-dropzone/react-dropzone#596]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [x] I want to propose a feature

**What is the current behavior?**

React 16.3 was [released](https://github.com/facebook/react/blob/master/CHANGELOG.md#1630-march-29-2018) a few weeks ago and it introduced some breaking changes. It would be nice if this lib would migrate to the new API.

**If the current behavior is a bug, please provide the steps to reproduce.**

1.
1.
1.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

Lots of perf improvements, better API for exposing refs with [React.createRef()](https://github.com/facebook/react/pull/12162) and [React.forwardRef()](https://github.com/facebook/react/pull/12346), etc.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by okonet** [comment]
Feel free to do so!

**Comment by rolandjitsu** [comment]
@okonet fair enough :) I guess I'll start working on it.

**Comment by TrySound** [comment]
Actually there isn't any breaking changes in react 16.3. Breaking changes happens only in major releases. Even deprecation warnings will happen since 16.4.

**Comment by TrySound** [comment]
@okonet The only thing I see can be changed is migrating to `createRef` api which will save a couple of lines. But since it will be a breaking change let's don't touch it yet. There's nothing deprecated in the code. I guess this issue is not relevant anymore.

**Comment by rolandjitsu** [comment]
@TrySound there's also `componentWillReceiveProps` which is deprecated with 16.3 and will be removed. Why are you closing this issue?

**Comment by TrySound** [comment]
@rolandjitsu Can you point me where exactly?

**Comment by rolandjitsu** [comment]
Sure, see [component-lifecycle-changes](https://reactjs.org/blog/2018/03/29/react-v-16-3.html#component-lifecycle-changes).

While that is not a breaking change, it will log a deprecation warning.

It might be easier to migrate incrementally rather than when breaking changes occur after n version releases.

**Comment by TrySound** [comment]
@rolandjitsu I know about lifecycles. Point to the code in this project where you see `componentWillReceiveProps`. I can't find it.

**Comment by rolandjitsu** [comment]
@TrySound oops, sorry. This project does not have that, it was [#428](https://github.com/oliviertassinari/react-swipeable-views/issues/428) that uses it.
