### ISSUE TITLE
How to show the dropzone area when the user drags a file to it's browser ?

### ISSUE THREAD

**Issue by arelaxend** [react-dropzone/react-dropzone#600]
Hi,

Is it possible to show the dropzone area when the user drags a file to it's browser ? The feature exists in Google image for example.

Is it manageable ?
Hagd, A.

**Comment by zanisis** [comment]
i want adding question, maybe possible if drags disabled ?.

**Comment by arelaxend** [comment]
It is useful for the user because he can see in advance where is the dropzone area! Is this what you mean ?

**Comment by rkmarks** [comment]
closing issue as this is not an issue of the component.
