### ISSUE TITLE
The window does not open when we are use accept="image/png"

### ISSUE THREAD

**Issue by sweelemk** [react-dropzone/react-dropzone#602]
Hi! We are using 3.7.0 version.

When I working with android < 6 version i get exception on the Chrome Browser. The exception affecting only with accept="image/*". 
2 weeks ago was not exception.

Example https://react-dropzone.netlify.com/#styling-dropzone  also does not work

I use android 4.4.2 and Chrome version 66.0.3359.126

**Comment by rkmarks** [comment]
Have you tried upgrading your version and testing it out? You are a whole major version behind and would be difficult to troubleshoot.

**Comment by sweelemk** [comment]
no, i dont update my version, but i looked example https://react-dropzone.netlify.com/#styling-dropzone and tested - the result is the same

**Comment by sweelemk** [comment]
I tested with version 4.2.9 and all work. Thx
