### ISSUE TITLE
when attempting to upload a file that exceeds maxSize it doesn't trigger rejectClassName

### ISSUE THREAD

**Issue by MareliBasson** [react-dropzone/react-dropzone#604]
I'm actually not sure if this is a bug, but it would be great if it could be added as a feature.

- [ ] I found a bug
- [x] I want to propose a feature

**What is the current behavior?**
Currently the dropzone prevents the file from being uploaded but there's no visual cue that the file will be rejected.

**What is the expected behavior?**
It would be great if a file that exceeds the maxSize that's been set, also triggers the rejectClassName. This way you can warn the user that their image won't be accepted due to it's size.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by rkmarks** [comment]
sounds like a good contribution :) do you mind opening a PR about it ?

**Comment by MareliBasson** [comment]
@rkmarks sure, i'm willing to try . I'm still quite junior when it comes to JS, so I'll see if I can figure out.

**Comment by stclairdaniel** [comment]
This should definitely still be looked at.

**Comment by shan-du** [comment]
The temporary work-around I had for this was
```
  onFileDrop = (acceptedFiles) => {
    const { maxSize } = this.props;

    if (acceptedFiles.length) {
      const file = acceptedFiles[0];
      const isFileValid = file.size <= maxSize; // check file size against maxSize
      this.setState({ isFileValid });

      if (isFileValid) this.uploadFile(file);
    }
  };

  renderError = !this.state.isFileValid ? <p>File size exceeds max allowed</p> : null;

  render = () => (
   <Fragment>
     <Dropzone ... onDrop={this.onFileDrop} ... />
     {this.renderError}
   </Fragment>
  );
```
