### ISSUE TITLE
Dropzone loses styling when hovering text

### ISSUE THREAD

**Issue by eluchsinger** [react-dropzone/react-dropzone#605]
- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
The styling for accepted or rejected filetype does not get applied when hovering over the dropzone text on Firefox. It works on Chrome and Edge.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Drag a file over a dropzone.
2. Move the file over the text of the dropzone (the styling will disappear).
3. Move the file away from the text inside the dropzone (the styling will reappear).

**What is the expected behavior?**
The styling gets applied when the file is hovering the text inside the dropzone.

- react-dropzone: 4.2.9
- Firefox 61.0b3

**Comment by rkmarks** [comment]
@eluchsinger i was unable to duplicate this issue using the example code though i was on 61.0b6. also keep in mind the browser you are in is a beta version and this is intended for stable versions for all browsers

**Comment by Franklyn-S** [comment]
Why this is closed? I'm facing this issue too

**Comment by rolandjitsu** [comment]
> Why this is closed? I'm facing this issue too

Most likely because:

> Furthermore, at this moment it's not possible to read file names (and thus, file extensions) during the drag operation. For that reason, if you want to react on different file types during the drag operation, you have to use mime types and not extensions! For example, the following example won't work even in Chrome:

So to sumarize, using file extensions for styling purposes for accept/reject during drag operations is not reliable across browsers and it will, most likely, be difficult to fix on our side. But, if the issue is different, then please provide a more accurate way of reproducing the issue so we can get to the bottom of it.
