### ISSUE TITLE
add ability to DnD at any part in document.

### ISSUE THREAD

**Issue by theGABS** [react-dropzone/react-dropzone#622]
I am confuse why you did not implement it before? It is looks like very often requirement. I see it on a lot of sites, for example in slack.com. 

example how at can look at code.
```
<Dropzone onDrop={this.onDrop} dropAnywhere={true}>
     <button>Click here, or drag you files to this window</div>
 </Dropzone>
```

**Comment by rkmarks** [comment]
@theGABS seems like a handy feature would you like to submit a PR about that ?

**Comment by theGABS** [comment]
Hi, I can try.
