### ISSUE TITLE
Officially supported browsers ?

### ISSUE THREAD

**Issue by Alekseykua** [react-dropzone/react-dropzone#630]
- [x] I want to propose a feature

**What is the current behavior?**
Does not specify which browsers are fully/partially supported. 

**If this is a feature request, what is motivation or use case for changing the behavior?**
Before integrating users would like to know if their desired browser support is available. Would also help to build support if we know which browsers need it.

**Comment by Alekseykua** [comment]
Bump

**Comment by slikts** [comment]
Ideally this should be done using [browserslist](https://github.com/browserslist/browserslist).

**Comment by amanadi007** [comment]
Any update on this?

**Comment by rolandjitsu** [comment]
@amanadi007 Not really, sorry. I was planning on running e2e tests on SauceLabs which would have helped, but never got the chance to do it.
