### ISSUE TITLE
Opacity regression in 4.2.12+

### ISSUE THREAD

**Issue by tjunnone** [react-dropzone/react-dropzone#631]
When upgrading from 4.2.11 to 4.2.12 or 4.2.13 (latest as of writing), with no other changes, we're seeing a strange regression or perhaps change in behavior.

We have a fixed positioned Dropzone component that covers the entire browser window, with other components both inside as children and others as siblings to the Dropzone. With 4.2.11, everything's fine, going to any later version the Dropzone is opaque white and any underlying components (not children of Dropzone) cannot be seen. Trying to restore the previous version behavior by applying opacity, background-color, etc. styling to the Dropzone component doesn't appear to work.

The commit in question is https://github.com/react-dropzone/react-dropzone/commit/d12f9f615f2d908a1c8d6e268701026b4fc7917c

**Comment by danielweck** [comment]
Same observation. We are sticking to version `4.2.11` for now.
