### ISSUE TITLE
[BUG] accept does not work with .tar.gz

### ISSUE THREAD

**Issue by microsoftly** [react-dropzone/react-dropzone#635]
**Current behavior and repro steps**
```jsx
 <DropZone accept=".tar.gz"/>
```
Current behavior: during file selection, no *.tar.gz files are accepted

**Expected behavior**
accepting of `*.tar.gz` files

**Other relevant info**

OS: `OSX 10.13.5`
browser: `Chrome  67.0.3396.99`
DropZone version: `4.2.13`

**Comment by justinshin621** [comment]
Having this same issue. Was it ever resolved?
