### ISSUE TITLE
Max number of files when dropzone has multiple prop

### ISSUE THREAD

**Issue by RaphaelRegnier** [react-dropzone/react-dropzone#636]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [X] I want to propose a feature

**What is the current behavior?**

When the multiple prop is on the dropzone, there is no limitation to the number of files a user can drop.

**If this is a feature request, what is motivation or use case for changing the behavior?**

I had to make a few tricks to limit the number of files the dropzone takes when it has a multiple prop. How about adding a prop to the dropzone like 'maxNumberFiles' that would make the dropzone reject all the files or the exceeding ones ? 
Maybe it would be more convenient directly in the multiple prop likeso : `multiple={3}` and that would not have any limit if left empty

I had to do it on top of the dropzone in my component which is a bit messy even though it works fine 😅

**Comment by dfsq** [comment]
This would be very convenient.

**Comment by danadn** [comment]
What about sharing the workaround @RaphaelRegnier please?

**Comment by conor-kelleher** [comment]
@RaphaelRegnier I'd also very much appreciate hearing about your workaround for this

**Comment by danadn** [comment]
I'm using react-dropzone with redux-form, and the Field component that wraps Dropzone component prevents multiple file to be uploaded:
`<Field name={"files"}
    component={ReduxFormDropzone}
    **multiple={false}**
dropzoneOnDrop={this.handleDrop} />`

So is redux-form the one preventing, not react-dropzone.

More information here:
https://github.com/erikras/redux-form/issues/71

**Comment by okonet** [comment]
This kind of functionality should live in user land and can be easily added using `onDrop` callback. I'd love to accept an example if you're up to.

**Comment by heshamelmasry77** [comment]
this is how you guys do it 
```
onDrop={acceptedFiles => {
                    // do nothing if no files
                    let handleDropImages;
                    if (acceptedFiles.length === 0) {
                      return;
                    } else if(acceptedFiles.length > 5){
                      return notify('maxImages');
                    }else {
                      
                    }

                  }}
```

**Comment by RaphaelRegnier** [comment]
Hello @okonet and sorry for taking so long. Here is a video sample of what I built using dropzones : 
https://www.useloom.com/share/8ad3082bec7c4d7abe0d5ef8cc561db7

In this demo you can see : 
1) I'm adding one file in the first dropzone, then 2 others but the limit is set to 3 so you get an error.
2) I'm dragging a file on the second dropzone by dropping it.
3) I'm adding 2 files to the third dropzone, with a max number of files that is set to 4

You can click on the trash icon to delete your item, once you click on the form submit button, it disables the dropzones while uploading the files. If you reload the page, we disable the dropzones and display a message saying we got all your files already.

Here's a gist of these custom dropzones, it could be refacto but eh, it has been working fine for a while :)

https://gist.github.com/RaphaelRegnier/797015e23a64e8959182528646b46954

**Comment by devcoderbuzz** [comment]
why is this issue closed? i think still i see the issue

**Comment by conor-kelleher** [comment]
While this _can_ live on the end of the developer using this library, through workarounds such as the one proposed around checking the amount of files dragged in, it doesn't lead to a great user-experience.

Allowing the user to do something and then telling them afterwards that they can't do it is usually a pretty bad UX. Would be much nicer if there was a way for the library to disallow the drop event entirely if the number of files dragged in is above a provided maximum and if it returned some boolean letting us know the user is trying to drop too many files, we can provide them with a custom messaging there an then rather than letting them drop and give an error message after

**Comment by joeyfigaro** [comment]
> I’m not opposed to what everyone is saying but this is the application-related logic where this library is a framework to build any application on top of.
> 
> See me comment [#636 (comment)](https://github.com/react-dropzone/react-dropzone/issues/636#issuecomment-428470118) and examples provided how to achieve that.

Running into this challenge now and wishing drop were disabled when maxFiles is hit–catching up on the conversation here and this bit:

> this library is a framework to build any application on top of 

Seems to be contradictory, considering the [default behavior appears to be to empty out all accepted files](https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L700) when max files is reached

Maybe I'm misinterpreting something, though.
