### ISSUE TITLE
Unable to configure Dropzone to accept .stl files

### ISSUE THREAD

**Issue by raviredd** [react-dropzone/react-dropzone#644]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1.
1.
1.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by ddela-cr** [comment]
I'm also trying to figure out how to upload stl files. When I drop a .stl file, the type is empty. According to #597, it should work.

![capture d ecran 2018-08-22 a 13 21 22](https://user-images.githubusercontent.com/16035265/44460831-dd753880-a60e-11e8-95fc-21c4cd3bb1bd.png)

**Comment by ddela-cr** [comment]
@raviredd i've been looking for a fix for this. Have you figured out how to make it work?

**Comment by rkmarks** [comment]
I've located the issue however it is not an issue with `react-dropzone` but an issue in `attr-accept` and reference this issue. I will open up an issue w/ that repo as I believe I have an idea of where this issue occurs.
