### ISSUE TITLE
`acceptedFiles` / `rejectedFiles` arrays are not updated when used as function as a child

### ISSUE THREAD

**Issue by kristofferh** [react-dropzone/react-dropzone#647]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Uploading files doesn't update the `acceptedFiles` / `rejectedFiles` arrays when used as function-as-a-child -- they stay as empty arrays. This bug can be seen in the docs: [Updating styles and contents based on user input](https://react-dropzone.js.org/#!/Styling%20Dropzone/1)

**If the current behavior is a bug, please provide the steps to reproduce.**

```
<Dropzone
  accept="image/png"
>
  {({ acceptedFiles, rejectedFiles }) => {
    return acceptedFiles.length || rejectedFiles.length
      ? `Accepted ${acceptedFiles.length}, rejected ${rejectedFiles.length} files`
      : "Try dropping some cool files.";
  }}
</Dropzone>
```

Verify that dropping / uploading a file does not show the number of accepted or rejected files

**What is the expected behavior?**
`acceptedFiles` / `rejectedFiles` arrays should be populated with files accordingly.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
5.0.1

**Comment by ml242** [comment]
I was looking just at this moment regarding this same issue, and found that if I rolled back to     
`"react-dropzone": "4.2.13",`
my app worked as it used to.

**Comment by Emidomenge** [comment]
I noticed this bug on the documentation as well. And I immediatly came here to check if someone reported this issue, haha.

**Comment by nfantone** [comment]
@Emidomenge There is. You can either use `isDragAccept` instead of `isDragActive` or you can just re-arrange the order in which the conditionals are written.

```jsx
<Dropzone
  accept="image/png"
>
  {({ isDragAccept, isDragReject, acceptedFiles, rejectedFiles }) => {
    return acceptedFiles.length || rejectedFiles.length
      ? `Accepted ${acceptedFiles.length}, rejected ${rejectedFiles.length} files`;
    if (isDragAccept) {
      return "This file is authorized";
    }
    if (isDragReject) {
      return "This file is not authorized";
    }
    return "Try dropping some files.";
  }}
</Dropzone>
```

**Comment by nfantone** [comment]
@kristofferh FYI, I fixed this issue by adding `this.setState({ acceptedFiles, rejectedFiles })` on the `onDrop` handler after L220 of `src/index.js`. I'm using a fork with this patch (cc. @Emidomenge @ml242)

**Comment by kristofferh** [comment]
@nfantone Cool. I haven't had a chance to look into the issue, but if your patch fixes it I'm sure the maintainers would love a PR.

**Comment by ml242** [comment]
@nfantone - thanks for digging around for that. I had pinned the library to the earlier commit but I'll keep an eye out for your change.

**Comment by nfantone** [comment]
@okonet https://github.com/react-dropzone/react-dropzone/pull/667

**Comment by AlexandrLi** [comment]
Hey, guys! When do you plan to release this fix? I'm currently implementing a feature that highly depends on this and it's kinda blocker for me.

**Comment by okonet** [comment]
It should be released already

**Comment by AlexandrLi** [comment]
> It should be released already

Just checked [npm-registry](https://www.npmjs.com/package/react-dropzone) and it shows the last publish date - 17 days ago. Could you double check, please? Did you change the version of the package after this fix?

**Comment by okonet** [comment]
Okay, it's semantic-release issues again 😠 Trying to fix it now.

**Comment by nfantone** [comment]
Many thanks for the prompt input and release, @okonet!
