### ISSUE TITLE
onFileDialogCancel not working correctly

### ISSUE THREAD

**Issue by frontalicious-martijn** [react-dropzone/react-dropzone#652]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
I've created this CodeSandbox to show that onFileDialogCancel is not only triggered when clicking the cancel button. In this example it almost always triggers the function, even when selecting a image the first time.

https://codesandbox.io/s/721y69j5p0

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Click the dropzone
2. Click an image to upload
3. onFileDialogCancel is also triggered (most of the time).

**What is the expected behavior?**
Only trigger the function when Cancel is clicked in File Dialog

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Tested in Chrome on new MacBook Pro, with latest version of React Dropzone (v5.0.1).

**Comment by dbelay22** [comment]
The same here on Chrome /  MacBook Pro / Dropzone v4.2.11

**Comment by rolandjitsu** [comment]
I can confirm that the cb is called when selecting files as well (besides when it's canceled). @frontalicious-martijn would you mind making a PR with a fix?

Most likely it happens at [index.js#L285](https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L285). You just need to check if `{acceptedFiles}` on the state is not empty and only if it is we invoke the cb.

**Comment by helemand** [comment]
Could it be possible that the bug is back? I'm using the latest version and it triggers onFileDialogCancel when files are selected.
