### ISSUE TITLE
Invalid attribute "autocomplete" 

### ISSUE THREAD

**Issue by mantelljason** [react-dropzone/react-dropzone#658]
**Do you want to request a *feature* or report a *bug*?**

- [x ] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Throws validation error when run through HTML validator. The attribute "autocomplete" is not valid for input type "file"

**If the current behavior is a bug, please provide the steps to reproduce.**

1.Run through an html validator
1.
1.

**What is the expected behavior?**
Not to fail validation
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by rkmarks** [comment]
I just ran the test page through an html validator and did not come across this error. https://validator.w3.org/nu/?doc=https%3A%2F%2Freact-dropzone.js.org%2F
