### ISSUE TITLE
Opacity Unknown Dimension on html validator

### ISSUE THREAD

**Issue by mantelljason** [react-dropzone/react-dropzone#659]
**Do you want to request a *feature* or report a *bug*?**

- [ x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Error: CSS: opacity: Unknown dimension.
<input aria-label="File Upload Input" type="file" multiple="" autocomplete="off" style="position: absolute; top: 0px; right: 0px; bottom: 0px; left: 0px; opacity: 1e-05; pointer-events: none;">
**If the current behavior is a bug, please provide the steps to reproduce.**

1.
1.
1.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by rkmarks** [comment]
I do not know what this issue is for? I just ran the test page through and it did not give me the same error https://validator.w3.org/nu/?doc=https%3A%2F%2Freact-dropzone.js.org%2F. Do you have an example site you are working with?
