### ISSUE TITLE
Add an example for folders drag'n'drop

### ISSUE THREAD

**Issue by okonet** [react-dropzone/react-dropzone#661]
As of #https://github.com/react-dropzone/react-dropzone/issues/609 and it's implementation in https://github.com/react-dropzone/react-dropzone/pull/616 we now officially support plugins that should allow integrations with plugins like https://github.com/quarklemotion/html5-file-selector a breeze. It would be great to have an example of such integration in the examples.

**Comment by d-ivashchuk** [comment]
I will work on that!

**Comment by d-ivashchuk** [comment]
I think I am little bit stuck and would need some help. I've looked at source code and #616 and understood that `getDataTransferItems` prop accepts some function and returns an array of files when dropped into the browser. There is also a `defaultGetDataTransferItem` default prop that should make dropping folders possible out of the box. 

So far I don't think I am able to get it working properly while when dropping a folder using pure `<Dropzone/>` component does not display neither contents of the folder nor the correct size of the files inside it.

I would appreciate any help or advice as it is my first open source issue!

**Comment by d-ivashchuk** [comment]
If that is not a problem I will make a PR so you can check how it looks then :)

**Comment by okonet** [comment]
@d-ivashchuk are you still working on this? I didn't see any PRs coming from you.

**Comment by d-ivashchuk** [comment]
@okonet sure, I’ve made a PR day ago 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by okonet** [comment]
Ah I see it now. A reference to this issue would be great...

**Comment by msirocki** [comment]
+1
