### ISSUE TITLE
Bug: Instagram Web View (Browser) at iOS trigger a page reload

### ISSUE THREAD

**Issue by fabian-hiller** [react-dropzone/react-dropzone#665]
Use **react-dropzone** (v.5.1.0) directly through **Instagram's internal browser on an iPhone**, trigger a **page reload**. This reloads the entire react app and makes uploading a file impossible.

By reloading the page, the memory of the react app is reset, which means that the file/s added via react-dropzone can not be processed.

In common browsers such as Chrome or Firefox, the problem does not occur.

**Steps to reproduce:**
1. Open Instagram on an iPhone and send somebody the following link: https://react-dropzone.js.org/
2. Click on the link you sent before -> Instagram open the website via the internal browser
3. Now scroll down on the website to the first example and upload a file -> react-dropzone trigger a page reload

We tested the "Steps to reproduce" with an iPhone 7 (iOS 11.4.1)

I hope there is a way to prevent the page reload.
If you need more information, just ask.

**Comment by rolandjitsu** [comment]
@fabian-hiller I just tested this on Android, seems to work just fine (no view reload).

I think this is an issue with the iOS [web view](https://developer.apple.com/design/human-interface-guidelines/ios/views/web-views/) or the way that the instagram app handles it.

I'm afraid that there isn't much we can do from our side. The logic we have in place should already prevent the default behaviour (see [src/index.js#L177](https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L177)).

If you want to help and illustrate the issue, you could try setting up a repo with a simple iOS app with a webview and load the react-dropzone page and check if the same happens there.
