### ISSUE TITLE
Multiple Dropzone components in same page is not working

### ISSUE THREAD

**Issue by shashanksheela** [react-dropzone/react-dropzone#666]
I have 2 dropzone components on the same page. The first one is working fine but the one which is loaded after the first is not able to accept any file(onDrop,onDropAccepted functions are not triggered).Kindly help

**Comment by theCuriousOne** [comment]
Hi @shashanksheela 
I am using 2 dropzones and both are working ok:

 <Dropzone onDrop={(file: any) => this.handleFileSelect('content1', file)} name="content1" className="dropzones" multiple={false} accept={allowedExtensions}>
                                            {contentChild1}
                                        </Dropzone>
                                        <Dropzone onDrop={(file: any) => this.handleFileSelect('content2', file)} name="content2" className="dropzones" multiple={false} accept={allowedExtensions}>
                                            {contentChild2}
                                        </Dropzone>

Maybe you are missing the "name" attributes?

If you share some code it would be more useful :)

**Comment by rkmarks** [comment]
closing this for now as I can confirm the same works. If this continues to be an issue please reopen this issue
