### ISSUE TITLE
rejectStyle prop doesn't work in Safari

### ISSUE THREAD

**Issue by sbaggott** [react-dropzone/react-dropzone#668]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
In Safari, rejectStyle is not applied to Dropzone component.

**If the current behavior is a bug, please provide the steps to reproduce.**
Very easy to reproduce:
1. Open the [3rd example in the documentation page](https://react-dropzone.js.org/#accepting-specific-file-types) in Safari
2. Drag any file that's not a png or jpg over the dropzone.

**What is the expected behavior?**
The outline should turn red.

**What is the actual behavior**
The outline turns green. In Chrome or Firefox, the outline turns red as expected.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Browser: Safari 11.1.2
OS: Mac OS 10.11.6
Dropzone version: 5.1.1

**Comment by rolandjitsu** [comment]
@sbaggott this is more of a browser limitation today. Not all browsers (including Safari) apply the [spec](https://html.spec.whatwg.org/multipage/dnd.html), hence the problem you're experiencing.

It seems that in Safari, there is no way to get the files or items (from [DataTransfer](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer)) during the `dragenter`, `dragleave` and `dragover` events, therefore, we cannot apply any styling correctly.

Though, no accept/reject styles should be applied at all. I've just tested in Safari 12 on macOS and I can confirm that this is not the case and it seems to be a bug.

I'm working on a fix for displaying no accept/reject style in Safari.
