### ISSUE TITLE
bug: Rejectstyle overwrites activeStyle even when the file is acceptable

### ISSUE THREAD

**Issue by carlosjunod** [react-dropzone/react-dropzone#670]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Dropzone is displaying the the rejectstyle when the file is acceptable

**If the current behavior is a bug, please provide the steps to reproduce.**
1.  open de link [https://codesandbox.io/s/ryl9kr4z5o](url)
1. drag an drop a jpg file
1. it will display Rejectstyle style (it should't display it)

**What is the expected behavior?**
the activeStyle should be visible instead of the rejectStyle

**Operating System and react-dropzone version.**
Operating system OS X 10.12.6
Javascript enabled Yes
Cookies enabled Yes
Flash version Not installed
Java version Not installed
Websockets supported Yes
Browser size 1905 x 983
Screen size 1920 x 1080
Color depth 24 bit

react-dropzone 5.1.1
react: 16.4.2

**Comment by rolandjitsu** [comment]
@carlosjunod please read the [browser limitations](https://react-dropzone.js.org/#accepting-specific-file-types) section. And see [ryj9lmz27q](https://codesandbox.io/s/ryj9lmz27q) to illustrate the workaround.
