### ISSUE TITLE
Demos?

### ISSUE THREAD

**Issue by chobo2** [react-dropzone/react-dropzone#672]
Hi

it would be great if there was some live demos of what this plugin can and cannot do.

**Comment by rkmarks** [comment]
@chobo2 the main page https://react-dropzone.js.org has demoable examples of what the component can do. Not sure how to demo what it cannot do but open to suggestions to what can be changed from the README to help with that :)

**Comment by chobo2** [comment]
Ah, ic they are scattered part of the documentation thought they where more like static representations.
