### ISSUE TITLE
Couple Questions (Also possible bug in demo version)

### ISSUE THREAD

**Issue by chobo2** [react-dropzone/react-dropzone#674]
Hi 

got a couple questions.

1.  There seems to be no max limit property(I saw a feature request on this). Can this plugin handle say like 500+ items dropped. It seems like I control how to send them to the server so I could send them individually or batches I guess.

2. Does this plugin work with IE 11? It seems like dragging and dropping folders does not. but the rest seems to work.

3. " On most recent browsers versions, the files given by onDrop won't have properties path or fullPath, see this SO question and this issue. If you want to access file content you have to use the FileReader API."

I am a little bit confused, as when I was trying the demos(I do see a folder demo but it does not seem to work... I am also unclear if this is the right 3rd party plugin https://www.npmjs.com/package/html5-file-selector) I thought it was extracting the files out of the folder but now it just seems to not extract anything out of the folder.

I sort of want both, I want the folder name but I also want all pictures in the folder to be extracted out.

When I try to use the sampel folder drag demo code on my project I get
```

Failed to generate preview for file {fileObject: File(137430), fullPath: "/New folder (2)/1.jpeg", lastModified: 1538504216353, lastModifiedDate: Tue Oct 02 2018 11:16:56 GMT-0700 (Pacific Daylight Time), name: "1.jpeg", …} TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at index.js:246
    at Array.forEach (<anonymous>)
    at index.js:243
```

**Comment by rolandjitsu** [comment]
@chobo2 to answer your questions:

1. If you're referring to a limit on how many files can be dropped, there isn't such a feature (see [proptypes](https://react-dropzone.js.org/#proptypes) for all available options). This lib does not read the files, so theoretically it should be ok to drop many files, but it's the user's responsibility to batch process the files.
2. As far as I know, folder API is only available in Firefox and Chrome (through a plugin, not baked into this lib) and it's a [draft](https://developer.mozilla.org/en-US/docs/Web/API/FileSystem#Specifications)
3. I don't follow what you're asking 😕 

For folder support, you need to use [file-selector](https://www.npmjs.com/package/file-selector) now. See [dropzone-for-folders](https://react-dropzone.js.org/#dropzone-for-folders) section, should be working just fine in Chrome.

What you get in the drop callback is a list of [File](https://developer.mozilla.org/en-US/docs/Web/API/File) objects with an additional property `{path}` which is populated with the full path in case of a file that has been inside a folder.

I'm closing this now. Reopen if you think you found some issues.
