### ISSUE TITLE
onDragEnter isn't triggered when drag a file 

### ISSUE THREAD

**Issue by jare-talend** [react-dropzone/react-dropzone#676]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

1. Go the demo page https://react-dropzone.js.org/#full-screen-dropzone
2. Start to drag a file from your file system on the dropzone
![react-dropzone](https://user-images.githubusercontent.com/20772261/46402998-91cfa780-c701-11e8-9f91-15bb87a2c6c4.gif)

**What is the expected behavior?**

No message "Drop files.."

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

Since https://github.com/react-dropzone/react-dropzone/pull/619, the onDragEnter isn't more triggered.

tested on chrome 69 & firefox 62 (Ubuntu 18.04)

**Comment by rolandjitsu** [comment]
This should have been fixed with https://github.com/react-dropzone/react-dropzone/pull/678.
