### ISSUE TITLE
onDragEnter and onDragLeave does not get called

### ISSUE THREAD

**Issue by christiannwamba** [react-dropzone/react-dropzone#685]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

The `onDragEnter` and `onDragLeave` methods do not get called but when you use the event on a parent [primitive element](https://github.com/react-dropzone/react-dropzone/issues/140#issuecomment-190534399) (eg `div`), it works.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. The [fullscreen example](https://react-dropzone.js.org/#full-screen-dropzone) on the website

**What is the expected behavior?**
The events should be called when entering or leaving a dropzone.

**If this is a feature request, what is motivation or use case for changing the behavior?**
No, I think it's more of a bug.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

I have only tested on the latest version of Chrome and using a Mac OS. I am also using the latest version of dropzone (v6.0.2)

**Comment by okonet** [comment]
Confirming. Can you please provide a fix for this?

**Comment by rolandjitsu** [comment]
I've tested the fullscreen example in Chrome `70.0.3538.54` on macOS and the events are triggered. This was an issue before https://github.com/react-dropzone/react-dropzone/pull/678 was merged and released, I don't think it's an issue anymore.

I'm closing the issue. @christiannwamba feel free to reopen and provide a reproducible example if you think this is still an issue.
