### ISSUE TITLE
event.stopPropagation in custom event handlers doesn't work

### ISSUE THREAD

**Issue by sumthief** [react-dropzone/react-dropzone#686]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
If you have Dropzone which nested into other Dropzone then when you'll try to upload file to the nested dropzone you'll also get this file upload to external Dropzone. It should be handled via `event.stopPropagation` in then nested Dropzone's onDrop handler. But `event.stopPropagation` doesn't prevent propagation of event.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. I made a simple demo - you can check it here (https://codepen.io/sumthief/pen/qJqPWO). When you'll upload to parent area - it'll console log 'parent'. But when you'll upload to child area it'll console log both 'children' and 'parent'. And it's not correct behavior because of `stopPropagation` should prevent event propagation.

**What is the expected behavior?**
`event.stopPropagation` should stop propagation of the event. Looks like it was broken in https://github.com/react-dropzone/react-dropzone/pull/616 when invocations of custom handlers were wrapped in `Promise` (looks like it's too late for stopPropagation invocation). 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Ubuntu 18.04.1 LTS, Chrome 69.0.3497.100, react-dropzone 5.1.0

**Comment by sumthief** [comment]
I think there are 2 ways to solve this:
1) We can do force `event.stopPropagation` in all react-dropzone's handlers.
2) We can remove `Promise` to make possible `event.stopPropagation` from custom handlers. But this can broke compatibility with external plugins such as https://github.com/quarklemotion/html5-file-selector.

**Comment by sumthief** [comment]
Also I can prepare MR but I need advice which way we should implement. I prefer the first way because I think that each Dropzone should have atomic logic and don't impact on other Dropzones but I can be wrong.

**Comment by okonet** [comment]
We can't remove things like Promise since it's going to break other features. First way sounds legit unless it's going to break some other implementation. 

We should call `event.persist()` and pass this instance to callbacks. This should allow calling whatever you want on it. 

Please create a PR!

**Comment by sumthief** [comment]
I've checked `onDrop` handler and it's already contains `event.persist()` but it doesn't work.

As you know React uses custom event dispatching system (see `executeDispatchesInOrder` in https://github.com/facebook/react/blob/master/packages/events/EventPluginUtils.js). And it handles events which have stopped propagation. So it should handle our event correctly. But I've set debugger in react-dropzone's `onDrop` handler and also set debugger in my custom handler. And I got this chain:
1. debugger in react-dropzone's `onDrop` for child dropzone
2. debugger in react-dropzone's `onDrop` for parent dropzone
3. debugger in custom handler

Looks like Promise just resolves after second dispatch was invoked.

So if we can't remove Promise in handlers then maybe we can introduce new prop (by default it'll be set to `false`) which will conditionally invoke `evt.stopPropagation` in all handlers? Or maybe I'm thinking wrong and there is other solution?

**Comment by okonet** [comment]
I believe there should be a better solution. Let’s start with finding the root cause. I think that persist should work, correct? Let’s find out why it doesn’t.

**Comment by sumthief** [comment]
I've mistaked in previous message: persist works fine.

I'll try to explain my vision of problem one more time. Usage Promise causes that code which located in `.then` pushed to event loop but not to call stack. You can check it by evaluating this code in console:
```javascript
const logNum = num => {
  console.log(`sync log: ${num}`);
  Promise.resolve(true).then(() => console.log(`async log: ${num}`));
};

for (let i = 0; i < 3; i++) {
  logNum(i);
}
```
In my previous message I've add link on React event`s subsystem which dispatch event for all registered targets in cycle. So I want to say that usage Promise in react-dropzone event listeners brokes `event.stopPropagation` because it violate order of callbacks execution.

![_021](https://user-images.githubusercontent.com/12448244/46784133-2451f580-cd57-11e8-9ff1-711148989dc8.png)

Hope it helps to clarify it.

**Comment by rolandjitsu** [comment]
@sumthief You're right, event propagation will not work as expected due to the async logic within each of our internal callback fns.

Removing the use of promises is not an option at the moment as it is the only way to allow 3rd party plugins to asynchronously read through a dir tree.

At the moment the easiest way to fix this is to do what you described, use `stopPropagation()` internally (maybe enabled via a property flag).

**Comment by rolandjitsu** [comment]
@sumthief would you give https://github.com/react-dropzone/react-dropzone/pull/701 a try and let me know if it fixes the issue you describe? If you checkout that PR and run the examples, there is already one illustrating nested dropzones where the child stops event propagation to the parent.

**Comment by sumthief** [comment]
@rolandjitsu I've started preparing PR but you've made it faster :1st_place_medal: 

Yeah, it looks great and fixes my issue

**Comment by rolandjitsu** [comment]
@sumthief sorry about that 🙄 Glad it helps though.

**Comment by claudiuchetan** [comment]
Unfortunately, this change (checking for isPropagationStopped) causes some issues in other cases.
I tried to integrate react-dropzone in a Dialog component from https://developer.microsoft.com/en-us/fabric#/components/dialog . 
Both DragOver and Drop events are being stopped by this isPropagationStopped check.

**Comment by rolandjitsu** [comment]
@claudiuchetan could you open a new issue and provide some reproducible example?
