### ISSUE TITLE
Can we make the lib flexible by allowing to override the default inline styles?

### ISSUE THREAD

**Issue by aruprakshit** [react-dropzone/react-dropzone#687]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [X] I want to propose a feature

**What is the current behavior?**

If I apply inline style, then default style is not applied anymore.

**If the current behavior is a bug, please provide the steps to reproduce.**

1.
1.
1.

**What is the expected behavior?**

I am looking for a feature where custom inline styles can be merged with the default styles if porvided.

**If this is a feature request, what is motivation or use case for changing the behavior?**

The [demo](https://codesandbox.io/s/q93o9wxpk6) app is created. When I apply the custom inline style, the default style is removed. What I am looking for just to override some default styles as per my need. For this case, I want the dropzone to be full width of the parent container. 

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

"react-dropzone": "^6.0.2",
OS: macOS 10.13.6

**Comment by okonet** [comment]
It's a duplicate for the ongoing work #468
