### ISSUE TITLE
React Dropzone is broken in version 6.2.0 with typescript

### ISSUE THREAD

**Issue by pantharshit00** [react-dropzone/react-dropzone#696]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
React Dropzone is broken in version 6.2.0 with typescript. It works fine with 6.1.3
I see some commits related to this, maybe you should have used the namespace instead of the default export?

Getting this error while using it 

![image](https://user-images.githubusercontent.com/22195362/46908123-9c791080-cf3b-11e8-8f17-4fe5dff456c8.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a new app using create react app typescript
2. Install dropzone and add it somewhere
3. start the app

**What is the expected behavior?**
It should work!

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Ubuntu 18.4 LTS
react-dropzone 6.2.0

**Comment by rolandjitsu** [comment]
@pantharshit00 I think you need to enable the `allowSyntheticDefaultImports` in your tsconfig. But maybe we should keep the previous import style for backwards compatibility.

**Comment by pantharshit00** [comment]
I did that just now, but many people use create-react-app-ts and it does add that option by default so you may get reports like this now and then so I'd recommend you to make it backward compatible and break it in v2
