### ISSUE TITLE
Remove the need for promises

### ISSUE THREAD

**Issue by hornta** [react-dropzone/react-dropzone#703]
https://github.com/react-dropzone/react-dropzone/blob/fd65863a0539c10cf3decd2b59b32c67e517dea0/src/index.js#L105

I don't think this helper should depend on Promises because not everyone is using promises and want to polyfill promises. Is there a reason Promises are used?

**Comment by rolandjitsu** [comment]
@hornta yes, there is a reason.

It is used for the plugin API which allows users to provide their own impl. of getting the files from the drag event (and some APIs are async, see [`.file()`](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileEntry/file)).

But it's there mainly to support folders, see [`.readEntries()`](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryReader/readEntries) and the [file-selector](https://github.com/react-dropzone/file-selector) plugin.

I think that promises are [widely supported](https://caniuse.com/#feat=promises) today and there are very few exceptions where they're not supported.

With that in mind, we cannot simply remove the usage of promises. Though, it might be a good idea to at least mention this in the docs.

There is a pending [PR](https://github.com/react-dropzone/react-dropzone/pull/688) which addresses the browser support, perhaps @rkmarks could also mention the APIs that we use and what would need to be polyfilled.

**Comment by rkmarks** [comment]
yeah i can see about adding that to my PR for updating docs.
