### ISSUE TITLE
Share example of file preview after dropping ?

### ISSUE THREAD

**Issue by DougWoodCDS** [react-dropzone/react-dropzone#704]
Hi I am just wondering if anyone could show me a simple example of how to show a preview of an image after it had been dropped onto dropzone. I am assuming one needs to use the 'FileReader' object to accomplish this ?
thanks for any help !

**Comment by DougWoodCDS** [comment]
never mind. I discovered the 'preview' property. wasn't mentioned in the docs.

**Comment by rolandjitsu** [comment]
@DougWoodCDS glad you managed to find it. But true, there is no example of showing a preview. Perhaps it might be a good idea to add one or mention this.
