### ISSUE TITLE
refactor: remove {preview} from File

### ISSUE THREAD

**Issue by rolandjitsu** [react-dropzone/react-dropzone#705]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [x] I want to propose a feature

**What is the current behavior?**
Currently, we create a `{preview}` property on the File object (unless the user disables that). This can lead to memory leaks if users do not read through the docs carefully.

**If the current behavior is a bug, please provide the steps to reproduce.**

1.
1.
1.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

I think it would be a good idea to remove this property and let the user handle it (it's a matter of just doing `URL.createObjectURL(file)`) for a few reasons:
- users that do not know that `{disablePreview}` has to be added to the dropzone in order to disable preview generation will not end up with mem. leaks
- avoid confusion when preview might mean to a user that we show an actual preview of the file (image, pdf, etc.)
- users have control over creating/revoking the data uris, whereas we do not control the latter

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

This would be a breaking change for users that use this feature.

@okonet what is your opinion on this?

**Comment by okonet** [comment]
Yes, we should remove it. I proposed to use a plugin (since we have the plugin architecture now) that we'd ship as the part of the package to support this.
