### ISSUE TITLE
Files don't load first time when a custom label is added

### ISSUE THREAD

**Issue by supertopoz** [react-dropzone/react-dropzone#706]
- [x] I found a bug

**What is the current behavior?**
When clicking on the dropzone area to up a file, the file picker opens. After selecting the file the first time nothing is loaded into the browser. Only when doing this operation again does the file get loaded into the browser. 

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Add dropzone component as described. 
2. Add custom label as below.

```
      <Wrapper>            
        <Dropzone 
          inputProps={{'id':"dropzone"}} 
          style={dropzone} 
          onDrop={this.handleOnDrop.bind(this)} 
          accept='image/*' 
          maxSize={5000000}>
          <label htmlFor="dropzone" >
            <Span><i class="material-icons">add</i></Span>
          </label>
        </Dropzone>
      </Wrapper>
```

3. Try to upload a file. 

**What is the expected behavior?**
Files should load first time. But only when the dropzone is clicked a second time, and the file is selected a second time is the file loaded. 

Please note: 
I'd like to include a custom label (code above) as this allows my application to pass accessibility testing. Please can I suggest that the "label" become a parameter in the main code rather than having to add a funky "HTMLfor" option. :)

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Chrome 70, Windows 10, dropzone 6.2.4

**Comment by rolandjitsu** [comment]
@supertopoz I have just tried the basic example from our docs page and I cannot reproduce the behaviour you're describing.

As for the label, we're currently working on https://github.com/react-dropzone/react-dropzone/pull/468 which changes the way the dropzone is used and will consequently allow users to have their own input with whatever else they need.

**Comment by ryanjyost** [comment]
I also experienced @supertopoz's issue outline above, using v8.0.0 and latest v8.0.3.

It seems to only occur if clicking a button in the `Dropzone` that triggers the `open` method, and `disabledClick=false`. 

So one should set `disableClick=true` if using a button to open the file dialog, it seems.

Not sure if it's good UX or worth supporting the case of being able to click either a button in the Dropzone or the Dropzone area itself?
