### ISSUE TITLE
Not to show other file types as valid drop targets

### ISSUE THREAD

**Issue by Miteshdv** [react-dropzone/react-dropzone#709]
**Do you want to request a *feature* or report a *bug*?**

- [x] I want to propose a feature

**What is the current behavior?**
When we try to drop invalid file type It shows a generic file and “+ Copy”, but then we do not take action as we only use accepted file

**What is the expected behavior?**
A different cursor when single file is selected and it is not a valid drop

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

Chrome 67
React-dropzone version  4.2.8

**Comment by rolandjitsu** [comment]
@Miteshdv changing the cursor based on whether a file is accepted or not would confuse users, because you could have many files amongst which just one is rejected. Then you also have clients that do not use a pointer (touch devices).

I think as it is right now is just fine.
