### ISSUE TITLE
Not Working with react-dnd elements inside dropzone

### ISSUE THREAD

**Issue by stealth86** [react-dropzone/react-dropzone#710]
Adding an Element inside <Dropzone> </Dropzone> that has react-dnd in it does not allow dropping file into the zone.

**Comment by rolandjitsu** [comment]
As I mentioned in https://github.com/react-dropzone/react-dropzone/issues/649, if react-dnd stops event propagation on the drag event, the dropzone will not react.

I'd avoid using these 2 libs together as you can achieve more or less the same functionality with react-dnd as well.

But it would also be helpful if you could provide a code sample on codepen or somewhere which illustrates this issue.
