### ISSUE TITLE
Invalid `previewsContainer` option provided.

### ISSUE THREAD

**Issue by leenyburger** [react-dropzone/react-dropzone#711]
**Do you want to request a *feature* or report a *bug*?**

- [X] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
When adding the preview functionality back in using the DropzoneWithPreview sample code `preview: URL.createObjectURL(file)` the following error is generated: `Uncaught Error: Invalid 
 previewsContainer option provided. Please provide a CSS selector or a plain HTML element.`
**If the current behavior is a bug, please provide the steps to reproduce.**

1. User DropzoneWithPreview example code
2. Run
3. See error 

**What is the expected behavior?**
No error 
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by rolandjitsu** [comment]
@leenyburger Could you share an example? The previews example at [react-dropzone.js.org](https://react-dropzone.js.org) seems to work just fine.

Are you actually doing a copy paste of the example and running in your env?

**Comment by leenyburger** [comment]
@rolandjitsu My mistake, I am transition to React and was still running Dropzone.js which was causing my error.
