### ISSUE TITLE
Upload a file by fetching

### ISSUE THREAD

**Issue by susuwatari2** [react-dropzone/react-dropzone#715]
**Do you want to request a *feature* or report a *bug*?**

- [v ] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
The onDrop method, provides me with an array of Files which I cannot send to a web api and without using any http/ajax libraries

**If the current behavior is a bug, please provide the steps to reproduce.**

fetch (endpoint, options)
method: 'POST'
What should my options for header and body be?

**What is the expected behavior?**
If I am uploading a file, I should return file[0] in the body.
If I am uploading an excel file, what is the type or content-type?

**Comment by rolandjitsu** [comment]
@susuwatari2 for these sort of questions, I would go to stackoverflow and ask there for help. This lib does not handle any parsing or requests to a server. You get the list of files, it's up to you to handle the rest according to your needs.

Perhaps [this](https://stackoverflow.com/questions/36067767/how-do-i-upload-a-file-with-the-js-fetch-api) is a good starting point.
