### ISSUE TITLE
Documentation example for adding preview to File object does not work.

### ISSUE THREAD

**Issue by seanpascoe** [react-dropzone/react-dropzone#716]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Documentation example for adding preview to File object does not work.
**If the current behavior is a bug, please provide the steps to reproduce.**

1. Follow documentation for adding a preview property to File object. 
2. Documentation uses es6 spread operator which doesn't work for File object's own properties, which are not enumerable.
3. Resultant object has only the preview property, none of the File properties.

**What is the expected behavior?**
The resultant object should have the preview property AS WELL AS all the File properties.
**If this is a feature request, what is motivation or use case for changing the behavior?**
n/a
**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Current Example:
```
  onDrop(files) {
    this.setState({
      files: files.map(file => ({
        ...file,
        preview: URL.createObjectURL(file)
      }))
    });
  }
```
**Fix:
Use Object.assign instead:
```
  onDrop(files) {
    this.setState({
      files: files.map(file => Object.assign(file, {preview: URL.createObjectURL(file)}))
    });
  }
```

**Comment by seanpascoe** [comment]
While you're at it, why not just use a forEach for the cWU?
current:
```
  componentWillUnmount() {
    // Make sure to revoke the data uris to avoid memory leaks
    const {files} = this.state;
    for (let i = files.length; i >= 0; i--) {
      const file = files[0];
      URL.revokeObjectURL(file.preview);
    }
  }
```

easier to read:
```
  componentWillUnmount() {
    // Make sure to revoke the data uris to avoid memory leaks
    this.state.files.forEach(f => URL.revokeObjectURL(f.preview))
  }
```

**Comment by rolandjitsu** [comment]
@seanpascoe feel free to make a PR.

**Comment by seanpascoe** [comment]
@rolandjitsu didn't see the examples in the readme, but just found the examples folder. Sorry, yea I'll do that.
