### ISSUE TITLE
Documentation: Browser limitations example isDragActive -> isDragAccepted 

### ISSUE THREAD

**Issue by mike1808** [react-dropzone/react-dropzone#718]
I didn't find repo with the documentation site so I'm creating an issue. I think, in the **Browser limitations** sector in the browser in the examples `isDragActive` should be replaced with `isDragAccepted` because currently it doesn't work. If you try to drag a correct file it will show accepted style (green border) however it will render the wrong text content. Switching to `isDragAccepted` can make it work.

**Comment by mike1808** [comment]
@rolandjitsu I didn't find docs in the repo to make the change.

**Comment by rolandjitsu** [comment]
@mike1808 see [examples](https://github.com/react-dropzone/react-dropzone/tree/master/examples).
