### ISSUE TITLE
Dropzone modal over an iframe won't work

### ISSUE THREAD

**Issue by justincrich** [react-dropzone/react-dropzone#720]
- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
I have a modal that's over an iframe video that has a dropzone that helps me upload documents. See [example][1]. The dropzone works perfectly when it is not overlaying the iframe. 

I'm wondering what needs to happen for the corresponding browser events to correctly register on the general parent page document rather than the iframe document? Or if any of you have any ideas on how to make this work I'd love your assistance. Thanks for your help.

  [1]: https://codesandbox.io/s/pjz2xxlkv7

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Drag an image over the blue zone that overlays the iframe video ... the zone won't turn red
1. Drag an image over the blue zone that doesn't overlay the iframe video ... the zone will turn red
1. Click hide iframe video and drop the file anywhere on the zone and it will turn red

**What is the expected behavior?**
The overlapping zone should respond to hovers and drops if you drop anywhere on the zone's area.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Dependency Versions
    "react": "^16.7.0-alpha.2",
    "react-dom": "^16.7.0-alpha.2",
    "react-dropzone": "7.0.1",
Operating system OS X 10.13.6
Javascript enabled Yes
Cookies enabled Yes
Websockets supported Yes
Browser size 1283 x 917
Screen size 1920 x 1200

**Comment by rolandjitsu** [comment]
@justincrich I think the events are registered, it's probably something else going on there. Most likely some layout issue (something in the iframe is overlapping your DZ element).

I'll take a look and see if I can help, but this is not really a dropzone issue.

**Comment by annezhou920** [comment]
@justincrich to get around this, i disabled the iframe with `pointer-events: none` styling when the dropzone modal is open. this prevents the iframe from consuming any drag/drop events.
