### ISSUE TITLE
refactor: move codebase to TypeScript

### ISSUE THREAD

**Issue by rolandjitsu** [react-dropzone/react-dropzone#721]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [x] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1.
1.
1.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
We already maintain a separate set of typings, it would be better to just rewrite everything in TS to keep things DRY.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by rolandjitsu** [comment]
Still working on this 😄

**Comment by thegreatercurve** [comment]
@rolandjitsu need any help with this if you haven't already started? Been using this package a while, and keen to contribute!

**Comment by rolandjitsu** [comment]
@thegreatercurve that'd be nice. But we should move to converting the component to a functional one and use the new rect hooks API before that.

I think I will soon start working on the hooks part. After we have a PR and merge it, if you're still interested, you can definitely help out with moving to TS.

**Comment by thegreatercurve** [comment]
@rolandjitsu sounds like a plan. Likewise, let me know if you need a hand with that or any other issue. Happy to help out.

**Comment by rolandjitsu** [comment]
@thegreatercurve maybe you could help with https://github.com/react-dropzone/react-dropzone/pull/688 meanwhile.

**Comment by thegreatercurve** [comment]
@rolandjitsu Apologies, I completely missed the notification for that last message. I've got some time this weekend though, so I can take a look at [#688](https://github.com/react-dropzone/react-dropzone/pull/688) then.
