### ISSUE TITLE
feat: use React hooks

### ISSUE THREAD

**Issue by rolandjitsu** [react-dropzone/react-dropzone#722]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [x] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1.
1.
1.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
When React officially releases [hooks](https://reactjs.org/docs/hooks-effect.html), let's switch to using a functional component and use the hooks to manage state.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by rolandjitsu** [comment]
Waiting for the official release of hooks before starting on this.

**Comment by SimenB** [comment]
Hooks have been released? https://reactjs.org/blog/2019/02/06/react-v16.8.0.html

**Comment by rolandjitsu** [comment]
Oh, that was just yesterday. I read the blog on 16.7 and they mentioned that we should not expect that the next release will have them.

I guess we can get started with this soon.
