### ISSUE TITLE
Drag & Drop While Open File Dialog Open?

### ISSUE THREAD

**Issue by chobo2** [react-dropzone/react-dropzone#723]
Hi

I am wondering what the expected behavior is if someone click in a drop zone which prompts the file dialog and then that user tries to drag in files.

From what I can tell this is valid use case but dropzone does not allow this.

**Comment by rolandjitsu** [comment]
@chobo2 please see https://github.com/react-dropzone/react-dropzone/pull/551.

**Comment by chobo2** [comment]
@rolandjitsu 

Sorry bit confused, from the issue you linked to it would seem that it was identified and fixed?

**Comment by rolandjitsu** [comment]
@chobo2 if you read one of the comments there:

```js
// The file dialog on Chrome allows users to drag files from the dialog onto
// the dropzone, causing the browser the crash when the file dialog is closed.
// A drop effect of 'none' prevents the file from being dropped
```

Meaning that we do not allow files to be dropped while you have the file dialog opened. I hope it's more clear now.

**Comment by yurykornilov** [comment]
This behavior is very confusing. Mail clients, facebook, Jira, dropzone.js don't have such problem.

**Comment by yurykornilov** [comment]
@rolandjitsu 
I'm sorry for my opinion. The file select window and a window of the file manager look the same for users. But from one I can drag and from another not.

**Comment by chobo2** [comment]
@rolandjitsu 

Yea it seems odd to me as well, but my users are trying to do this.  One pulled me over and was like "I am trying to drag and drop and it's not working".

I honestly never thought of doing it like that as I just thought it was not possible but from what seen my users do people think it should be something they can do.

**Comment by rolandjitsu** [comment]
@chobo2 I'll try to see if Chrome still crashes in this case, if not, I guess we can revert the current behaviour.

@yurykornilov no worries. I haven't used windows in quite a while, so I'm not familiar with its ux.

**Comment by rolandjitsu** [comment]
@chobo2 see https://github.com/react-dropzone/react-dropzone/pull/725, tested in latest Chrome and there seem to be no issues now. Please test it as well and let me know if you encounter any issues.

**Comment by chobo2** [comment]
@rolandjitsu 

I upgraded from react-dropzone from 7.0 to 8.0 and now it does not work

    "react-dropzone": "^8.0.1",

```
Uncaught TypeError: children is not a function
    at Dropzone.render (:8080/main.js:68141)
    at finishClassComponent (:8080/main.js:63404)
    at updateClassComponent (:8080/main.js:63366)
    at beginWork (:8080/main.js:64034)
    at performUnitOfWork (:8080/main.js:66060)
    at workLoop (:8080/main.js:66099)
    at HTMLUnknownElement.callCallback (:8080/main.js:50419)
    at Object.invokeGuardedCallbackDev (:8080/main.js:50457)
    at invokeGuardedCallback (:8080/main.js:50506)
    at replayUnitOfWork (:8080/main.js:65513)
14:59:47.002 :8080/main.js:64432 The above error occurred in the <Dropzone> component:
    in Dropzone (created by Formik)
    in div (created by Formik)
    in form
    in Unknown
    in Form (created by Formik)
    in Formik (created by PartComponent)
    in PartComponent (created by inject-PartComponent-with-domainStores-uiStores-routingStore)
    in inject-PartComponent-with-domainStores-uiStores-routingStore (created by Route)
    in Route (created by withRouter(inject-PartComponent-with-domainStores-uiStores-routingStore))
    in withRouter(inject-PartComponent-with-domainStores-uiStores-routingStore) (created by AddInventoryComponent)
    in AddInventoryComponent (created by inject-AddInventoryComponent-with-domainStores-uiStores)
    in inject-AddInventoryComponent-with-domainStores-uiStores (created by Route)
    in Route (created by withRouter(inject-AddInventoryComponent-with-domainStores-uiStores))
    in withRouter(inject-AddInventoryComponent-with-domainStores-uiStores) (created by Route)
    in Route (created by MemberAreaComponent)
    in Switch (created by MemberAreaComponent)
    in div (created by MemberAreaComponent)
    in div (created by MemberAreaComponent)
    in MemberAreaComponent (created by inject-MemberAreaComponent-with-domainStores-uiStores-routingStore)
    in inject-MemberAreaComponent-with-domainStores-uiStores-routingStore (created by Route)
    in Route (created by withRouter(inject-MemberAreaComponent-with-domainStores-uiStores-routingStore))
    in withRouter(inject-MemberAreaComponent-with-domainStores-uiStores-routingStore) (created by Route)
    in Route (created by App)
    in Switch (created by App)
    in App (created by inject-App-with-domainStores-uiStores)
    in inject-App-with-domainStores-uiStores (created by Route)
    in Route (created by withRouter(inject-App-with-domainStores-uiStores))
    in withRouter(inject-App-with-domainStores-uiStores)
    in Router
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

**Comment by rolandjitsu** [comment]
@chobo2 it seems like you're experiencing the same as https://github.com/react-dropzone/react-dropzone/issues/727, with `8.0.0` you need to provide a fn as children. Please refer to the docs for examples.

**Comment by chobo2** [comment]
@rolandjitsu 

Yep, that was my problem, I guess it was changed how that area works from 7 and 8.

The drag and drop from file dialog now work. 

However drag and drop folders no longer work for me, I am not sure if this has changed as well as in 7.0 and can't really verify as the example doc one does not seem to work.

**Comment by rolandjitsu** [comment]
@chobo2 please see the [dropzone-for-folders](https://react-dropzone.js.org/#dropzone-for-folders) example.

**Comment by chobo2** [comment]
@rolandjitsu 

Yep that is the example that I checked out and when I try to drag a folder into that area. Nothing happens.

**Comment by rolandjitsu** [comment]
@chobo2 I can confirm it works in Chrome, latest version. You might be dropping outside the dropzone area (which in the example is just above the text).

**Comment by chobo2** [comment]
@rolandjitsu 

Ok, yea I see it is working just seems I got to be very precise in the example where I drop.

I will look at the example and change my code accordingly.

Thanks!
