### ISSUE TITLE
Migration notes from 7 -> 8 ?

### ISSUE THREAD

**Issue by b0gd4n** [react-dropzone/react-dropzone#724]
Where can I find the migration notes from moving to v8?
Updated the package from v7.0.1 to v8.0.0 and now my app brakes:

`index.js:1452 Warning: Failed prop type: Invalid prop `children` of type `object` supplied to `Dropzone`, expected `function`.`

`index.js:482 Uncaught TypeError: children is not a function
    at Dropzone.render (index.js:482)`

**Comment by rolandjitsu** [comment]
@b0gd4n if you check the [v8.0.0](https://github.com/react-dropzone/react-dropzone/releases/tag/v8.0.0) release, you'll see a note on the breaking change.

Furthermore, all examples have been updated to reflect the new changes.
