### ISSUE TITLE
Ability to remove dropped file

### ISSUE THREAD

**Issue by b0gd4n** [react-dropzone/react-dropzone#728]
I have the example with previews, and was wondering if there's a way to click on one of the previews to remove the file?

**Comment by rolandjitsu** [comment]
@b0gd4n I'd refer to stackoverflow for such questions. But in any case, you control the state of your own component, so you can easily remove any files. So in the example with previews, you'd have a method similar to the following:
```js
class DropzoneWithPreview extends React.Component {
...
// call this method on some event where you render the thumbnails
removeFile(file) {
  this.setState(state => {
    const index = state.files.indexOf(file);
    const files = state.files.slice(0);
    files.splice(index, 1);
    return {files}; 
  });
}
...
```
