### ISSUE TITLE
What is the problem !

### ISSUE THREAD

**Issue by AbdelhafidFutureTrendz** [react-dropzone/react-dropzone#732]
<img width="1098" alt="screen shot 2018-12-18 at 12 06 11 am" src="https://user-images.githubusercontent.com/36513569/50123495-da0a5a80-0258-11e9-9279-2c4392247775.png">

**Comment by rolandjitsu** [comment]
@AbdelhafidFutureTrendz this is not related to react-dropzone. Please refer to stackoverflow for such questions.
