### ISSUE TITLE
FLV is not considered as Video file

### ISSUE THREAD

**Issue by hirokimoto** [react-dropzone/react-dropzone#734]
This library does not consider FLV file as Video files.

**Comment by rolandjitsu** [comment]
You'd have to be more descriptive with this. This lib only checks the ext. or mime type as given by the `accept` property and rejects/accepts the files based on that.

**Comment by hirokimoto** [comment]
Thanks for your reply @rolandjitsu 
Let me elaborate the issue that I have experienced.

When you add **accept="video/*"**, I think all types of video files should be acceptable.
But it does not accept FLV extension's video when I put **accept="video/*"**.

**Comment by rolandjitsu** [comment]
@hirokimoto please see [attr-accept](https://github.com/okonet/attr-accept) and open an issue there as this lib uses it internally to validate the mime type or file ext.
