### ISSUE TITLE
onDropReject() callback specify reason of rejection

### ISSUE THREAD

**Issue by danielesalvatore** [react-dropzone/react-dropzone#735]
Dear all, 

thank you very much for you excellent work and making this project open source. 
I write you to propose a possible enhancement on the onDropReject() callback. 

I saw that the onDropReject() callback has two parameters:
- the file(s) you dropped
- the Proxy obj

<img width="1114" alt="screenshot 2018-12-28 at 16 59 43" src="https://user-images.githubusercontent.com/6150475/50521355-923fca80-0ac5-11e9-851e-16e0daf7ac39.png">

I would kindly ask you if it makes sense to you to add information on the rejection reason (or if I can already find the info somewhere else).
In my case, I simply call an alert to give the user a generic "Invalid file" message, but it would be nice to give the user the reason why a file was rejected. 

If the dropzone is part of a form, of course a proper validation can be performed at the form level too, but the user will drop a file and it won't be added to the dropzone. 

Thank you in advance

**Comment by rolandjitsu** [comment]
@danielesalvatore the `onDropRejected` cb is only called when one of the files does not meet the `accept` property requirements (see [src/index.js#L189](https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L189)).

**Comment by danielesalvatore** [comment]
@rolandjitsu Thank you very much for you reply!
