### ISSUE TITLE
Make it compatible with React-like libs

### ISSUE THREAD

**Issue by jschill** [react-dropzone/react-dropzone#736]
Latest versions of react-dropzone introduce the use of event.isDefaultPrevented() which is a jquery-specific[1] function and should be replaced with event.defaultPrevented[2].

[1] https://api.jquery.com/event.isDefaultPrevented/
[2] https://developer.mozilla.org/en-US/docs/Web/API/Event/defaultPrevented

**Comment by jschill** [comment]
isPropagationStopped is also in the code
https://github.com/react-dropzone/react-dropzone/blob/d4ee298e119c11f2087859dece66cd43642a6e15/src/index.js#L76

**Comment by jschill** [comment]
After some reading I see React has its own implementation[1] of isDefaultPrevented/isPropagationStopped. It broke on my machine since I'm using Preact, that doesn't have those fancy props. I will have to check if isDefaultPrevented/isPropagationStopped exists and fall back on defaultPrevented vs cancelBubble.

[1] https://reactjs.org/docs/events.html

**Comment by rxmarbles** [comment]
@jschill can you provide a working example of it breaking in `React-like libs`? curious of your use case. Haven't seen this breaking in other libs.

**Comment by jschill** [comment]
@rxmarbles My use case is Preact + react-dropzone. react-dropzone use props specific to react's synthetic events.

<img width="631" alt="skarmklipp 2019-01-14 22 49 33" src="https://user-images.githubusercontent.com/224493/51143476-ef21db80-184e-11e9-83d9-a09237ce30db.png">

I've fixed it in a fork:
https://github.com/jschill/react-dropzone/commit/721af2cbf7356da5caf5105564c21c05ea21387d

**Comment by rolandjitsu** [comment]
@jschill would you mind making a PR for this and adding some tests?

**Comment by jschill** [comment]
Sure. Someone will have to help me out with how you write your tests though.
