### ISSUE TITLE
Reactdropzone error while using react-dropzone

### ISSUE THREAD

**Issue by ShrawanBK** [react-dropzone/react-dropzone#744]
I am trying to use react-dropzone in my project but got error that does not render the reactDropzone component. I tried this:
import ReactDropzone from 'react-dropzone';
export class BankingDetail extends React.Component {
  render() {
    return (
      <ReactDropzone
        accept="image/*"
        onDrop={()=>console.log("this.onPreviewDrop")}
      >
        Drop an image, get a preview!
      </ReactDropzone>
    );
  }
}
![error](https://user-images.githubusercontent.com/19337402/50954061-77198580-14dd-11e9-8e9c-39cb278e6ff4.png)

https://stackoverflow.com/questions/54124086/reactdropzone-error-while-using-react-dropzone

**Comment by rolandjitsu** [comment]
@ShrawanBK someone just opened a similar issue a few days ago, https://github.com/react-dropzone/react-dropzone/issues/743. With v8.0, you need to provide a fn as child.
