### ISSUE TITLE
Apollo Mutation - Pass a function to onDrop as third argument

### ISSUE THREAD

**Issue by ScottAgirs** [react-dropzone/react-dropzone#750]
Trying to pass a function ( `newFunction();` ) as third variable in onDrop: 

```
     <Dropzone
        ..
        onDrop={() => this.onDrop(acceptedFiles, rejectedFiles, newFunction)}
      />
```

**Why?**
Need to pass an Apollo Client Mutation to onDrop to mutate database with the acceptedFiles

**If this is a feature request, what is motivation or use case for changing the behavior?**
If this is not possible now, then not only this would enabled developers to use this with Apollo Client, but also allow for additional manipulations and make this much more flexible.

**Comment by rolandjitsu** [comment]
@ScottAgirs I'm not sure I follow what you're trying to do. The `this.onDrop()` fn that's illustrated there would be your own function, so you can pass whatever you want to it.

As for the dropzone `onDrop`, the 3rd argument is the drop event, see [src/index.js#L186](https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L186)

**Comment by rolandjitsu** [comment]
@ScottAgirs I'm gonna close this issue for now. If you provide more context and an example of what you're describing, I'll be happy to reopen.

**Comment by ScottAgirs** [comment]
> @ScottAgirs I'm gonna close this issue for now. If you provide more context and an example of what you're describing, I'll be happy to reopen.

hey @rolandjitsu, thanks a lot for reply, I must have missed the reply.

I figured it out, the issue turned out to be not with React-Dropzone, but with my basic JavaScript knowledge, hah. 

I needed to declare the props in the onDrop() function, before actually passing and using them inside the onDrop() and it looks like this (in case someone else stumbles upon this:

```
onDrop = async (acceptedFiles, rejectedFiles, newFunction) => {
    // do stuff with your files and the newFunction
    ..
    newFunction(acceptedFiles, rejectedFiles)
    .. 
  };

..

     <Dropzone
                  onDrop={(acceptedFiles, rejectedFiles) =>          
                    this.onDrop(acceptedFiles, rejectedFiles, newFunction)
                  }
                  ..
                >
```
