### ISSUE TITLE
Fullscreen/Full frame support

### ISSUE THREAD

**Issue by leoc** [react-dropzone/react-dropzone#753]
**Do you want to request a *feature* or report a *bug*?**

Not sure, I guess both?

- [X] I found a bug
- [X] I want to propose a feature

**What is the current behavior?**

The current fullscreen option (from the docs) does not work for me. I can only drop to the dropzone.

**What is the expected behavior?**

I would have expected to be able to drop the file to any place of the document, no?

**If this is a feature request, what is motivation or use case for changing the behavior?**

I have an application with just one dropzone. The dropzone may be smallish, to avoid confusion I want to allow users to drop files anywhere in the document, but still trigger the dropzone as if the file was dragged over the dropzone.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

What do you (maintainers) think about this PR #521 ? I would gladly prepare a rebased PR and add some tests.

Thanks! :smile:

**Comment by eoghanmccarthy** [comment]
After updating to v8.0.4 this morning the fullscreeen doesn't work with me either.

```
<Dropzone
          disableClick
          onDrop={files =>
           console.log('on drop')
          }
          onDragEnter={onDragEnter}
          onDragLeave={onDragLeave}
          multiple={false}
        >
          {children}
        </Dropzone>
```

**Comment by rolandjitsu** [comment]
@eoghanmccarthy you need a render fn as child since v8. See the [docs](https://react-dropzone.js.org/#basic-example).

@leoc if you want fullscreen, just wrap the whole app in the dropzone. That should do the trick. I use it in a similar way. But it's true, the example it's misleading.

**Comment by eoghanmccarthy** [comment]
@rolandjitsu Great, thanks :)

```
const MyFullscreenDropzone = ({ children }) => {
    return (
        <Dropzone
            disableClick
            onDrop={files => console.log('on drop')}
            onDragEnter={onDragEnter}
            onDragLeave={onDragLeave}
            multiple={false}
        >
            {({ getRootProps, getInputProps }) => (
                <div {...getRootProps()}>
                    <input {...getInputProps()} hidden />
                    {children}
                </div>
            )}
        </Dropzone>
    )}
};
```

**Comment by leoc** [comment]
@rolandjitsu Thanks for your feedback! I currently use react-router to display various different nested components. I thought about adding a context that would keep the configuration of the dropzone for child components to adjust the dropzone at root level accordingly. But I have the feeling that this would clutter the code. The dropzone is only needed for one or two "pages" right now.

A `fullscreen` flag sounds nice in theory. Having the whole browser viewport as a dropzone whereas the component itself still resides in the subcomponent. I don't know.

Would you merge something like the aforementioned PR #521 if it was updated?

**Comment by rolandjitsu** [comment]
@leoc I see, I don't think that using the context API is necessary, unless your child components are deep down the DOM tree. You can pass the dropped files as props to your child components.

Event using the context API would not be so bad, if done properly, it should not clutter your code.

Furthermore, I think that binding drag events to the document would probably bring a whole lotta of trouble, especially if there are other libraries biding to the same events on the document.
It also feels odd that some child component binds events on a parent component (except some rare cases).

Therefore, I'm honestly not keen on adding such a change, but if the community feels like it is necessary, I would not oppose it.

**Comment by leoc** [comment]
Thank you for the feedback. For now I have chosen a big enough dropzone.

I will check a context solution when I have the time and add an example here.

**Comment by rolandjitsu** [comment]
Ok, I'm closing this for now.

**Comment by jlarmstrongiv** [comment]
Would love full screen dragging.  Here’s a workaround:

```js
  const [isDragging, setIsDragging] = React.useState(false);
  const dragCounter = React.useRef(0);

  const { setFile, setError, setSvg } = React.useContext(ConverterContext);

  const handleDrag = React.useCallback((event) => {
    event.preventDefault();
    event.stopPropagation();
  }, []);
  const handleDragIn = React.useCallback((event) => {
    event.preventDefault();
    event.stopPropagation();
    dragCounter.current++;
    if (event.dataTransfer.items && event.dataTransfer.items.length > 0) {
      setIsDragging(true);
    }
  }, []);
  const handleDragOut = React.useCallback((event) => {
    event.preventDefault();
    event.stopPropagation();
    dragCounter.current--;
    if (dragCounter.current > 0) return;
    setIsDragging(false);
  }, []);
  const handleDrop = React.useCallback((event) => {
    event.preventDefault();
    event.stopPropagation();
    setIsDragging(false);
    if (event.dataTransfer.files && event.dataTransfer.files.length > 0) {
      dragCounter.current = 0;
      console.log(event.dataTransfer.files);
      event.dataTransfer.clearData();
    }
  }, []);

  React.useEffect(() => {
    window.addEventListener("dragenter", handleDragIn);
    window.addEventListener("dragleave", handleDragOut);
    window.addEventListener("dragover", handleDrag);
    window.addEventListener("drop", handleDrop);
    return function cleanUp() {
      window.removeEventListener("dragenter", handleDragIn);
      window.removeEventListener("dragleave", handleDragOut);
      window.removeEventListener("dragover", handleDrag);
      window.removeEventListener("drop", handleDrop);
    };
  });
```

**Comment by fabb** [comment]
I‘ve seen on some pages that a dropzone is shown small inside a form, but when dragging files to the window, a dropzone overlay appears over the whole page. This works pretty well UX-wise, but I‘m not yet sure how to solve it with react-dropzone. 

Maybe something like that?
http://stackoverflow.com/a/33917000

**Comment by zapetin52** [comment]
@jlarmstrongiv thank you! Your solution works like a charm for me!

**Comment by sgrund14** [comment]
hey @jlarmstrongiv , thanks for this solution. Works really nice on chrome, but unfortunately it's not working on safari!

it's this line
```
if (event.dataTransfer.items && event.dataTransfer.items.length > 0) {
      setIsDragging(true);
    }
```
for some reason, on safari, the `items` array is empty :(

wondering if you were running into the same issue 🙏

**Comment by lung2008123** [comment]
@sgrund14 just jumped into this component yesterday

Safari does not fire any `event.dataTransfer.files` or `event.dataTransfer.items` array.

Safari do fires `['Files']` into `event.dataTransfer.types` nevertheless.

My workaround is replace them by checking whether `event.dataTransfer.types` array includes `'Files'`:
- if yes, trigger @jlarmstrongiv workaround drag logic & state control
- if no, just pass on the workaround 

```ts
  /* Safari will not recognize on-drop files into:
    * 1. event.dataTransfer.files
    * 2. event.dataTransfer.files.length
    *
    * Instead, Safari will fire 'Files' into array of:
    * 1.event.dataTransfer.types
    * 
    * update workaround with event.dataTransfer.types
    */

  const handleDragIn = React.useCallback((event: DragEvent) => {
    event.preventDefault();
    event.stopPropagation();
    dragCounter.current += 1;
    // if (event.dataTransfer !== null && event.dataTransfer.items && event.dataTransfer.items.length > 0) {
    if (event.dataTransfer !== null && event.dataTransfer.types.includes('Files')) {
      setIsDragging(true);
    }
  }, []);
  
  const handleDrop = React.useCallback((event: DragEvent) => {
    event.preventDefault();
    event.stopPropagation();
    setIsDragging(false);
    // if (event.dataTransfer !== null && event.dataTransfer.files && event.dataTransfer.files.length > 0) {
    if (event.dataTransfer !== null && event.dataTransfer.types.includes('Files')) {
      dragCounter.current = 0;
      event.dataTransfer.clearData();
    }
  }, []);
```

You can trigger the false event if you select some text, point your mouse cursor _**exactly**_ on the text ink, and drag it out. The result `event.dataTransfer.types` is empty array `[]`.

Let me know if it helps! Cheers!
