### ISSUE TITLE
Load image from props URL

### ISSUE THREAD

**Issue by cuongduong257** [react-dropzone/react-dropzone#756]
I write a function to edit a user profile. The function needs to load the current avatar (image) by URL to show on Dropzone after that User can remove and drag another image.
But I don't see anything to support this. Someone could help me. Thank a lot.

**Comment by rolandjitsu** [comment]
@cuongduong257 I'm not sure I follow what you're trying to do. Please provide a proper example to illustrate your issue.

**Comment by rolandjitsu** [comment]
Closing this. Feel free to reopen if you provide an example illustrating your issue.

**Comment by theone3nu** [comment]
Hey instead of attaching the images from local disk i want to load the images from the url is that possible using this component?

**Comment by rolandjitsu** [comment]
Unfortunately not, this lib just handles drag 'n' drop (and file selection).
