### ISSUE TITLE
onDrop, receiving console error node.contains is not a function

### ISSUE THREAD

**Issue by paulmichaelxd** [react-dropzone/react-dropzone#763]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
All functionality works as expected, however, when dragging and dropping files there is always this console error:
`Uncaught TypeError: r.node.contains is not a function
    at HTMLDocument.r.onDocumentDrop`

**If the current behavior is a bug, please provide the steps to reproduce.**

With the following code:
```
<Dropzone
      className={classes.dropzone}
      accept="image/jpeg, image/png"
      onDrop={onDrop}
      id="poster-dropzone"
    >
      {({ getRootProps, getInputProps, isDragActive }) => (
        <Paper
          {...getRootProps()}
          className={classNames({
            [classes.posterArt]: true,
            [classes.hoverPoster]: isDragActive,
          })}
          elevation={8}
        >
          <input {...getInputProps()} />
          <Masonry>
            {posterFiles.map(poster => (
              <PosterThumbnail
                key={poster._id}
                data={data}
                onChange={onChange}
                poster={poster}
                posterTitle={getPosterTitle(posterTypes, posterMetadata, poster._id)}
              />
            ))}
          </Masonry>

          <div className={classes.addIcon}>
            <Add />
          </div>
        </Paper>
      )}
    </Dropzone>
```
Clicking the input to upload works with no problems. But when dragging and dropping, the upload works, but I get this error:
`Uncaught TypeError: r.node.contains is not a function
    at HTMLDocument.r.onDocumentDrop`
Upon inspecting this error, I see it takes me to the minified react-dropzone dist/index.js

**What is the expected behavior?**

For the functionality to work with no console errors.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

Testing in Chrome on macOs Mojave. Using react-dropzone 8.1.0

**Comment by rolandjitsu** [comment]
@paulmichaelxd I think your issue is that you're using `<Paper>` as dropzone. As far as I know, the `{ref}` prop on that component will not work (and we need it), but you can use `{...getRootProps({refKey: 'innerRef'})}` to fix it.

Let me know if that works for you.

**Comment by paulmichaelxd** [comment]
@rolandjitsu Thanks for your response!
Unfortunately, adding the `refKey: 'innerRef'` gave me some console error about refs not working on function components.

However, simply wrapping my `<Paper>` component with `<div {...getRootProps()}>` fixed the issue. Thanks!

**Comment by rolandjitsu** [comment]
@paulmichaelxd Hmm, maybe try opening an issue with mui or ask on SO using the mui tag.

In any case, I will close this issue as it's not specific to this lib.

**Comment by vanyakosmos** [comment]
With MUI you should use [RootRef component](https://material-ui.com/api/root-ref/).

**Comment by rolandjitsu** [comment]
@vanyakosmos does your suggestion work? I think it would be helpful to have an example on our side illustrating the workaround for this.

**Comment by vanyakosmos** [comment]
I had similar issue as OP and with RootRef everything is fine. 

But I don't think that we should have an example in docs for this specific case, because, as you said, it is more MUI-related issue and knowing that `RootRef` exists is 99% of the answer.
Also when I googled error there were literally only 4 links and this issues was first in list, so people with the same problem will surely find this issue and my comment with fix.

**Comment by rolandjitsu** [comment]
@vanyakosmos we already have this sort of issue example in our docs, but for styled components. Since they moved away from `innerRef`, I think it's a good idea to use mui instead as example for setting references using custom `refKey`.
