### ISSUE TITLE
"process is not defined" in 8.2.0

### ISSUE THREAD

**Issue by CleyFaye** [react-dropzone/react-dropzone#764]
- [X] I found a bug
- [ ] I want to propose a feature

**Issue**

When using react-dropzone 8.2.0, I get an error: "process is not defined" when loading "index.js"

**How to reproduce**

1. Import index.js in a page through a <script> tag
2. Import fail because process is not defined

**What is the expected behavior?**

The dist/index.js file should probably not reference process.

Going back to 8.1.0 works since it does not reference process.

**Comment by rolandjitsu** [comment]
Hmm, this might be because of the way it's bundled. I'll check and let you know.
