### ISSUE TITLE
onDrop not working

### ISSUE THREAD

**Issue by ppi-mzl** [react-dropzone/react-dropzone#770]
**Do you want to request a *feature* or report a *bug*?**
- [X] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
I'm using the example code from the documentation but the onDrop function is never called. The isDragActive, isDragAccept and isDragReject work fine. Using the file selector works too.

Code:
```typescript
<Dropzone onDrop={() => alert("Dropped")}>
{({ getRootProps, getInputProps, isDragActive }) => {
    return (
    <div {...getRootProps()} className={"dropzone" + isDragActive ? " dropzone--isActive" : ""}>
        <input {...getInputProps()} />
        {isDragActive ? (
        <p>Drop files here...</p>
        ) : (
        <p>Try dropping some files here, or click to select files to upload.</p>
        )}
    </div>
    );
}}
</Dropzone>
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Install react-dropzone
1. Include code from above
1. Drag file(s) from finder onto the dropzone
1. Drop file
1. Nothing happens, no console output

**What is the expected behavior?**

1. ...
1. Drop file
1. Alert is shown

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

* macOS High Sierra 10.13.4, Windows 10
* Safari 11.1, Chrome 72.0.3626.109, and Firefox 65.0
* react-dropzone 9.0.0

**Comment by darekchynek** [comment]
Have same issue, with the same version of react-dropzone and Windows 10 (Google Chrome 72.0.3626.119 ). 

Open method works correctly - onDrop don't launch when You drop file.

**Comment by rolandjitsu** [comment]
Doing this on [react-dropzone.js.org](https://react-dropzone.js.org) works just fine (the basic example shows the file you dropped).

So I'm not sure what you're experiencing. Please provide an example on codesandbox or some other tool.

**Comment by alfaslash** [comment]
@ppi-mzl are you used [React DnD](https://github.com/react-dnd/react-dnd)?

**Comment by darekchynek** [comment]
We're using React Dnd with react-sortable-tree.

**Comment by alfaslash** [comment]
@darekchynek This problem in React DND https://github.com/react-dnd/react-dnd/issues/457

**Comment by ppi-mzl** [comment]
> @ppi-mzl are you used [React DnD](https://github.com/react-dnd/react-dnd)?

Yes we are using react-dnd and using the [fork](https://github.com/silvainSayduck/react-dnd/tree/master/packages/react-dnd-html5-backend) / [nmp Package](https://www.npmjs.com/package/@silvain-sayduck/react-dnd-html5-backend) of @silvainSayduck  instead fixes the issue.

So this is not a bug in react-dropzone but react-dnd. Maybe this should be mentioned in the documentation since this seems to be a common error.

**Comment by ppi-mzl** [comment]
Wrapping the Dropzone in a ConnectDropTarget which accepts NativeTypes.FILE works also.

**Comment by ronaiza-cardoso** [comment]
I'm also using with react-dnd and is not working. `"react-dropzone": "^7.0.1",`. When is on localhost works like expected but when build to prod doesn't works

**Comment by felipe-vicente** [comment]
In case of anyone having an issue that "looks like this one". Sometimes browsers use diferente MIME_TYPE for diferente file types. I had a problema with 'text/csv' mimetype, wich did not work on Chrome running on Windows. Took a while to detect the cause.

I just wanted to write it here so developers with the same problem I had won't lose time thinking it could be any more complex error. Cheers
