### ISSUE TITLE
feat: upgrade to babel7

### ISSUE THREAD

**Issue by rxmarbles** [react-dropzone/react-dropzone#773]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [x] I want to propose a feature

**If this is a feature request, what is motivation or use case for changing the behavior?**
Currently the repo is outdated in regards to several dependencies (per npm audit 3 w/ critical issues). However in upgrading our babel configuration to v7 we should get a bump in build performance with its most recent improvements.

**Comment by rolandjitsu** [comment]
@rxmarbles please see [#772](https://github.com/react-dropzone/react-dropzone/pull/772/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R97).

**Comment by rxmarbles** [comment]
Sorry about that @rolandjitsu thought that was only moving to hooks 😅. I'll give it a review tonight

**Comment by rolandjitsu** [comment]
@rxmarbles no worries. Well, I needed to upgrade react-styleguidist to latest in order to use react hooks, but that also required upgrading everything else (webpack, babel, etc.).

Maybe I should have added that in the commit message 🤔
