### ISSUE TITLE
Where can I find docs for version (9.0.0)?

### ISSUE THREAD

**Issue by zifahm** [react-dropzone/react-dropzone#777]
where can i find docs for version 9.0.0. I'm still using classes.

**Comment by rolandjitsu** [comment]
You can still use class components, the `<Dropzone>` is still exported, see [class-components](https://react-dropzone.js.org/#class-components). Otherwise [v9.0.0](https://github.com/react-dropzone/react-dropzone/tree/v9.0.0).

**Comment by zifahm** [comment]
I get a document not defined Error after updating to 10.0.0. It doesn't seem like I'm using getDataTransferItems anywhere. 
I'm using Nextjs

**Comment by rolandjitsu** [comment]
I think it's related to https://github.com/react-dropzone/react-dropzone/issues/775.
