### ISSUE TITLE
Add CHANGELOG.md 

### ISSUE THREAD

**Issue by crobinson42** [react-dropzone/react-dropzone#782]
Hello - thanks for the awesome project and efforts! I just noticed a small project I'm working on is 2 major versions behind so before upgrading I came to the repo to read a changelog to see what api or other breaking changes I might need to address when upgrading.

It would be great if there was a CHANGELOG.md file added to the repo :-) 

I'm happy to contribute with a PR to add some automation of the this changelog file generation based on the commitizen formatted commits, just let me know 💭

**Comment by thaddeusreid** [comment]
I found the Releases tab meet my needs: https://github.com/react-dropzone/react-dropzone/releases Maybe you've already seen it and are yearning for more :)

**Comment by crobinson42** [comment]
Ahh! I forgot about that github feature, thanks @thaddeusreid
