### ISSUE TITLE
Regression: Unable to click DOM elements inside drop zone with recommended code

### ISSUE THREAD

**Issue by dimroc** [react-dropzone/react-dropzone#783]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

The removal of `disableClick` in https://github.com/react-dropzone/react-dropzone/pull/767 has caused a regression. You are now unable to click on buttons inside a dropzone when performing the recommended alternative because propagation is stopped entirely: 

```javascript
{onClick: evt => evt.preventDefault()} // stops all propagtion
```

`disableClick` skipped the dropzone element, but continued propagation.

The following replacement stops all propagation and is functionally different:

```jsx
return (
      <Dropzone
        accept={accept}
        onDrop={this.onDrop.bind(this)}
      >
        {({getRootProps, getInputProps, isDragActive}) => (
            <div {...getRootProps({onClick: evt => evt.preventDefault()})} style={{position: "relative"}}>
              <input {...getInputProps()} />
```

https://github.com/react-dropzone/react-dropzone/pull/767/files#diff-0b1f9c3babb635d33ee2724a6f8d78b9

**If the current behavior is a bug, please provide the steps to reproduce.**

The Fullscreen example that would reproduce this has been removed in commit https://github.com/react-dropzone/react-dropzone/commit/5398f44f8fdcab8429b0c7769161bba72dad2800#diff-0b1f9c3babb635d33ee2724a6f8d78b9. (Why?)

1. Create a button inside the fullscreen dropzone
2. Disable click on dropzone by following the recommendation
3. Unable to click button.

Or just add a button inside https://github.com/rolandjitsu/react-dropzone/blob/c31e06e93a96162e4c23cd1167270ac61a1bddf5/examples/Fullscreen/Readme.md

**What is the expected behavior?**

I am able to click the button inside the dropzone.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

1. Broken in v9 and v10, as a result of https://github.com/react-dropzone/react-dropzone/pull/767. 
2. This can be seen because the old logic would continue propagating the click without invoking the file dialog:

```javascript
if (!disableClick && !isDefaultPrevented(evt)) { // I can disable click but still continue propagation
      evt.stopPropagation()
```

3. Would love to see the return of a full screen dropzone example.
4. Let's bring back disableClick, it is functionally different to the current approach.

Thanks for all the cleanup and work!

**Comment by rolandjitsu** [comment]
@dimroc thanks for reporting this.

The fullscreen example was removed because it was misleading, as some users thought it meant they can drag 'n' drop on the document.

If we introduce `{disableClick}` we ought to do the same for all other events (focus, blur, keydown and drag events).

Using `preventDefault()` would not work because it will introduce other issues (e.g. parent dropzones would also pick up on it and stop the expected behavior), that's why I resorted to `stopPropagation()`. But I haven't thought of this scenario when I did it and it is indeed a problem.

I'll give this a thought and try to fix it as soon as possible.

**Comment by localjo** [comment]
I think in order to be able to disable on the Dropzone parent from triggering on the input, while still being able to manually trigger clicks on the input with `open()` the `onClickCb` should be changed to check if propagation has been stopped;

```
const onClickCb = useCallback(evt => {
    if (!isPropagationStopped(evt)) { 
      if (isIeOrEdge()) {
        setTimeout(openFileDialog, 0)
      } else {
        openFileDialog()
      }
    }
  }, [inputRef])
```

Then you could do this to disable clicks;
```
 <div {...getRootProps({ onClick: e => e.stopPropagation() })}>
```

As it is right now, I have no way of disabling clicks but still manually opening the file browser.

**Comment by rolandjitsu** [comment]
@localjo please see [index.js#L594](https://github.com/react-dropzone/react-dropzone/blob/v10.0.0/src/index.js#L594) and [utils/index.js#L77](https://github.com/react-dropzone/react-dropzone/blob/v10.0.0/src/utils/index.js#L77). There is also an [example](https://react-dropzone.js.org/#event-propagation) illustrating exactly what you're describing.

**Comment by localjo** [comment]
It seems that this does not stop events from getting forwarded to the input;
```
<div {...getRootProps({ onClick: e => e.preventDefault() })}>
```
However this prevents the input from opening at all;
```
<input {...getInputProps({ onClick: e => e.preventDefault() }))} />
```
Since forwarding an event from a parent to the child is not standard JS behavior, I think there needs to be a way to stop it.

**Comment by localjo** [comment]
Judging by that example, my suggestion should work;
```
<div {...getRootProps({ onClick: e => e.stopPropagation() })}>
            <input {...getInputProps()} />
...
```
But this still forwards the click from the Dropzone to the input.

**Comment by localjo** [comment]
Hmm... now it's working. I must have had my wires crossed somewhere. I've been struggling with this all morning. Sorry for the confusion.

**Comment by rolandjitsu** [comment]
Please check #801 and let me know if it helps with this issue.

**Comment by damianobarbati** [comment]
@localjo honestly I'm not understanding. Does the following work for you?

```js
<div {...getRootProps({ onClick: e => e.stopPropagation() })}>
            <input {...getInputProps()} />
```

Because it totally stops the dialog from opening to me.

**Comment by AlanKiri** [comment]
I had similar issues with buttons and inputs inside of dropzone specifically them not focusing but i didn't knew what's causing those issues. I tried removing onFocus handle from root element and it removed all issues.
Code snippet:
<div {...getRootProps()} onFocus={undefined}>
