### ISSUE TITLE
I got  `Minified React error #307` on 10.0.0 version.

### ISSUE THREAD

**Issue by miroslavkremenovic** [react-dropzone/react-dropzone#784]
**Do you want to request a *feature* or report a *bug*?**

- [o] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
I got `Minified React error #307` on 10.0.0 version. My app crashes on pages were dropzone is implemented. When I return it on 9.0.0 it works fine. 
**If the current behavior is a bug, please provide the steps to reproduce.**

1.
1.
1.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by wmertens** [comment]
@miroslavkremenovic your error is very vague. You should click on the link it shows in the error to know what the minified error is, and ideally you should figure out what the error really is in your non-minified source. 

This is not a product you pay for to get support, we should all help to improve it and okonet is spending his probably rare spare time keeping it all under control. So you are expected to report errors so that they cause the least amount of wasted time for others.
(note I'm not a dev here, just pointing out how open source works)

**Comment by miroslavkremenovic** [comment]
Ok, I'll be clearer. Problem is not happening in my  non-minified source. Only when i build app ( on staging for example).

- I'm using node v10.0.0 (npm v5.6.0).
- react-dom v16.4.0, react v16.7.0
- Link for the error decoder is https://reactjs.org/docs/error-decoder.html/?invariant=307
My app crashed on several pages and i figure out it  is because of dropzone ( it was only thing that all pages had in common), also my last change in code was upgrading dropzone to v 10.0.0. When I install again 9.0.0 version, the problem was gone.

I apologize for being unclear before.

**Comment by rolandjitsu** [comment]
I'm on my phone, but one thing to note is that v10 requires react v16.8
(also react-dom).

I will be back from holiday next week and I will take a look at all the
reported issues.

**Comment by thaddeusreid** [comment]
I am also seeing an app-crashing error after upgrading to v10.

Some additional details:
- react/react-dom@16.8.3
- webpack@3.2.3

The react-dropzone component loads just fine when loading my app without minification. To reproduce the error, bundle the app and minify it. When the component is loaded the app will crash (white screen) and throw an error in console:

```
app.04245da74f0362e33719.js:145 TypeError: Cannot set property 'lastEffect' of null
    at ti (app.04245da74f0362e33719.js:145)
    at ni (app.04245da74f0362e33719.js:145)
    at Object.useEffect (app.04245da74f0362e33719.js:145)
    at useEffect (app.04245da74f0362e33719.js:129)
    at L (app.04245da74f0362e33719.js:121)
    at E (app.04245da74f0362e33719.js:121)
    at Ko (app.04245da74f0362e33719.js:145)
    at app.04245da74f0362e33719.js:145
    at Xa (app.04245da74f0362e33719.js:145)
    at Ha (app.04245da74f0362e33719.js:145)
    at Ss (app.04245da74f0362e33719.js:145)
    at qs (app.04245da74f0362e33719.js:145)
    at xe (app.04245da74f0362e33719.js:145)
    at wn (app.04245da74f0362e33719.js:145)
```

Happy to share more details as needed.

**Comment by rolandjitsu** [comment]
I think `lastEffect` is an internal react error, see this [SO](https://stackoverflow.com/questions/53348653/react-cannot-set-property-lasteffect-of-null) and [facebook/react#14014](https://github.com/facebook/react/issues/14014). In any case, the error is not a direct cause of this lib, so I'll be closing the issue.
