### ISSUE TITLE
Crash when dragging and dropping in IE 11

### ISSUE THREAD

**Issue by SpudNyk** [react-dropzone/react-dropzone#791]
**Do you want to request a *feature* or report a *bug*?**

- [X] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Drop a file onto a drop zone in IE 11
1. Observe exception is thrown due to setting dropEffect
1.

**What is the expected behavior?**
No crash
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
OS: Windows 7 and Windows 10
Browser: Internet Explorer 11
React-dropzone: 10.0.4

I believe this is a regression of the fix for #248

**Comment by rolandjitsu** [comment]
Strangely, when I tested on IE11 on a [lambdatest](https://www.lambdatest.com) vm, I saw no errors about the dropEffect. Will investigate and fix soon.

**Comment by SpudNyk** [comment]
I'm getting the error on an enterprise network so my guess would be something in the security policy for windows prevents the setting of the flag, wrapping the line with try catch seems to fix it.
I just tried on a plain windows 10 + IE 11 install and I don't get the error there, only difference would be lack of the group security policy.
