### ISSUE TITLE
Invalid prop `children` of type `object` supplied to `Dropzone`, expected `function`.

### ISSUE THREAD

**Issue by Shaker-Hamdi** [react-dropzone/react-dropzone#794]
I'm getting this error when I try to apply the example you have on redux-form ...
https://github.com/BBB/dropzone-redux-form-example/blob/master/src/App.js

I'm on the latest version of React and react-dropzone.

**Comment by rolandjitsu** [comment]
Please see [class-components](https://react-dropzone.js.org/#class-components) example; the child of the `<Dropzone>` needs to be a render fn.

**Comment by sajera** [comment]
Link not work...

**Comment by naoya7076** [comment]
Example of class-components is Here
https://github.com/react-dropzone/react-dropzone/tree/master/examples/class-component
