### ISSUE TITLE
Does the latest version require React 16.8 

### ISSUE THREAD

**Issue by carpben** [react-dropzone/react-dropzone#795]
**Do you want to request a *feature* or report a *bug*?**

- [x ] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
I want to add 'react-dropzone' to our existing live project. 
After installing I followed the usage instructions. Since Hooks are only available on React 16.8, and our React version is 16.7 I used the Wrapper component option. When running "npm start" the following Error showed in the browser's console: 
```
Uncaught TypeError: Object(...) is not a function
    at useDropzone (index.js:502)
    at eval (index.js:170)
```
Here is a screenshot from the Sources: 
![image](https://user-images.githubusercontent.com/13496178/54522597-4d198f00-4976-11e9-81ec-579a9ab39d1c.png)

It seems React-Dropzone is dependent on React hooks, and therefor on React 16.8. It seems React 16.8 is a requirement of the latest version of React-Dropzone. But nowhere in the documentation does it mention it. 

React v: 16.7
"react-dropzone": "^10.0.4",

**Comment by rolandjitsu** [comment]
@carpben see [v10.0.0](https://github.com/react-dropzone/react-dropzone/releases/tag/v10.0.0). It's documented as a breaking change. Upgrading react from 16.7 to 16.8 should not be an issue as far as I know.

**Comment by carpben** [comment]
I understand. NPM even declares it right after installing. 
However, since React 16.8 is relatively new, and installed in a minority of projects, I'd reccommend to add a comment in the installation section of the documentation.

**Comment by rolandjitsu** [comment]
Will make an update in the coming days, thanks for pointing it out.

**Comment by gupta-kartik** [comment]
Can the non-hook version, (using the hook wrapper) be used with versions < 16.8?

**Comment by rolandjitsu** [comment]
@gupta-kartik see release notes for [v10.0.0](https://github.com/react-dropzone/react-dropzone/releases/tag/v10.0.0).
