### ISSUE TITLE
Uploading  multiple image one by one 

### ISSUE THREAD

**Issue by jpcodeforit** [react-dropzone/react-dropzone#796]
Thanks for the Library .is it possible to upload multiple images one by one.
Example 
https://www.dropzonejs.com/

**Comment by rolandjitsu** [comment]
@jpcodeforit next time you open an issue please use the provided template.

This lib doesn't do any file uploads to a server, it simply provides you with the files that you dropped onto the dropzone or selected. It is up to you to implement the upload logic.

**Comment by fnaquira** [comment]
I thought at first the answer was kind of rude, but then it hit me: it is something to manage on my application!
Thank you very much, this library is awesome
