### ISSUE TITLE
Preventing default `onClick` behaviour.

### ISSUE THREAD

**Issue by mrlubos** [react-dropzone/react-dropzone#797]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [x] I want to propose a feature

**What is the current behavior?**

Version `9.0.0` deprecated the prop `disableClick` and introduced native event handling instead. As noted in [releases](https://github.com/react-dropzone/react-dropzone/releases), we should use `evt.preventDefault()` if we want to migrate this feature. However, this does not work in the latest version `10.0.5`. Instead, using `evt.stopPropagation()` works and it does not seem to behave the native way either – it does not actually stop the event propagation. This is documented in the [examples](https://github.com/react-dropzone/react-dropzone/blob/master/examples/events/README.md) as well. #530 contains a discussion on why this is not a good practice (h/t @smeijer).

**What is the expected behavior?**

Call `evt.preventDefault()` to prevent the default behaviour.

**Comment by rolandjitsu** [comment]
@mrlubos please refer to https://github.com/react-dropzone/react-dropzone/issues/783, let's keep this discussion there.
