### ISSUE TITLE
DragEnter and Drop events are not triggered when using an office-ui-fabric-react Dialog

### ISSUE THREAD

**Issue by claudiuchetan** [react-dropzone/react-dropzone#799]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
When using the react-dropzone inside an **office-ui-fabric-react Dialog** (https://github.com/OfficeDev/office-ui-fabric-react) component, the DragEnter and Drop events are not triggered.

**If the current behavior is a bug, please provide the steps to reproduce.**

You can find an example here: https://codesandbox.io/s/0m31n02ozl 

Dragging and dropping a file in the first dropzone, everything works as expected.
1. Press "Open Dialog"
2. Drag and drop (or click to open) a file on the dropzone in the popup
3. No DragOver or Drop events are triggered

**What is the expected behavior?**
All events should be correctly triggered.

**If this is a feature request, what is motivation or use case for changing the behavior?**
-

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
This fails because of the isPropagationStopped checks done for the 2 events.
In react-dropzone versions prior to 6.2.4 things work ok.
Also, in react-dropzone version 9.0.0, only the DragEnter event is triggered.

**Comment by rolandjitsu** [comment]
Please refer to https://github.com/react-dropzone/react-dropzone/issues/783 and add a comment about your use case. But as I see it, the dialog should not stop event propagation for drag events and this will likely be an issue after the aforementioned issue is resolved.

**Comment by rolandjitsu** [comment]
As far as I can see, [EventGroup.ts](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/utilities/src/EventGroup.ts) might be stopping event propagation in modals. You might want to open an issue on their side, because there isn't much we can do from our side.

**Comment by claudiuchetan** [comment]
@rolandjitsu I understand that Fabric's Dialog component stops the propagation. However, it might be that more than one library does this. 
Maybe adjust react-dropzone's behaviour so that it handles such cases? 
The event is properly received. Its handling is stopped after the promise runs. 
Shouldn't it be only stopped if it is not valid initially?

**Comment by rolandjitsu** [comment]
That argument works both ways, there are other libs that also listen to events some other libs stop from propagating.

If we remove this check, we break https://github.com/react-dropzone/react-dropzone/issues/686. But maybe https://github.com/react-dropzone/react-dropzone/pull/801 would cover the scenario described in the aforementioned issue and then we could remove the check.

> Shouldn't it be only stopped if it is not valid initially?

I do not understand what you mean by that.

**Comment by claudiuchetan** [comment]
> > Shouldn't it be only stopped if it is not valid initially?
> 
> I do not understand what you mean by that.

I meant that we should know when the event is triggered if we want to handle it or not, and not determine this based on isPropagationStopped's value.
Just to handle integration with libraries that don't handle this correctly.

I'm not sure why Fabric's stopping all events. They shouldn't have any saying in a drag/drop event's cycle.

Indeed, [#801](https://github.com/react-dropzone/react-dropzone/pull/801) seems to cover this.

**Comment by rolandjitsu** [comment]
@claudiuchetan that would mean we have to introduce a dropzone manager which keeps track of all dropzones and their position in the DOM tree. I definitely want to avoid that as it will introduce a lot of complexity.

Did you open an issue on their side as well?

#801 still has the event propagation check and I'm not sure at this point whether I will remove it or not as it will probably be a breaking change. Maybe in a different PR.

**Comment by claudiuchetan** [comment]
@rolandjitsu 
Not a dropzone manager, it would not be a viable approach. 
[#801](https://github.com/react-dropzone/react-dropzone/pull/801) as I understand it, gives the user additional options for configuring the dropzone. 
Having an option to ignore external propagation flags would handle this kind of edge cases while having no impact on existing functionality.

I just opened an issue on Office Fabric's side: [#8491](https://github.com/OfficeDev/office-ui-fabric-react/issues/8491)

**Comment by rolandjitsu** [comment]
@claudiuchetan right now, we still have the stop propagation check in #801, so it will still not work in your case.

If we remove it (the check), the `noDragEventsBubbling` option will not do anything (at least not for the async `onDrop` and `onDragEnter`). I might have to do some more work on that, perhaps I can manage to remove the check for stop propagation.

**Comment by rolandjitsu** [comment]
I'm closing this as `{eventBubblingEnabled}` on fabric's side seems to fix what you're currently experiencing.

If someone feel like they could come up with a simple way of removing the check we have in our lib for event propagation, feel free to make a PR.
