### ISSUE TITLE
dragging is not working after using other dragging component.

### ISSUE THREAD

**Issue by php4518** [react-dropzone/react-dropzone#802]
I am using react-email-editor and react-dropzone in the same project. 
Dragging a file in react-dropzone works fine initially. but after dragging component in react-email-editor, dragging files in react-dropzone doesn't work. here is a demo. I have used both libraries on the same page after editing email-template, dragging files in dropzone does not work.
https://codesandbox.io/s/x39wxnx5lz

the issue is only with chrome in Mac OS. works fine with firefox, safari, and opera.

**Comment by rolandjitsu** [comment]
I think this is an issue with unlayer, they might be binding drag event listeners to the document and blocking it somehow. I briefly checked the bound event listeners and I saw a couple of `editor.js` listeners on `dragenter`.

**Comment by php4518** [comment]
I have tried to catch that. But I don't know how to manage that. I am stuck with it. I have use both libraries at time. Do you have any idea how can I manage that?

**Comment by rolandjitsu** [comment]
I would definitely open an issue on their side or write them an email explaining this issue. There isn't much you can do I guess, maybe unlayer has some method to disable it or remove it from the DOM (which hopefully also removes all event listeners from the document).

**Comment by php4518** [comment]
I have already added issue on their side but didn't get any response.

**Comment by rolandjitsu** [comment]
Sorry to hear that, they'll eventually answer, probably.

**Comment by rolandjitsu** [comment]
I will close this for now as there's not much we can do from our side.
