### ISSUE TITLE
Return full file paths on Electron

### ISSUE THREAD

**Issue by Qrysto** [react-dropzone/react-dropzone#804]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [x ] I want to propose a feature

**What is the current behavior?**

The `acceptedFiles` list of the `onDrop` callback doesn't contain the full paths of the files even in Electron environment.

**What is the expected behavior?**

In Electron, `acceptedFiles` should contain the full paths of the files.

**Comment by rolandjitsu** [comment]
Hi, could you please provide a reproducible example? Such as a repo with some steps.

**Comment by nonoesp** [comment]
Seeing this same issue. I'm not sure if this is happening due to Chromium restrictions or due to this library not exposing the file path properly.

![image](https://user-images.githubusercontent.com/1243210/55008821-e0d80480-4fe1-11e9-97cf-88c9f046f826.png)

Note how `name` and `path` are the same. No reference to the path in the local file system.

**Comment by rolandjitsu** [comment]
Please see [file-selector](https://github.com/react-dropzone/file-selector) and move this issue there as this is definitely related to that lib. I think that electron already sets a [path](https://github.com/electron/electron/blob/v1.2.8/docs/api/file-object.md), so we might just need to detect that and use it.

**Comment by jmcrthrs** [comment]
Hello,

Would the following PR be considered: include a option to ignore the absolute path that Electron provides, and instead use the path normally returned by in a browser environment?

The reason for this is we actually don't want the absolute path provided by Electron. Currently we have forked this library and react-dropzone.

Having this option may be useful for other people.

Thanks

**Comment by rolandjitsu** [comment]
> Hello,
> 
> Would the following PR be considered: include a option to ignore the absolute path that Electron provides, and instead use the path normally returned by in a browser environment?
> 
> The reason for this is we actually don't want the absolute path provided by Electron. Currently we have forked this library and file-selector.
> 
> Having this option may be useful for other people.
> 
> Thanks

I've replied at https://github.com/react-dropzone/file-selector/issues/10#issuecomment-714312214. No need to track it in both repositories.
