### ISSUE TITLE
Issue with ref open() after upgrading from version 5

### ISSUE THREAD

**Issue by MastroLindus** [react-dropzone/react-dropzone#806]
I am upgrading react-dropzone from version 5.

I have some code like this:
```
private refCallback = (el: DropzoneRef | null) => {
  if (el !== null && anotherFlagThatDoesntMatter) {
    el.open();
  }
}


public render() {
  return <Dropzone ref={this.refCallback} {...otherProps}/>;
}
```

Basically when I am rendering the dropzone, and a certain flag is true, I want to open the dropzone programmatically, otherwise not.
This code used to work perfectly, but now for some reason refCallback gets called A LOT of times. If I insert a console.log inside that callback, it spams my console, even if render() gets called only once. The Ref callback API should be called only once when the component gets mounted, and once when it gets unmounted, so something is wrong.

If I use the newer React api using createRef(), I still need to know when the ref becomes assigned, so I need to do the tracking by myself and its a bit annoying (if I check in componentDidMount, the ref.current object is still null)

**Comment by rolandjitsu** [comment]
Could you provide a sandbox reproducing this?

**Comment by MastroLindus** [comment]
This code is all that is needed (typescript)

```
import Dropzone, { DropzoneRef } from "react-dropzone";

// inside a react component:

private callback = (el: DropzoneRef | null) => {
    console.log("WHY");
    if (el !== null) {
      // el.open();
    }
  }

  public render() {
    return (
      <div>
        <Dropzone onDrop={() => { }} ref={this.callback}>
          {({ getInputProps, getRootProps }) => <div {...getRootProps()}>
            <input {...getInputProps()} />
            test
       </div>}
        </Dropzone>
      </div>
    );
  }
```

if you leave el.open() commented out, you can see that the callback gets called once.
If el.open is called, the callback prints "WHY" a LOT of times, as open() would unmount the dropzone component. I am quite sure that this behaviour changed since version 5

**Comment by rolandjitsu** [comment]
It would still be easier if you could just create a sandbox. An example is provided in the issue template, use that as reference.

`.open()` does not unmount anything, it just opens the file dialog. If it's an issue, it's probably something else.

**Comment by MastroLindus** [comment]
https://codesandbox.io/s/qkloo1p9qw

check the console: 1 call to callback
now uncomment the line with el.open()
check the console again: a lot of calls

**Comment by rolandjitsu** [comment]
Thanks for creating the sandbox. I will take a look this weekend.
