### ISSUE TITLE
Export Typescript File type

### ISSUE THREAD

**Issue by fandy** [react-dropzone/react-dropzone#808]
It would be great to get access to the `File` type.

**Comment by rolandjitsu** [comment]
I'm not sure I understand what you're asking for. Could you describe your issue in more detail?

**Comment by Akuukis** [comment]
@rolandjitsu please reopen, I've got the same problem and can provide details.

When using `@types/react-dropzone` in Typescript, compiler throws the following error:

```
$ tsc -v && tsc -b tsconfig-src.json
Version 3.4.3
../../node_modules/@types/react-dropzone/index.d.ts:16:36 - error TS2304: Cannot find name 'File'.

16 export interface ImageFile extends File {
                                      ~~~~


Found 1 error.
```

**Comment by rolandjitsu** [comment]
You do not need `@types/react-dropzone`, the types are provided by the lib.

**Comment by Akuukis** [comment]
@rolandjitsu Oh. In that case, the `@types/react-dropzone` should get deprecated to avoid confusion

**Comment by rolandjitsu** [comment]
It wasn't created by us and I don't have the time to make a PR at the moment. Feel free to do it.

**Comment by universalhandle** [comment]
For posterity:

I was getting a similar `TS2304: Cannot find name 'File'` error, using the typings in the lib (not `@types/react-dropzone`. The solution was to update `tsconfig.json` as follows:

```json
{
    "compilerOptions": {
        ...
        "lib": [
            "dom",
            ...
        ],
        ...
    }
}
```
