### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by chobo2** [react-dropzone/react-dropzone#810]
Hi

I upgraded my version (version 8) of React Dropzone and now my code is not working when I upgraded to version 10.
```

Uncaught TypeError: Object(...) is not a function
    at useDropzone (:8080/main.js:85977)
    at :8080/main.js:85645
    at updateForwardRef (:8080/main.js:81088)
    at beginWork (:8080/main.js:81883)
    at performUnitOfWork (:8080/main.js:83897)
    at workLoop (:8080/main.js:83936)
    at HTMLUnknownElement.callCallback (:8080/main.js:68256)
    at Object.invokeGuardedCallbackDev (:8080/main.js:68294)
    at invokeGuardedCallback (:8080/main.js:68343)
    at replayUnitOfWork (:8080/main.js:83350)
```

```
   <Dropzone
                accept="image/jpeg, image/png"
                onDrop={this.onDrop.bind(this)}
                maxSize={1000000}
                getDataTransferItems={evt => fromEvent(evt)}>
                {({ getRootProps, getInputProps, isDragActive }) => {
                  return (
                    <div
                      {...getRootProps()}
                      className={classNames('dropzone', { 'dropzone--isActive': isDragActive })}>
                      <input {...getInputProps()} />
                      {isDragActive ? (
                        <p>Drop files here...</p>
                      ) : (
                        <p>
                          Try dropping some files here, or click to select files to upload. Only
                          jpeg and png images under 1mb will be accepted
                        </p>
                      )}
                      <ImagePreviewContainer item={this.props.item} />
                    </div>
                  );
                }}
              </Dropzone>
```

**Comment by chobo2** [comment]
It seems like some major changes happened from version 8 to 10? What is the fastest way I can change my code to get up and running. I am not using the latest version of reactjs and not sure if I can upgrade to it.

**Comment by rolandjitsu** [comment]
You just need to upgrade to react > 16.8. There are no breaking changes in regards to react, so you should be fine.

**Comment by chobo2** [comment]
Ok, I will check out react > 16.8 got to make sure it can work with IE 11(finding lots of stuff I am upgrading to newest versions just don't work with IE 11)

**Comment by rolandjitsu** [comment]
I'm gonna close this, but if you discover an issue after you do the upgrade, please report it.

**Comment by chobo2** [comment]
@rolandjitsu 

Ok, I upgraded and inital tests seem to be fine, though is there any changes to my dropzone I should change. Looking at the examples it looks like stuff has changed?

I am also having trouble disabling dragging. I tried

 <Dropzone
                accept="image/jpeg, image/png"
                onDrop={this.onDrop.bind(this)}
                onDrag={true}

Is this the right way?

**Comment by rolandjitsu** [comment]
Yes, some things have changed. You can look at the releases to see what changed. You can still use the `<Dropzone>` component, you don't need to switch to hooks if you don't want to.

To disable drag, use `noDrag` property (e.g. `<Dropzone noDrag> ... </Dropzone>`).
