### ISSUE TITLE
acceptClassName not working

### ISSUE THREAD

**Issue by adamcoulombe** [react-dropzone/react-dropzone#812]
I had been using a previous version of dropzone that used the acceptClassName prop.

It doesnt seem like there is that feature anymore? Though I dont see any documentation about it. All I know is its not working anymore, and I would like to restore those classes:

```
               <FileDropzone
                  {...dropzoneOptions}
                  className={[
                     "file-input-field-default",
                     !this.state.file ? "" : "file-input-field-has-files"
                  ].join(" ")}
                  acceptClassName="file-input-field-accept"
                  activeClassName="file-input-field-active"
                  rejectClassName="file-input-field-reject"
                  }
                  onDrop={f => {
                     this.handleOnDrop(f).then(res => {
                        onFileSelect(f);
                        return onChange(res);
                     });
                  }}
                  name={name}
               >
```

**Comment by adamcoulombe** [comment]
I think I figured out how to do this. By using the `useDropzone` thing. I guess that lets you customize your own dropzone component.

I'm not sure why the classes were removed as a default feature. To have good UX it makes sense to provide some feedback when the user is dragging a file. It should be easier to do this IMO, as it had been before. 

I could submit a PR to address this?

```
function MyDropzone(props) {
   const {
      getRootProps,
      getInputProps,
      isDragActive,
      isDragAccept,
      isDragReject
   } = useDropzone({
      onDrop: files => {
         props.onDrop(files);
      }
   });

   return (
      <div className={
         [
            "file-input-field-default",
            isDragAccept ? "file-input-field-accept" : '',
            isDragReject ? "file-input-field-reject" : '',
            isDragActive ? "file-input-field-active" : ''
         ].join(' ')
      }
         {...getRootProps({ isDragActive, isDragAccept, isDragReject })}>

         <input {...getInputProps()} />
         {props.children}

      </div>
   );
}

```

**Comment by rolandjitsu** [comment]
@adamcoulombe the hook and component are both headless, meaning there are no DOM elements rendered, hence no need to have classes.

On the other hand, you have some properties (`isDragActive`, `isDragAccept`, etc.) that can help with what you're describing. It's up to you to render whatever you need.

**Comment by perrywarner** [comment]
Thanks for the pseudo "migration guide" @adamcoulombe! There wasn't any information in the documentation for updating from an older version to the new one, so this helps out
