### ISSUE TITLE
Example integration with Redux Form

### ISSUE THREAD

**Issue by cristian-sima** [react-dropzone/react-dropzone#816]

**Comment by rolandjitsu** [comment]
I'm not quite sure what you're asking for here 😕 Could you use the issue template please?

**Comment by cristian-sima** [comment]
hi @rolandjitsu . I want to use reactdropzone together with redux-form https://redux-form.com/.

I was asking for an example how to integrate these two. 

Thanks

**Comment by rolandjitsu** [comment]
@cristian-sima This sounds more like a question for SO than an issue. In any case, here's an [example](https://codesandbox.io/s/24pm48ymjy?fontsize=14) of how you could integrate the two.

I will close this, but if you encounter an issue, feel free to report it.
