### ISSUE TITLE
isDragActive isn't working in Safari

### ISSUE THREAD

**Issue by leogiertz** [react-dropzone/react-dropzone#819]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
When dragging a file in Safari over a dropzone, isDragActive still is false. It works in Chrome however.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Go to https://react-dropzone.js.org/#!/Styling%20Dropzone
2. Drag a file over the dropzone
3. Notice that there's no change in styling.

**What is the expected behavior?**
That it gets a change in styling, as in Chrome.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Safari 12.1 on Mojave 10.14.4. Not tested on older versions.

react-dropzone 10.1.0.

**Comment by eugenio1590** [comment]
@leogiertz are you using "getFilesFromEvent"  function?

**Comment by leogiertz** [comment]
@eugenio1590 No, I'm doing it in a similar way as the code example for how to style a drop zone is doing it.

**Comment by eugenio1590** [comment]
Ummm I get the same error but using  "getFilesFromEvent" function. #818

**Comment by rolandjitsu** [comment]
I can confirm that Safari is not working as expected. Though, it's not just `isDragActive`, it's also the `isDragAccept`/`isDragReject` props.

I'd also argue that we don't really need `isDragActive` because on drag enter you'd get either `isDragAccept` or `isDragReject`.

I will investigate the issue further to see what's going on.
