### ISSUE TITLE
Dropzone should support string children, as react does. 

### ISSUE THREAD

**Issue by r3wt** [react-dropzone/react-dropzone#820]
solution: remove line 80

https://github.com/react-dropzone/react-dropzone/blob/ea5fb32de4e5eb709f4f7d0851e8030addb5f6f4/src/index.js#L80

use case:
https://stackoverflow.com/questions/55692809/warning-failed-prop-type-invalid-prop-children-of-type-string-supplied-to

**Comment by rolandjitsu** [comment]
Our `<Dropzone>` component is headless, therefore, you're required to provide a function as child and use the prop getters to render.
