### ISSUE TITLE
Error: Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by seth-seikosoft** [react-dropzone/react-dropzone#821]
- [x ] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
When trying to use the "Class Component"  example code I'm seeing `Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen...`  when rendering the page.  
*Class Component*
```
...
<Dropzone
  multiple={false}
  accept={acceptedTypes}
  onDrop={this.onDrop}
>
  {({getRootProps, getInputProps}) => (
    <section className="container">
      <div {...getRootProps({className: 'dropzone'})}>
        <input {...getInputProps()} />
        <p>Drag 'n' drop some files here, or click to select files</p>
      </div>
    </section>
  )}
</Dropzone>
...
```
I've also tried to create a functional component using the hooks example 
*functional component*
```
import React            from 'react'
import { useDropzone }  from 'react-dropzone'

const ImageDropzone = ({ multiple, accept, onDrop }) => {
  const { getRootProps, getInputProps } = useDropzone({ multiple, accept, onDrop })

  return (
    <div {...getRootProps()}>
      <input {...getInputProps()} />
      <p>Drag 'n' drop some files here, or click to select files</p>
    </div>
  )
}

export default ImageDropzone
```
I get the same error as above.  

**What is the expected behavior?**

I expect the page to load with the dropzone div showing.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Browser version:  FF - 66.0.2, Chromium - 73.0.3683.103
OS: openSUSE Tumbleweed
react-dropzone: 10.1.3
react & react-dom: 16.8.6

I'm also running this is a dotnet core project using [Reactjs.net](https://reactjs.net/2019/03/4.1.1-release.html) 
I'm using reactjs.net: 4.1.1 which they've stated works with react hooks.  They're using an internal version of react 16.8.4

I'm also bundling this with webpack : 4.30.0

I'm new to hooks (like everyone haha) but old to react.  I believe I've got all the correct versions and I'm setting things up correctly.  Any help will be much appreciated.

**Comment by rolandjitsu** [comment]
Please provide an example reproducing your issue. The example we have at [react-dropzone.js.org](https://react-dropzone.js.org/#class-components) works just fine.

**Comment by seth-seikosoft** [comment]
Here is the jsx file (had to zip it so I'm not coping the whole file into here)  that shows the component I'm trying to load.  The component will initially load correctly.  When the "onClick" event attached to the div on line 65 runs it then opens/shows the div block on line 72.  When the browser tries to render this block I get the error above.  If I replace the Dropzone block on line 73  with my custom functional component which has the code from above I get the same error when following the same steps provided. 
[ImageUploader.jsx.zip](https://github.com/react-dropzone/react-dropzone/files/3085400/ImageUploader.jsx.zip)

I hope this explanation helps.

**Comment by jkeruzec** [comment]
Same error here ... 

Error is showing up when using with Mobx observer pattern.

https://codesandbox.io/s/9zoq2kqj3p

**Comment by rolandjitsu** [comment]
@seth-seikosoft would be nice to see a simple sandbox ;) @jkeruzec thanks, I will take a look.

**Comment by rolandjitsu** [comment]
@seth-seikosoft as explained in https://github.com/mobxjs/mobx-react/issues/656, you have to hang on until the PR they reference is merged and released or use the `<Observer>` component. Check out a [fork](https://codesandbox.io/s/nnv0ll1nnl?fontsize=14) of @jkeruzec's sandbox.

**Comment by seth-seikosoft** [comment]
@rolandjitsu I'm sorry I should have thought about that.... #facepalm haha!  (sandbox) 

ok I'll hangout until that PR gets merged in and come back to this feature.  Thank you again for your reply and you're work on this project!
