### ISSUE TITLE
TypeScript Compiler Error: node_modules/@types/react-dropzone"' has no exported member 'useDropzone'.

### ISSUE THREAD

**Issue by perrywarner** [react-dropzone/react-dropzone#822]
**Do you want to request a *feature* or report a *bug*?**

- [X] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
The latest version of react-dropzone's documentation has most examples using the `useDropzone` hook, but the latest TypeScript type definitions via the associated project _DefinitelyTyped/types/react-dropzone_ [hasn't been updated in 8 months](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-dropzone/index.d.ts). 

As a result of this, when attempting to use the custom hook `useDropzone`, the following TS error gets thrown:
`node_modules/@types/react-dropzone"' has no exported member 'useDropzone'.`

I found that removing _@types/react-dropzone_ from my project's dependencies allowed me to properly use the `useDropzone` hook.

**If the current behavior is a bug, please provide the steps to reproduce.**

Align the relevant dependencies to the application I'm working with (each of which are latest as of time of issuing this bug):
1. "_typescript_": "3.4.3"
1. "_react_": "16.8.6"
1. "_react-dropzone_": "10.1.3"
1. " _@types/react-dropzone_": "4.2.2"

Following the documentation's [first example](https://github.com/react-dropzone/react-dropzone#usage); in application-level code, attempt to:
`import { useDropzone } from 'react-dropzone';`

**What is the expected behavior?**

- I should be able to use the `useDropzone` hook and have no problems, assuming the outside dependencies are okay. 
- I should also be able to update  _@types/react-dropzone_ and be able to make use of react-dropzone with whatever implementation details - either Hooks via `useDropzone` or "the old way" via `<Dropzone/>` and have no problems. 
- The type defs for the @types package shouldn't conflict with the [type defs already defined in react-dropzone](https://github.com/react-dropzone/react-dropzone/blob/master/typings/react-dropzone.d.ts)

The discrepancy in type definitions are very jarring, as the current documentation mentions that the wrapper component `<Dropzone/>` can be used, but [certain](https://github.com/react-dropzone/react-dropzone#dropzone-props-getters) examples only show how to access react-dropzone via the `useDropzone` hook.

IMHO: if the types are going to be accessible via the [base react-dropzone](https://github.com/react-dropzone/react-dropzone/blob/master/typings/react-dropzone.d.ts) library going forward, I think the external [DefinitelyTyped type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-dropzone/index.d.ts) could be removed altogether.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Browser Version: Chrome v. 73.0.3683.103 (Official Build) (64-bit)
Operating System: macOS Mojave v. 10.14.4
[react-dropzone](https://github.com/react-dropzone/react-dropzone) Version: 10.1.3
[@types/react-dropzone](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dropzone) Version: 4.2.2

**Comment by rolandjitsu** [comment]
Types are hosted with this package, so you should not use the ones from DT. As far as I know, we do not own the types at DT. And I think they're also versioned, so it should be pretty obvious that they're not compatible with the latest version of dropzone.

As for examples, it's pretty easy to infer that the props you use for the `useDropzone()` hook are the same you apply on the `<Dropzone>`.

There are already a lot of examples, but if you feel you need more, feel free to open a PR.

**Comment by perrywarner** [comment]
Thanks for the feedback @rolandjitsu! I'll keep that in mind going forward.
