### ISSUE TITLE
how can I add a slot into it?

### ISSUE THREAD

**Issue by caijh23** [react-dropzone/react-dropzone#824]
I can not use it just like this 
```javascript
const FileUpload =  ({children}) => (
  <Dropzone
    multiple={false}
    accept="image/*"
    onDrop={(file)=>{console.log(file)}}
  >
    {children}
  </Dropzone>
);
```
It would throw a error like this:
TypeError: children is not a function

**Comment by rolandjitsu** [comment]
That's because the child must be a render function. Check the [docs](https://react-dropzone.js.org/#src) and an [example](https://react-dropzone.js.org/#class-components) illustrating how to use the component.
