### ISSUE TITLE
Swallowing click events of DOM elements

### ISSUE THREAD

**Issue by troutowicz** [react-dropzone/react-dropzone#826]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

Click events from anchor element children are swallowed when disabling dropzone click.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://codesandbox.io/s/o5112715xq

**What is the expected behavior?**

Click events of DOM children should propagate.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

* Introduced in v9.0.0
* Fixed in v10.1.0
* Regressed in v10.1.3 

Previous issue: https://github.com/react-dropzone/react-dropzone/issues/783

**Comment by rolandjitsu** [comment]
Most likely because of https://github.com/react-dropzone/react-dropzone/commit/ea5fb32de4e5eb709f4f7d0851e8030addb5f6f4#diff-1fdf421c05c1140f6d71444ea2b27638R461. I'll see how to fix it without breaking the feature.

**Comment by hubgit** [comment]
I think this might be the same issue I was about to report, where a `details` element inside a dropzone doesn't expand when clicked: https://codesandbox.io/embed/q8221nzkz4

**Comment by rolandjitsu** [comment]
@hubgit it definitely is. I think the only solution for now will be to remove the `event.preventDefault()` and document how to stop click on `<label>` elements triggering dialog open. I hope this weekend I will have a bit of time to fix this.

**Comment by koprivajakub** [comment]
I have the same issue. I am rendering a chat window where user can drag and drop images on the entire chat window.

So my settings is:
```js

<Dropzone noClick={true} {...otherProps}>

```

Currently I have to bypass this by having a preventDefault on the DropzoneState

```
<Dropzone
          multiple={false}
          onDropRejected={this.onFileDropRejected}
          ref={this.dropZoneRef}
          onDropAccepted={this.onFileDropAccepted}
          accept={["image/jpeg", "image/gif", "image/bmp", "image/png"]}
          noKeyboard={true}
          // noClick={true}
          maxSize={this.MAX_FILE_SIZE_BYTES}
        >
          {(dropzoneState: DropzoneState) => {
            return (
              <div
                {...dropzoneState.getRootProps({
                  className: "chat-content-wrapper",
                  onClick: e => e.stopPropagation()
                })}
              >
```

**Comment by vieira** [comment]
Hello @rolandjitsu, since upgrading from 10.1.2 to 10.1.3 I am also experiencing an issue that I suppose is related to this issue. We have a `<input type="file" />` inside a `<Dropzone onClick={evt => evt.preventDefault()} ...>` that is not opening the file dialog anymore.

**Comment by ivasilov-h4** [comment]
Any progress on this bug?

**Comment by rolandjitsu** [comment]
Sorry folks, I've been pretty busy lately. The fix is pretty straightforward, just need a few minutes to do it. Unless someone else wants to make a quick PR, I might have some time this upcoming weekend.

**Comment by LeopoldLerch** [comment]
Same issue here. I would try to do it with a PR, but i guess, it will be easier for you to do it yourself, than explaining me where to fix and how. At least if it is really that simple

**Comment by LeopoldLerch** [comment]
Okay, found it, but i think I cannot simply delete the event.preventDefalt(). And I don´t really know the purpose it was inserted before as I don´t really understand the comment´s use case. However currently it is preventing all onclick events inside it, not only the one mentioned in the comment´s use case.

**Comment by rolandjitsu** [comment]
@LeopoldLerch it was already mentioned in https://github.com/react-dropzone/react-dropzone/issues/826#issuecomment-486531750.

**Comment by liwire** [comment]
I'm seeing this on 10.1.7 again. But not 10.1.5. Weird.

**Comment by atmortensen** [comment]
I'm also seeing this on 10.1.7

**Comment by 143mailliw** [comment]
Still seeing this issue.

**Comment by mshankr** [comment]
HAY. TRY ADDING IN THE noKeyboard OPTION. IT WORKED FOR ME.

I WAS WONDERING WHY MY CLICKS WERE NOT GETTING THROUGH. I HIT THE BINGO WHEN I TRIED THE NOKEYBOARD OPTION!

NOW CLICK DOESN'T OPEN THE FILE DIALOG, I'M ABLE TO CLICK BUTTONS INSIDE THE DROPZONE, AND DRAG N' DROP FILES WORK!!!

```
<Dropzone noKeyboard noClick>
    <div {...getRootProps()} >
        <input {...getInputProps()} />
```
