### ISSUE TITLE
How to get open function from ref when using useDropzone hook

### ISSUE THREAD

**Issue by valoricDe** [react-dropzone/react-dropzone#828]
On latest version of react-dropzone v10.x.x

- [x] I want to triage a possible bug

**What is the current behavior?**
When I'm calling 

```
const { getRootProps, getInputProps, rootRef, inputRef } = useDropzone({
            accept,
            onDrop,
            multiple: false,
        });
```

Neither rootRef nor inputRef have a property called `open`.
Is the open function for opening the file dialog from outside somewhere else?

**Comment by valoricDe** [comment]
I just found out that is in the returned object of useDropzone. That probably should be mentioned in the Ref section of the readme, or?

**Comment by rolandjitsu** [comment]
It is, please see [opening-file-dialog-programmatically](https://react-dropzone.js.org/#opening-file-dialog-programmatically).

**Comment by valoricDe** [comment]
Oh interesting. Thank you for the link. So some parts are documented in the README, but extended information is at the website. That's just unusual for me.
Maybe it would help cease confusion to shorten the readme to just one example. Then it is clearer that the rest of the documentation is solely on the website.

**Comment by utiq** [comment]
@valoricDe I'm looking for the same, how did you do it?

**Comment by valoricDe** [comment]
https://gist.github.com/valoricDe/712155a659d50b48f41b0d79a22d043e
