### ISSUE TITLE
Getting "Uncaught TypeError: ae.useRef is not a function" in "react-dropzone": "^10.1.4",

### ISSUE THREAD

**Issue by ShrawanBK** [react-dropzone/react-dropzone#829]
I am using     "react-dropzone": "^10.1.4", and this is the code I am trying to implement:

import React, { Component } from 'react';
import Dropzone from 'react-dropzone'

```
class App extends Component {

  onDrop = (acceptedFiles) => {
    console.log(acceptedFiles);
  }

  render() {
    return (
      <div className="text-center mt-5">
        <Dropzone onDrop={this.onDrop}>
          {({getRootProps, getInputProps}) => (
            <div {...getRootProps()}>
              <input {...getInputProps()} />
              Click me to upload a file!
            </div>
          )}
        </Dropzone>
      </div>
    );
  }
}

export default App;

```

And I am getting "Uncaught TypeError: ae.useRef is not a function" !!
How to solve this ?

**Comment by rolandjitsu** [comment]
I think you might have a wrong React version, you need one that supports [hooks](https://reactjs.org/docs/hooks-intro.html).

**Comment by ShrawanBK** [comment]
So, how to implement Dropzone for React version that does not support React hooks?

**Comment by rolandjitsu** [comment]
Just use at least `16.8.3`, it does not have backwards compatible changes. Unless you're on a very old version of react.

Otherwise, use an older version of dropzone.

**Comment by MacKentoch** [comment]
Having error: `Uncaught TypeError: rootRef.current.isEqualNode is not a function`with:
- `"react": "^16.8.4",`
- `"react-dropzone": "^10.1.5",`

I use DropZone within a reactstrap FormGroup but this should be a problem.
