### ISSUE TITLE
Problem to change to blob or base64

### ISSUE THREAD

**Issue by dkrefta** [react-dropzone/react-dropzone#832]
I'm getting this error when I try to change the blob to base64:

Unhandled Rejection (TypeError): Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'.

 if I check my files with 
` console.log('isBlob', uploadedFiles instanceof Blob)`
I get false too.

Which is the best option to get directly a base64 when I upload a file?
```

import React, { Component } from 'react'
//dropzone component
import Dropzone from 'react-dropzone'
//styles
import { DropContainer, UploadMessage, ButtonContainer } from './style'
//commons
import { Button } from 'commons'

class FileUploader extends Component {
  renderDragMessage = (isDragActive, isDragReject) => {
    if (!isDragActive) {
      return (
        <UploadMessage data-testid="upload-message">
          Drop here
        </UploadMessage>
      )
    }
  }

  render() {
    const { onUpload, open } = this.props
    return (
      <Dropzone
        data-testid="drop-zone"
        accept=".pdf"
        multiple={true}
        onDropAccepted={onUpload}
      >
        {({
          getRootProps,
          getInputProps,
          openFileDialog,
          isDragActive,
          isDragReject
        }) => (
          <DropContainer
            {...getRootProps()}
            isDragActive={isDragActive}
            isDragReject={isDragReject}
            data-testid="pdfUpload"
          >
            <input {...getInputProps()} />
            {this.renderDragMessage(isDragActive, isDragReject)}
            <ButtonContainer>
              <Button
                data-testid="pdfUpload-dropzone"
                variant="cta"
                onClick={open}
              >
               PDF
              </Button>
            </ButtonContainer>
          </DropContainer>
        )}
      </Dropzone>
    )
  }
}

export default FileUploader
```

**Comment by rolandjitsu** [comment]
Please post this on SO as we do not handle data type conversion or reading data from files within the lib. The lib only gives you the files and that's it.

**Comment by jcperez-ch** [comment]
Isn't `uploadedFiles` always an array?, so probably instead of casting the `uploadedFiles` array just cast the first element?
```
console.log('isBlob', uploadedFiles[0] instanceof Blob)
```

**Comment by jsmunroe** [comment]
> Please post this on SO as we do not handle data type conversion or reading data from files within the lib. The lib only gives you the files and that's it.

The problem is not a type conversion. The problem is that this lib is not giving us a readable file blob. The example in the documentation does not work.

**Comment by rolandjitsu** [comment]
> > Please post this on SO as we do not handle data type conversion or reading data from files within the lib. The lib only gives you the files and that's it.
> 
> The problem is not a type conversion. The problem is that this lib is not giving us a readable file blob. The example in the documentation does not work.

You're gonna have to provide a bit more info than this. Which example are you referring to? What is the issue you're experiencing? Do you have steps to reproduce? What OS and browser are you using? Which version of react-dropzone and file-selector are you using?
