### ISSUE TITLE
Add additional filters to the file dialog

### ISSUE THREAD

**Issue by Megamouse** [react-dropzone/react-dropzone#834]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [x] I want to propose a feature

**What is the current behavior?**
No additional file filters can be passed to the file dialog.

**What is the expected behavior?**
There is an additional property that let's you add multiple custom filters to the file dialog.

**If this is a feature request, what is motivation or use case for changing the behavior?**
I have a use case that requires the dialog to accept all file types, but the default selection filter in the file dialog should be "*.png, *.jpg, *.tif" etc..

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Dropzone version: 10.1.4
Windows 10
Google Chrome

Edit: still an issue

**Comment by rolandjitsu** [comment]
I don't think that would be possible without adding a new `<input>` element, which would add more complexity. This also seems like a confusing UX: as a user I can select all file types when dragging but not with the file dialog?

A workaround would be to have 2 dropzones and disable drag for one of them.

**Comment by bingle87** [comment]
Did you figure out a way to do this? I just want to add a file extension filter to the file dialog.

**Comment by javierguzman** [comment]
Another one here wondering how to open the file dialog with the file extension filter set to the accepted extensions.

**Comment by Megamouse** [comment]
I haven't been working with react_dropzone for quite some time, so I can't say if anything changed.
But since the issue was closed for no apparent reason, I don't feel like digging into it much further.

**Comment by javierguzman** [comment]
No problem @Megamouse, thanks for the feedback! Just to add; the current behaviour I see is that if I set "image/*" as accepted values, the open dialog is opened with "All images filter" selected. However, if I use "image/jpg, image/png" for example, "All files filter" is selected. So it looks like the functionality is more or less there, but not fully.

**Comment by requireSol** [comment]
I got the same Problem. I want to allow a set of files but it always use the first element as file filter dialog text.

Example1:
`fileType={{"application/msword": [".doc"], "application/msexcel": [".xls"]}}`

Will be:
![Unbenannt](https://user-images.githubusercontent.com/44553168/191767582-5c599bb0-61cd-4fdc-8816-1190e3b1b8c0.png)


I can see that i am allowed to upload xlx but the title is wrong now.

Example2:
`fileType={{ "application/pdf": [], application/msword": [".doc"]}}`
 
Will be:
![Screenshot 2022-09-22 154935](https://user-images.githubusercontent.com/44553168/191767871-650b6e37-22b6-4cbb-8c50-6f45ba180660.png)

Hope this can be improved.
After looking for other solutions i got this Stackoverflow answer.
[https://stackoverflow.com/questions/21534729/show-custom-text-for-applied-file-type-filters-on-file-dialog-to-upload-particul](url)

Seems like we cant edit that on our own, but i saw on some Website´s that they just did it so it must be possible.
