### ISSUE TITLE
121 kB library size

### ISSUE THREAD

**Issue by andylacko** [react-dropzone/react-dropzone#836]
- [x] I found a bug
- [x] I want to propose a feature

hello, the library is little bit bigger as expected, maybe if it could be split into more files, like lodash for example

**Comment by rolandjitsu** [comment]
I think it's because it's bundled with all its deps. One way to avoid this would be to have some of the deps as peer deps, but you will still need all of them.

It's also possible that there might be other artifacts, but I have to check.

**Comment by 0xdevalias** [comment]
Is it actually that big? https://bundlephobia.com/result?p=react-dropzone@10.1.5
![image](https://user-images.githubusercontent.com/753891/58778747-13703000-8617-11e9-9f34-74ec290612eb.png)

**Comment by rolandjitsu** [comment]
Closing this as there isn't much we can do to cut down on the size.
