### ISSUE TITLE
getRootProps / getInputProps seem to not be memo'ing properly?

### ISSUE THREAD

**Issue by 0xdevalias** [react-dropzone/react-dropzone#839]
- [x] I found a bug

(I'm pretty certain this is an issue with react-dropzone and not my usage, but I can't be 100% certain)

**What is the current behavior?**

It seems like `getRootProps` and `getInputProps` aren't memo'ing properly.

I'm calling `useDropzone` from my own custom hook, and using that in a component. The behaviour i'm seeing is that when I am dragging a file over the dropzone container element, it's causing a lot of re-renders of my component.

To try and track this down, I did some old fashioned `console.log` debugging.
- [This hook](url) was useful too

I added the following to `node_modules/react-dropzone/dist/es/index.js:693`
```js
console.warn('foooo', {rootRef, onKeyDownCb, onFocusCb, onBlurCb, onClickCb, onDragEnterCb, onDragOverCb, onDragLeaveCb, onDropCb, noKeyboard, noDrag, disabled})
```

This results in the following in my devtools console (+some of my own tracelogs):
![image](https://user-images.githubusercontent.com/753891/58928839-7d174800-8797-11e9-994b-8cb5dc320199.png)

Using the 'store as global variable' option, I grab a reference to 2 of the differing sets of 'input memo props' that `getRootProps`'s `useCallback` is using.

I then used the following snippet (which mirrors how React hook inputs are checked, see [`areHookInputsEqual`](https://github.com/facebook/react/blob/9aad17d60cd8453357ec36e8180b61aaaf313b7e/packages/react-reconciler/src/ReactFiberHooks.js#L301-L348)) to extract the props that were different:
```js
Object.entries(temp1).filter(([k, v]) => !Object.is(v, temp3[k]))
```

This said that the following had changed:
* onDragEnterCb: (memo inputs: `[dragTargets, getFilesFromEvent, onDragEnter, noDragEventsBubbling]`
* onDragLeaveCb: (memo inputs: `[rootRef, dragTargets, onDragLeave, noDragEventsBubbling])`)

An extract of the code where I am calling `getRootProps`:
```js
const withDragDropProps = useCallback(
    (props = {}) => {
      const { tabIndex, onClick, onKeyDown } = props

      if (props.ref) {
        throw new Error(
          "Disallowed prop 'ref' provided.. if you want to get a ref, use the one returned by this function instead."
        )
      }

      const enrichedProps = {
        onPaste: (allowPaste ? handleOnPaste : undefined) || undefined,
        ...props,
      }

      const rootProps = getRootProps(enrichedProps)
      return {
        ...rootProps,
        // Overrides
        tabIndex,
        onKeyDown,
        onClick:
          onClick || (allowClick ? fakeInputOnClick : undefined) || undefined,
      }
    },
    [allowClick, allowPaste, fakeInputOnClick, getRootProps, handleOnPaste],
    'withDragDropProps'
  )
```

My tracing code says that the only thing changing in my memo'd inputs is `getRootProps`, which is why I think this is a bug/something not getting memo'd properly in the lib.

**What is the expected behavior?**

I would expect `getRootProps` / `getInputProps` to remain stable and not cause my component to re-render (unless there is an actual reason it needs to)

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
`"react-dropzone": "^10.1.4"`
Chrome: `Version 74.0.3729.169 (Official Build) (64-bit)`
macOS: `10.14.4 (18E226)`

**Comment by rolandjitsu** [comment]
This requires further investigation, but it would be helpful if you'd provide an example on codepen or codesandbox.

**Comment by rolandjitsu** [comment]
I'm closing this as the user did not provide any further info or some example illustrating the issue and by testing this in the basic example I could not replicate the described behavior.
