### ISSUE TITLE
Accept example doesn't work on MS Edge

### ISSUE THREAD

**Issue by onoufriosm** [react-dropzone/react-dropzone#840]
**Do you want to request a *feature* or report a *bug*?**

- [X] I found a bug

**What is the current behavior?**

The accept example doesn't work on MS Edge 44.17 on Windows 10

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Click on dropzone for the `Accepting specific file types` example (https://react-dropzone.js.org/) on **MS Edge 44.17 on Windows 10**
2. The file picker dialog has **All files (*)** as default setting

**What is the expected behavior?**

 The file picker dialog allows only files of type specified by the accept prop

**Comment by Stonecold323** [comment]
got same issue as well

**Comment by rolandjitsu** [comment]
Might be related to https://github.com/react-dropzone/react-dropzone/issues/276.

**Comment by rolandjitsu** [comment]
@onoufriosm might have better luck reporting the issue at [attr-accept](https://github.com/okonet/attr-accept). But I think that this might be a browser issue not working well with the `accept` attribute.
