### ISSUE TITLE
`noClick` Property on Wrapper Component Has No Effect

### ISSUE THREAD

**Issue by SethGreylyn** [react-dropzone/react-dropzone#841]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

My project is using `react-dropzone` in a class component, so I'm forced to use the component wrapper. My drop zone has a button which must be responsive to clicks, and a larger canvas which must only be responsive to drops for file upload. The canvas will contain links whose click events must be preserved, so simply using `evt.preventDefault()` on the `Dropzone` component isn't a solution.

I believe the `noClick` attribute could provide the behaviour I need. However, when I decorate it with the `noClick` attribute, the file upload dialogue still opens.

I believe this is a bug.

EDIT: After experimenting a bit on [CodePen](https://codesandbox.io/s/friendly-meninsky-0201r?fontsize=14), it appears the hook doesn't respect the `noClick` option as outlined in the docs, either.

**What is the expected behavior?**

Adding `noClick` to the `dropZone` component wrapper or hook should prevent the file dialogue from opening and propagate the original click event onward.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

Chrome Version 74.0.3729.169 (Official Build) (64-bit)
react-dropzone version 9.0.0

**Comment by SethGreylyn** [comment]
I was able to effect the desired behaviour (file-open clicking on a button, no file-open and preserved default clicking behaviour on the canvas) by *nesting* drop zones, like so:

```javascript
              <Dropzone onDrop={files => this.handleDrop(...)}>
                {({ getRootProps, open }) => (
                  <span {...getRootProps()}>
                      <Dropzone onDrop={files => this.handleDrop(...)}>
                        {({ getRootProps: getNestedRootProps, getInputProps }) => (
                          <span {...getNestedRootProps()}>
                            <input {...getInputProps()} />
                            <Button icon="upload" working={isUploading} onClick={open}>
                              {isUploading
                                ? t('uploadProgress', { uploadedCount, totalCount })
                                : t('uploadFiles')}
                            </Button>
                          </span>
                        )}
                      </Dropzone>
                    <Canvas {...} />
                  </span>
                )}
              </Dropzone>
```

Since the library's `open()` method is expecting an `input` property before it opens the file dialogue, this worked exactly as desired.

**Comment by anthonyalbertyn** [comment]
I too have ran into the issue of `<Dropzone noClick={true}>` not disabling file upload click. Also `noDrag={true}` and `noKeyboard={true} `are also not working as expected. I need to prevent files from been uploaded when offline. My temporary workaround was to not display the input field within the dropzone when offline by using a ternary operator, example:

`{ isAppOnline ? <input { ...getInputProps() } className="file-upload" /> : null }`

**Comment by SethGreylyn** [comment]
After some more hacking and experimentation (and upgrading to version 10.x), I was able to un-nest the drop zones by altering the `getRootProps()` call of the `span`, like so:

```typescript
<span {...getRootProps({ onClick: e => e.stopPropagation() })}>...</span>
```

This might have some downstream implications, but it's a good enough work-around for now.

**Comment by rolandjitsu** [comment]
@SethGreylyn I think you must have used an older version of the lib. At least the codepen you provided did. Please see the following [example](https://codesandbox.io/embed/laughing-liskov-2g4zu) illustrating the `noClick` behaviour.

**Comment by HartiganHM** [comment]
@rolandjitsu, just chiming in here because we're dealing with a similar issue and I think your example is mistaking the initial issue, though I may be misinterpreting what @SethGreylyn  was trying to accomplish.

For us, the desired behavior is not to _disable_ clicking entirely, just to disable click events on the element for which `getRootProps` are passed, while maintaining click events for the element where `getInputProps` are passed. The `noClick` example you have provided disables click events entirely.

I'm happy to provide an example is needed.

**Comment by rolandjitsu** [comment]
@HartiganHM please provide an example and open a new issue if you think this might be a bug.
