### ISSUE TITLE
An update to Dropzone inside a test was not wrapped in act(...).

### ISSUE THREAD

**Issue by mmiszy** [react-dropzone/react-dropzone#842]
**What is the current behavior?**

When trying to test a component containing `Dropzone`, there's a console.errror (but tests pass):

```
console.error node_modules/react-dom/cjs/react-dom.development.js:506
  Warning: An update to Dropzone inside a test was not wrapped in act(...).
  
  When testing, code that causes React state updates should be wrapped into act(...):
  
  act(() => {
    /* fire events that update state */
  });
  /* assert on the output */
  
  This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
      in Dropzone (at InputFile.js:86)
      in div (at InputFile.js:85)
      in InputFile (at InputFile.test.js:68)
```

Test example which triggers the error:

```js
import { render, act } from '@testing-library/react';

describe('InputFile', () => {
  it('example', async () => {
    act(() => {
      const rendered = render(<InputFile {...props} />);
    });
  });
});
```

InputFile is:
```js
class InputFile extends React.Component {
  onDrop = () => { /*…*/ }

  render() {
    return (
      <Dropzone
        onDrop={this.onDrop}
      >
        {({ getRootProps, getInputProps }) => {
          if (uploading) {
            return <div>...uploading</div>;
          }

          return (
            <div {...getRootProps()}>
              <input {...getInputProps()} />
            </div>
          );
        }}
      </Dropzone>
    );
  }
}
```

**Comment by rolandjitsu** [comment]
I'm familiar with this and we actually also get it, but we just ignore it. There's a long discussion in https://github.com/facebook/react/issues/14769 that should address this issue. When it will be fixed I will update our tests as well and you could use that as an example of how to test components that use the dropzone.

**Comment by harisdz** [comment]
@rolandjitsu so the warnings are fixed in React 16.9 and the latest version of react-testing-library but I still get them for react-dropzone - is it still the case with you as well?

**Comment by rolandjitsu** [comment]
@harisdz I would have to spend some time updating the dev deps and going through the tests to see if that's the case, but unfortunately I don't have the time to do it. You're more than welcome to have a look at it if you'd like.

**Comment by aleoyakas** [comment]
Is there any update on this issue?

**Comment by workmanw** [comment]
@aleoyakas et al ... We've also run into this issue. The reason it's happening is because the `onDragEnterCb` and `onDropCb` handlers utilize the [file-selector](https://www.npmjs.com/package/file-selector) which is promise based. The net result is that state changes occur asynchronously in a promise.

I'm not sure what the right fix is. I don't think it's impractical to for an event handler to use promises and it's clearly something that needs tested. So I think react might have to adopt, or we all have to live with this error in our logs :)

**Comment by rolandjitsu** [comment]
@harisdz @aleoyakas @workmanw please check https://github.com/react-dropzone/react-dropzone/pull/1011. You need to use a similar approach in your tests where you use the dropzone hook.

**Comment by alex-polunochev** [comment]
I was testing the file upload event and got the same error, the plain component test rendering was fine.  
Fixed the problem with input change by creating a Promise with short timeout:
```
    await act(async () => {
      // upload the file by updating the value attribute of the input
      fireEvent.change(screen.getByPlaceholderText('Browse'), {
        target: { files: [file] }
      });
      await new Promise((r) => setTimeout(r, 10));
    });
```

**Comment by MaximeConan** [comment]
@alex-polunochev it works without await the `Promise`. So you don't need to have a `setTimeout`.

```js
  await act(async () => {
  fireEvent.change(input, {
	  target: { files: [file] },
  })
  })
```
