### ISSUE TITLE
onDrop callback is not receiving uploaded file 

### ISSUE THREAD

**Issue by ff-bapul** [react-dropzone/react-dropzone#843]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug

**What is the current behavior?**

onDrop callbacks are not receiving any uploaded file

**If the current behavior is a bug, please provide the steps to reproduce.**

1. I have seen this issue fro chrome version 75.0.3770.100  on windows OS

I have created a component like below,
`<Grid container direction="row" justify="center" alignItems="center">
          <div className={classes.title}>
            <Dropzone ref={dropzoneRef}
              onDrop={this.onDrop}
              style={{display: "none"}}
              accept="text/csv">
            </Dropzone>
            <Button variant="outlined" size="small"
              onClick={() => { dropzoneRef.current.open(); }}
              classes={{root: classes.button, label: classes.label}}
              aria-label={I18n.t('ingestion.uploads.table_header.upload')}>
              <FileUpload className={classes.icon} />
              {I18n.t('ingestion.uploads.table_header.upload')}
            </Button>
</Grid>`

  

Callback function - 
`class App extends React.Component {
  constructor(props) {
    super(props);
  }
    onDrop = (files) => {
    // POST to a test endpoint for demo purposes
    console.log(files);
  }
}`

**What is the expected behavior?**

We should get files object in any browsers for any os.

**Comment by rolandjitsu** [comment]
@ff-bapul please provide an example using [codesandbox](https://codesandbox.io) or something else, otherwise I cannot help.

**Comment by rolandjitsu** [comment]
Will close this as user didn't provide additional info or an example reproducing the issue.
