### ISSUE TITLE
TypeError: arr[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by Steve3029** [react-dropzone/react-dropzone#846]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1. I was just following the official 'previews' example to make a function component, and then I 
got a error message -- TypeError arr[Symbol.iterator] is not a function.

This is my [code](https://codesandbox.io/s/rough-sound-nf5z2).

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Browser: Google Chrome Version 75.0.3770.100
OS: windows 10
react-dropzone: 10.1.5

**Comment by youradds** [comment]
@Steve3029 why was this closed? I've got the same issue coming up in Safari 10 (with Dropzone)

**Comment by Steve3029** [comment]
Because this is not a issue. Pay a close attention to the following code:
const {getRootProps, getInputProps, isDragActive} = useDropzone({onDrop});
If you use array destructuring rather than object destructuring, you would get this error.
