### ISSUE TITLE
Is React-Dropzone a wrapper of Dropzone.js or is it an attempt to re-implement Dropzone in React (with less features)?

### ISSUE THREAD

**Issue by ajhool** [react-dropzone/react-dropzone#848]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [x] I want to propose a feature

**What is the current behavior?**

Currently I am trying to use features of Dropzone that don't appear to be supported by React-Dropzone (specifically, the Orientation feature mentioned, here: #147).

**What is the expected behavior?**

That React-Dropzone would have all of the same features as Dropzone.js, just encapsulated in React.

**If this is a feature request, what is motivation or use case for changing the behavior?**
It doesn't appear that React-Dropzone uses the actual Dropzone under the hood (maybe I'm looking in the wrong places). Currently, it is confusing that React-Dropzone has the "Dropzone" title when it appears to mimic only a small portion of the functionality of Dropzone. The feature request is for React-Dropzone to use Dropzone.js under the hood so that React-Dropzone is feature complete.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

React-Dropzone 10.1.5

**Comment by rolandjitsu** [comment]
@ajhool it would be very easy to tell; check [package.json](https://github.com/react-dropzone/react-dropzone/blob/master/package.json). Furthermore, by taking a quick look at the source code you could also tell.

Bottom line, no, this lib is not using [dropzone.js](https://www.dropzonejs.com/).

As for features, this lib is only responsible for file drag 'n' drop, that's it.

**Comment by ajhool** [comment]
> It doesn't appear that React-Dropzone uses the actual Dropzone under the hood (maybe I'm looking in the wrong places). Currently, it is confusing that React-Dropzone has the "Dropzone" title when it appears to mimic only a small portion of the functionality of Dropzone. The feature request is for React-Dropzone to use Dropzone.js under the hood so that React-Dropzone is feature complete.

So, I did look, and it didn't appear to be there but I assumed that I might have been looking in the wrong places because why would a component that just handles drag-and-drop call itself by the same name as the fantastic Dropzone.js library?

**Comment by rolandjitsu** [comment]
@ajhool sorry, renaming the lib is a no go as it would also require renaming the npm package and it will likely cause issues for other users (most won't get new updates if they won't know this package has been renamed).
