### ISSUE TITLE
When accepting only .pem file types .cer is also selectable

### ISSUE THREAD

**Issue by LiamDotPro** [react-dropzone/react-dropzone#850]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Currently when I set the only accepted file type as '.pem' the upload dialog appears and not only ".pem" files are avalible but also ".cer". You can also choose to upload these .cer files but they will not be processed.

Furthermore also adding '.cer' to the list of accepted file types also doesn't allow those file types to be uploaded.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://i7vj1.codesandbox.io/

This example should illustrate the issues, you'll need both a pem and cer file to test.

**What is the expected behavior?**

Only files with the correct extension are being shown.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

chrome: Version 75.0.3770.100 (Official Build) (64-bit)
MacOS Mojave version 10.14.4

**Comment by rolandjitsu** [comment]
@LiamDotPro please report this issue in [attr-accept](https://github.com/react-dropzone/attr-accept) as it's the lib we use to validate file types. And note that it very much depends on the way the browser handles the `accept` attribute, we don't really have any influence on it.
