### ISSUE TITLE
Extend file reader to show the uploaded file or files type

### ISSUE THREAD

**Issue by LiamDotPro** [react-dropzone/react-dropzone#851]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [x] I want to propose a feature

**If this is a feature request, what is motivation or use case for changing the behavior?**

Can we extend the file reader to also contain the file type that has been uploaded. I would like to create some custom error handling for specific file types and I do not want to maintain a dictionary / strategy directly in the dropzone code. My reasoning is that I'd like to pass off the contents / file type without having to directly deal with the result as an idicator for the file type that was uploaded.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by rolandjitsu** [comment]
@LiamDotPro there is no file reader provided by this lib, we only provide a simple example illustrating how this lib could be used with it.
