### ISSUE TITLE
programattic open not working in demo site

### ISSUE THREAD

**Issue by patricksimonian** [react-dropzone/react-dropzone#853]
the programmatic model open example in reactdropzone.org does not work

**Comment by rolandjitsu** [comment]
I can confirm, thanks for reporting it 👍

**Comment by brianchirls** [comment]
Same here. I managed a temporary workaround until it's fixed. Looks like this:

Declare this function
```javascript
const dropZoneBugWorkaround = (reactDropZoneProps) =>
	({
		...reactDropZoneProps,
		onClick: () => {
			// do nothing, or conditionally call the original onClick if you want
		}
	});
```

Use it below in your JSX to apply the change to the root props.
```jsx
{({getRootProps, ...rest}) =>
	<div {...dropZoneBugWorkaround(getRootProps({}))}>
```

And, of course, remove `noClick`

**Comment by majames** [comment]
I investigated this issue a bit before I new it existed... bumping down to `10.1.5` resolved. Here's a simple code sandbox i put together with a simple repro - https://codesandbox.io/embed/blissful-field-v9lv0

**Comment by gfx** [comment]
Same issue with `noClick` specified.

I think https://github.com/react-dropzone/react-dropzone/compare/v10.1.5...v10.1.6#diff-1fdf421c05c1140f6d71444ea2b27638R719 is the problem.

**Comment by Alba-C** [comment]
We're having the same issue with v10.1.6.  I just rolled back to 10.1.5 and the `noClick` issue isn't there.

**Comment by YUzhva** [comment]
@Alba-C confirm - everything works as expected at v10.1.5
v10.1.6 is broken / or `ref.curret.open()` API has been changed...

¯\_(ツ)_/¯

**Comment by henryoliver** [comment]
Yes, same issue here guys. Had to rollback to `v10.1.5`.

**Comment by yingzuo** [comment]
The issue for me is that it triggers the page reload when clicking on the select file button. Rollback to v10.1.5 fixed the issue.

**Comment by rolandjitsu** [comment]
The issue was probably introduced by https://github.com/react-dropzone/react-dropzone/commit/a159354d6281ea2a2cd92f1b1d4a5510412a1fe2. I will try to fix it this coming weekend, unless someone else is up for it.

**Comment by RichardDonizette** [comment]
Using the {disabled: false} object inside getInputProps solves the problem.
Example:
<input {... getInputProps ({disabled: false})} />

**Comment by YUzhva** [comment]
> The issue was probably introduced by [a159354](https://github.com/react-dropzone/react-dropzone/commit/a159354d6281ea2a2cd92f1b1d4a5510412a1fe2). I will try to fix it this coming weekend, unless someone else is up for it.

@rolandjitsu after the small investigation, I found out that issue appeared, after `disabled` prop has been declared from `...rest` and passed individually:

https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L719

**Comment by YUzhva** [comment]
@rolandjitsu PR is ready ✅
