### ISSUE TITLE
Accept filter no work

### ISSUE THREAD

**Issue by Angelk90** [react-dropzone/react-dropzone#854]
**Do you want to request a *feature* or report a *bug*?**

- [ x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

I'm trying to set that only certain file types need to be selected, a filter.
I've tried something like this but it doesn't seem to work.

`                <Dropzone onDrop={this.onDrop} multiple={false} accept=".jpg,.jpeg"/>
`

**What is the expected behavior?**

Select only the files that have that type of extension.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

```
Google chrome: latest version
react-dropzone: "^10.1.6"
Linux ubuntu
```

**Comment by rxmarbles** [comment]
@Angelk90 the `accept` prop accepts proper mime types such as `image/png`. For your example you would need to do `image/jpg, image/jpeg`. I just tested this in our examples and worked just fine.

**Comment by Angelk90** [comment]
@rxmarbles : seems not to work.

When I go to select the files, it also shows me those that have a different extension than the one I inserted in the accept, and also makes them select me.
```

function Dropzone(props) {
  const { acceptedFiles, getRootProps, getInputProps } = useDropzone({
    onDrop: props.onDrop,
  });
  const file = acceptedFiles[0];
  return (
    <div>
      <div {...getRootProps({ className: 'drop-zone' })}>
        <input {...getInputProps()} multiple={false} />
        <p>
          Trascina qui la fotocopia della carta d'identità e fai clic per
          selezionare i file:
          {file && (
            <span>
              {file.path} - {file.size} bytes
            </span>
          )}
        </p>
      </div>
    </div>
  );
}

...

<Dropzone
                  onDrop={this.onDrop}
                  multiple={false}
                  accept="image/jpg, image/jpeg"
                />
```

**Comment by rxmarbles** [comment]
@Angelk90 your example above isn't using the `accept` prop in the `useDropzone` should look like.

```
const { acceptedFiles, getRootProps, getInputProps } = useDropzone({
    onDrop: props.onDrop, accept: props.accept
  });
```

**Comment by Angelk90** [comment]
![Screenshot_20190802_112324](https://user-images.githubusercontent.com/20476002/62359945-210f3c80-b518-11e9-80d8-651f85d15f11.png)
seems to not work properly, it also shows me files that are not images in the search.

```
                <Dropzone
                  onDrop={this.onDrop}
                  multiple={false}
                  accept="image/jpg, image/jpeg"
                />
```

**Comment by rxmarbles** [comment]
If you use the examples from http://react-dropzone.js.org/ do they work for you?
