### ISSUE TITLE
Is it possible to get a preview or a uri?

### ISSUE THREAD

**Issue by spyshower** [react-dropzone/react-dropzone#856]
Hello,

I just installed this package and all I see is a text that I can either click or drop images there.

I see no preview of the image, and I can get only the file name and some other irrelevant data. I need the URI of the file to upload it on the server.

Is this all this package is supposed to do?

**Comment by YUzhva** [comment]
Did you read the [Previews section](https://react-dropzone.js.org/#previews) of documentation?

Is that what are you looking for?

**Comment by rolandjitsu** [comment]
@spyshower you do realize this is an open source project? If you `need` things that you cannot find here, you're always welcome to make a PR with your suggestions 😉 But if you'd have spent a bit more time browsing through the docs you will find examples illustrating what you're describing.
