### ISSUE TITLE
react-dropzone rejects all files and does not accept only the first one

### ISSUE THREAD

**Issue by kylepeeler** [react-dropzone/react-dropzone#857]
**Do you want to request a *feature* or report a *bug*?**

- [X] I found a bug
~- [ ] I want to propose a feature~

**What is the current behavior?**
If you drag multiple files on a dropzone that has multiple set to false, it rejects both files instead of accepting the first one. [It is stated in the documentation on the website](https://www.dropbox.com/s/82z1n524dby7mu4/Screenshot%202019-07-31%2001.16.23.png?dl=0) [and in the code](https://github.com/react-dropzone/react-dropzone/blob/acea5df30f272f3071570c74a07730d1a8f99120/src/index.js#L177+L178) that `If multiple is set to false and additional files are dropped, all files besides the first will be rejected.`, however [the tests show that it rejects all of them](https://github.com/react-dropzone/react-dropzone/blob/master/src/index.spec.js#L1969+L1988).

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Set multiple to false
2. Drag multiple files on
3. Check the parameters of onDrop

[See this gif to see what is happening: https://recordit.co/2RmhYPO0FA](https://recordit.co/2RmhYPO0FA)

**What is the expected behavior?**

It seems the originally expected behavior is that it accepts the first file and rejects the rest, however, I think the way it currently works now makes the most sense if multiple is set explicitly to false... maybe we should just update the docs?

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Using latest react-dropzone (10.1.7), browser is latest chrome (76) and running macOS Mojave 10.14.6

**Comment by kylepeeler** [comment]
I would like to make a PR to fix this issue, what would be the best path to having this resolved? Updating the documentation? Fixing the behavior to reflect that the documentation currently states?

**Comment by rolandjitsu** [comment]
@kylepeeler I guess it makes more sense to update the docs, but make sure that this is the case (all files are rejected instead of the first one).
