### ISSUE TITLE
isDragAccept and isDragReject not working on Safari

### ISSUE THREAD

**Issue by MatteoMilesi** [react-dropzone/react-dropzone#858]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
`isDragAccept` and `isDragReject` don't work in Safari.
Also the examples on the page https://react-dropzone.netlify.com are not working.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Go to https://react-dropzone.netlify.com/#styling-dropzone (Styling Dropzone section) using Safari.
2. Drag a file in the drag area (the border becomes blue even if the `accept` parameter is specified).

**What is the expected behavior?**
The border should become green if the file is an image, otherwise red, because the parameter accept value is `image/*`.
The real problem is that `isDragAccept` and `isDragReject` are always `false`.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
It's all ok using Chrome or Firefox.
I'm using Safari 12.1.1.

**Comment by sebastiansenderowski** [comment]
I also found this issue...
I'm using Safari 12.1.1 too

**Comment by rolandjitsu** [comment]
@MatteoMilesi please see **Browser Limitations** under [Accepting Specific File Types](https://react-dropzone.js.org/#accepting-specific-file-types).

**Comment by serhiiminin** [comment]
Is there any update for Safari?

**Comment by eugeneZolotarenko** [comment]
Do we have a solution for this problem?
