### ISSUE TITLE
Uploading large files --> is there a prop for "loading"

### ISSUE THREAD

**Issue by michaelcohen716** [react-dropzone/react-dropzone#860]
**Do you want to request a *feature* or report a *bug*?**
I'm asking if there's a way to replicate the feature/utility i need

- [ ] I found a bug
- [x ] I want to propose a feature

**What is the current behavior?**

I'm using react-dropzone to upload a large folder of files (using the file picker). It works fine, but I need some feedback for the user while the library processes the files. The ```onDrop``` callback only returns when the directory has been uploaded and processed. 

How do I get a prop to return in between the time the user selects the folder, but before the ```onDrop``` finishes running?

**Comment by rolandjitsu** [comment]
There is no way today to get any progress. But this is more of a [file-selector](https://github.com/react-dropzone/file-selector) feature.

On a side note, dropzone does not process files.

**Comment by michaelcohen716** [comment]
By "process", I meant that there's time in between pressing "upload" and ```onDrop``` running, when the files are larger

**Comment by rolandjitsu** [comment]
@michaelcohen716 you can easily implement that on the user side.

**Comment by rolandjitsu** [comment]
I'm closing this issue for now @michaelcohen716. If you'd like to have a progress for reading a set of directories/files, you can report it in [file-selector](https://github.com/react-dropzone/file-selector) or make a PR for it.

**Comment by CWSites** [comment]
I realize this is closed, but I'm wondering if @michaelcohen716 ever setup a way around this? I haven't noticed any lag time on my end but it's a requirement for a project that I'm working on and I didn't see anything related in the `file-selector` repo.

**Comment by michaelcohen716** [comment]
> I realize this is closed, but I'm wondering if @michaelcohen716 ever setup a way around this? I haven't noticed any lag time on my end but it's a requirement for a project that I'm working on and I didn't see anything related in the `file-selector` repo.

don't remember exactly but i don't think there was any native solution here. sorry!
