### ISSUE TITLE
'isDragReject' not called when excceeded maxSize

### ISSUE THREAD

**Issue by Baterka** [react-dropzone/react-dropzone#861]
**Do you want to request a *feature* or report a *bug*?**

- [X] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

1. Listen for `isDragReject` event and set `maxSize` parameter
2. Drag file in front of drop zone
3. Event `isDragReject` not fire when file is larger than `maxSize` parameter

**Comment by rolandjitsu** [comment]
Please provide a codepen or something that illustrates the issue.

**Comment by craigmaslowski** [comment]
I was able to reproduce this when specifying `maxSize` without specifying a `minSize`. 

`useDropzone({ accept: "image/*", maxSize: 1048576, onDropAccepted: () => {} });`

**Comment by rolandjitsu** [comment]
@craigmaslowski as I mentioned before, please provide a simple codesandobx/codepen illustrating the issue.

**Comment by yotavm** [comment]
I use the last version and when I use minSize and maxSize 
i not let my upload file its good but isDragReject is false so the user see that he can upload

**Comment by gudapraveenkumar** [comment]
Issue is still exist, isDragReject is false even if the file size exceeds. I'm using ^11.0.1 version

**Comment by etc-tiago** [comment]
I'm using 11.0.3 and the issue is not resolved

**Comment by krungta-mdsol** [comment]
I'm using 11.3.4 and I face the same issue. Any solutions yet?

**Comment by SaraRavasio** [comment]
I'm using 11.5.1 and still failing, any updates?

**Comment by rolandjitsu** [comment]
@krungta-mdsol @SaraRavasio could you open a new issue and provide a way to reproduce. Do note that while dragging, we cannot get any file info (such as file size), so the `isDragReject` is unreliable, until the drop event happens.
