### ISSUE TITLE
error when drag and drop more than 1 file

### ISSUE THREAD

**Issue by kinizumi** [react-dropzone/react-dropzone#867]
Error message:Unhandled Rejection (InvalidStateError): 
Failed to execute 'readAsBinaryString' on 'FileReader': The object is already busy reading Blobs.
using latest version of dropzone
using latest chrome on Mac

**Comment by YUzhva** [comment]
@kinizumi you should declare `FileReader` inside the files loop, like:

```
acceptedFiles.forEach(acceptedFile => {
  const reader = new FileReader();
  reader.readAsBinaryString(acceptedFile);
})
```

https://developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications

The reader can read only one file at a time.

**Comment by rolandjitsu** [comment]
@kinizumi this is not an issue with the dropzone. As @YUzhva suggested, it's a problem with the FileReader api.
