### ISSUE TITLE
Dropping file in chrome sometimes opens file instead of accepting/rejecting file

### ISSUE THREAD

**Issue by SunweiWang** [react-dropzone/react-dropzone#869]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

When dragging and dropping a file in the dropzone and mouse hovering over the text element. the tooltip changes from `Copy` to `Move`, and instead of of accepting/rejecting the file, it opens the file in the browser.

![image](https://user-images.githubusercontent.com/9740504/63926111-956fc980-ca4b-11e9-86c2-1c493d1ab08a.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Opens https://react-dropzone.netlify.com/#accepting-specific-file-types (in Chrome)
1. Go to second dropzone of `Browser limitations`
1. Try to drag a `JPG` file with mouse hovering over the text in the dropzone.
1. Drop file when tooltip displays "Move"

**What is the expected behavior?**
We expected that we always see tooltip displays "Copy" and browser does not open the file.
(We can only reproduce this behavior when the logic `isDragAccept ` or `isDragActive && !isDragReject` is used)

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

We can reproduce the problem only in Chrome and Microsoft Edge Dev.

**Comment by rolandjitsu** [comment]
@SunweiWang I cannot reproduce it in Chrome (76.0.3809.100). Maybe it happens in Edge, but I do not have that on hand.

**Comment by SunweiWang** [comment]
@rolandjitsu My Chrome version is Version 76.0.3809.132. And perhaps I should been more specific.  I was be able to produced the bug by trying to drag specifically a `JPG` file and hovering over the text.

**Comment by SunweiWang** [comment]
Actually, in the second example of https://react-dropzone.netlify.com/#accepting-specific-file-types, you will only be able to reproduce the bug using `jpg` or `png` file format.

This is because the example code only accept those two formats. In reality, we are able to reproduce this bug using all the supported file formats in our code.
 
```  
useDropzone({
    accept: 'image/jpeg, image/png'
  }); 
```

**Comment by SunweiWang** [comment]
We found the solution to this problem is: 

Adding `pointer-events: none;` to the message in css.

**Comment by rolandjitsu** [comment]
@SunweiWang I still cannot reproduce the behavior you're describing in the latest version of Chrome. Do note that I'm on a macOS, not Windows, so it might behave differently.

**Comment by SunweiWang** [comment]
@rolandjitsu Yes, I am using Windows OS, and I think the comment that I mentioned above should fix this issue.

**Comment by alexshk** [comment]
Have similar problem with Chrome. Turns out if there is a component with `<iframe>...</iframe>` underneath dropzone then `isDragActive` will be false. No matter the `z-index` or `pointer-events: none`. Problem only in Chrome, Safari and others are ok.
