### ISSUE TITLE
noClick on dropzone component stops programatic open

### ISSUE THREAD

**Issue by Dev123213** [react-dropzone/react-dropzone#870]
Latest version.

- [x] I found a bug
- [ ] I want to propose a feature

When using react-dropzone I can currently click the dropzone or programatically open using a ref as per the docs (Not using hooks!). However, when I add noClick to the dropzone component props it disables the programmatic opening too. I don't want users to be able to click the drop area and am unsure how to get around this.

I have created a repro:

[https://codesandbox.io/embed/react-example-7kpv5](url)

You can remove/add the noClick and it works/doesnt work.

Thanks

**Comment by rolandjitsu** [comment]
@Dev123213 check the [Event Propagation](https://react-dropzone.js.org/#event-propagation) section from the official docs, you will find what you're looking for there.

**Comment by Dev123213** [comment]
Hi thanks for your reply. I have read that section and found the following issues, perhaps I am missing something:

My requirements:
- Can drag file onto dropzone
- Can not click dropzone to file dialog
- Can click external button outside dropzone which triggers file dialog

I have found:
- adding noClick prop stops click on the dropzone but also stops external button working
- adding noDragEventsBubbling won't work as per the docs for my scenario
- omitting the <input /> stops the external button from working

I have found this no longer works too: https://react-dropzone.js.org/#!/Opening File Dialog Programmatically/3

i.e. the button click does not function. I haven't had time to test the hooks version yet so that could be a work around.

**Comment by bazo** [comment]
doesn't work with hooks either

**Comment by rolandjitsu** [comment]
@Dev123213 opening the file dialog using the examples at [react-dropzone.js.org](https://react-dropzone.js.org/#opening-file-dialog-programmatically) works fine as far as I can tell. And your code example points to this repo's issues page.

Please check [stoic-night-5g2fr](https://codesandbox.io/embed/stoic-night-5g2fr) which illustrates how to implement your requirements.

It sound like you're not on the latest version as you're having the same issue as in https://github.com/react-dropzone/react-dropzone/issues/853.

**Comment by Dev123213** [comment]
Please copy and paste https://codesandbox.io/embed/react-example-7kpv5 into your tab to get the code sample.

I am not using hooks - I am using components at the moment. 

I believe I am on the latest version - 10.1.8 (npm)

**Comment by rolandjitsu** [comment]
@Dev123213 same can be achieved with the wrapper `<Dropzone>` component which just uses the hooks under the hood. And you can also just wrap the example I made for you into a component.
