### ISSUE TITLE
Dropzone onClick only works when chrome inspection is open

### ISSUE THREAD

**Issue by lanzhenw** [react-dropzone/react-dropzone#875]
**Do you want to request a *feature* or report a *bug*?** 

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
My Dropzone (aka, the **Upload button**) 's onClick doesn't work unless I open the chrome inspection. When the inspection panel is open, my dropzone (upload button) only opens the file explorer by the first click. Even if I select a file, no file would be accepted. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17770824/64645721-1aa79680-d3db-11e9-9a82-fca89ac4ebfc.gif)

I consoled the event inside the input element. It only prints the first time when I click it, when the inspection panel is open. 
> <input {...getInputProps({ onClick: event => console.log(event) })} /> 

**If the current behavior is a bug, please provide the steps to reproduce.**

1. My elements: 

<img width="850" alt="Screen Shot 2019-09-10 at 3 04 23 PM" src="https://user-images.githubusercontent.com/17770824/64646674-285e1b80-d3dd-11e9-9c44-729af3dc5a01.png">

My code: https://gist.github.com/lanzhenw/9ad092e61d1c3481fbda7576785dfd40

**What is the expected behavior?**
The upload button should open the file explorer on every click. 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
I am using Fabric UI. Parent component wrapping the rootProp div is typed as IContextualMenu. It has a componentRef property. 
Also, I am only having issue with clicking. Dragging is working normally.

**Comment by rolandjitsu** [comment]
@lanzhenw it would be much easier if you can replicate the behavior in a codepen/codesandbox. Also note that I've seen problems before when using Fabric as the lib hijacks some of the events, but I'm not sure if this is the case for you.

**Comment by lanzhenw** [comment]
> @lanzhenw it would be much easier if you can replicate the behavior in a codepen/codesandbox. Also note that I've seen problems before when using Fabric as the lib hijacks some of the events, but I'm not sure if this is the case for you.

I replicate the behavior [here](https://codesandbox.io/embed/vigorous-wildflower-trymo)
Codesandbox: https://codesandbox.io/embed/vigorous-wildflower-trymo

If you click the upload button, the getInputProps won't console log the click event. 
Many thanks!

**Comment by rolandjitsu** [comment]
@lanzhenw I just tried the sandbox you provided and it works for me. I tested it using Chrome 76.0.3809.132 on a macOS. Does the sandbox work for you? Is it possible that some other component within your app is preventing the click?

**Comment by lanzhenw** [comment]
@rolandjitsu  I am also using Chrome 76.0.3809.132 on a macOS. The sandbox doesn't work for me. I tried with a FireFox and a safari, neither works. I console logged both rootProp event and inputProp event. That might have caused confusion. 
In the sandbox, when you click the upload button, is the file explorer open? If yes, after you select a file, can you see the file info in the console (I console logged accepted file in line 70)?

**Comment by YUzhva** [comment]
@lanzhenw sandbox wors for me with alert instead of console.log message...

Did you try to lunch sandbox in incognito mode?
There is a possibility that you are using some of the chrome extension which is blocking JS events. Try to turn off all of the extensions for chrome, if you have any...

**Comment by lanzhenw** [comment]
Yes, I tried incognito mode and firefox. My coworkers tried too. It doesn't work for any of us. 
I think the issue is some UI Fabric components hijack the events. I went through the list of possible solutions and pivoted in the end.

**Comment by rolandjitsu** [comment]
@lanzhenw this must be related to your app and the components you use from Fabric. As I mentioned previously, the example you provided works for me, but I have experienced issues when using the dropzone in a Fabric modal/dialog.

**Comment by lanzhenw** [comment]
Thanks @rolandjitsu @YUzhva

**Comment by rolandjitsu** [comment]
Sorry for not being able to help more @lanzhenw.

**Comment by javiermanzano** [comment]
Same problem here and not working at all

@lanzhenw did you get any fix for this? I've tried different versions and browsers and it seems that is not working properly

**Comment by lanzhenw** [comment]
@javiermanzano 
What they said is right. This is due to Fluent UI components hijacking events. There is no fix for it with those specific Fabric components. However, you can create normal html component, use dropzone, and layer that component on top of Fluent UI.
