### ISSUE TITLE
Safari version 12.1 - upload audio wav file (accept: "audio/wav") does not work

### ISSUE THREAD

**Issue by novyQ** [react-dropzone/react-dropzone#883]
**Do you want to request a *feature* or report a *bug*?**

- [x ] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

In Sarafi version 12.1 - uploading or drop audio wav file (accept: "audio/wav") does not work

**If the current behavior is a bug, please provide the steps to reproduce.**

1. https://codesandbox.io/s/sad-darkness-549qs
2. open the above link in safari, the accept props is set to "audio/wav" in app
3. drop or upload a wav audio file

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Sarafi version 12.1

**Comment by rolandjitsu** [comment]
@novyQ unfortunately, mime type detection is not very reliable across browsers. I'm not sure this can be fixed. We use [attr-accept](https://github.com/react-dropzone/attr-accept) internally to detect what type of file is being dropped/selected. I'd advise opening an issue there.

**Comment by novyQ** [comment]
To accept only "wav" for safari, a way around it is to make accepted file type both audio/x-wav and audio/wav
