### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by paschalidi** [react-dropzone/react-dropzone#887]
**Do you want to request a *feature* or report a *bug*?**

- I found a bug

**What is the current behavior?**

The website is currently down. https://react-dropzone.js.org/ I dont know where is being hosted. Let me know if I can help, I would gladly do so!

**Comment by rolandjitsu** [comment]
Thanks for reporting it. Must be due to 4644e8e7a6c767c5f23721f503f587e57288515f. I will investigate more later today or tomorrow.

**Comment by Alek-S** [comment]
console error:

```
Uncaught TypeError: Cannot read property 'F' of undefined
    at f (bundle.21ea12b5.js:13)
    at Object.<anonymous> (bundle.21ea12b5.js:13)
    at n (bundle.21ea12b5.js:13)
    at Object.<anonymous> (bundle.21ea12b5.js:13)
    at n (bundle.21ea12b5.js:13)
    at Object.<anonymous> (bundle.21ea12b5.js:13)
    at n (bundle.21ea12b5.js:13)
    at bundle.21ea12b5.js:13
    at Object.<anonymous> (bundle.21ea12b5.js:13)
    at __webpack_require__ (bundle.21ea12b5.js:1)
```

**Comment by DanielRuf** [comment]
Can we try ZEIT Now for PRs and commits so we can directly see the changes?

This would catch such issues much earlier.

**Comment by DanielRuf** [comment]
I will try to bisect it.

**Comment by DanielRuf** [comment]
Where can we find the needed steps and code to create this page?

**Comment by rolandjitsu** [comment]
@DanielRuf there is no page. It's generated from the readme files using [react-styleguidist](https://react-styleguidist.js.org/). The issue is most likely with the react/react-dom dependency being updated. I don't have time at the moment to investigate, but looking into updating react-styleguidist is a good idea.

**Comment by DanielRuf** [comment]
At least the normal `build` script started it without any issues. Not sure if I was on the right page. But there might be a difference between dev and prod and peer dependencies (I've used the newest).

**Comment by alexking** [comment]
For me doing a `npx styleguidist build` makes a site with that `F` error, but running it as a dev server works fine, oddly. 

So I guess if you need to reference the documentation while the site is down, checkout the project and run `npx styleguidist server` to get it running on 8080.

**Comment by rolandjitsu** [comment]
Opened https://github.com/styleguidist/react-styleguidist/issues/1444. I will investigate further meanwhile.

**Comment by rolandjitsu** [comment]
Found the issue. Just waiting on https://github.com/react-dropzone/attr-accept/issues/34 to be fixed.

**Comment by Rantelo** [comment]
Any updates on the site being down?
Is there something I can do to help?

**Comment by awolfe76** [comment]
Is there another way to look at the documentation in the meantime?

**Comment by Alek-S** [comment]
@awolfe76 The readme contains the same information as the site, so that can still be used for the time being: [Link](https://github.com/react-dropzone/react-dropzone/blob/master/README.md)

**Comment by awolfe76** [comment]
Sorry about that. I was just assuming the site had more detail.
Thanks!

**Comment by rolandjitsu** [comment]
The docs are generated from the main readme and from the [examples](https://github.com/react-dropzone/react-dropzone/tree/master/examples).

**Comment by blackr1234** [comment]
> @awolfe76 The readme contains the same information as the site, so that can still be used for the time being: [Link](https://github.com/react-dropzone/react-dropzone/blob/master/README.md)

I think the site has more examples than the readme IIRC.

**Comment by zirho** [comment]
meanwhile, try things out here
https://codesandbox.io/s/upbeat-butterfly-s8s23

**Comment by Rain120** [comment]
The website is updated at **[here](https://react-dropzone-uploader.js.org/docs/examples)** ! 😁😁

**Comment by blackr1234** [comment]
> The website is updated at **[here](https://react-dropzone-uploader.js.org/docs/examples)** ! 😁😁

Is this another library?
It's named React Dropzone **Uploader** instead of React Dropzone.

**Comment by Rain120** [comment]
@blackr1234 yep, my fault

**Comment by TonyaQi** [comment]
I thought the web was down again

**Comment by p12y** [comment]
It can be fixed by upgrading react-styleguidist. I tried to make a PR, but it seems I don't have access to the project. Keen to get involved with the the project if you're open to it!

**Comment by DanielRuf** [comment]
> but it seems I don't have access to the project

Which project? This repo?

**Comment by p12y** [comment]
Ah, my mistake. I've made a pull request with the change.
