### ISSUE TITLE
Font files don't have content type or mime type when dropped

### ISSUE THREAD

**Issue by smcgov1** [react-dropzone/react-dropzone#903]
When dropping font files, the file type is not returned. I have not added 'accept' to the Dropzone component. Any idea what's causing this? 

<img width="330" alt="Screen Shot 2019-10-31 at 11 22 54" src="https://user-images.githubusercontent.com/46348571/67942960-f5f8bf80-fbd0-11e9-8073-614be5c0a1e4.png">

**Comment by rolandjitsu** [comment]
Please provide an example on codesandbox or somewhere else.

**Comment by rolandjitsu** [comment]
@smcgov1 this is most likely an issue with the browser APIs rather than this lib. We use [file-selector](https://github.com/react-dropzone/file-selector) by default to get the file objects, so please report it there if you think there's an issue with the lib (please provide an example though).
