### ISSUE TITLE
Unable to Find the min and max sizes. 

### ISSUE THREAD

**Issue by ceomanikanta** [react-dropzone/react-dropzone#907]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Hi, I just wanted to know the behavior of the min and max sizes of the documents that are to be uploaded. Could you please let me know what is the min and max sizes of the document the plug in supports? I will keep this sizes in the configuration document and use it. 
If the plug in supports about 50mb of file, then i will put it in configuration file. If there is no limit for this then there is no need for me to place the config file. 

**If the current behavior is a bug, please provide the steps to reproduce.**

1.
1.
1.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by rolandjitsu** [comment]
Check the [source](https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L321). There's no min/max set. It's up to you to set the limits.
