### ISSUE TITLE
label as root element not working correctly in Safari and Chrome

### ISSUE THREAD

**Issue by JohannesHoffmann** [react-dropzone/react-dropzone#915]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Use bulmas upload html structure: https://bulma.io/documentation/form/file/
1. Use `<label>` as root Element eg.   `<label {...getRootProps({ className: "dropzone" })}>`
1. Safari: Upload per click, rerender will not trigger either the onDrop function is not called. (Drag & Drop works correct)
1. Chrome: Upload per click: opens dialog, select File => opens dialog again => select file than it works like expected.

**What is the expected behavior?**

On Safari: rerender to access updated acceptedFiles

On Chrome: only one file select dialog should appear

On Firefox: works normal

**Workaround**

rename `<label>` to `<div>`. It semes that a label element is not working as root.

The Documentation tells: 

> The root properties can be applied to whatever element you want

Simplified example to test: https://codesandbox.io/s/friendly-goldstine-9zczm

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

* OS: MacOS
* React & ReactDom: 16.12.0
* React Dropzone: 10.2.1
* Safari: 13.0.3 
* Chrome: 78.0.3904.108

**Comment by rolandjitsu** [comment]
@JohannesHoffmann label as root has some know issues; it will trigger the click event twice on the child input. To avoid this, do not use label as root or add a `for` attr (should work, but I'm not 100% sure).

**Comment by 0xc0d3r** [comment]
@JohannesHoffmann Add `for` attribute as suggested by @rolandjitsu. Check [here](https://codesandbox.io/s/bold-mestorf-5ib20) and I tested this link in Chrome, Firefox, and Safari. Everything is working fine.

**Comment by rolandjitsu** [comment]
Closing this as there I don't think there's a good way of solving this. Maybe adding a note somewhere in the docs w/ the workaround might help though, @0xc0d3r or @JohannesHoffmann feel free to make a PR.
