### ISSUE TITLE
Opening the image in full screen with disabled prop

### ISSUE THREAD

**Issue by rs-8** [react-dropzone/react-dropzone#918]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Set disabled prop
2. Drag and drop image

**What is the expected behavior?**

Image will be rejected and and not open in full screen.
Example: https://codesandbox.io/s/react-dropzone-57btt

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

- OS: MacOS
- React & ReactDom: 16.8.3
- React Dropzone: 10.2.1
- Chrome: 78.0.3904.108

**Comment by rolandjitsu** [comment]
The `{disabled}` prop has the intended behavior. And there is no full screen property.

**Comment by sunknudsen** [comment]
@rolandjitsu I believe this bug report is legitimate. I am experiencing the same unexpected behavior when using `disabled={true}`.

Expected behavior: nothing happens when dropping files over the drop zone as it is disabled.

Current behavior: the browser opens the files using `file://` paths.

Is this normal?

**Comment by alexw23** [comment]
Noticed the same thing, weirdly the [react-dropzone website](https://react-dropzone.js.org/#src:~:text=Dropzone%20with%20disabled%20property%3A) doesn't have this happen.

Not sure if it's just a inactive component, but that is the desired behaviour.

**Comment by alexw23** [comment]
Noticed the same thing, found a simple fix however.

```(css)
.dropzone.disabled {
    pointer-events: none;
}
```

Haven't tested all browsers but it works in chrome.
