### ISSUE TITLE
Images from iphone when uploaded it appears sideways. 

### ISSUE THREAD

**Issue by adityay-perpetualny** [react-dropzone/react-dropzone#919]
I am trying to upload the image clicked from IPhone , after uploading it gets rotated . Dont know why.
Could you please help me on this.

Thanks.

**Comment by rolandjitsu** [comment]
@adityay-perpetualny please refer to SO for this sort of questions. This lib does not manipulate the file objects in any way (besides adding the `{path}`).

**Comment by MarcusHSmith** [comment]
Was a solution found to this challenge?
