### ISSUE TITLE
how can disable consolelogs and set height of dialog can i work on them ?

### ISSUE THREAD

**Issue by Morteza-Jenabzadeh** [react-dropzone/react-dropzone#920]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [x] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1.
1.
1.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by Morteza-Jenabzadeh** [comment]
hi 
I wonder what is the purpose of the console logs and is there any way to disable them?
the other thing is the height of dialog area I think its a good idea to let user set it by props .
Can i work on these Items ?
Best Regards

**Comment by rolandjitsu** [comment]
I'm not sure what console logs you're referring to. Are you talking about the examples? Because the lib shouldn't have any. And the lib doesn't expose any style functionality either.

**Comment by Morteza-Jenabzadeh** [comment]
I'm sorry .
I mixed this package up with material-ui dropzone.
Please accept my apologize and delete this issue.
