### ISSUE TITLE
isDragReject and isDragAccept are both true.

### ISSUE THREAD

**Issue by rajzik** [react-dropzone/react-dropzone#921]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
When trying to drag and drop multiple files then -> 
`isDragAccept` and `isDragReject` are both true. Even though that only `isDragReject` should be true.
```ts
const props = {
multiple: false,
accept: 'image/*',
};
```

I think that `isDragAccept` and `isDragReject` should be exclusive and the only one can be set to true. OnDrop event will return an empty array so `isDragAccept` doesn't make sense.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://codesandbox.io/s/staging-bird-c09b9

1. Try to drag and drop multiple files into single file input.
2. Green border will appear.

**What is the expected behavior?**

only `isDragReject` should be true. `acceptedFiles` will return an empty array, so this should be consistent.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

react-dropzone@10.2.1

**Comment by rolandjitsu** [comment]
I can confirm that there's an issue with the multiple prop. I've also noticed the the `rejectedFiles` doesn't get cleared after the drop operation.

I don't have time at the moment to work on this, so PRs are welcome.

**Comment by rajzik** [comment]
I have opened PR.

**Comment by rajzik** [comment]
@rolandjitsu can you please take a look at the PR?
