### ISSUE TITLE
dropzone open file dialogue, formik form is Automatically submitted

### ISSUE THREAD

**Issue by AdnanMuhib** [react-dropzone/react-dropzone#923]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1. ``package.json`` react-dropzone v ``^10.0.1`` and ``package-lock.json`` react-dropzone v ``10.1.5`` everything working fine
2. deleted_node modules and ran ``npm install`` command  ``package.json`` react-dropzone v ``^10.0.1`` and ``package-lock.json`` react-dropzone v ``10.2.1`` Form in which react-dropzone is used as input is automatically submitted when select file dialogue is opened before selecting a file

**What is the expected behavior?**
Form should be submitted when a user manually clicks on submit button instead of automatic submission on the trigger of dropzone open file dialogue

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
OS : ``Ubuntu 19.04``
Chrome: ``Version 79.0.3945.130``
react-dropzone: ``10.2.1``

**Comment by hassan-bazzi** [comment]
> **Do you want to request a _feature_ or report a _bug_?**
> 
> * [x]  I found a bug
> 
> **What is the current behavior?**
> 
> **If the current behavior is a bug, please provide the steps to reproduce.**
> 
> 1. `package.json` react-dropzone v `^10.0.1` and `package-lock.json` react-dropzone v `10.1.5` everything working fine
> 2. deleted_node modules and ran `npm install` command  `package.json` react-dropzone v `^10.0.1` and `package-lock.json` react-dropzone v `10.2.1` Form in which react-dropzone is used as input is automatically submitted when select file dialogue is opened before selecting a file
> 
> **What is the expected behavior?**
> Form should be submitted when a user manually clicks on submit button instead of automatic submission on the trigger of dropzone open file dialogue
> 
> **Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
> OS : `Ubuntu 19.04`
> Chrome: `Version 79.0.3945.130`
> react-dropzone: `10.2.1`

Please show the code of your drop zone component

If you have a button make sure that you set button `type="button"`, otherwise button submits the form by default

**Comment by rolandjitsu** [comment]
@AdnanMuhib the dropzone component/hook does not contain any buttons. If you're referring to the examples, feel free to make a PR with a fix.

**Comment by AdnanMuhib** [comment]
``type="button"`` was not mentioned explicitly that's why form was submitted automatically.

**Comment by rodricarranza** [comment]
I'm having the same issue. @rolandjitsu  did you find a solution/workaround ? I don't have any other button in my form except for the one that submits the form.
