### ISSUE TITLE
Chunking Feature

### ISSUE THREAD

**Issue by Horzta** [react-dropzone/react-dropzone#924]
**What is the current behavior?**
No Chunking documentation

**What is the expected behavior?**
Have Chunking feature/documentation

**If this is a feature request, what is motivation or use case for changing the behavior?**
So that we can use the library for chunking upload files. Base Dropzone already has this feature.

**Comment by rolandjitsu** [comment]
This library does not process the files, so this sort of feature should be implemented in the user land.
