### ISSUE TITLE
isDragReject and isDragAccept are both false.

### ISSUE THREAD

**Issue by gadiGuesty** [react-dropzone/react-dropzone#925]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
isDragReject and isDragAccept are always false if I use maxSize/ accept. only validates if I use callbacks
**If the current behavior is a bug, please provide the steps to reproduce.**

pass maxSize or accept param to useDropZone and console.log isDragReject & isDragAccept and see it always returns false. Btw onDragReject and onDragAccept works perfectly.
The examples in the docs with the styling don't work if you cannot seem to reproduce.

1.
1.
1.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by rolandjitsu** [comment]
This is a browser limitation of the `accept` prop and the `maxSize` which cannot be evaluated during the drag operation, only during the drop.
