### ISSUE TITLE
[IE] - cannot drag and drop folder with files in IE 11

### ISSUE THREAD

**Issue by Aleksey-Timoschenko** [react-dropzone/react-dropzone#926]
**Do you want to request a *feature* or report a *bug*?**

- [ y ] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1. select folder with files 
2. try to drag and drop this folder
3. first parameter acceptedFiles for onDrop callback has length 0 and there are no info about files from folder

I just want to understand: is it just an IE bug? Or we can drag and drop folders in IE? 

**What is the expected behavior?**
acceptedFiles should not be empty 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
IE - v11.0.15063.0 OS - Windows 10, react-dropzone - v 10.2.1

**Comment by rolandjitsu** [comment]
IE 11 does not support folder drag drop. Check [file-selector#browser-support](https://github.com/react-dropzone/file-selector#browser-support) for more info.
