### ISSUE TITLE
[IE-11] - should't open modal twice

### ISSUE THREAD

**Issue by seirykborys** [react-dropzone/react-dropzone#928]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1. click on upload
1. press 'cancel'
1.see that modal is opening

**What is the expected behavior?**
first click on "cancel" shouldn't reopen modal
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by patrykcieszkowski** [comment]
It's also the case on Chrome. Firefox seems to be handling it just fine. It must have something to do with the fact that both `getRootProps` and `getInputProps` are binding to `onClick` event. Overriding `onClick` method at `getRootProps` works for me. (so far)

**Comment by rolandjitsu** [comment]
It sounds like the input is triggered twice. Do you happen to use <label> somewhere within the dropbox or as the dropbox root element?

It's difficult for me to test as I don't have access to a Windows machine.

**Comment by patrykcieszkowski** [comment]
@rolandjitsu So here I include a super-simplified version of what my setup looked liked. Again, it works just fine on FireFox, other than that, it seems to open the modal twice - regardless of whether you select your input file on the 1st modal nor not, it's output is ignored and the input is triggered second time.

Tested on Chrome 80.0 causes just that. Both, on linux and windows.


    import React from 'react'            
    import { useDropzone } from 'react-dropzone'
                                                     
    const Content = props => {
      const { getRootProps, getInputProps } = useDropzone({   
        accept: 'video/*',
        onDrop: props.onDrop
      })                     
                                                     
      return (      
        <div>                              
          <div    
            {...getRootProps()}
          >     
            <label>
              <input             
                {...getInputProps()}
              />
              <div>
                <span>click or drop</span>
              </div> 
            </label>
          </div>                                  
        </div>
      )
    }


My workaround was the following, but again - I'm not really aware of any drawbacks to doing it this way:

       {...getRootProps({
          onClick: e =>  e.preventDefault()
       })

**Comment by rolandjitsu** [comment]
Can you try adding a `for` attr to your `<label>` and maybe provide an id for the `<input>`? I think it's related to that.
That example could be turned into a codesandbox, would be much easier to illustrate the issue.
