### ISSUE TITLE
activeClassName & other props cause error in <Dropzone /> component

### ISSUE THREAD

**Issue by paolavness** [react-dropzone/react-dropzone#931]
- [x] I found a bug - tho unable to find documentation regarding correct usage
- [ ] I want to propose a feature

**What is the current behavior?**
Passing `activeClassName`, `disablePreview` and `acceptClassName` to `getRootProps()` in `<Dropzone />` component throws DOM error:

`React does not recognize the `activeClassName` prop on a DOM element.`

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Add the above props as per below 
```
`render()` code returns:
```
 <Dropzone onDrop={this.handleOnDrop} >
	{({getRootProps, getInputProps}) => (
		<div {...getRootProps({
			activeClassName: 'uploader-thumb-dragover',
			acceptClassName: 'uploader-thumb-dragover',
			className: 'uploader-thumb',
			disablePreview: true,
			onClick: dismissMessage, 
			})}>
			<input {...getInputProps()} />
			<div className="uploader-thumb-face">
				<i className="fal fa-cloud-upload fa-6x" />
				<span>
					<u>{I18n.get('Drop or Select file')}</u>
				</span>
			</div>
		</div>
	)}
</Dropzone>
```

**What is the expected behavior?**
Props should be accepted and have an impact.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Latest chrome, react 16.9, react-dropzone 10.2.1

**Comment by rolandjitsu** [comment]
I think you're using an old version of the lib, please update.

**Comment by paolavness** [comment]
I upgraded, so this explains it. 

Where can I find info on how to refactor for this upgrade? The upgrade has broken dropping files completely - no active class for drop, dropped files are not received, and no error messages...

**Comment by paolavness** [comment]
Correction - I'm using this with react-dnd. It looks like react-dnd is mucking around with it. 
Regardless, a migration path would be helpful :)
Thank you!

**Comment by rolandjitsu** [comment]
Breaking change happened at [v8.0.0](https://github.com/react-dropzone/react-dropzone/releases/tag/v8.0.0). There are lots of examples at [react-dropzone.js.org](https://react-dropzone.js.org/).
