### ISSUE TITLE
Add support for maxFiles

### ISSUE THREAD

**Issue by depiction** [react-dropzone/react-dropzone#932]
- [ ] I found a bug
- [X] I want to propose a feature

**What is the current behavior?**

Users may add as many files to a dropzone as they want. There is a multiple prop, but that only prevents users from selecting multiple files at a time. 

**What is the expected behavior?**

Add a `maxFiles` prop that accepts a number, allowing users to only add as many files to the dropzone area as allowed. Any files above the limit will be rejected.

**If this is a feature request, what is motivation or use case for changing the behavior?**

This is a requirement in my current project and I think it's a fairly common need.

**Comment by rolandjitsu** [comment]
You're welcome to make a PR.
