### ISSUE TITLE
Question: how to manage empty folders ? 

### ISSUE THREAD

**Issue by Aarbel** [react-dropzone/react-dropzone#934]
Hi 

I use react dropzone to drop folders and files trees.

React-Dropzone returns only files with path but not empty folders. So when a folder is empty, i can't detect it with the `onDrop` method and then create it in my database.

Is there a way to do it or is that a limitation of this library ? 

Thanks a lot for your help.

**Comment by Aarbel** [comment]
Problem seem to come from here: https://github.com/react-dropzone/react-dropzone/blob/b09129b57155852264358e213bdc9d45ac06f5bb/src/utils/index.js#L43

@rolandjitsu Why did you not allowed empty folders ?

**Comment by Aarbel** [comment]
After hours of investigation, it's a https://www.npmjs.com/package/file-selector limitation.

**Comment by ashuvssut** [comment]
- Checkout my solution for that https://github.com/react-dropzone/react-dropzone/issues/986#issuecomment-1808733306
