### ISSUE TITLE
Accessibility: File input is invisible to screen readers.

### ISSUE THREAD

**Issue by mat-sz** [react-dropzone/react-dropzone#935]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

`getInputProps` returns `style` with property `display` set to `none` which makes the input field invisible to screen readers. This issue was originally reported in my project - https://github.com/mat-sz/filedrop-web/issues/3. 

This bug may be related to #922, but on my end I'm able to focus the Dropzone element with Tab, it's just invisible to screen readers.

**What is the expected behavior?**

To do something like GitHub's "Attach files by dragging and dropping, selecting or pasting them." field - the `input` element is actually `opacity: 0.001`, not completely hidden. This also requires for the parent element to have `overflow: hidden` on it.

The temporary solution I've applied is to call `getInputProps`, like this:

```js
getInputProps({
  style: {}
})
```

And in CSS:

```css
.dropzone input {
  opacity: 0.001;
}
.dropzone {
  overflow: hidden;
}
```

The issue still exists in the latest version (`master` branch): https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L697 - I can make a pull request with the fix (if the solution of using `opacity: 0.001` is acceptable).

**Comment by rolandjitsu** [comment]
@mat-sz sure, let's give it a try. Would help if you'd provide a simple codesandbox to illustrate how changing the style changes the current behaviour.

**Comment by mat-sz** [comment]
I'm trying to reproduce the original issue I had but testing with VoiceOver it seems to work just fine, the only issue that still exists is VoiceOver not picking up the field as a file field.

This is the isolated solution, relying only on the props argument for the functions: https://codesandbox.io/s/billowing-dew-jd9eh

I suspect the original issue arose from me misusing the library, instead of `display: none;`, the fix I've used is in this commit: https://github.com/mat-sz/filedrop-web/commit/bff87c2b3de7f80f76bd8847d8b2118343d4cfe2 (if that's helpful), but there's still the issue of screen readers not recognizing the dropzone div as a true file input (semantic web thing).
