### ISSUE TITLE
Feature: Property to reject duplicate file submissions

### ISSUE THREAD

**Issue by PaulSHahn2** [react-dropzone/react-dropzone#937]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [x] I want to propose a feature

**What is the current behavior?**
It appears that you have to write your own reject handler in the ondrop event to reject a second file with the same name (when the multiple property is selected).

**If the current behavior is a bug, please provide the steps to reproduce.**

1. N/A

**What is the expected behavior?**
Programmer adds a new property, called something like nodups or nodupname to be used in conjunction with the multiple property. When a user tries to add the same file name twice, the second file is rejected. 

My apologies if this is already requested. I searched on duplicate, dups and other similar terms and did not see anything here or in the docs on react-dropzone.js.org.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Increased usability, convenience.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by rolandjitsu** [comment]
I think this belongs to the user land, so I'm going to close it.

**Comment by GreenBayRules** [comment]
Hi I'm trying to get this to work, can someone help me?
