### ISSUE TITLE
Resize images with other libraries not working

### ISSUE THREAD

**Issue by trongbang86** [react-dropzone/react-dropzone#941]
**Do you want to request a *feature* or report a *bug*?**

- [ x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Currently I'm using react-dropzone ^4.2.1 with react-image-file-resizer. The problem is after i resize the images, the dropzone become blank and the file sent to server is still too big.

**If the current behavior is a bug, please provide the steps to reproduce.**

1.
1.
1.

**What is the expected behavior?**

The preview should work and the image sent back to server should be minimized

**If this is a feature request, what is motivation or use case for changing the behavior?**

I have read this https://github.com/react-dropzone/react-dropzone/issues/439 and this https://github.com/react-dropzone/react-dropzone/issues/438#issuecomment-307031166

I'm trying to use my own but it's having problems. Can you pls give some guideline which can also be helpful for others.
```
class Image extends BaseImage {
  constructor(props) {
    super(props);
  }

  onDrop ( filesToUpload, e, input ) {
    Utils.resizeImageUpload(filesToUpload[0],
      (img, resizedImg) => {
        input.onChange([resizedImg]);
      });
    input.onChange(filesToUpload);
  }
  render() {
    const {input, initValue, intl} = {...this.props};
    const file = input.value[0];

  // more code for formatting
    return (
      <div className='dropzone-image'>
        <Dropzone
          name={input.name}
          multiple={false}
          onDrop={ (filesToUpload, e ) => this.onDrop(filesToUpload, e, input )} >
          { !file && 
              <div className=''><FormattedMessage id={desc} /></div>
          }
          { file && <img style={{maxWidth: '100%',
                maxHeight: '100%'}} src={file.preview} /> }

        </Dropzone>
        { Goback }
      </div>
    );
  }
```

In utils class, I use react-image-file-resizer and define callback like this.

```
Utils.resizeImageUpload=(image, func) => {
  Resizer.imageFileResizer(
    image,
    50,
    50,
    'PNG',
    50,
    0,
    uri => {
      func(image, Utils.dataURLtoFile(uri, image.name));
    },
    'base64'
  );
}

Utils.dataURLtoFile = (dataurl, filename) => {

  let arr = dataurl.split(','),
    mime = arr[0].match(/:(.*?);/)[1],
    bstr = atob(arr[1]), 
    n = bstr.length, 
    u8arr = new Uint8Array(n);

  while(n--){
    u8arr[n] = bstr.charCodeAt(n);
  }

  return new File([u8arr], filename, {type:mime});
}
```
Pls ignore the value width=50, height=50. I'm just trying to debug. The code dataURLtoFile is copied from another stackoverflow to convert to javascript File object.

**Comment by trongbang86** [comment]
I have submitted on stackoverflow but no one is helping me

https://stackoverflow.com/questions/60563650/how-to-resize-images-with-javascript-in-react-dropzone-before-uploading-them-to

**Comment by SanNic20** [comment]
@trongbang86 : Do you find a solution ? I will be very interested. Thanks
