### ISSUE TITLE
All Files Uploaded Event

### ISSUE THREAD

**Issue by neilchaudhuri** [react-dropzone/react-dropzone#944]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [ X] I want to propose a feature

**What is the current behavior?**

There appears to be no event that fires when all files in the queue have been processed.

**If this is a feature request, what is motivation or use case for changing the behavior?**

There are times when it is helpful to perform an action after all files have been uploaded rather than after (or in addition to) an individual file in the queue being uploaded.

**Comment by rolandjitsu** [comment]
The `onDrop` cb is the cb you're looking for. It fires after you've dropped (or selected) some file(s).

**Comment by yelnyaface** [comment]
> The `onDrop` cb is the cb you're looking for. It fires after you've dropped (or selected) some file(s).

what does `onDrop` have anything to do with the event `that fires when all files in the queue have been processed`?

**Comment by rolandjitsu** [comment]
> > The `onDrop` cb is the cb you're looking for. It fires after you've dropped (or selected) some file(s).
> 
> what does `onDrop` have anything to do with the event `that fires when all files in the queue have been processed`?

There's no file processing or upload. This lib just calls the `onDrop` with the files that you selected or dropped. There's no individual callbacks for every file you drop as the browser does not provide such an API.
