### ISSUE TITLE
how to use dropzone with array input

### ISSUE THREAD

**Issue by shipcake** [react-dropzone/react-dropzone#946]
![image](https://user-images.githubusercontent.com/30076862/77520083-3bd15f80-6eb3-11ea-8862-884be08b34be.png)

I use dropzone to upload image multiple key id (multiple field)  save into object in array but ref. (inputref) not show correct (show only last element)

how to work together

**Comment by rolandjitsu** [comment]
@shipcake your description is not following the guide, please provide an adequate one.
