### ISSUE TITLE
Typescript - defaultValue type error

### ISSUE THREAD

**Issue by jazzdragon** [react-dropzone/react-dropzone#947]
- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

With basic setup, pretty much identical to the example in readme, getting a type error after updating @types/react from 16.8.22 to 16.9.25:

https://www.dropbox.com/s/s3dr4rglsl9bbsw/Screenshot%202020-03-25%2008.51.59.png?dl=0 

**What is the expected behavior?**

No type error

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

react-dropzone: 10.2.1
react: 16.9
@types/react: 16.9.25

**Comment by rolandjitsu** [comment]
@jazzdragon the snapshot you added doesn't show an issue with this lib. It would be easier to setup an example on codesandbox or some other service to illustrate the issue.
