### ISSUE TITLE
Reader result is empty, when i uploaded mat(.mat) file

### ISSUE THREAD

**Issue by pavanmehtre69** [react-dropzone/react-dropzone#948]
my ondrop function:- 

const onDrop = (files) => {
    if (files && files.length > 0) {
        const reader = new FileReader()
        reader.onload = () => {
          console.log(reader.result)
        }
        reader.readAsBinaryString(files[0]);
    }
}

**Comment by rolandjitsu** [comment]
Please provide a proper issue description with an example codesandbox. Also note that the issue is most likely not due to this lib.
