### ISSUE TITLE
Show files in react drop zone

### ISSUE THREAD

**Issue by tanweer2k9** [react-dropzone/react-dropzone#957]
I have Urls of files on server. I want to show files from these urls in react-dropzone like when we add files in react-dropzone. I want to fulfill edit purpose too

**Comment by rolandjitsu** [comment]
@tanweer2k9 I also want many things, but asking for them here won't help much 😆 I will close this as it doesn't describe an issue with this lib. For future reference, use [SO](https://stackoverflow.com) to ask for such things.
