### ISSUE TITLE
model Content-Type not recognized

### ISSUE THREAD

**Issue by dotesfera** [react-dropzone/react-dropzone#962]
Hi, I tried this 

` const [files, setFiles] = useState([]);
  const { getRootProps, getInputProps } = useDropzone({
    accept: "model/gltf-binary",
    onDrop: (acceptedFiles) => {
      setFiles(
        acceptedFiles.map((file) =>
          Object.assign(file, {
            preview: URL.createObjectURL(file),
          })
        )
      );
    },
  });`

**model/gltf-binary** is not being recognized on input, what could it be? It works with image and video content-types...

_If you feel this should not be here, feel free to close it._

**Comment by lossen** [comment]
I have the same issue. None of these formats allow uploading gltf or glb files
model/gltf+json
model/gltf-binary
application/octet-stream
How to fix that?

**Comment by rolandjitsu** [comment]
@lossen file types are very difficult to handle properly across browsers. There's a note in our docs that mentions this:

> Because of HTML5 File API differences across different browsers during the drag, Dropzone might not be able to detect whether the files are accepted or rejected in Safari nor IE.

> Furthermore, at this moment it's not possible to read file names (and thus, file extensions) during the drag operation. For that reason, if you want to react on different file types during the drag operation, you have to use mime types and not extensions! For example, the following example won't work even in Chrome:

I would check if a simple file input can detect the file type/mime type properly, and if yes, then we can reopen the issue and investigate, otherwise there's not much we can do.

**Comment by motifdev** [comment]
same issue

**Comment by ECMGD** [comment]
same issue here as well, might I ask how you validated file type? 

> same issue. solved by validating the file type in the drophandler function.

**Comment by haywirez** [comment]
Struggling with this as well. You can validate on drop from the filename, but there's false feedback during dragging. In #1244 I suggested implementing a `isDragUnknown` handler.

**Comment by arcticmatt** [comment]
I just used `.glb` instead of the media type to work around this

**Comment by AlexandreSi** [comment]
> I just used `.glb` instead of the media type to work around this

This might not work for Safari as it seems like Safari does not use extensions in `accept` attribute
https://stackoverflow.com/questions/37357970/safari-doesnt-respect-input-type-accept-extension
