### ISSUE TITLE
Drag and drop file directly from email

### ISSUE THREAD

**Issue by weslei-dias-vakt** [react-dropzone/react-dropzone#964]
Its possible drag files directly from email and drop in this component?

**Comment by Sannnao** [comment]
I'm curious about this issue too. When I dragging some file from the email - its doesn't recognized at all. Could you please provide an information how to handle this?

**Comment by rolandjitsu** [comment]
@weslei-dias-vakt could you please provide more context? What email are you talking about? Is this a native desktop app? Is this a web based app?

In any case, I doubt there's anything we can do about this as this is more of a browser API issue. So if the browser supports it, then we support it, otherwise there's not much we can do.

**Comment by weslei-dias-vakt** [comment]
Hey @rolandjitsu,

I'm talking about desktop app like outlook. 
What i want do to is, drag an attachment from an email and drop directly to the component in my web app.
I notice that this works on Safari,  but not to others browsers.
I'm using a Mac, maybe this is the problem.

**Comment by rolandjitsu** [comment]
> Hey @rolandjitsu,
> 
> I'm talking about desktop app like outlook.
> What i want do to is, drag an attachment from an email and drop directly to the component in my web app.
> I notice that this works on Safari, but not to others browsers.
> I'm using a Mac, maybe this is the problem.

As far as I can see, there's a bunch of discussions about this ([#322605](https://bugs.chromium.org/p/chromium/issues/detail?id=322605&desc=3), [chrome-drag-drop-files-from-outlook-to-web](https://www.chromestory.com/2019/02/chrome-drag-drop-files-from-outlook-to-web/)), and all indicate that on Windows it should work with Chrome as well, but I cannot find any info about the other platforms.

**Comment by rolandjitsu** [comment]
Gonna close this as I don't see a way to handle this on our side. If any info comes up on this topic that could help we'll reopen the issue or address it in a PR.
