### ISSUE TITLE
application/vnd.ms-powerpoint mimetype shows greyed out files in fileviewer

### ISSUE THREAD

**Issue by martinseanhunt** [react-dropzone/react-dropzone#965]
**Do you want to request a *feature* or report a *bug*?**

- [X] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Pass the mimetype of 'application/vnd.ms-powerpoint' to the Dropzone accept prop
2. click to open the file browser (tested on mac osx)
3. .ppt files with the 'application/vnd.ms-powerpoint' mimetype appear greyed out although they can still be selected. 

**What is the expected behavior?**

Should not be greyed out when correct mimetype passed

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

Tested in 11.0.1 & 10.1.5

**Comment by danielcrisp** [comment]
I had the same problem, but I don't think it is the fault of react-dropzone.

On my Mac I found that the only way I could get it to work was to use the file extensions in the `accept` attribute as well as the mimetypes, e.g. 

```
<input accept="application/vnd.openxmlformats-officedocument.presentationml.presentation,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.slideshow,.ppt,.pptx" type="file">
```

**Comment by akitto69** [comment]
I used the following for csv after too much reading the key on windows was the .csv the rest I left in just in case. I guess the same would work for ppt
```acceptedFiles={[".csv, text/csv, application/vnd.ms-excel, application/csv, text/x-csv, application/x-csv, text/comma-separated-values, text/x-comma-separated-values"]}```
