### ISSUE TITLE
How to handle heic files

### ISSUE THREAD

**Issue by twigs67** [react-dropzone/react-dropzone#966]
Maybe I missed it, but I don't see a way of handling .heic (Apple) files. In other libs, its seems like you can alter the file name to convert it, but the file is immutable ```onDrop```.

**Comment by rafael-vitor** [comment]
@twigs67 have you found a solution?

**Comment by kluplau** [comment]
HEIC is standard format for images taken by an iPhone. Shouldn't this be supported in `react-dropzone`?

**Comment by WebMasterSam** [comment]
Same concern here. Since it's easily handled in the backend (converting it to JPG for example), this component should accept this file type (HEIC and HEIF) as images.

**Comment by rolandjitsu** [comment]
@WebMasterSam I'm not quite sure what the issue is. This lib does not process files. Could someone explain?

**Comment by WebMasterSam** [comment]
I have a dropzone, added the "image/heic" and "image/heif" as accepted content types. Dragging a file always gets on the fileRejection handler...

![image](https://user-images.githubusercontent.com/3845583/154867725-232b50d5-2250-42b9-a5b1-91ca65e3cd79.png)

**Comment by rolandjitsu** [comment]
> I have a dropzone, added the "image/heic" and "image/heif" as accepted content types. Dragging a file always gets on the fileRejection handler...
> 
> ![image](https://user-images.githubusercontent.com/3845583/154867725-232b50d5-2250-42b9-a5b1-91ca65e3cd79.png)

Well, the `type` is not available and you're validating by MIME type. This is probably a browser issue as it doesn't recognise that type.

We do keep a list of known file extensions and then we set the MIME type in [react-dropzone/file-selector](https://github.com/react-dropzone/file-selector/blob/5f42ace2c72bde8371af2318b265bf8ab0dee735/src/file.ts#L1), so you could make a PR and add these to the list.

**Comment by ahnaf-abir** [comment]
I had a similar issue with `react-dropzone` version `12.0.2`, had to downgrade to `11.3.0` to fix the issue.

**Comment by syedmahmad** [comment]
Please re open this issue. This issue still exist. 
Here is my user case:
- dropZone is working fine on all desktop browsers.
- Same dropZone not working on mobile browsers. In mobile, we are not getting **type** of **heic, heif** images. All other image types are working fine.

NOTE: I even downgrade and try different versions but issue still same.

**Comment by marianne00** [comment]
Any updates? Also having the same issue.

**Comment by vasilvestre** [comment]
Pretty much the same issue here. Can't send any heic file

**Comment by vasilvestre** [comment]
I don't have preview of these files, I wonder if I do something wrong here or if extra code is needed

**Comment by MattHalloran** [comment]
I was able to add heic support by using [heic2any](https://github.com/alexcorvi/heic2any). Here's what it looks like:

```
    const [profileImg, setProfileImg] = useState(defaultImg);

    const handleImagePreview = async (file: any) => {
        // Extract extension from file name or path
        const ext = (file.name ? file.name.split(".").pop() : file.path.split(".").pop()).toLowerCase();
        // If heic or heif, convert to jpeg
        if (ext === "heic" || ext === "heif") {
            // Dynamic import of heic2any
            const heic2any = (await import("heic2any")).default;

            // Convert HEIC/HEIF file to JPEG Blob
            const outputBlob = await heic2any({
                blob: file,  // Use the original file object
                toType: "image/jpeg",
                quality: 0.7, // adjust quality as needed
            }) as Blob;
            // Return as object URL
            return URL.createObjectURL(outputBlob);
        } else {
            // If not a HEIC/HEIF file, proceed as normal
            return URL.createObjectURL(file);
        }
    };

    const { getRootProps, getInputProps } = useDropzone({
        accept: ["image/*", ".heic", ".heif"],
        maxFiles: 1,
        onDrop: async acceptedFiles => {
            if (acceptedFiles.length <= 0) {
                console.error("No files were uploaded");
                return;
            }

            const previews = await Promise.all(
                acceptedFiles.map(file =>
                    handleImagePreview(file).then(preview =>
                        Object.assign(file, { preview }),
                    ),
                ),
            );

            setFiles(previews);
            onChange(acceptedFiles[0]);
        },
    });

    // Update profile image after file has been uploaded
    useEffect(() => {
        if (files.length > 0) {
            setProfileImg(files[0].preview);
        }
    }, [files]);
    
    //...
    return (
    <input name="profile" {...getInputProps()} />
    )
    ```

**Comment by Sahal-P** [comment]
> I was able to add heic support by using [heic2any](https://github.com/alexcorvi/heic2any). Here's what it looks like:
> 
> ```
>     const [profileImg, setProfileImg] = useState(defaultImg);
> 
>     const handleImagePreview = async (file: any) => {
>         // Extract extension from file name or path
>         const ext = (file.name ? file.name.split(".").pop() : file.path.split(".").pop()).toLowerCase();
>         // If heic or heif, convert to jpeg
>         if (ext === "heic" || ext === "heif") {
>             // Dynamic import of heic2any
>             const heic2any = (await import("heic2any")).default;
> 
>             // Convert HEIC/HEIF file to JPEG Blob
>             const outputBlob = await heic2any({
>                 blob: file,  // Use the original file object
>                 toType: "image/jpeg",
>                 quality: 0.7, // adjust quality as needed
>             }) as Blob;
>             // Return as object URL
>             return URL.createObjectURL(outputBlob);
>         } else {
>             // If not a HEIC/HEIF file, proceed as normal
>             return URL.createObjectURL(file);
>         }
>     };
> 
>     const { getRootProps, getInputProps } = useDropzone({
>         accept: ["image/*", ".heic", ".heif"],
>         maxFiles: 1,
>         onDrop: async acceptedFiles => {
>             if (acceptedFiles.length <= 0) {
>                 console.error("No files were uploaded");
>                 return;
>             }
> 
>             const previews = await Promise.all(
>                 acceptedFiles.map(file =>
>                     handleImagePreview(file).then(preview =>
>                         Object.assign(file, { preview }),
>                     ),
>                 ),
>             );
> 
>             setFiles(previews);
>             onChange(acceptedFiles[0]);
>         },
>     });
> 
>     // Update profile image after file has been uploaded
>     useEffect(() => {
>         if (files.length > 0) {
>             setProfileImg(files[0].preview);
>         }
>     }, [files]);
>     
>     //...
>     return (
>     <input name="profile" {...getInputProps()} />
>     )
>     ```
> ```

this is taking longer to process 
is there any efficient way

**Comment by syedmahmad** [comment]
Yes, I even tried the same **heic2any** package to convert `heic` iamges and I agree, it is taking longer to process only for **heic** images. It would be good if `react-dropzone` add support of `heic` images.

**Comment by kode15333** [comment]
> > I don't have preview of these files, I wonder if I do something wrong here or if extra code is needed
> 
> Same here, let me know if you found any fix.

I got same issue
I couldn't preview HEIC/HEIF images on my Android device using the Chrome browser.
I discovered that that environment does not support the HEIC/HEIF format in Photo Gallery .
(heic/heif image show gray box)

if you take away heic/heif format  in accept Type, you can preveiw that file and handle heic/heif format
I think the system automatically recognizes HEIC/HEIF files as PNG/JPG formats.

**my solution**
```
const acceptType =  useMemo(() => {
  if(isAnroid && isChrome) {
   return {
        accept: ["image/*"]
    }
  }


return { accept: ["image/*", ".heic", ".heif"] }}, [isAndroid, isChrome])

```

**Comment by xlgabriel** [comment]
So I guess no solution for this yet? Do I really have to stop using this package?

**Comment by christopherdro** [comment]
you can use `"image/*": [".heic"]` or `"image/heic": []`

**Comment by yusuke-imayama** [comment]
> you can use "image/*": [".heic"] or "image/heic": []

Preview is not available

**Comment by waqaskhan55701** [comment]
The issue still exists , I am not getting an error by passing heic/heif in allowed formats but it still doesn't get the data required for me to upload to the server. Has anyone find an alternative to this?

**Comment by littlestbrother** [comment]
I don't think this is going to be resolved by drop zone since HEIC isn't compatible with HTML unless you're on Safari :/
