### ISSUE TITLE
open isolated example and close isolated example, Docs issue.

### ISSUE THREAD

**Issue by Binu42** [react-dropzone/react-dropzone#968]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [x] I want to propose a feature

**What is the current behavior?**
currently on clicking icon of open isolated, example is opening isolated that's fine but after closing isolated icon page scroll back to top that's not expected behavior.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. go to https://react-dropzone.js.org/
2. scroll down to seen examples.
3. click on open isolated and then close isolated example and you will be able to see the issue.

**i'm attaching gif it will explain it better**
![react-dropzone](https://user-images.githubusercontent.com/45959932/81679158-acd2d380-946f-11ea-8bfc-3925ac18822e.gif)

**What is the expected behavior?**
page should not scroll back to top it should again show the same example in unisolated form. it will make the developer life easy in reading docs.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
it common in all browsers, OS and not releated with react-dropzone version.

**Comment by Binu42** [comment]
if this issue get accepted assign it to me...

**Comment by Binu42** [comment]
if this issue get accepted **assign it to me**. i would like to contribute and fix this issue.

**Comment by rolandjitsu** [comment]
We ought to update all dev deps which might fix the issue as this is most likely an issue with styleguidist.
