### ISSUE TITLE
Disabled still causing file to download when dropped

### ISSUE THREAD

**Issue by navari-technologies** [react-dropzone/react-dropzone#971]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
When setting "disabled: true" and using the Dropzone hook, a dropped file is automatically downloaded by the browser.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Go to https://react-dropzone.js.org/#!/Basic%20example/3 (example Dropzone with disabled property)
1. Drag and drop any file over the Dropzone area
1. The browser will automatically download the file

This is exactly what I'm experiencing when using the same code in my application. Oddly, it doesn't happen in the same example located on the main page. (https://react-dropzone.js.org)

**What is the expected behavior?**
Being that the Dropzone is disabled, there should be no action taken when dragging and dropping a file -- i.e. nothing should automatically download.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
react-dropzone: 10.2.1 (not the latest version, but still happening on https://react-dropzone.js.org/#!/Basic%20example/3)
Browser: Chrome 81.0.4044.129
OS: macOS 10.15.4

**Comment by navari-technologies** [comment]
Bump. This issue still remains, please advise.

**Comment by rolandjitsu** [comment]
This can be fixed by adding `onDrop` on the dropzone element:
```jsx
<div {...getRootProps({className: 'dropzone disabled'})} onDrop={evt => evt.preventDefault()}>
```

I think this is due to the way we handle `disabled`. Normally, to prevent this behaviour in browsers, you would do:
```jsx
const {getRootProps} = useDropzone({
  onDrop: (files, rejections, evt) => evt.preventDefault()
})
```

But if `disabled` is set, we ignore any callbacks (they're set to `null`).

**Comment by rolandjitsu** [comment]
Closing this as there's no response from author.
