### ISSUE TITLE
Using rejectedFile prop gives an undefined error and crashes the application.

### ISSUE THREAD

**Issue by ayushmalviya27** [react-dropzone/react-dropzone#973]
**Do you want to request a *feature* or report a *bug*?**

- [X] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Using `rejectedFiles `prop crashes the application, giving an error saying that it's undefined.
Even the same snippet on the documentation page is crashing.
**If the current behavior is a bug, please provide the steps to reproduce.**

1. use the code snippet from here: [https://react-dropzone.js.org/#!/Accepting%20specific%20file%20types/1](url)

**What is the expected behavior?**
Page renders properly

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
React Dropzone v11.0.1
Firefox v76.0.1
Windows 10 64bit
![Screenshot (218)](https://user-images.githubusercontent.com/22271679/82834844-f0055b80-9edf-11ea-9fda-c1078898e4f5.png)

**Comment by mariosar** [comment]
I think in the documentation and example there is a type. It should be: fileRejections.

const {acceptedFiles, fileRejections} = useDropzone(...)

**Comment by ayushmalviya27** [comment]
Makes sense.
Closing the issue.
