### ISSUE TITLE
Dropzone in a FluentUI Modal does not work

### ISSUE THREAD

**Issue by joosttk** [react-dropzone/react-dropzone#976]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
I am trying to ad a Dropzone to a FluentUI/FabricUI Modal component, but this does not work. The onDrop callback seems not to get triggered.

Documentation on the Modal component: https://uifabric.azurewebsites.net/#/controls/web/modal

**If the current behavior is a bug, please provide the steps to reproduce.**
https://codesandbox.io/s/stoic-tree-53guu?file=/src/app.js

When I add my own Dropzone component (that uses the hooks), inside the FluentUI Modal component, it does not work. The same component works fine outside of the Modal (see sandbox)

**What is the expected behavior?**
It should trigger the callback similar to a dropzone outside of a Modal.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Win 10, Edge Chromium DEV version.

**Comment by linkorn** [comment]
@joosttk , use Modal with eventBubblingEnabled: true

```
<Modal
        layerProps={{ eventBubblingEnabled: true }}
        titleAriaId="modalid"
        isOpen={true}
        onDismiss={onCancel}
        isBlocking={true}
      >
...
```
