### ISSUE TITLE
Can I use this library in an old React 15 project?

### ISSUE THREAD

**Issue by mirko77** [react-dropzone/react-dropzone#978]
Hi All,

I have an old React 15 project which I cannot update, can I still use this library? 

Which version would you recommend, 2.x or 4.0? Master is using `hooks` which is React 16 feature only.

Thanks

**Comment by Jhonatangiraldo** [comment]
You can use it, however, you cannot use hooks. You may use the HOC to get the properties. I wouldn't recommend you to use it since you would need too much overhead due to you would need to have react15 and react16 in your node_modules(in order to make your application and this library work)
