### ISSUE TITLE
Use `FileWithPath` instead of `File` in TypeScript definitions

### ISSUE THREAD

**Issue by tobiasweibel** [react-dropzone/react-dropzone#981]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
In the TypeScript definitions the type `File` is used instead of `FileWithPath`, that's at least what I think is wrong. When using the latter type then `path` property can be used directly.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
const { acceptedFiles } = useDropzone({});
console.log('acceptedFiles', acceptedFiles.map(a => a.path));
```
Error: TS2339: Property 'path' does not exist on type 'File'.

**What is the expected behavior?**
No error should be shown by TypeScript or ESLint.

**If this is a feature request, what is motivation or use case for changing the behavior?**
\- 

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
* react-dropzone: 11.0.1

**Comment by ImCesar** [comment]
This wasn't apparent to me right away but I figured out that you can import FileWithPath from the library to use as well. 

Here is one of the examples slightly modified to show what I used to get around it
``` javascript
import React, { ReactNode } from 'react';
import { FileWithPath, useDropzone } from 'react-dropzone';

function Basic(props) {
  const {acceptedFiles, getRootProps, getInputProps} = useDropzone();
  
  // This is another component but concise example
  const fileList = (files: FileWithPath[]): ReactNode => (
    files.map(file => (
      <li key={file.path}>
        {file.path} - {file.size} bytes
      </li>
    ))
  );

  return (
    <section className="container">
      <div {...getRootProps({className: 'dropzone'})}>
        <input {...getInputProps()} />
        <p>Drag 'n' drop some files here, or click to select files</p>
      </div>
      <aside>
        <h4>Files</h4>
        <ul>{fileList(acceptedFiles)}</ul>
      </aside>
    </section>
  );
}
```

**Comment by tobiasweibel** [comment]
> This wasn't apparent to me right away but I figured out that you can import FileWithPath from the library to use as well.
> 
> Here is one of the examples slightly modified to show what I used to get around it
> 
> ```js
> import React, { ReactNode } from 'react';
> import { FileWithPath, useDropzone } from 'react-dropzone';
> 
> function Basic(props) {
>   const {acceptedFiles, getRootProps, getInputProps} = useDropzone();
>   
>   // This is another component but concise example
>   const fileList = (files: FileWithPath[]): ReactNode => (
>     files.map(file => (
> [...]
> ```
Yeah, that's what we are doing as well, but it's still a workaround.

**Comment by rolandjitsu** [comment]
@tobiasweibel that's the intended way of using it. Check [basic.tsx](https://github.com/react-dropzone/react-dropzone/blob/master/typings/tests/basic.tsx). `react-dropzone` also exports the type.

This is because the library returns whatever the `getFilesFromEvent` returns and that's something users can change by providing their own plugin/function.

**Comment by kuzdogan** [comment]
If you're wonderin how to do it on the `useDropzone` functions such as `onDrop` this is the way to go:

```ts
interface DropzoneFile extends File {
  size: number;
  path?: string;
}

const { getRootProps, getInputProps } = useDropzone({
  onDrop: async (files: DropzoneFile[]) => {
     ...
  },
});

**Comment by FutureKode** [comment]
FileWithPath does not include `preview` key but that is available it seems

**Comment by rolandjitsu** [comment]
> FileWithPath does not include `preview` key but that is available it seems

@FutureKode could you point to the doc showing the preview property on a `File`?

**Comment by FutureKode** [comment]
@rolandjitsu File and screenshot of the console with the preview property
![Screenshot 2024-11-13 at 13 34 24](https://github.com/user-attachments/assets/1da1b39d-ea7a-4744-a0d1-33b8fdb9a1e1)
![futuristic-city](https://github.com/user-attachments/assets/f1c6b481-85ab-4493-a926-18539dc624f0)

**Comment by rolandjitsu** [comment]
That's probably added by some other code. It's not part of the standard [File[(https://developer.mozilla.org/en-US/docs/Web/API/File) API.

**Comment by FutureKode** [comment]
@rolandjitsu oh my bad, I copied some example from somewhere and you're right preview is being added by other code.
