### ISSUE TITLE
Provide state to indicate when files are being processed.

### ISSUE THREAD

**Issue by jedBrennen** [react-dropzone/react-dropzone#984]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [x] I want to propose a feature

**What is the current behavior?**
As far as I can tell, without completely re-implementing the `getFilesFromEvent` method (seems like overkill for this small feature), there is no way to update the component whilst files are being uploaded, meaning the UI just hangs whilst the `file-selector` `fromEvent` method runs.

**What is the expected behavior?**
Provide a state which indicates the files are being processed. Or provide a prop which lets the user define a callback to run prior to processing. 
**Bonus:** Being able to track the progress (i.e. num of files processed / total files), however I'm not sure this is possible using the current implementation with `file-selector`.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Being able to display a loading indicator whilst the files are being processed.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
React-dropzone: v11.0.1

I have no time right now, but will look in to putting together a PR when I do if no one has picked it up/provided a simple workaround.

**Comment by grempe** [comment]
I came here for this. Stale bot had closed it though.  Would love to see this addressed.
