### ISSUE TITLE
Allow acceptedFiles to be accumulative

### ISSUE THREAD

**Issue by Jhonatangiraldo** [react-dropzone/react-dropzone#985]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [x] I want to propose a feature

**What is the current behavior?**
There is no way of dragging or selecting various lists of files in an accumulative way

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Click to select files or drag and drop them in the box
2. Then click again or drag files, the list of **acceptedFiles** and **draggedFiles** are restored and filled with the new selection

**What is the expected behavior?**
There should be provided a prop `accumulative={fase|true}` if true, the acceptedFiles and draggedFiles are accumulative so you can drag or select various lists of files, from different folders even.

**If this is a feature request, what is motivation or use case for changing the behavior?**
More flexibility for the developer

### Note
I am willing to help with this feat in case the team agree with this functionality :)

**Comment by vdevired** [comment]
This really is not an issue and can be changed quite easily by changing the onDrop function:
```
onDrop: acceptedFiles => {
      setFiles((curFiles) => ([...curFiles, ...acceptedFiles]));
}
```

**Comment by Jhonatangiraldo** [comment]
@vdevired  The expected behavior is to accumulate files but filter them out, so if there are repeated files it shouldn't add them again.
Thinking about it it should accept a filter function, if no function is provided the library may filter out by names. So it accumulates the files but also doesn't repeat a file that is added again.

What do you think? btw this is more a proposed feature rather than a bug :)

**Comment by MrChe** [comment]
+1

**Comment by rolandjitsu** [comment]
@Jhonatangiraldo Adding more state just adds more complexity to the lib and I don't see the benefits of that since users can easily do it.
