### ISSUE TITLE
How can I get empty folders when occur onDrop event

### ISSUE THREAD

**Issue by Sujin1135** [react-dropzone/react-dropzone#986]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [x] I want to propose a feature

**What is the current behavior?**
I tried to select empty folders and print acceptFiles, but It's empty array. I've been wondering the way to get empty file objects.

**What is the expected behavior?**
I want to get empty folder objects when occur onDrop event.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Browser: Chrome
react-dropzone: 11.0.1

**Comment by rolandjitsu** [comment]
@Sujin1135 your best option is to add a dotfile inside (e.g `.gitkeep`).

**Comment by mkurczewski** [comment]
> @Sujin1135 your best option is to add a dotfile inside (e.g `.gitkeep`).

Lol. This isn't helpful at all. Should I tell my users "hey, if you want to upload a directory where some folders are empty, just add some trash file in them"?

DropZone treats empty folders as non-existing and that's the issue. Not the fact, that somebody has an empty folder.

**Comment by rolandjitsu** [comment]
> > @Sujin1135 your best option is to add a dotfile inside (e.g `.gitkeep`).
> 
> Lol. This isn't helpful at all. Should I tell my users "hey, if you want to upload a directory where some folders are empty, just add some trash file in them"?
> 
> DropZone treats empty folders as non-existing and that's the issue. Not the fact, that somebody has an empty folder.

What you're saying makes little sense. How would you upload an empty directory? If it's empty, then there's nothing to upload.

What the user is asking for or what you call an issue is creating a directory tree, which is not the purpose of this lib. There's a reason why it's extensible via the `getFilesFromEvent` property: users can provide their own impl. of what to do with a drop event.

If you'd like, you can impl. this sort of plugin and we can link it in our docs.

**Comment by thienho1997** [comment]
I have implemented the solution for this situation....  refer to https://react-dropzone.js.org/#section-extending-dropzone.
You can overrite the default myCustomFileGetter by my code so we can get the result as a tree directory with Files as children of folders. 

async function getFile(fileEntry) {
    try {
      return await new Promise((resolve, reject) => fileEntry.file(resolve, reject));
    } catch (err) {
      console.log(err);
    }
  }

  async function traverseFileTree(item, path, result) {
    path = path || "";
    if (item.isFile) {
        const fileGet = await getFile(item);
        Object.defineProperty(fileGet, 'path', {
            value: path 
          });
          result.push(fileGet)
    //     item.file((file)=> {
           
    //       result.push(file)
    //   });
    } else if (item.isDirectory) {
        const folder = {};
        folder.path = path 
        folder.name = item?.name
        folder.children = []
        result.push(folder)
      var dirReader = item.createReader();
      dirReader.readEntries(function(entries) {
        for (var i=0; i<entries.length; i++) {
          traverseFileTree(entries[i], path + item.name + "/", folder.children);
        }
      });
    }
  }

async function myCustomFileGetter(event) {
    var items = event.dataTransfer?.items || [];
    let result = []
   
  for (var i=0; i<items.length; i++) {
    var item = items[i].webkitGetAsEntry();
    if (item) {
     await traverseFileTree(item,null, result);
    }
  }
  return result
  }

**Comment by ashuvssut** [comment]
Here's my solution for this. 

Refer to [react-dropzone.js.org/#section-extending-dropzone](https://react-dropzone.js.org/#section-extending-dropzone).

You can overwrite the default `myCustomFileGetter` by my `droppedItemHeirarchyProber` so we can get files as well as folders data

**Important: Read the code comments if you want to make that code work**

```js

import { fromEvent } from 'file-selector'

async function droppedItemHeirarchyProber(e) {
  const filesDataPromise = fromEvent(e)
  const heirarchyDetails = await probeFolders(e)

  const filesData = await filesDataPromise
  console.log(JSON.stringify(heirarchyDetails, null, 2), filesData)

  return { filesData, heirarchyDetails }
}

async function probeFolders(event) {
  const heirarchyDetails = {
    emptyFolders: [],
    allFolders: [],
    files: [],
  }

  // IMPORTANT: FileSystemDirectoryHandle or FileSystemFileHandle are experimental.
  // ref 1 : https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle
  // ref 2: https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryHandle
  // The app needs to be served with secure contexts (HTTPS) using ngrok: https://frontendguruji.com/blog/run-next-js-app-locally-in-https/
  const rootHandle = await event.dataTransfer.items[0].getAsFileSystemHandle()
  // rootHandle can be "FileSystemFileHandle" or "FileSystemDirectoryHandle"
  // rootHandle.kind can be "file" or "directory"

  const path = `/${rootHandle.name}`
  if (rootHandle.kind === 'directory') {
    await traverseDirectory(rootHandle, path, heirarchyDetails)
  } else if (rootHandle.kind === 'file') {
    const file = { name: rootHandle.name, kind: rootHandle.kind, path }
    heirarchyDetails.files.push(file)
  }

  return heirarchyDetails
}

async function traverseDirectory(dirHandle, currentPath, heirarchyDetails) {
  const folderDetails = {
    name: dirHandle.name,
    kind: dirHandle.kind,
    path: currentPath,
    children: [],
  }

  for await (const [name, handle] of dirHandle.entries()) {
    const path = `${currentPath}/${name}`

    if (handle.kind === 'file') {
      const file = { path, name: handle.name, kind: handle.kind }
      heirarchyDetails.files.push(file)
      folderDetails.children.push(file)
    } else if (handle.kind === 'directory') {
      const childDetails = //
        await traverseDirectory(handle, path, heirarchyDetails)

      if (childDetails.children.length === 0) {
        heirarchyDetails.emptyFolders.push(childDetails)
      }

      folderDetails.children.push(childDetails)
    }
  }

  heirarchyDetails.allFolders.push(folderDetails)
  return folderDetails
}

```

 I am planning to make a npm package for the implementation I have shown above if I get free time.

**Comment by ameet-dew** [comment]
@ashuvssut is this solution covering for folders selected via native explorer and not via drag and drop?

**Comment by ashuvssut** [comment]
It uses the File System Web API. Please check MDN to know it's capabilities 

I have a much better version which is closed source right now

**Comment by ashuvssut** [comment]
Hey guys, I have written [this NPM package](https://github.com/stacknide/fs-prober) to address this issue. Give it a try and open issues if you find any!
