### ISSUE TITLE
Improve Typescript support for errors

### ISSUE THREAD

**Issue by MBrendel** [react-dropzone/react-dropzone#988]
**Do you want to request a *feature* or report a *bug*?**
- [ ] I found a bug
- [x] I want to propose a feature

**What is the current behavior?**
The FileError ist typed as
```
export interface FileError {
  message: string;
  code: string;
}
```

**What is the expected behavior?**
The FileError should be typed as
```
export interface FileError {
  message: string;
  code: 'file-invalid-type' | 'file_too_large' | 'file_too_small' | 'too-many-files';
}
```

In addition it would be nice if ALL errors were (re-) exported from the utils. Currently only the _TOO_MANY_FILES_REJECTION_ is exported.

**Comment by ashishiiit01** [comment]
How do I define onDrop in typescript ???

  const { acceptedFiles, getRootProps, getInputProps } = useDropzone({**onDrop**});

**Comment by rolandjitsu** [comment]
This is addressed in https://github.com/react-dropzone/react-dropzone/pull/998.
