### ISSUE TITLE
onDrop hangs when input has many files

### ISSUE THREAD

**Issue by yumeixox** [react-dropzone/react-dropzone#999]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [x] I want to propose a feature

**What is the current behavior?**
The onDrop callback can take a long time to return when, I presume, there are too many files to iterate through. When dragging large enough folders it even seems to crash Chrome.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Enable the multiple option. (I'm using the useDropzone hook.)
2. Drag and drop a directory containing many files, such as a directory containing a few projects that contain node_modules folders.

**What is the expected behavior?**
Wish it didn't take so long. 

**If this is a feature request, what is motivation or use case for changing the behavior?**
Perhaps a maxFiles option could provide a work around. That way if we know the directory contains many files, we can tell the user to compress before drag and drop happens.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
I'm using Chrome, OSX Catalina and the latest react-dropzone (11.0.3)

**Comment by rolandjitsu** [comment]
@yumeixox there's not much we can do on our side to improve how fast the machine can process the files.

Sure, a max files prop could prevent this from happening. You're welcome to make a PR to add support for this.

**Comment by Morteza-Jenabzadeh** [comment]
Can I work on this issue? to have accepted number of files?

**Comment by rolandjitsu** [comment]
> Can I work on this issue? to have accepted number of files?

Of course!

**Comment by vvannada** [comment]
@rolandjitsu @morijenab 

Even if we have the `maxFiles` prop, the dropzone still seems to process each file, this will still crash the browser. Btw, I have the maxFiles prop and also have a accept prop to allow only image Files
